import type { ChurchHistoryEvent } from "./types";

const W = "https://en.wikipedia.org/wiki/";

/**
 * Church-history spine, part 3: from the foundation stone of the new
 * St Peter's (1506) to Quanta cura and the Syllabus of Errors (1864) — the
 * close of the Renaissance, the Reformation and Trent, the age of missions
 * and the Enlightenment, and the Church's passage through revolution to the
 * eve of Vatican I.
 */
export const EVENTS_3: ChurchHistoryEvent[] = [
  // ---------------------------------------------------------------- Western Schism & Renaissance
  {
    slug: "new-saint-peters-begun",
    title: "Foundation stone of the new St Peter's",
    year: 1506,
    date: "1506-04-18",
    precision: "day",
    era: "schism-renaissance",
    kind: "event",
    location: "Rome",
    context:
      "Pope Julius II lays the foundation stone of Bramante's basilica over the tomb of St Peter; the completed church is consecrated in 1626.",
    significance:
      "The preaching of indulgences to fund the building becomes the spark for Luther's protest.",
    citation: `${W}St._Peter's_Basilica`,
    links: { popes: ["pope-julius-ii"] },
  },
  {
    slug: "fifth-council-of-the-lateran",
    title: "Fifth Lateran Council",
    year: 1512,
    date: "1512-05-03",
    precision: "day",
    era: "schism-renaissance",
    kind: "council",
    tags: ["reform"],
    location: "Rome",
    context:
      "The council issues reform decrees and affirms the immortality of the individual soul against the Averroist philosophers.",
    significance:
      "Its closing session in March 1517 comes only months before the Ninety-five Theses.",
    citation: `${W}Fifth_Council_of_the_Lateran`,
    links: { documentSlug: "fifth-council-of-the-lateran", popes: ["pope-leo-x"] },
  },
  // ---------------------------------------------------------------- Reformation & Trent
  {
    slug: "luthers-ninety-five-theses",
    title: "Luther's Ninety-five Theses",
    year: 1517,
    date: "1517-10-31",
    precision: "day",
    era: "reformation-trent",
    kind: "event",
    tags: ["reformation", "schism"],
    location: "Wittenberg",
    context:
      "The Augustinian friar Martin Luther publishes his theses against the abuse of indulgences.",
    significance: "The Protestant Reformation begins.",
    citation: `${W}Ninety-five_Theses`,
  },
  {
    slug: "excommunication-of-luther",
    title: "Luther excommunicated",
    year: 1521,
    date: "1521-01-03",
    precision: "day",
    era: "reformation-trent",
    kind: "document",
    tags: ["reformation"],
    location: "Rome",
    context:
      "Leo X issues Decet Romanum Pontificem after Luther refuses the recantation demanded by Exsurge Domine (15 June 1520).",
    significance: "The formal break with Rome; the Diet of Worms follows within months.",
    citation: `${W}Decet_Romanum_Pontificem`,
    links: { popes: ["pope-leo-x"] },
  },
  {
    slug: "sack-of-rome-1527",
    title: "Sack of Rome",
    year: 1527,
    date: "1527-05-06",
    precision: "day",
    era: "reformation-trent",
    kind: "event",
    location: "Rome",
    context:
      "Mutinous imperial troops of Charles V sack the city while Clement VII is besieged in Castel Sant'Angelo.",
    significance: "Conventionally marks the end of the High Renaissance in Rome.",
    citation: `${W}Sack_of_Rome_(1527)`,
    links: { popes: ["pope-clement-vii"] },
  },
  {
    slug: "capuchins-approved",
    title: "Capuchin Franciscans approved",
    year: 1528,
    date: "1528-07-03",
    precision: "day",
    era: "reformation-trent",
    kind: "order",
    tags: ["reform"],
    location: "Rome",
    context: "Clement VII approves the Capuchin reform in the bull Religionis zelus.",
    significance: "A reformed Franciscan order of preachers to the poor.",
    citation: `${W}Order_of_Friars_Minor_Capuchin`,
  },
  {
    slug: "our-lady-of-guadalupe",
    title: "Our Lady of Guadalupe appears to St Juan Diego",
    year: 1531,
    date: "1531-12-09",
    precision: "day",
    era: "reformation-trent",
    kind: "apparition",
    tags: ["marian"],
    location: "Tepeyac, Mexico",
    context:
      "The Virgin appears to Juan Diego between 9 and 12 December, leaving her image on his tilma.",
    significance: "The conversion of Mexico; Our Lady of Guadalupe is Patroness of the Americas.",
    citation: `${W}Our_Lady_of_Guadalupe`,
    links: {
      apparitions: ["apparition-our-lady-of-guadalupe"],
      saints: ["saint-juan-diego"],
    },
  },
  {
    slug: "act-of-supremacy-1534",
    title: "Act of Supremacy",
    year: 1534,
    precision: "year",
    era: "reformation-trent",
    kind: "schism",
    tags: ["schism", "reformation"],
    location: "England",
    context: "Parliament declares Henry VIII the supreme head of the Church of England.",
    significance: "The English schism from Rome.",
    citation: `${W}Acts_of_Supremacy`,
  },
  {
    slug: "ursulines-founded",
    title: "St Angela Merici founds the Ursulines",
    year: 1535,
    date: "1535-11-25",
    precision: "day",
    era: "reformation-trent",
    kind: "order",
    location: "Brescia",
    context:
      "Angela Merici establishes the Company of St Ursula, the first religious institute of women devoted to teaching.",
    significance: "Opens the apostolic education of girls by consecrated women.",
    citation: `${W}Ursulines`,
    links: { saints: ["saint-angela-merici"] },
  },
  {
    slug: "martyrdom-of-fisher-and-more",
    title: "Martyrdom of Sts John Fisher and Thomas More",
    year: 1535,
    date: "1535-07-06",
    precision: "day",
    era: "reformation-trent",
    kind: "martyrdom",
    location: "London",
    context:
      "Bishop John Fisher is beheaded on 22 June and Thomas More on 6 July for refusing the royal supremacy.",
    significance: "Witnesses to papal primacy and to the rights of conscience.",
    citation: `${W}Thomas_More`,
    links: { saints: ["saint-thomas-more", "saint-john-fisher"] },
  },
  {
    slug: "jesuits-approved",
    title: "Society of Jesus approved",
    year: 1540,
    date: "1540-09-27",
    precision: "day",
    era: "reformation-trent",
    kind: "order",
    tags: ["reform"],
    location: "Rome",
    context:
      "Paul III approves the Society founded by Ignatius of Loyola in the bull Regimini militantis Ecclesiae.",
    significance: "An engine of the Catholic Reformation and of the world missions.",
    citation: `${W}Society_of_Jesus`,
    links: { saints: ["saint-ignatius-of-loyola"], popes: ["pope-paul-iii"] },
  },
  {
    slug: "council-of-trent",
    title: "Council of Trent opens",
    year: 1545,
    date: "1545-12-13",
    precision: "day",
    era: "reformation-trent",
    kind: "council",
    tags: ["reform"],
    location: "Trent",
    context:
      "The council meets in twenty-five sessions, with long interruptions, until 4 December 1563.",
    significance:
      "Defines justification and the sacraments, affirms Scripture and Tradition, and mandates seminaries.",
    citation: `${W}Council_of_Trent`,
    links: {
      documentSlug: "council-of-trent",
      popes: ["pope-paul-iii", "pope-pius-iv"],
    },
  },
  {
    slug: "francis-xavier-reaches-japan",
    title: "St Francis Xavier lands in Japan",
    year: 1549,
    date: "1549-08-15",
    precision: "day",
    era: "reformation-trent",
    kind: "mission",
    tags: ["mission"],
    location: "Kagoshima",
    context:
      "The Jesuit missionary opens the mission to Japan; he dies off the coast of China in 1552.",
    significance: "The great age of the Asian missions begins.",
    citation: `${W}Francis_Xavier`,
    links: { saints: ["saint-francis-xavier"] },
  },
  {
    slug: "peace-of-augsburg",
    title: "Peace of Augsburg",
    year: 1555,
    date: "1555-09-25",
    precision: "day",
    era: "reformation-trent",
    kind: "event",
    tags: ["reformation"],
    location: "Augsburg",
    context: "The Empire's princes settle religion by the principle cuius regio, eius religio.",
    significance: "The confessional map of Germany is fixed.",
    citation: `${W}Peace_of_Augsburg`,
  },
  {
    slug: "teresa-of-avila-reform",
    title: "St Teresa founds St Joseph's, Ávila",
    year: 1562,
    date: "1562-08-24",
    precision: "day",
    era: "reformation-trent",
    kind: "order",
    tags: ["reform"],
    location: "Ávila",
    context:
      "Teresa opens the first convent of the Discalced Carmelite reform; John of the Cross joins the reform in 1568.",
    significance: "Two mystical Doctors of the Church and a lasting renewal of religious life.",
    citation: `${W}Teresa_of_Ávila`,
    links: {
      saints: ["saint-teresa-of-avila", "saint-john-of-the-cross"],
      doctors: ["doctor-teresa-of-avila", "doctor-john-of-the-cross"],
    },
  },
  {
    slug: "council-of-trent-closes",
    title: "Council of Trent closes",
    year: 1563,
    date: "1563-12-04",
    precision: "day",
    era: "reformation-trent",
    kind: "council",
    tags: ["reform"],
    location: "Trent",
    context: "The final session ends the council; Pius IV confirms its decrees in 1564.",
    significance:
      "The Tridentine reform is carried out by bishops such as Charles Borromeo and by Pope Pius V.",
    citation: `${W}Council_of_Trent`,
    links: { saints: ["saint-charles-borromeo"] },
  },
  {
    slug: "roman-catechism",
    title: "Roman Catechism published",
    year: 1566,
    precision: "year",
    era: "reformation-trent",
    kind: "document",
    location: "Rome",
    context:
      "The Catechism of the Council of Trent is issued under Pius V as a manual for parish priests.",
    significance: "The Church's standard catechism until the Catechism of 1992.",
    citation: `${W}Roman_Catechism`,
    links: { popes: ["pope-saint-pius-v"] },
  },
  {
    slug: "quo-primum-tridentine-missal",
    title: "Quo primum: the Tridentine Missal",
    year: 1570,
    date: "1570-07-14",
    precision: "day",
    era: "reformation-trent",
    kind: "document",
    location: "Rome",
    context: "Pius V promulgates the reformed Roman Missal for the whole Latin Church.",
    significance: "The Roman Rite is unified for four hundred years.",
    citation: `${W}Quo_primum`,
    links: { popes: ["pope-saint-pius-v"] },
  },
  {
    slug: "battle-of-lepanto",
    title: "Battle of Lepanto",
    year: 1571,
    date: "1571-10-07",
    precision: "day",
    era: "reformation-trent",
    kind: "event",
    tags: ["marian"],
    location: "Gulf of Patras",
    context:
      "The Holy League defeats the Ottoman fleet; Pius V attributes the victory to the Rosary.",
    significance: "Origin of the feast of Our Lady of the Rosary on 7 October.",
    citation: `${W}Battle_of_Lepanto`,
  },
  {
    slug: "st-bartholomews-day-massacre",
    title: "St Bartholomew's Day Massacre",
    year: 1572,
    date: "1572-08-24",
    precision: "day",
    era: "reformation-trent",
    kind: "event",
    location: "Paris",
    context:
      "Thousands of Huguenots are killed in Paris and the provinces during the Wars of Religion.",
    significance: "Deepens the confessional conflict in France and across Europe.",
    citation: `${W}St._Bartholomew's_Day_massacre`,
  },
  {
    slug: "oratory-of-saint-philip-neri",
    title: "Oratory of St Philip Neri approved",
    year: 1575,
    date: "1575-07-15",
    precision: "day",
    era: "reformation-trent",
    kind: "order",
    location: "Rome",
    context: "Gregory XIII confirms the Congregation of the Oratory gathered by Philip Neri.",
    significance: "A reform of Roman piety through preaching, music, and joyful pastoral care.",
    citation: `${W}Oratory_of_Saint_Philip_Neri`,
    links: { saints: ["saint-philip-neri"] },
  },
  {
    slug: "martyrdom-of-edmund-campion",
    title: "St Edmund Campion martyred",
    year: 1581,
    date: "1581-12-01",
    precision: "day",
    era: "reformation-trent",
    kind: "martyrdom",
    location: "Tyburn",
    context: "The Jesuit priest is hanged, drawn, and quartered under Elizabeth I.",
    significance: "One of the Forty Martyrs of England and Wales.",
    citation: `${W}Edmund_Campion`,
  },
  {
    slug: "gregorian-calendar",
    title: "Gregorian calendar promulgated",
    year: 1582,
    date: "1582-02-24",
    precision: "day",
    era: "reformation-trent",
    kind: "event",
    location: "Rome",
    context:
      "Gregory XIII reforms the calendar in the bull Inter gravissimas; 4 October 1582 is followed by 15 October.",
    significance: "The civil calendar used throughout the world today.",
    citation: `${W}Gregorian_calendar`,
    links: { popes: ["pope-gregory-xiii"] },
  },
  {
    slug: "douay-rheims-bible",
    title: "Douay–Rheims Bible",
    year: 1582,
    precision: "year",
    era: "reformation-trent",
    kind: "document",
    location: "Rheims and Douai",
    context:
      "The English College publishes the New Testament at Rheims in 1582 and the Old Testament at Douai in 1609–1610.",
    significance: "The English Catholic Bible for three centuries.",
    citation: `${W}Douay–Rheims_Bible`,
  },
  {
    slug: "union-of-brest",
    title: "Union of Brest",
    year: 1596,
    precision: "year",
    era: "reformation-trent",
    kind: "event",
    location: "Brest",
    context:
      "Ruthenian bishops of the Kyivan metropolia enter full communion with Rome while keeping the Byzantine rite.",
    significance: "Origin of the Ukrainian Greek Catholic Church.",
    citation: `${W}Union_of_Brest`,
  },
  {
    slug: "martyrs-of-nagasaki",
    title: "Twenty-six Martyrs of Japan",
    year: 1597,
    date: "1597-02-05",
    precision: "day",
    era: "reformation-trent",
    kind: "martyrdom",
    location: "Nagasaki",
    context: "St Paul Miki and twenty-five companions are crucified on a hill above Nagasaki.",
    significance: "The Japanese Church survives underground for two and a half centuries.",
    citation: `${W}Twenty-six_Martyrs_of_Japan`,
    links: { saints: ["saint-paul-miki"] },
  },
  {
    slug: "matteo-ricci-in-beijing",
    title: "Matteo Ricci enters Beijing",
    year: 1601,
    date: "1601-01-24",
    precision: "day",
    era: "reformation-trent",
    kind: "mission",
    tags: ["mission"],
    location: "Beijing",
    context: "The Jesuit scholar is received at the Ming court.",
    significance: "A model of inculturated mission to China.",
    citation: `${W}Matteo_Ricci`,
  },
  {
    slug: "propaganda-fide-founded",
    title: "Congregation de Propaganda Fide founded",
    year: 1622,
    date: "1622-01-06",
    precision: "day",
    era: "reformation-trent",
    kind: "mission",
    tags: ["mission"],
    location: "Rome",
    context: "Gregory XV founds the congregation to direct the missions from Rome.",
    significance: "Today's Dicastery for Evangelization.",
    citation: `${W}Congregation_for_the_Evangelization_of_Peoples`,
    links: { popes: ["pope-gregory-xv"] },
  },
  {
    slug: "vincent-de-paul-congregation-of-the-mission",
    title: "St Vincent de Paul founds the Congregation of the Mission",
    year: 1625,
    precision: "year",
    era: "reformation-trent",
    kind: "order",
    location: "Paris",
    context:
      "Vincent de Paul founds the Vincentians for missions to the rural poor; with Louise de Marillac he founds the Daughters of Charity in 1633.",
    significance: "Charity to the poor is given lasting institutional form.",
    citation: `${W}Vincent_de_Paul`,
    links: { saints: ["saint-vincent-de-paul", "saint-louise-de-marillac"] },
  },
  {
    slug: "condemnation-of-galileo",
    title: "Galileo condemned",
    year: 1633,
    date: "1633-06-22",
    precision: "day",
    era: "reformation-trent",
    kind: "event",
    location: "Rome",
    context:
      "The Holy Office requires Galileo to abjure heliocentrism and places him under house arrest.",
    significance:
      "The emblematic science-and-faith episode; John Paul II acknowledged the errors of Galileo's judges in 1992.",
    citation: `${W}Galileo_affair`,
    links: { popes: ["pope-urban-viii"] },
  },
  {
    slug: "peace-of-westphalia",
    title: "Peace of Westphalia",
    year: 1648,
    date: "1648-10-24",
    precision: "day",
    era: "reformation-trent",
    kind: "event",
    location: "Münster and Osnabrück",
    context: "The treaties end the Thirty Years' War; Innocent X protests their religious clauses.",
    significance: "The end of Christendom's wars of religion.",
    citation: `${W}Peace_of_Westphalia`,
    links: { popes: ["pope-innocent-x"] },
  },
  // ---------------------------------------------------------------- Missions & Enlightenment
  {
    slug: "north-american-martyrs",
    title: "St Jean de Brébeuf and the North American Martyrs",
    year: 1649,
    date: "1649-03-16",
    precision: "day",
    era: "early-modern",
    kind: "martyrdom",
    tags: ["mission"],
    location: "Huronia",
    context:
      "Jean de Brébeuf is killed on 16 March 1649, one of eight Jesuit missionaries martyred between 1642 and 1649.",
    significance: "Patrons of Canada.",
    citation: `${W}Canadian_Martyrs`,
  },
  {
    slug: "cum-occasione",
    title: "Cum occasione condemns Jansenism",
    year: 1653,
    date: "1653-05-31",
    precision: "day",
    era: "early-modern",
    kind: "document",
    location: "Rome",
    context: "Innocent X condemns five propositions drawn from Jansen's Augustinus.",
    significance: "Opens a century of Jansenist controversy in France.",
    citation: `${W}Cum_occasione`,
  },
  {
    slug: "sacred-heart-apparitions-paray",
    title: "Sacred Heart apparitions to St Margaret Mary",
    year: 1673,
    date: "1673-12-27",
    precision: "day",
    era: "early-modern",
    kind: "apparition",
    location: "Paray-le-Monial",
    context:
      "Christ reveals his Heart to the Visitation nun Margaret Mary Alacoque in a series of apparitions from 1673 to 1675.",
    significance:
      "Devotion to the Sacred Heart spreads through the Church; its feast is extended universally in 1856.",
    citation: `${W}Margaret_Mary_Alacoque`,
    links: { saints: ["saint-margaret-mary-alacoque"] },
  },
  {
    slug: "unigenitus",
    title: "Unigenitus",
    year: 1713,
    date: "1713-09-08",
    precision: "day",
    era: "early-modern",
    kind: "document",
    location: "Rome",
    context: "Clement XI condemns 101 Jansenist propositions from Pasquier Quesnel.",
    significance: "Divides the French Church and provokes Gallican appeals against the bull.",
    citation: `${W}Unigenitus`,
    links: { popes: ["pope-clement-xi"] },
  },
  {
    slug: "redemptorists-founded",
    title: "St Alphonsus founds the Redemptorists",
    year: 1732,
    date: "1732-11-09",
    precision: "day",
    era: "early-modern",
    kind: "order",
    location: "Scala",
    context:
      "Alphonsus Liguori founds the Congregation of the Most Holy Redeemer for missions to the rural poor.",
    significance: "Alphonsus's moral theology earns him the title Doctor of the Church.",
    citation: `${W}Redemptorists`,
    links: {
      saints: ["saint-alphonsus-liguori"],
      doctors: ["doctor-alphonsus-liguori"],
    },
  },
  {
    slug: "ex-quo-singulari-chinese-rites",
    title: "Ex quo singulari ends the Chinese Rites",
    year: 1742,
    date: "1742-07-11",
    precision: "day",
    era: "early-modern",
    kind: "document",
    location: "Rome",
    context:
      "Benedict XIV forbids Chinese Catholics to take part in Confucian and ancestral rites.",
    significance: "The Chinese mission is curtailed until the ruling is relaxed in 1939.",
    citation: `${W}Chinese_Rites_controversy`,
    links: { popes: ["pope-benedict-xiv"] },
  },
  {
    slug: "mission-san-diego-founded",
    title: "St Junípero Serra founds Mission San Diego",
    year: 1769,
    date: "1769-07-16",
    precision: "day",
    era: "early-modern",
    kind: "mission",
    tags: ["mission"],
    location: "California",
    context: "The Franciscan Junípero Serra founds the first of the California missions.",
    significance: "The evangelisation of the Pacific coast.",
    citation: `${W}Junípero_Serra`,
    links: { saints: ["saint-junipero-serra"] },
  },
  {
    slug: "suppression-of-the-jesuits",
    title: "Suppression of the Society of Jesus",
    year: 1773,
    date: "1773-07-21",
    precision: "day",
    era: "early-modern",
    kind: "event",
    location: "Rome",
    context:
      "Under pressure from the Bourbon courts, Clement XIV suppresses the Society in the brief Dominus ac Redemptor.",
    significance: "The Society is restored in 1814.",
    citation: `${W}Suppression_of_the_Society_of_Jesus`,
    links: { popes: ["pope-clement-xiv"] },
  },
  // ---------------------------------------------------------------- Revolution to Vatican I
  {
    slug: "first-bishop-of-the-united-states",
    title: "John Carroll appointed first US bishop",
    year: 1789,
    date: "1789-11-06",
    precision: "day",
    era: "revolution-19c",
    kind: "event",
    location: "Baltimore",
    context: "Pius VI erects the Diocese of Baltimore and names John Carroll its bishop.",
    significance: "The beginning of the American hierarchy.",
    citation: `${W}John_Carroll_(archbishop_of_Baltimore)`,
  },
  {
    slug: "civil-constitution-of-the-clergy",
    title: "Civil Constitution of the Clergy",
    year: 1790,
    date: "1790-07-12",
    precision: "day",
    era: "revolution-19c",
    kind: "event",
    location: "Paris",
    context:
      "The Revolution subordinates the French Church to the state; Pius VI condemns the measure in 1791.",
    significance: "Persecution of the clergy who refuse the oath follows.",
    citation: `${W}Civil_Constitution_of_the_Clergy`,
  },
  {
    slug: "martyrs-of-compiegne",
    title: "Martyrs of Compiègne",
    year: 1794,
    date: "1794-07-17",
    precision: "day",
    era: "revolution-19c",
    kind: "martyrdom",
    location: "Paris",
    context:
      "Sixteen Carmelites of Compiègne are guillotined during the Terror, singing as they go to the scaffold.",
    significance: "Canonised in 2024.",
    citation: `${W}Martyrs_of_Compiègne`,
  },
  {
    slug: "death-of-pius-vi-in-captivity",
    title: "Pius VI dies a prisoner of France",
    year: 1799,
    date: "1799-08-29",
    precision: "day",
    era: "revolution-19c",
    kind: "pope",
    location: "Valence",
    context: "Seized from Rome by French troops, the aged pope dies in captivity at Valence.",
    significance: "The papacy seems finished; Pius VII is elected at Venice in 1800.",
    citation: `${W}Pope_Pius_VI`,
    links: { popes: ["pope-pius-vi"] },
  },
  {
    slug: "concordat-of-1801",
    title: "Concordat of 1801",
    year: 1801,
    date: "1801-07-15",
    precision: "day",
    era: "revolution-19c",
    kind: "event",
    location: "Paris",
    context: "Napoleon and Pius VII agree to restore the Catholic Church in France.",
    significance: "A model for later Church–state concordats.",
    citation: `${W}Concordat_of_1801`,
    links: { popes: ["pope-pius-vii"] },
  },
  {
    slug: "pius-vii-arrested",
    title: "Napoleon imprisons Pius VII",
    year: 1809,
    date: "1809-07-06",
    precision: "day",
    era: "revolution-19c",
    kind: "pope",
    location: "Rome",
    context: "The pope is arrested and held at Savona and later Fontainebleau until 1814.",
    significance: "The moral prestige of the papacy rises through his steadfastness.",
    citation: `${W}Pope_Pius_VII`,
  },
  {
    slug: "restoration-of-the-jesuits",
    title: "Society of Jesus restored",
    year: 1814,
    date: "1814-08-07",
    precision: "day",
    era: "revolution-19c",
    kind: "order",
    location: "Rome",
    context: "Pius VII restores the Society worldwide in the bull Sollicitudo omnium ecclesiarum.",
    significance: "A Jesuit revival in education and the missions.",
    citation: `${W}Suppression_of_the_Society_of_Jesus`,
  },
  {
    slug: "catholic-emancipation",
    title: "Catholic Emancipation in Britain",
    year: 1829,
    date: "1829-04-13",
    precision: "day",
    era: "revolution-19c",
    kind: "event",
    location: "London",
    context: "The Roman Catholic Relief Act receives royal assent.",
    significance: "Catholics are admitted to Parliament and most public offices.",
    citation: `${W}Roman_Catholic_Relief_Act_1829`,
  },
  {
    slug: "miraculous-medal-apparition",
    title: "Our Lady of the Miraculous Medal",
    year: 1830,
    date: "1830-11-27",
    precision: "day",
    era: "revolution-19c",
    kind: "apparition",
    tags: ["marian"],
    location: "Rue du Bac, Paris",
    context: "The Virgin shows St Catherine Labouré the design of the medal.",
    significance: "The beginning of the Marian revival of the nineteenth century.",
    citation: `${W}Miraculous_Medal`,
    links: {
      apparitions: ["apparition-miraculous-medal-rue-du-bac"],
      saints: ["saint-catherine-laboure"],
    },
  },
  {
    slug: "mirari-vos",
    title: "Mirari vos",
    year: 1832,
    date: "1832-08-15",
    precision: "day",
    era: "revolution-19c",
    kind: "document",
    location: "Rome",
    context: "Gregory XVI condemns the liberal Catholicism of Lamennais and his circle.",
    significance: "The Church's long debate with liberalism begins.",
    citation: `${W}Mirari_vos`,
    links: { popes: ["pope-gregory-xvi"] },
  },
  {
    slug: "newman-received-into-the-church",
    title: "John Henry Newman received into the Church",
    year: 1845,
    date: "1845-10-09",
    precision: "day",
    era: "revolution-19c",
    kind: "saint",
    location: "Littlemore",
    context: "The leader of the Oxford Movement is received into the Catholic Church.",
    significance:
      "His theology of the development of doctrine shapes modern Catholic thought; canonised in 2019.",
    citation: `${W}John_Henry_Newman`,
    links: { saints: ["saint-john-henry-newman"] },
  },
  {
    slug: "martyrdom-of-andrew-kim-taegon",
    title: "Korean Martyrs: St Andrew Kim Taegon",
    year: 1846,
    date: "1846-09-16",
    precision: "day",
    era: "revolution-19c",
    kind: "martyrdom",
    location: "Seoul",
    context: "The first Korean priest is beheaded; he and 102 companions are canonised in 1984.",
    significance: "A Church born of lay converts before any missionary arrived.",
    citation: `${W}Andrew_Kim_Taegon`,
    links: { saints: ["saint-andrew-kim-taegon"] },
  },
  {
    slug: "our-lady-of-la-salette",
    title: "Our Lady of La Salette",
    year: 1846,
    date: "1846-09-19",
    precision: "day",
    era: "revolution-19c",
    kind: "apparition",
    tags: ["marian"],
    location: "La Salette",
    context: "The weeping Virgin appears to two shepherd children in the French Alps.",
    significance: "Approved by the Bishop of Grenoble in 1851.",
    citation: `${W}Our_Lady_of_La_Salette`,
    links: { apparitions: ["apparition-our-lady-of-la-salette"] },
  },
  {
    slug: "restoration-of-the-english-hierarchy",
    title: "English Catholic hierarchy restored",
    year: 1850,
    date: "1850-09-29",
    precision: "day",
    era: "revolution-19c",
    kind: "event",
    location: "Rome",
    context:
      "Pius IX restores the hierarchy in Universalis Ecclesiae; Nicholas Wiseman becomes the first Archbishop of Westminster.",
    significance: 'The "papal aggression" outcry, and the Catholic revival in England.',
    citation: `${W}Universalis_Ecclesiae`,
  },
  {
    slug: "ineffabilis-deus",
    title: "Ineffabilis Deus: Dogma of the Immaculate Conception",
    year: 1854,
    date: "1854-12-08",
    precision: "day",
    era: "revolution-19c",
    kind: "document",
    tags: ["dogma", "marian"],
    location: "Rome",
    context: "Pius IX defines that Mary was conceived without original sin.",
    significance: "The first ex cathedra definition of the modern era.",
    citation:
      "https://www.vatican.va/content/pius-ix/it/documents/18541208-costituzione-apostolica-ineffabilis-deus.html",
    links: { popes: ["pope-pius-ix"] },
  },
  {
    slug: "feast-of-the-sacred-heart-universal",
    title: "Feast of the Sacred Heart extended to the whole Church",
    year: 1856,
    date: "1856-08-23",
    precision: "day",
    era: "revolution-19c",
    kind: "event",
    location: "Rome",
    context: "Pius IX extends the feast to the universal Church.",
    significance: "Devotion to the Sacred Heart becomes universal.",
    citation: `${W}Feast_of_the_Sacred_Heart`,
  },
  {
    slug: "our-lady-of-lourdes",
    title: "Our Lady of Lourdes",
    year: 1858,
    date: "1858-02-11",
    precision: "day",
    era: "revolution-19c",
    kind: "apparition",
    tags: ["marian"],
    location: "Lourdes",
    context:
      'In eighteen apparitions the Virgin appears to Bernadette Soubirous, declaring "I am the Immaculate Conception."',
    significance: "The world's great Marian shrine of healing.",
    citation: `${W}Our_Lady_of_Lourdes`,
    links: {
      apparitions: ["apparition-our-lady-of-lourdes"],
      saints: ["saint-bernadette-soubirous"],
    },
  },
  {
    slug: "salesians-founded",
    title: "St John Bosco founds the Salesians",
    year: 1859,
    date: "1859-12-18",
    precision: "day",
    era: "revolution-19c",
    kind: "order",
    location: "Turin",
    context: "John Bosco founds the Society of St Francis de Sales for the care of poor youth.",
    significance: "A youth apostolate that spreads worldwide.",
    citation: `${W}Salesians_of_Don_Bosco`,
    links: { saints: ["saint-john-bosco"] },
  },
  {
    slug: "quanta-cura-syllabus-of-errors",
    title: "Quanta cura and the Syllabus of Errors",
    year: 1864,
    date: "1864-12-08",
    precision: "day",
    era: "revolution-19c",
    kind: "document",
    location: "Rome",
    context: "Pius IX condemns eighty propositions of contemporary liberalism.",
    significance: "Sets the Church in open opposition to the modern ideologies.",
    citation: `${W}Syllabus_of_Errors`,
    links: { popes: ["pope-pius-ix"] },
  },
];
