import type { ChurchHistoryEvent } from "./types";

const W = "https://en.wikipedia.org/wiki/";

/**
 * Church-history spine, part 4: from the First Vatican Council (1869) to the
 * election of Pope Leo XIV (2025) — the close of the Revolution-to-Vatican-I
 * era, the Twentieth Century, and the Post-Conciliar Church.
 */
export const EVENTS_4: ChurchHistoryEvent[] = [
  // ---------------------------------------------------------------- Revolution to Vatican I
  {
    slug: "first-vatican-council",
    title: "First Vatican Council",
    year: 1869,
    date: "1869-12-08",
    precision: "day",
    era: "revolution-19c",
    kind: "council",
    tags: ["dogma"],
    location: "Rome",
    context:
      "Pius IX opens the council in St Peter's; it issues Dei Filius (24 April 1870) on faith and reason and Pastor Aeternus (18 July 1870) on the papacy.",
    significance: "Papal primacy and infallibility are solemnly defined.",
    citation: `${W}First_Vatican_Council`,
    links: { documentSlug: "first-vatican-council", popes: ["pope-pius-ix"] },
  },
  {
    slug: "capture-of-rome-1870",
    title: "Capture of Rome ends the Papal States",
    year: 1870,
    date: "1870-09-20",
    precision: "day",
    era: "revolution-19c",
    kind: "event",
    tags: ["papacy"],
    location: "Porta Pia, Rome",
    context:
      "The Italian army breaches the walls at Porta Pia and enters Rome; Pius IX withdraws into the Vatican as its self-described prisoner.",
    significance: "Opens the Roman Question, unresolved until the Lateran Treaty of 1929.",
    citation: `${W}Capture_of_Rome`,
  },
  {
    slug: "kulturkampf",
    title: "Kulturkampf",
    year: 1871,
    precision: "year",
    era: "revolution-19c",
    kind: "event",
    tags: ["persecution"],
    location: "Germany",
    context:
      "Bismarck's government legislates against the Church: the Pulpit Law of 1871, the expulsion of the Jesuits in 1872, and state control of clerical training and appointments.",
    significance:
      "German Catholics rally around the Centre Party; the conflict is gradually resolved under Leo XIII.",
    citation: `${W}Kulturkampf`,
  },
  {
    slug: "election-of-leo-xiii",
    title: "Leo XIII elected",
    year: 1878,
    date: "1878-02-20",
    precision: "day",
    era: "revolution-19c",
    kind: "pope",
    tags: ["papacy"],
    location: "Rome",
    context: "Gioacchino Pecci is elected and begins a pontificate of twenty-five years.",
    significance:
      "Rerum Novarum founds modern Catholic social teaching; Aeterni Patris launches the Thomist revival.",
    citation: `${W}Pope_Leo_XIII`,
    links: { popes: ["pope-leo-xiii"] },
  },
  {
    slug: "our-lady-of-knock",
    title: "Our Lady of Knock",
    year: 1879,
    date: "1879-08-21",
    precision: "day",
    era: "revolution-19c",
    kind: "apparition",
    tags: ["marian"],
    location: "Knock, Ireland",
    context:
      "Fifteen villagers see a silent apparition of Our Lady with St Joseph, St John the Evangelist, and the Lamb upon an altar at the gable of the parish church.",
    significance: "Ireland's national Marian shrine.",
    citation: `${W}Knock_Shrine`,
    links: { apparitions: ["apparition-our-lady-of-knock"] },
  },
  {
    slug: "uganda-martyrs",
    title: "Uganda Martyrs",
    year: 1886,
    date: "1886-06-03",
    precision: "day",
    era: "revolution-19c",
    kind: "martyrdom",
    tags: ["persecution"],
    location: "Namugongo",
    context:
      "St Charles Lwanga and his companions, young converts at the court of Kabaka Mwanga, are burned alive for their faith.",
    significance: "Canonised in 1964; a foundation stone of the Church in Africa.",
    citation: `${W}Uganda_Martyrs`,
    links: { saints: ["saint-charles-lwanga"] },
  },
  {
    slug: "death-of-therese-of-lisieux",
    title: "Death of St Thérèse of Lisieux",
    year: 1897,
    date: "1897-09-30",
    precision: "day",
    era: "revolution-19c",
    kind: "saint",
    location: "Lisieux",
    context:
      'The young Carmelite dies of tuberculosis at twenty-four, leaving the autobiography published as Story of a Soul and her "Little Way" of confidence and love.',
    significance: "Declared a Doctor of the Church in 1997; patroness of the missions.",
    citation: `${W}Thérèse_of_Lisieux`,
    links: {
      saints: ["saint-therese-of-lisieux"],
      doctors: ["doctor-therese-of-lisieux"],
    },
  },
  {
    slug: "election-of-pius-x",
    title: "St Pius X elected",
    year: 1903,
    date: "1903-08-04",
    precision: "day",
    era: "revolution-19c",
    kind: "pope",
    tags: ["papacy"],
    location: "Rome",
    context: 'Giuseppe Sarto is elected and takes as his motto "To restore all things in Christ."',
    significance:
      "Reform of sacred music (Tra le sollecitudini, 22 November 1903), frequent Communion, and the condemnation of Modernism.",
    citation: `${W}Pope_Pius_X`,
    links: { popes: ["pope-saint-pius-x"] },
  },
  {
    slug: "french-separation-of-church-and-state",
    title: "French law separating Church and State",
    year: 1905,
    date: "1905-12-09",
    precision: "day",
    era: "revolution-19c",
    kind: "event",
    location: "Paris",
    context:
      "The Third Republic abolishes the Concordat of 1801 and takes Church property into state hands.",
    significance: "Pius X condemns the law in Vehementer Nos (1906).",
    citation: `${W}1905_French_law_on_the_Separation_of_the_Churches_and_the_State`,
  },
  {
    slug: "quam-singulari",
    title: "Quam singulari: Communion for children",
    year: 1910,
    date: "1910-08-08",
    precision: "day",
    era: "revolution-19c",
    kind: "document",
    location: "Rome",
    context:
      "Under Pius X the decree lowers the age of First Communion to the age of reason, about seven years.",
    significance: "A landmark of Eucharistic renewal in the life of families and parishes.",
    citation: `${W}Quam_singulari`,
  },

  // ---------------------------------------------------------------- Twentieth Century
  {
    slug: "our-lady-of-fatima",
    title: "Our Lady of Fatima",
    year: 1917,
    date: "1917-05-13",
    precision: "day",
    era: "twentieth",
    kind: "apparition",
    tags: ["marian"],
    location: "Fátima",
    context:
      "Our Lady appears six times to the shepherd children Lucia, Francisco, and Jacinta; the Miracle of the Sun is witnessed on 13 October 1917.",
    significance:
      "Her call to the Rosary, penance, and the consecration of Russia; the apparitions are approved in 1930.",
    citation: `${W}Our_Lady_of_Fátima`,
    links: { apparitions: ["apparition-our-lady-of-fatima"] },
  },
  {
    slug: "code-of-canon-law-1917",
    title: "1917 Code of Canon Law",
    year: 1917,
    date: "1917-05-27",
    precision: "day",
    era: "twentieth",
    kind: "document",
    tags: ["canon"],
    location: "Rome",
    context:
      "Benedict XV promulgates the first codification of the Church's law on Pentecost 1917; it comes into force in 1918.",
    significance: "Replaces the Corpus Iuris Canonici with a single modern code.",
    citation: `${W}1917_Code_of_Canon_Law`,
    links: { popes: ["pope-benedict-xv"] },
  },
  {
    slug: "benedict-xv-peace-note",
    title: "Benedict XV's peace note",
    year: 1917,
    date: "1917-08-01",
    precision: "day",
    era: "twentieth",
    kind: "document",
    location: "Rome",
    context: "Benedict XV sends the belligerent powers a seven-point plan to end the Great War.",
    significance: "A defining moment of the papal diplomacy of peace.",
    citation: `${W}Pope_Benedict_XV`,
    links: { popes: ["pope-benedict-xv"] },
  },
  {
    slug: "cristero-war",
    title: "Cristero War",
    year: 1926,
    precision: "year",
    era: "twentieth",
    kind: "event",
    tags: ["persecution"],
    location: "Mexico",
    context:
      "Mexican Catholics rise against the anti-clerical Calles laws in a conflict that lasts until 1929.",
    significance: "Its martyrs are canonised in 2000.",
    citation: `${W}Cristero_War`,
  },
  {
    slug: "opus-dei-founded",
    title: "Opus Dei founded",
    year: 1928,
    date: "1928-10-02",
    precision: "day",
    era: "twentieth",
    kind: "order",
    location: "Madrid",
    context: "St Josemaría Escrivá founds Opus Dei.",
    significance:
      "Preaches the sanctification of ordinary work; erected as a personal prelature in 1982.",
    citation: `${W}Opus_Dei`,
    links: { saints: ["saint-josemaria-escriva"] },
  },
  {
    slug: "lateran-treaty",
    title: "Lateran Treaty",
    year: 1929,
    date: "1929-02-11",
    precision: "day",
    era: "twentieth",
    kind: "event",
    tags: ["papacy"],
    location: "Rome",
    context: "Pius XI and Mussolini's government sign the treaty creating Vatican City State.",
    significance: "Ends the Roman Question opened in 1870.",
    citation: `${W}Lateran_Treaty`,
    links: { popes: ["pope-pius-xi"] },
  },
  {
    slug: "election-of-pius-xii",
    title: "Pius XII elected",
    year: 1939,
    date: "1939-03-02",
    precision: "day",
    era: "twentieth",
    kind: "pope",
    tags: ["papacy"],
    location: "Rome",
    context:
      "Eugenio Pacelli is elected; his pontificate spans the Second World War and the Cold War.",
    significance: "Wartime diplomacy, Mystici Corporis, and the definition of the Assumption.",
    citation: `${W}Pope_Pius_XII`,
    links: { popes: ["pope-venerable-pius-xii"] },
  },
  {
    slug: "martyrdom-of-maximilian-kolbe",
    title: "St Maximilian Kolbe dies at Auschwitz",
    year: 1941,
    date: "1941-08-14",
    precision: "day",
    era: "twentieth",
    kind: "martyrdom",
    location: "Auschwitz",
    context:
      "The Franciscan priest volunteers to die in the starvation bunker in place of a father of a family.",
    significance: "Martyr of charity; canonised in 1982.",
    citation: `${W}Maximilian_Kolbe`,
    links: { saints: ["saint-maximilian-kolbe"] },
  },
  {
    slug: "martyrdom-of-edith-stein",
    title: "St Teresa Benedicta of the Cross (Edith Stein) killed",
    year: 1942,
    date: "1942-08-09",
    precision: "day",
    era: "twentieth",
    kind: "martyrdom",
    location: "Auschwitz",
    context:
      "The Jewish-born philosopher and Carmelite nun is killed in the gas chambers with her sister Rosa.",
    significance: "Named a co-patroness of Europe.",
    citation: `${W}Edith_Stein`,
    links: { saints: ["saint-teresa-benedicta-of-the-cross"] },
  },
  {
    slug: "missionaries-of-charity-founded",
    title: "Mother Teresa founds the Missionaries of Charity",
    year: 1950,
    date: "1950-10-07",
    precision: "day",
    era: "twentieth",
    kind: "order",
    location: "Calcutta",
    context:
      "The new congregation receives diocesan approval, dedicated to the service of the poorest of the poor.",
    significance: "Mother Teresa is canonised in 2016.",
    citation: `${W}Missionaries_of_Charity`,
    links: { saints: ["saint-mother-teresa-of-calcutta"] },
  },
  {
    slug: "munificentissimus-deus",
    title: "Munificentissimus Deus: Dogma of the Assumption",
    year: 1950,
    date: "1950-11-01",
    precision: "day",
    era: "twentieth",
    kind: "document",
    tags: ["dogma", "marian"],
    location: "Rome",
    context:
      "Pius XII solemnly defines that Mary, at the end of her earthly life, was assumed body and soul into heavenly glory.",
    significance: "The only ex cathedra definition since 1870.",
    citation:
      "https://www.vatican.va/content/pius-xii/en/apost_constitutions/documents/hf_p-xii_apc_19501101_munificentissimus-deus.html",
    // No documentSlug: the document is ingested (not curated), and the merge
    // enriches this event by its own slug whenever it is published.
  },
  {
    slug: "holy-week-reform-1955",
    title: "Restoration of the Holy Week rites",
    year: 1955,
    date: "1955-11-16",
    precision: "day",
    era: "twentieth",
    kind: "document",
    tags: ["liturgy"],
    location: "Rome",
    context:
      "The decree Maxima redemptionis restores the Holy Week rites, following the experimental restoration of the Easter Vigil in 1951.",
    significance: "A prelude to the conciliar liturgical reform.",
    citation: `${W}Reform_of_the_Roman_Liturgy_(1955)`,
  },
  {
    slug: "chinese-catholic-patriotic-association",
    title: "Chinese Catholic Patriotic Association created",
    year: 1957,
    precision: "year",
    era: "twentieth",
    kind: "event",
    tags: ["persecution"],
    location: "Beijing",
    context:
      "The state establishes a body to control the Church independently of Rome; an underground Church loyal to the pope persists.",
    significance:
      "The division endures; a provisional Holy See–China agreement on bishops is signed in 2018.",
    citation: `${W}Chinese_Patriotic_Catholic_Association`,
  },
  {
    slug: "john-xxiii-announces-a-council",
    title: "St John XXIII announces an ecumenical council",
    year: 1959,
    date: "1959-01-25",
    precision: "day",
    era: "twentieth",
    kind: "event",
    location: "St Paul Outside the Walls",
    context:
      "Three months after his election on 28 October 1958, the pope announces his intention to convene a council.",
    significance: "The Second Vatican Council is set in motion.",
    citation: `${W}Pope_John_XXIII`,
    links: { popes: ["pope-saint-john-xxiii"] },
  },
  {
    slug: "second-vatican-council",
    title: "Second Vatican Council opens",
    year: 1962,
    date: "1962-10-11",
    precision: "day",
    era: "twentieth",
    kind: "council",
    location: "St Peter's",
    context:
      "John XXIII opens the council in St Peter's; four sessions to 8 December 1965 produce sixteen documents.",
    significance:
      "Teaching on the liturgy, the Church, divine revelation, religious liberty, and ecumenism.",
    citation: `${W}Second_Vatican_Council`,
    links: {
      documentSlug: "second-vatican-council",
      popes: ["pope-saint-john-xxiii", "pope-saint-paul-vi"],
    },
  },
  {
    slug: "election-of-paul-vi",
    title: "St Paul VI elected",
    year: 1963,
    date: "1963-06-21",
    precision: "day",
    era: "twentieth",
    kind: "pope",
    tags: ["papacy"],
    location: "Rome",
    context: "Giovanni Battista Montini is elected and continues and closes the Council.",
    significance: "Humanae Vitae, the new Missal, and the first papal journeys by air.",
    citation: `${W}Pope_Paul_VI`,
    links: { popes: ["pope-saint-paul-vi"] },
  },
  {
    slug: "lifting-of-the-anathemas-of-1054",
    title: "Mutual lifting of the excommunications of 1054",
    year: 1965,
    date: "1965-12-07",
    precision: "day",
    era: "twentieth",
    kind: "event",
    tags: ["schism"],
    location: "Rome and Constantinople",
    context:
      "Paul VI and Patriarch Athenagoras I simultaneously remove from memory the mutual excommunications of 1054.",
    significance: "A milestone of Catholic–Orthodox reconciliation.",
    citation: `${W}Catholic–Orthodox_Joint_Declaration_of_1965`,
    links: { popes: ["pope-saint-paul-vi"] },
  },
  {
    slug: "second-vatican-council-closes",
    title: "Second Vatican Council closes",
    year: 1965,
    date: "1965-12-08",
    precision: "day",
    era: "twentieth",
    kind: "event",
    location: "St Peter's",
    context: "Paul VI closes the final session of the Council.",
    significance: "The post-conciliar era begins.",
    citation: `${W}Second_Vatican_Council`,
    links: { documentSlug: "second-vatican-council", popes: ["pope-saint-paul-vi"] },
  },

  // ---------------------------------------------------------------- Post-Conciliar Church
  {
    slug: "catholic-charismatic-renewal-begins",
    title: "Catholic Charismatic Renewal begins",
    year: 1967,
    precision: "year",
    era: "post-conciliar",
    kind: "event",
    tags: ["holy-spirit"],
    location: "Duquesne University",
    context:
      'At a student retreat in February 1967, the "Duquesne Weekend", participants experience an outpouring of the Holy Spirit.',
    significance: "A movement that grows to tens of millions of Catholics worldwide.",
    citation: `${W}Catholic_Charismatic_Renewal`,
  },
  {
    slug: "medellin-conference",
    title: "CELAM conference at Medellín",
    year: 1968,
    precision: "year",
    era: "post-conciliar",
    kind: "event",
    location: "Medellín",
    context:
      "The Latin American bishops apply Vatican II to their continent and speak of a preferential option for the poor.",
    significance: "Opens the debates over liberation theology.",
    citation: `${W}Latin_American_Episcopal_Conference`,
  },
  {
    slug: "new-roman-missal-1969",
    title: "Missale Romanum: the new Order of Mass",
    year: 1969,
    date: "1969-04-03",
    precision: "day",
    era: "post-conciliar",
    kind: "document",
    tags: ["liturgy"],
    location: "Rome",
    context:
      "Paul VI promulgates the reformed Roman Missal; the new Order of Mass comes into use on 30 November 1969.",
    significance: "Mass in the vernacular becomes the norm worldwide.",
    citation: `${W}Mass_of_Paul_VI`,
    links: { popes: ["pope-saint-paul-vi"] },
  },
  {
    slug: "election-of-john-paul-ii",
    title: "St John Paul II elected",
    year: 1978,
    date: "1978-10-16",
    precision: "day",
    era: "post-conciliar",
    kind: "pope",
    tags: ["papacy"],
    location: "Rome",
    context:
      "In the year of three popes — Paul VI dies on 6 August and John Paul I reigns from 26 August to 28 September — Karol Wojtyła of Kraków is elected.",
    significance: "First non-Italian pope since 1523; a pontificate of twenty-six years.",
    citation: `${W}Pope_John_Paul_II`,
    links: {
      popes: ["pope-saint-john-paul-ii", "pope-john-paul-i"],
      saints: ["saint-john-paul-ii"],
    },
  },
  {
    slug: "john-paul-ii-first-pilgrimage-to-poland",
    title: "John Paul II's first pilgrimage to Poland",
    year: 1979,
    date: "1979-06-02",
    precision: "day",
    era: "post-conciliar",
    kind: "event",
    location: "Warsaw",
    context:
      'In Victory Square the pope prays, "Let your Spirit descend and renew the face of the earth — the face of this land."',
    significance: "A catalyst for Solidarity and the fall of communism in Eastern Europe.",
    citation: `${W}Pope_John_Paul_II's_visit_to_Poland_(1979)`,
    links: { popes: ["pope-saint-john-paul-ii"] },
  },
  {
    slug: "assassination-of-oscar-romero",
    title: "St Óscar Romero assassinated",
    year: 1980,
    date: "1980-03-24",
    precision: "day",
    era: "post-conciliar",
    kind: "martyrdom",
    location: "San Salvador",
    context: "The Archbishop of San Salvador is shot while celebrating Mass in a hospital chapel.",
    significance: "Recognised as a martyr; canonised in 2018.",
    citation: `${W}Óscar_Romero`,
    links: { saints: ["saint-oscar-romero"] },
  },
  {
    slug: "assassination-attempt-on-john-paul-ii",
    title: "Assassination attempt on John Paul II",
    year: 1981,
    date: "1981-05-13",
    precision: "day",
    era: "post-conciliar",
    kind: "event",
    location: "St Peter's Square",
    context:
      "Mehmet Ali Ağca shoots the pope during a general audience on the anniversary of the first Fatima apparition.",
    significance:
      "John Paul II credits Our Lady of Fatima with saving his life and forgives his attacker.",
    citation: `${W}Attempted_assassination_of_Pope_John_Paul_II`,
    links: { popes: ["pope-saint-john-paul-ii"] },
  },
  {
    slug: "code-of-canon-law-1983",
    title: "1983 Code of Canon Law",
    year: 1983,
    date: "1983-01-25",
    precision: "day",
    era: "post-conciliar",
    kind: "document",
    tags: ["canon"],
    location: "Rome",
    context:
      "John Paul II promulgates the revised code with the apostolic constitution Sacrae disciplinae leges.",
    significance:
      "The law of the Latin Church today; the Code of Canons of the Eastern Churches follows in 1990.",
    citation: `${W}1983_Code_of_Canon_Law`,
    links: { popes: ["pope-saint-john-paul-ii"] },
  },
  {
    slug: "world-youth-day-instituted",
    title: "World Youth Day instituted",
    year: 1985,
    date: "1985-12-20",
    precision: "day",
    era: "post-conciliar",
    kind: "event",
    location: "Rome",
    context: "John Paul II announces the institution of an annual celebration of World Youth Day.",
    significance: "Grows into the largest recurring gathering of Catholics in the world.",
    citation: `${W}World_Youth_Day`,
    links: { popes: ["pope-saint-john-paul-ii"] },
  },
  {
    slug: "assisi-world-day-of-prayer-for-peace",
    title: "Assisi World Day of Prayer for Peace",
    year: 1986,
    date: "1986-10-27",
    precision: "day",
    era: "post-conciliar",
    kind: "event",
    location: "Assisi",
    context:
      "At the invitation of John Paul II, leaders of the world's religions gather in Assisi to pray for peace.",
    significance: "Interreligious dialogue in the spirit of Nostra Aetate.",
    citation: `${W}World_Day_of_Prayer_for_Peace`,
    links: { popes: ["pope-saint-john-paul-ii"] },
  },
  {
    slug: "great-jubilee-2000",
    title: "Great Jubilee of the Year 2000 opens",
    year: 1999,
    date: "1999-12-24",
    precision: "day",
    era: "post-conciliar",
    kind: "event",
    location: "St Peter's",
    context:
      "John Paul II opens the Holy Door on Christmas Eve; the Day of Pardon follows on 12 March 2000.",
    significance: "The Church enters the third millennium.",
    citation: `${W}Great_Jubilee`,
    links: { popes: ["pope-saint-john-paul-ii"] },
  },
  {
    slug: "canonization-of-faustina-divine-mercy-sunday",
    title: "St Faustina canonised; Divine Mercy Sunday instituted",
    year: 2000,
    date: "2000-04-30",
    precision: "day",
    era: "post-conciliar",
    kind: "saint",
    location: "Rome",
    context:
      "John Paul II canonises the Polish nun and declares the Second Sunday of Easter to be Divine Mercy Sunday.",
    significance: "The Divine Mercy devotion becomes universal.",
    citation: `${W}Faustina_Kowalska`,
    links: { saints: ["saint-faustina-kowalska"], popes: ["pope-saint-john-paul-ii"] },
  },
  {
    slug: "dallas-charter",
    title: "US bishops adopt the Dallas Charter",
    year: 2002,
    date: "2002-06-14",
    precision: "day",
    era: "post-conciliar",
    kind: "document",
    location: "Dallas",
    context:
      "The United States bishops adopt the Charter for the Protection of Children and Young People.",
    significance:
      "Reforms in response to the abuse crisis; the universal norms of Vos estis lux mundi follow in 2019.",
    citation: `${W}Charter_for_the_Protection_of_Children_and_Young_People`,
  },
  {
    slug: "death-of-john-paul-ii",
    title: "Death of St John Paul II",
    year: 2005,
    date: "2005-04-02",
    precision: "day",
    era: "post-conciliar",
    kind: "pope",
    location: "Vatican",
    context:
      'The pope dies on the vigil of Divine Mercy Sunday; crowds at his funeral cry "Santo subito."',
    significance: "Canonised on 27 April 2014.",
    citation: `${W}Death_and_funeral_of_Pope_John_Paul_II`,
    links: { popes: ["pope-saint-john-paul-ii"], saints: ["saint-john-paul-ii"] },
  },
  {
    slug: "election-of-benedict-xvi",
    title: "Benedict XVI elected",
    year: 2005,
    date: "2005-04-19",
    precision: "day",
    era: "post-conciliar",
    kind: "pope",
    tags: ["papacy"],
    location: "Rome",
    context:
      "Joseph Ratzinger, Prefect of the Congregation for the Doctrine of the Faith, is elected.",
    significance: "Deus Caritas Est and Summorum Pontificum.",
    citation: `${W}Pope_Benedict_XVI`,
    links: { popes: ["pope-benedict-xvi"] },
  },
  {
    slug: "summorum-pontificum",
    title: "Summorum Pontificum",
    year: 2007,
    date: "2007-07-07",
    precision: "day",
    era: "post-conciliar",
    kind: "document",
    tags: ["liturgy"],
    location: "Rome",
    context: "Benedict XVI's motu proprio permits wider use of the 1962 Roman Missal.",
    significance: "Its provisions are restricted by Traditionis custodes in 2021.",
    citation: `${W}Summorum_Pontificum`,
    links: { popes: ["pope-benedict-xvi"] },
  },
  {
    slug: "anglicanorum-coetibus",
    title: "Anglicanorum coetibus",
    year: 2009,
    date: "2009-11-04",
    precision: "day",
    era: "post-conciliar",
    kind: "document",
    location: "Rome",
    context:
      "Benedict XVI's apostolic constitution provides personal ordinariates for former Anglicans entering full communion.",
    significance: "Ordinariates are erected in 2011 and 2012.",
    citation: `${W}Anglicanorum_coetibus`,
    links: { popes: ["pope-benedict-xvi"] },
  },
  {
    slug: "resignation-of-benedict-xvi",
    title: "Benedict XVI resigns",
    year: 2013,
    date: "2013-02-28",
    precision: "day",
    era: "post-conciliar",
    kind: "pope",
    tags: ["papacy"],
    location: "Vatican",
    context:
      "Announced on 11 February 2013, the resignation takes effect at 8 p.m. on 28 February — the first since 1415.",
    significance: "Benedict lives on as pope emeritus.",
    citation: `${W}Resignation_of_Pope_Benedict_XVI`,
    links: { popes: ["pope-benedict-xvi"] },
  },
  {
    slug: "election-of-pope-francis",
    title: "Pope Francis elected",
    year: 2013,
    date: "2013-03-13",
    precision: "day",
    era: "post-conciliar",
    kind: "pope",
    tags: ["papacy"],
    location: "Rome",
    context:
      "Jorge Mario Bergoglio of Buenos Aires is elected — the first Jesuit and the first pope from the Americas.",
    significance: "Evangelii Gaudium, Laudato si', and the path of synodality.",
    citation: `${W}Pope_Francis`,
    links: { popes: ["pope-francis"] },
  },
  {
    slug: "canonization-of-john-xxiii-and-john-paul-ii",
    title: "Canonisation of Sts John XXIII and John Paul II",
    year: 2014,
    date: "2014-04-27",
    precision: "day",
    era: "post-conciliar",
    kind: "saint",
    location: "St Peter's Square",
    context: "Pope Francis canonises the two popes on Divine Mercy Sunday.",
    significance: "Two conciliar popes raised to the altars.",
    citation: `${W}Canonization_of_Pope_John_XXIII_and_Pope_John_Paul_II`,
    links: {
      popes: ["pope-saint-john-xxiii", "pope-saint-john-paul-ii", "pope-francis"],
      saints: ["saint-john-paul-ii"],
    },
  },
  {
    slug: "jubilee-of-mercy",
    title: "Extraordinary Jubilee of Mercy",
    year: 2015,
    date: "2015-12-08",
    precision: "day",
    era: "post-conciliar",
    kind: "event",
    location: "St Peter's",
    context: "Pope Francis opens the Holy Door for a jubilee that runs until 20 November 2016.",
    significance: "Proclaimed by the bull Misericordiae Vultus.",
    citation: `${W}Extraordinary_Jubilee_of_Mercy`,
    links: { popes: ["pope-francis"] },
  },
  {
    slug: "francis-meets-patriarch-kirill",
    title: "Pope Francis meets Patriarch Kirill",
    year: 2016,
    date: "2016-02-12",
    precision: "day",
    era: "post-conciliar",
    kind: "event",
    location: "Havana",
    context: "The first meeting in history between a pope and a Patriarch of Moscow.",
    significance: "A new chapter in Catholic–Russian Orthodox relations.",
    citation: `${W}2016_meeting_of_Pope_Francis_and_Patriarch_Kirill`,
    links: { popes: ["pope-francis"] },
  },
  {
    slug: "document-on-human-fraternity",
    title: "Document on Human Fraternity",
    year: 2019,
    date: "2019-02-04",
    precision: "day",
    era: "post-conciliar",
    kind: "document",
    location: "Abu Dhabi",
    context:
      "Pope Francis and the Grand Imam of al-Azhar sign a joint declaration on human fraternity for world peace and living together.",
    significance: "A basis for the encyclical Fratelli Tutti.",
    citation: `${W}Document_on_Human_Fraternity`,
    links: { popes: ["pope-francis"] },
  },
  {
    slug: "urbi-et-orbi-pandemic",
    title: "Extraordinary Urbi et Orbi during the pandemic",
    year: 2020,
    date: "2020-03-27",
    precision: "day",
    era: "post-conciliar",
    kind: "event",
    location: "Empty St Peter's Square",
    context:
      "Pope Francis prays alone in the rain before an empty square and gives the Urbi et Orbi blessing with the Blessed Sacrament.",
    significance: "An image of the Church in the COVID-19 crisis.",
    citation:
      "https://www.vatican.va/content/francesco/en/homilies/2020/documents/papa-francesco_20200327_omelia-epidemia.html",
    links: { popes: ["pope-francis"] },
  },
  {
    slug: "death-of-benedict-xvi",
    title: "Death of Benedict XVI",
    year: 2022,
    date: "2022-12-31",
    precision: "day",
    era: "post-conciliar",
    kind: "pope",
    location: "Vatican",
    context: "The pope emeritus dies at the Mater Ecclesiae monastery aged ninety-five.",
    significance: "His funeral is celebrated by Pope Francis on 5 January 2023.",
    citation: `${W}Death_and_funeral_of_Pope_Benedict_XVI`,
    links: { popes: ["pope-benedict-xvi", "pope-francis"] },
  },
  {
    slug: "synod-on-synodality",
    title: "Synod on Synodality assemblies",
    year: 2023,
    date: "2023-10-04",
    precision: "day",
    era: "post-conciliar",
    kind: "event",
    location: "Rome",
    context:
      "The first assembly meets in October 2023 and the second in October 2024, which approves its final document on 26 October 2024.",
    significance: "Lay members vote in a synod of bishops for the first time.",
    citation: `${W}Synod_on_Synodality`,
    links: { popes: ["pope-francis"] },
  },
  {
    slug: "fiducia-supplicans",
    title: "Fiducia supplicans",
    year: 2023,
    date: "2023-12-18",
    precision: "day",
    era: "post-conciliar",
    kind: "document",
    location: "Rome",
    context:
      "The Dicastery for the Doctrine of the Faith issues a declaration on the pastoral meaning of blessings.",
    significance: "Prompts wide debate among bishops' conferences.",
    citation: `${W}Fiducia_supplicans`,
  },
  {
    slug: "jubilee-2025-opens",
    title: 'Jubilee 2025 "Pilgrims of Hope" opens',
    year: 2024,
    date: "2024-12-24",
    precision: "day",
    era: "post-conciliar",
    kind: "event",
    location: "St Peter's",
    context:
      "Pope Francis opens the Holy Door on Christmas Eve, as proclaimed in the bull Spes non confundit of 9 May 2024.",
    significance: "An ordinary Jubilee, closed on the Epiphany of 2026.",
    citation: `${W}2025_Jubilee`,
    links: { popes: ["pope-francis"] },
  },
  {
    slug: "death-of-pope-francis",
    title: "Death of Pope Francis",
    year: 2025,
    date: "2025-04-21",
    precision: "day",
    era: "post-conciliar",
    kind: "pope",
    location: "Vatican",
    context: "Pope Francis dies on Easter Monday; he is buried in the Basilica of St Mary Major.",
    significance: "The end of a twelve-year pontificate.",
    citation: `${W}Death_and_funeral_of_Pope_Francis`,
    links: { popes: ["pope-francis"] },
  },
  {
    slug: "election-of-pope-leo-xiv",
    title: "Pope Leo XIV elected",
    year: 2025,
    date: "2025-05-08",
    precision: "day",
    era: "post-conciliar",
    kind: "pope",
    tags: ["papacy"],
    location: "Rome",
    context: "Robert Francis Prevost is elected, the first pope from the United States.",
    significance: "His first apostolic exhortation, Dilexi Te, follows on 9 October 2025.",
    citation: `${W}Pope_Leo_XIV`,
    links: { popes: ["pope-leo-xiv"] },
  },
];
