import type { ChurchHistoryEvent } from "./types";

/**
 * Church-history timeline events, part 1: the Apostolic Age through the
 * early Middle Ages (c. 33 – 787). Every event cites one authoritative page;
 * approximate dates carry `precision: "circa"`, and a day is stored only
 * where the exact day is well attested.
 */
export const EVENTS_1: ChurchHistoryEvent[] = [
  // ---------------------------------------------------------------- Apostolic
  {
    slug: "pentecost",
    title: "Pentecost — the Church is born",
    year: 33,
    precision: "circa",
    era: "apostolic",
    kind: "event",
    tags: ["holy-spirit"],
    location: "Jerusalem",
    context:
      "Fifty days after Easter the Holy Spirit descends on the Apostles and Mary in the upper room (Acts 2).",
    significance:
      "Traditionally the birthday of the Church; Peter's first sermon draws about three thousand baptisms.",
    citation: "https://en.wikipedia.org/wiki/Pentecost",
    links: { saints: ["saint-peter"] },
  },
  {
    slug: "martyrdom-of-saint-stephen",
    title: "Martyrdom of St Stephen",
    year: 34,
    precision: "circa",
    era: "apostolic",
    kind: "martyrdom",
    location: "Jerusalem",
    context:
      "The deacon Stephen is stoned after his speech before the Sanhedrin (Acts 7); Saul consents.",
    significance: "First Christian martyr; persecution scatters the Church beyond Jerusalem.",
    citation: "https://en.wikipedia.org/wiki/Saint_Stephen",
    links: { saints: ["saint-stephen"] },
  },
  {
    slug: "conversion-of-saint-paul",
    title: "Conversion of St Paul",
    year: 35,
    precision: "circa",
    era: "apostolic",
    kind: "saint",
    location: "Road to Damascus",
    context: "Saul of Tarsus, persecutor, encounters the risen Christ (Acts 9).",
    significance: "Makes the Apostle to the Gentiles; his letters form much of the New Testament.",
    citation: "https://en.wikipedia.org/wiki/Conversion_of_Paul_the_Apostle",
    links: { saints: ["saint-paul"] },
  },
  {
    slug: "martyrdom-of-saint-james-the-greater",
    title: "Martyrdom of St James the Greater",
    year: 44,
    precision: "circa",
    era: "apostolic",
    kind: "martyrdom",
    location: "Jerusalem",
    context: "Herod Agrippa I has James, son of Zebedee, put to the sword (Acts 12:2).",
    significance: "First of the Twelve to be martyred.",
    citation: "https://en.wikipedia.org/wiki/James_the_Great",
    links: { saints: ["saint-james-the-greater"] },
  },
  {
    slug: "pauls-first-missionary-journey",
    title: "Paul's first missionary journey",
    year: 46,
    precision: "circa",
    era: "apostolic",
    kind: "mission",
    location: "Antioch, Cyprus, Asia Minor",
    context: "Barnabas and Paul are sent from Antioch (Acts 13–14).",
    significance: "Begins the systematic mission to the Gentiles.",
    citation: "https://en.wikipedia.org/wiki/Paul_the_Apostle",
    links: { saints: ["saint-paul"] },
  },
  {
    slug: "council-of-jerusalem",
    title: "Council of Jerusalem",
    year: 50,
    precision: "circa",
    era: "apostolic",
    kind: "council",
    location: "Jerusalem",
    context: "Apostles and elders decide Gentile converts need not be circumcised (Acts 15).",
    significance: "Prototype of every later council; Peter and James lead the decision.",
    citation: "https://en.wikipedia.org/wiki/Council_of_Jerusalem",
    links: { saints: ["saint-peter"] },
  },
  {
    slug: "great-fire-of-rome-neronian-persecution",
    title: "Great Fire of Rome and Nero's persecution",
    year: 64,
    date: "0064-07-18",
    precision: "day",
    era: "apostolic",
    kind: "event",
    tags: ["persecution"],
    location: "Rome",
    context: "Nero blames Christians for the fire and executes them in his gardens and circus.",
    significance:
      "First imperial persecution; Rome's Christian community produces its first martyrs.",
    citation: "https://en.wikipedia.org/wiki/Great_Fire_of_Rome",
  },
  {
    slug: "martyrdom-of-saint-peter",
    title: "Martyrdom of St Peter",
    year: 64,
    precision: "circa",
    era: "apostolic",
    kind: "martyrdom",
    tags: ["papacy"],
    location: "Vatican Hill, Rome",
    context: "Peter is crucified under Nero; buried where St Peter's Basilica stands.",
    significance: "Seals the Roman primacy in blood; the papacy continues from him.",
    citation: "https://en.wikipedia.org/wiki/Saint_Peter",
    links: { popes: ["pope-saint-peter"], saints: ["saint-peter"] },
  },
  {
    slug: "martyrdom-of-saint-paul",
    title: "Martyrdom of St Paul",
    year: 67,
    precision: "circa",
    era: "apostolic",
    kind: "martyrdom",
    location: "Rome",
    context: "Paul is beheaded on the Ostian Way.",
    significance: "Rome becomes the city of the two Apostles.",
    citation: "https://en.wikipedia.org/wiki/Paul_the_Apostle",
    links: { saints: ["saint-paul"] },
  },
  {
    slug: "destruction-of-the-temple",
    title: "Destruction of the Temple of Jerusalem",
    year: 70,
    precision: "year",
    era: "apostolic",
    kind: "event",
    location: "Jerusalem",
    context: "Titus's legions sack Jerusalem and burn the Temple.",
    significance:
      "Definitively separates the Church from Temple Judaism; centre of gravity shifts to Antioch and Rome.",
    citation: "https://en.wikipedia.org/wiki/Siege_of_Jerusalem_(70_CE)",
  },
  {
    slug: "first-epistle-of-clement",
    title: "First Letter of Clement",
    year: 96,
    precision: "circa",
    era: "apostolic",
    kind: "document",
    tags: ["papacy"],
    location: "Rome → Corinth",
    context: "Pope Clement I writes to restore deposed presbyters in Corinth.",
    significance: "Earliest surviving exercise of Roman authority outside Rome.",
    citation: "https://en.wikipedia.org/wiki/First_Epistle_of_Clement",
    links: { popes: ["pope-saint-clement-i"], saints: ["saint-clement-of-rome"] },
  },
  {
    slug: "death-of-saint-john-the-apostle",
    title: "Death of St John, end of the apostolic age",
    year: 100,
    precision: "circa",
    era: "apostolic",
    kind: "saint",
    location: "Ephesus",
    context: "The last Apostle dies after writing the Fourth Gospel and Revelation.",
    significance:
      "Public revelation closes; the sub-apostolic Church relies on Tradition and the bishops.",
    citation: "https://en.wikipedia.org/wiki/John_the_Apostle",
  },

  // -------------------------------------------------------------- Persecution
  {
    slug: "martyrdom-of-saint-ignatius-of-antioch",
    title: "Martyrdom of St Ignatius of Antioch",
    year: 107,
    precision: "circa",
    era: "persecution",
    kind: "martyrdom",
    location: "Rome",
    context: "Bishop of Antioch thrown to beasts; writes seven letters en route.",
    significance:
      'First use of "Catholic Church"; witnesses to bishops, Eucharist, Roman pre-eminence.',
    citation: "https://en.wikipedia.org/wiki/Ignatius_of_Antioch",
    links: { saints: ["saint-ignatius-of-antioch"] },
  },
  {
    slug: "pliny-trajan-correspondence",
    title: "Pliny and Trajan on the Christians",
    year: 112,
    precision: "circa",
    era: "persecution",
    kind: "document",
    location: "Bithynia",
    context: "Governor Pliny asks how to try Christians; Trajan replies.",
    significance: "Earliest pagan description of Christian worship and of imperial policy.",
    citation: "https://en.wikipedia.org/wiki/Pliny_the_Younger_on_Christians",
  },
  {
    slug: "martyrdom-of-saint-polycarp",
    title: "Martyrdom of St Polycarp",
    year: 155,
    precision: "circa",
    era: "persecution",
    kind: "martyrdom",
    location: "Smyrna",
    context: "Aged bishop and disciple of John burned in the stadium.",
    significance: "Earliest detailed martyr account; model of the cult of martyrs.",
    citation: "https://en.wikipedia.org/wiki/Polycarp",
    links: { saints: ["saint-polycarp"] },
  },
  {
    slug: "saint-justin-martyr-first-apology",
    title: "St Justin's First Apology",
    year: 155,
    precision: "circa",
    era: "persecution",
    kind: "document",
    tags: ["liturgy"],
    location: "Rome",
    context: "Philosopher-convert defends Christians to the emperor; describes Sunday Mass.",
    significance: "Earliest description of the Eucharistic liturgy; martyred c. 165.",
    citation: "https://en.wikipedia.org/wiki/Justin_Martyr",
    links: { saints: ["saint-justin-martyr"] },
  },
  {
    slug: "martyrs-of-lyon",
    title: "Martyrs of Lyon",
    year: 177,
    precision: "year",
    era: "persecution",
    kind: "martyrdom",
    location: "Lyon",
    context: "Blandina, Pothinus and companions killed.",
    significance: "Persecution reaches Gaul; Irenaeus succeeds Pothinus.",
    citation: "https://en.wikipedia.org/wiki/Persecution_in_Lyon",
  },
  {
    slug: "irenaeus-against-heresies",
    title: "Irenaeus writes Against Heresies",
    year: 180,
    precision: "circa",
    era: "persecution",
    kind: "document",
    tags: ["canon"],
    location: "Lyon",
    context: "Refutes Gnosticism by apostolic succession and the rule of faith.",
    significance: 'Rome\'s "pre-eminent authority"; canon of four Gospels affirmed.',
    citation: "https://en.wikipedia.org/wiki/Irenaeus",
    links: {
      saints: ["saint-irenaeus-of-lyon"],
      doctors: ["doctor-irenaeus-of-lyon"],
    },
  },
  {
    slug: "martyrdom-of-perpetua-and-felicity",
    title: "Martyrdom of Sts Perpetua and Felicity",
    year: 203,
    date: "0203-03-07",
    precision: "day",
    era: "persecution",
    kind: "martyrdom",
    location: "Carthage",
    context: "Young mother and her slave killed in the arena; Perpetua's prison diary survives.",
    significance: "Earliest Christian text by a woman; named in the Roman Canon.",
    citation: "https://en.wikipedia.org/wiki/Perpetua_and_Felicity",
    links: { saints: ["saint-perpetua-and-felicity"] },
  },
  {
    slug: "decian-persecution",
    title: "Decian persecution",
    year: 250,
    precision: "year",
    era: "persecution",
    kind: "event",
    tags: ["persecution"],
    location: "Empire-wide",
    context: "Decius orders universal sacrifice; Pope Fabian martyred 20 January 250.",
    significance: "First empire-wide persecution; the lapsi controversy shapes penance.",
    citation: "https://en.wikipedia.org/wiki/Decian_persecution",
    links: { popes: ["pope-saint-fabian"], saints: ["saint-fabian"] },
  },
  {
    slug: "martyrdom-of-saint-cyprian",
    title: "Valerian's persecution: Sts Sixtus II, Lawrence, Cyprian",
    year: 258,
    date: "0258-09-14",
    precision: "day",
    era: "persecution",
    kind: "martyrdom",
    tags: ["persecution"],
    location: "Rome & Carthage",
    context:
      "Pope Sixtus II (6 August), deacon Lawrence (10 August) and Bishop Cyprian (14 September) are executed.",
    significance: "Cyprian's On the Unity of the Church; Lawrence becomes Rome's great martyr.",
    citation: "https://en.wikipedia.org/wiki/Cyprian",
    links: {
      saints: ["saint-cyprian-of-carthage", "saint-lawrence"],
      popes: ["pope-saint-sixtus-ii"],
    },
  },
  {
    slug: "saint-anthony-goes-to-the-desert",
    title: "St Anthony of Egypt embraces the desert",
    year: 270,
    precision: "circa",
    era: "persecution",
    kind: "saint",
    tags: ["monastic"],
    location: "Egypt",
    context: "Anthony sells all and lives as a hermit; Athanasius later writes his Life.",
    significance: "Father of monasticism; the desert tradition spreads across the Church.",
    citation: "https://en.wikipedia.org/wiki/Anthony_the_Great",
    links: { saints: ["saint-anthony-the-abbot"] },
  },
  {
    slug: "conversion-of-armenia",
    title: "Armenia adopts Christianity",
    year: 301,
    precision: "circa",
    era: "persecution",
    kind: "event",
    location: "Armenia",
    context: "King Tiridates III is baptised by St Gregory the Illuminator (traditional date).",
    significance: "First nation to adopt Christianity as its state religion.",
    citation: "https://en.wikipedia.org/wiki/Gregory_the_Illuminator",
  },
  {
    slug: "diocletianic-persecution",
    title: "The Great Persecution under Diocletian",
    year: 303,
    date: "0303-02-24",
    precision: "day",
    era: "persecution",
    kind: "event",
    tags: ["persecution"],
    location: "Empire-wide",
    context: "Edicts order churches razed, Scriptures burned and clergy arrested.",
    significance:
      "Last and bloodiest persecution (Sts Agnes, Lucy, Sebastian, George and many others).",
    citation: "https://en.wikipedia.org/wiki/Diocletianic_Persecution",
    links: { saints: ["saint-agnes", "saint-lucy", "saint-sebastian"] },
  },

  // ------------------------------------------------------------------ Fathers
  {
    slug: "edict-of-milan",
    title: "Edict of Milan",
    year: 313,
    precision: "year",
    era: "fathers",
    kind: "document",
    location: "Milan",
    context: "Constantine and Licinius grant religious liberty and restore Church property.",
    significance: "Ends the persecutions; the Church emerges into public life.",
    citation: "https://en.wikipedia.org/wiki/Edict_of_Milan",
  },
  {
    slug: "council-of-arles-314",
    title: "Council of Arles",
    year: 314,
    precision: "year",
    era: "fathers",
    kind: "council",
    location: "Arles",
    context: "Western bishops rule against the Donatists.",
    significance: "First Western council under imperial patronage.",
    citation: "https://en.wikipedia.org/wiki/Council_of_Arles",
  },
  {
    slug: "first-council-of-nicaea",
    title: "First Council of Nicaea",
    year: 325,
    date: "0325-05-20",
    precision: "day",
    era: "fathers",
    kind: "council",
    tags: ["dogma"],
    location: "Nicaea",
    context: "Convened by Constantine against Arius.",
    significance:
      "Defines the Son as consubstantial with the Father; Nicene Creed; date of Easter.",
    citation: "https://en.wikipedia.org/wiki/First_Council_of_Nicaea",
    links: {
      documentSlug: "first-council-of-nicaea",
      popes: ["pope-saint-sylvester-i"],
      doctors: ["doctor-athanasius-of-alexandria"],
    },
  },
  {
    slug: "martin-of-tours-founds-liguge",
    title: "St Martin founds Ligugé",
    year: 361,
    precision: "circa",
    era: "fathers",
    kind: "order",
    tags: ["monastic"],
    location: "Gaul",
    context: "The first monastery in Gaul.",
    significance: "Monasticism reaches the West; Martin is later bishop of Tours.",
    citation: "https://en.wikipedia.org/wiki/Ligug%C3%A9_Abbey",
    links: { saints: ["saint-martin-of-tours"] },
  },
  {
    slug: "athanasius-festal-letter-canon",
    title: "Athanasius lists the 27 New Testament books",
    year: 367,
    precision: "year",
    era: "fathers",
    kind: "document",
    tags: ["canon"],
    location: "Alexandria",
    context: "His 39th Festal Letter names the books of the New Testament.",
    significance: "First exact list of the New Testament canon.",
    citation: "https://en.wikipedia.org/wiki/Athanasius_of_Alexandria",
    links: { doctors: ["doctor-athanasius-of-alexandria"] },
  },
  {
    slug: "edict-of-thessalonica",
    title: "Edict of Thessalonica",
    year: 380,
    date: "0380-02-27",
    precision: "day",
    era: "fathers",
    kind: "document",
    location: "Thessalonica",
    context: "Theodosius makes Nicene Christianity the religion of the empire.",
    significance: "Christendom begins.",
    citation: "https://en.wikipedia.org/wiki/Edict_of_Thessalonica",
  },
  {
    slug: "first-council-of-constantinople",
    title: "First Council of Constantinople",
    year: 381,
    precision: "year",
    era: "fathers",
    kind: "council",
    tags: ["dogma"],
    location: "Constantinople",
    context: "Convened against the Pneumatomachi.",
    significance: "Divinity of the Holy Spirit; the Creed said at Mass.",
    citation: "https://en.wikipedia.org/wiki/First_Council_of_Constantinople",
    links: {
      documentSlug: "first-council-of-constantinople",
      popes: ["pope-saint-damasus-i"],
    },
  },
  {
    slug: "jerome-begins-the-vulgate",
    title: "St Jerome begins the Vulgate",
    year: 382,
    precision: "year",
    era: "fathers",
    kind: "document",
    tags: ["scripture"],
    location: "Rome → Bethlehem",
    context: "Pope Damasus commissions a revision of the Latin Bible; the work is finished c. 405.",
    significance: "The Church's Latin Bible for 1,500 years; Trent declares it authentic.",
    citation: "https://en.wikipedia.org/wiki/Vulgate",
    links: { doctors: ["doctor-jerome"], saints: ["saint-jerome"] },
  },
  {
    slug: "baptism-of-saint-augustine",
    title: "Baptism of St Augustine",
    year: 387,
    date: "0387-04-24",
    precision: "day",
    era: "fathers",
    kind: "saint",
    location: "Milan",
    context: "Ambrose baptises Augustine at the Easter Vigil; Monica dies months later.",
    significance: "The greatest Latin Father enters the Church.",
    citation: "https://en.wikipedia.org/wiki/Augustine_of_Hippo",
    links: {
      saints: ["saint-augustine-of-hippo", "saint-monica"],
      doctors: ["doctor-augustine-of-hippo", "doctor-ambrose-of-milan"],
    },
  },
  {
    slug: "council-of-carthage-397",
    title: "Council of Carthage confirms the canon of Scripture",
    year: 397,
    precision: "year",
    era: "fathers",
    kind: "council",
    tags: ["canon"],
    location: "Carthage",
    context: "Lists the 73 books of the Bible, as Hippo (393) had.",
    significance: "The Catholic canon received in the West.",
    citation: "https://en.wikipedia.org/wiki/Council_of_Carthage_(397)",
  },
  {
    slug: "sack-of-rome-410",
    title: "Sack of Rome by Alaric",
    year: 410,
    date: "0410-08-24",
    precision: "day",
    era: "fathers",
    kind: "event",
    location: "Rome",
    context: "The Visigoths sack the city; pagans blame Christianity.",
    significance: "Augustine answers with The City of God.",
    citation: "https://en.wikipedia.org/wiki/Sack_of_Rome_(410)",
  },
  {
    slug: "death-of-saint-augustine",
    title: "Death of St Augustine",
    year: 430,
    date: "0430-08-28",
    precision: "day",
    era: "fathers",
    kind: "saint",
    location: "Hippo",
    context: "Dies while the Vandals besiege his city.",
    significance: "His theology of grace and the Church shapes the West.",
    citation: "https://en.wikipedia.org/wiki/Augustine_of_Hippo",
    links: {
      saints: ["saint-augustine-of-hippo"],
      doctors: ["doctor-augustine-of-hippo"],
    },
  },
  {
    slug: "council-of-ephesus",
    title: "Council of Ephesus",
    year: 431,
    date: "0431-06-22",
    precision: "day",
    era: "fathers",
    kind: "council",
    tags: ["dogma", "marian"],
    location: "Ephesus",
    context: "Convened against Nestorius.",
    significance: "Mary is Theotokos; one Person in Christ.",
    citation: "https://en.wikipedia.org/wiki/Council_of_Ephesus",
    links: {
      documentSlug: "council-of-ephesus",
      doctors: ["doctor-cyril-of-alexandria"],
      popes: ["pope-saint-celestine-i"],
    },
  },
  {
    slug: "saint-patrick-mission-to-ireland",
    title: "St Patrick's mission to Ireland",
    year: 432,
    precision: "circa",
    era: "fathers",
    kind: "mission",
    location: "Ireland",
    context: "A former slave returns as bishop.",
    significance: 'Ireland converted; later the "island of saints and scholars".',
    citation: "https://en.wikipedia.org/wiki/Saint_Patrick",
    links: { saints: ["saint-patrick"] },
  },
  {
    slug: "council-of-chalcedon",
    title: "Council of Chalcedon",
    year: 451,
    date: "0451-10-08",
    precision: "day",
    era: "fathers",
    kind: "council",
    tags: ["dogma"],
    location: "Chalcedon",
    context: 'Pope Leo\'s Tome is received: "Peter has spoken through Leo."',
    significance: "Two natures in one Person; Monophysitism condemned.",
    citation: "https://en.wikipedia.org/wiki/Council_of_Chalcedon",
    links: {
      documentSlug: "council-of-chalcedon",
      popes: ["pope-saint-leo-the-great"],
      doctors: ["doctor-leo-the-great"],
    },
  },
  {
    slug: "leo-the-great-meets-attila",
    title: "Pope Leo the Great turns back Attila",
    year: 452,
    precision: "year",
    era: "fathers",
    kind: "pope",
    tags: ["papacy"],
    location: "Mincio river, Italy",
    context: "Leo persuades the Huns to spare Rome.",
    significance: "The papacy emerges as protector of Rome.",
    citation: "https://en.wikipedia.org/wiki/Pope_Leo_I",
    links: { popes: ["pope-saint-leo-the-great"], doctors: ["doctor-leo-the-great"] },
  },
  {
    slug: "fall-of-the-western-roman-empire",
    title: "Fall of the Western Roman Empire",
    year: 476,
    date: "0476-09-04",
    precision: "day",
    era: "fathers",
    kind: "event",
    location: "Ravenna",
    context: "Odoacer deposes Romulus Augustulus.",
    significance: "The Church becomes the bearer of Roman civilisation to the barbarian kingdoms.",
    citation: "https://en.wikipedia.org/wiki/Fall_of_the_Western_Roman_Empire",
  },
  {
    slug: "acacian-schism",
    title: "Acacian Schism",
    year: 484,
    precision: "year",
    era: "fathers",
    kind: "schism",
    tags: ["schism"],
    location: "Rome–Constantinople",
    context:
      "Pope Felix III excommunicates Patriarch Acacius over the Henotikon; the breach is healed in 519 by the Formula of Hormisdas.",
    significance: "First formal East–West schism, lasting thirty-five years.",
    citation: "https://en.wikipedia.org/wiki/Acacian_schism",
    links: { popes: ["pope-saint-gelasius-i", "pope-saint-hormisdas"] },
  },
  {
    slug: "baptism-of-clovis",
    title: "Baptism of Clovis",
    year: 496,
    precision: "circa",
    era: "fathers",
    kind: "event",
    location: "Reims",
    context: "The Frankish king is baptised by St Remigius.",
    significance:
      'The Franks become Catholic, not Arian — France the "eldest daughter of the Church".',
    citation: "https://en.wikipedia.org/wiki/Clovis_I",
  },
  {
    slug: "council-of-orange-529",
    title: "Second Council of Orange",
    year: 529,
    date: "0529-07-03",
    precision: "day",
    era: "fathers",
    kind: "council",
    tags: ["grace"],
    location: "Orange",
    context: "Condemns semi-Pelagianism and affirms prevenient grace.",
    significance: "Augustinian doctrine of grace received; later cited by Trent.",
    citation: "https://en.wikipedia.org/wiki/Council_of_Orange_(529)",
  },
  {
    slug: "saint-benedict-founds-monte-cassino",
    title: "St Benedict founds Monte Cassino",
    year: 529,
    precision: "circa",
    era: "fathers",
    kind: "order",
    tags: ["monastic"],
    location: "Monte Cassino",
    context: "Benedict founds the abbey and writes his Rule there (c. 530–540).",
    significance: "The Rule of St Benedict shapes Western monasticism and Europe.",
    citation: "https://en.wikipedia.org/wiki/Benedict_of_Nursia",
    links: { saints: ["saint-benedict-of-nursia", "saint-scholastica"] },
  },
  {
    slug: "second-council-of-constantinople",
    title: "Second Council of Constantinople",
    year: 553,
    date: "0553-05-05",
    precision: "day",
    era: "fathers",
    kind: "council",
    tags: ["dogma"],
    location: "Constantinople",
    context: "Condemns the Three Chapters.",
    significance: "Chalcedon reaffirmed against Nestorian readings.",
    citation: "https://en.wikipedia.org/wiki/Second_Council_of_Constantinople",
    links: {
      documentSlug: "second-council-of-constantinople",
      popes: ["pope-vigilius"],
    },
  },
  {
    slug: "saint-columba-founds-iona",
    title: "St Columba founds Iona",
    year: 563,
    precision: "year",
    era: "fathers",
    kind: "mission",
    tags: ["monastic"],
    location: "Iona",
    context: "Irish monks establish the mission base.",
    significance: "Evangelisation of Scotland and northern England.",
    citation: "https://en.wikipedia.org/wiki/Iona_Abbey",
    links: { saints: ["saint-columba"] },
  },

  // ----------------------------------------------------------- Early medieval
  {
    slug: "election-of-gregory-the-great",
    title: "St Gregory the Great becomes pope",
    year: 590,
    date: "0590-09-03",
    precision: "day",
    era: "early-medieval",
    kind: "pope",
    tags: ["papacy"],
    location: "Rome",
    context:
      "Elected after the death of Pelagius II and consecrated on 3 September 590, Gregory is the first monk to become pope.",
    significance: 'Pastoral Rule, chant, missions; "servant of the servants of God".',
    citation: "https://en.wikipedia.org/wiki/Pope_Gregory_I",
    links: {
      popes: ["pope-saint-gregory-the-great"],
      doctors: ["doctor-gregory-the-great"],
    },
  },
  {
    slug: "gregorian-mission-to-england",
    title: "Augustine of Canterbury's mission to England",
    year: 597,
    precision: "year",
    era: "early-medieval",
    kind: "mission",
    location: "Kent",
    context: "Gregory sends Augustine; King Æthelberht is baptised.",
    significance: "See of Canterbury founded; England re-evangelised.",
    citation: "https://en.wikipedia.org/wiki/Gregorian_mission",
    links: {
      saints: ["saint-augustine-of-canterbury"],
      popes: ["pope-saint-gregory-the-great"],
    },
  },
  {
    slug: "arab-conquest-of-jerusalem",
    title: "Arab conquest of Jerusalem",
    year: 637,
    precision: "circa",
    era: "early-medieval",
    kind: "event",
    location: "Jerusalem",
    context: "Patriarch Sophronius surrenders the city.",
    significance: "The Christian East passes under Islam; Antioch and Alexandria follow.",
    citation: "https://en.wikipedia.org/wiki/Siege_of_Jerusalem_(636%E2%80%93637)",
  },
  {
    slug: "synod-of-whitby",
    title: "Synod of Whitby",
    year: 664,
    precision: "year",
    era: "early-medieval",
    kind: "council",
    location: "Whitby",
    context: "Northumbria adopts the Roman Easter and customs over Celtic usage.",
    significance: "The English Church aligned with Rome.",
    citation: "https://en.wikipedia.org/wiki/Synod_of_Whitby",
  },
  {
    slug: "third-council-of-constantinople",
    title: "Third Council of Constantinople",
    year: 680,
    date: "0680-11-07",
    precision: "day",
    era: "early-medieval",
    kind: "council",
    tags: ["dogma"],
    location: "Constantinople",
    context: "Convened against Monothelitism.",
    significance: "Two wills in Christ.",
    citation: "https://en.wikipedia.org/wiki/Third_Council_of_Constantinople",
    links: { documentSlug: "third-council-of-constantinople" },
  },
  {
    slug: "byzantine-iconoclasm-begins",
    title: "Iconoclasm begins under Leo III",
    year: 726,
    precision: "circa",
    era: "early-medieval",
    kind: "event",
    location: "Constantinople",
    context: "The emperor bans sacred images; John of Damascus writes in their defence.",
    significance: "A crisis lasting until 843.",
    citation: "https://en.wikipedia.org/wiki/Byzantine_Iconoclasm",
    links: { doctors: ["doctor-john-of-damascus"] },
  },
  {
    slug: "bede-ecclesiastical-history",
    title: "Bede completes the Ecclesiastical History",
    year: 731,
    precision: "year",
    era: "early-medieval",
    kind: "document",
    location: "Jarrow",
    context: "A history of the English Church from the Roman mission to his own day.",
    significance: "Father of English history; popularises AD dating.",
    citation: "https://en.wikipedia.org/wiki/Bede",
    links: {
      saints: ["saint-bede-the-venerable"],
      doctors: ["doctor-bede-the-venerable"],
    },
  },
  {
    slug: "battle-of-tours",
    title: "Battle of Tours",
    year: 732,
    date: "0732-10-10",
    precision: "day",
    era: "early-medieval",
    kind: "event",
    location: "near Tours",
    context: "Charles Martel halts the Umayyad advance.",
    significance: "Frankish Christendom secured.",
    citation: "https://en.wikipedia.org/wiki/Battle_of_Tours",
  },
  {
    slug: "martyrdom-of-saint-boniface",
    title: "Martyrdom of St Boniface",
    year: 754,
    date: "0754-06-05",
    precision: "day",
    era: "early-medieval",
    kind: "martyrdom",
    location: "Dokkum",
    context: "The Apostle of Germany is killed by Frisians.",
    significance: "The German Church organised in union with Rome.",
    citation: "https://en.wikipedia.org/wiki/Saint_Boniface",
    links: { saints: ["saint-boniface"] },
  },
  {
    slug: "donation-of-pepin",
    title: "Donation of Pepin",
    year: 756,
    precision: "year",
    era: "early-medieval",
    kind: "event",
    tags: ["papacy"],
    location: "Central Italy",
    context: "Pepin grants conquered Lombard lands to the pope.",
    significance: "Origin of the Papal States (to 1870).",
    citation: "https://en.wikipedia.org/wiki/Donation_of_Pepin",
  },
  {
    slug: "second-council-of-nicaea",
    title: "Second Council of Nicaea",
    year: 787,
    date: "0787-09-24",
    precision: "day",
    era: "early-medieval",
    kind: "council",
    tags: ["dogma"],
    location: "Nicaea",
    context: "Ends the first period of iconoclasm.",
    significance: "Veneration of images defined.",
    citation: "https://en.wikipedia.org/wiki/Second_Council_of_Nicaea",
    links: { documentSlug: "second-council-of-nicaea", popes: ["pope-adrian-i"] },
  },
];
