import type { ChurchHistoryEvent } from "./types";

const W = "https://en.wikipedia.org/wiki/";

/**
 * Church-history spine, part 2: from the coronation of Charlemagne (800) to
 * the execution of Savonarola (1498) — the later Early Middle Ages, the High
 * Middle Ages, and the Western Schism & Renaissance era.
 */
export const EVENTS_2: ChurchHistoryEvent[] = [
  // ---------------------------------------------------------------- Early Middle Ages
  {
    slug: "coronation-of-charlemagne",
    title: "Coronation of Charlemagne",
    year: 800,
    date: "0800-12-25",
    precision: "day",
    era: "early-medieval",
    kind: "event",
    location: "St Peter's, Rome",
    context:
      "On Christmas Day Pope Leo III crowns Charles, King of the Franks, as emperor in St Peter's Basilica.",
    significance:
      "Birth of the Holy Roman Empire and of the Carolingian renaissance in learning, liturgy, and monastic life.",
    citation: `${W}Charlemagne`,
    links: { popes: ["pope-saint-leo-iii"] },
  },
  {
    slug: "mission-of-cyril-and-methodius",
    title: "Sts Cyril and Methodius go to Moravia",
    year: 863,
    precision: "year",
    era: "early-medieval",
    kind: "mission",
    location: "Great Moravia",
    context:
      "The two brothers from Thessalonica bring the liturgy in Slavonic and a new alphabet for the Slavic tongue.",
    significance: "Apostles of the Slavs; named co-patrons of Europe by St John Paul II.",
    citation: `${W}Saints_Cyril_and_Methodius`,
  },
  {
    slug: "photian-schism",
    title: "Photian Schism",
    year: 863,
    precision: "year",
    era: "early-medieval",
    kind: "schism",
    tags: ["schism"],
    location: "Rome and Constantinople",
    context:
      "Pope Nicholas I declares Patriarch Photius deposed; Photius in turn condemns Latin practices, including the Filioque.",
    significance: "A rehearsal of the divisions that would harden into the schism of 1054.",
    citation: `${W}Photian_schism`,
    links: { popes: ["pope-saint-nicholas-i"] },
  },
  {
    slug: "fourth-council-of-constantinople",
    title: "Fourth Council of Constantinople",
    year: 869,
    date: "0869-10-05",
    precision: "day",
    era: "early-medieval",
    kind: "council",
    location: "Constantinople",
    context: "The council deposes Photius and restores Patriarch Ignatius.",
    significance: "The last ecumenical council held in the East in the Catholic reckoning.",
    citation: `${W}Fourth_Council_of_Constantinople_(Catholic_Church)`,
    links: { documentSlug: "fourth-council-of-constantinople" },
  },
  {
    slug: "founding-of-cluny",
    title: "Foundation of Cluny",
    year: 910,
    date: "0910-09-11",
    precision: "day",
    era: "early-medieval",
    kind: "order",
    tags: ["reform"],
    location: "Burgundy",
    context:
      "William of Aquitaine founds the abbey and places it directly under the protection of the pope, free of lay control.",
    significance:
      "The Cluniac reform renews Benedictine monasticism and, in time, the papacy itself.",
    citation: `${W}Cluny_Abbey`,
  },
  {
    slug: "baptism-of-kievan-rus",
    title: "Baptism of Rus'",
    year: 988,
    precision: "year",
    era: "early-medieval",
    kind: "mission",
    location: "Kiev",
    context: "Prince Vladimir of Kiev is baptised and leads his people to the faith.",
    significance: "Christianity takes root among the Eastern Slavs.",
    citation: `${W}Christianization_of_Kievan_Rus'`,
  },
  {
    slug: "peace-of-god",
    title: "Peace of God movement",
    year: 989,
    precision: "year",
    era: "early-medieval",
    kind: "event",
    location: "Charroux",
    context:
      "Bishops gathered at Charroux place clergy, peasants, and church property under protection from armed violence.",
    significance:
      "The Church begins to tame feudal warfare; the Truce of God later limits the days on which fighting is allowed.",
    citation: `${W}Peace_and_Truce_of_God`,
  },
  {
    slug: "coronation-of-saint-stephen-of-hungary",
    title: "St Stephen crowned King of Hungary",
    year: 1000,
    precision: "circa",
    era: "early-medieval",
    kind: "event",
    location: "Esztergom",
    context:
      "Stephen is crowned Hungary's first Christian king; tradition holds that the crown was sent by Pope Sylvester II.",
    significance: "Hungary enters Catholic Christendom.",
    citation: `${W}Stephen_I_of_Hungary`,
    links: {
      saints: ["saint-stephen-of-hungary"],
      popes: ["pope-sylvester-ii"],
    },
  },
  {
    slug: "filioque-in-the-roman-creed",
    title: "Filioque sung in the Creed at Rome",
    year: 1014,
    precision: "year",
    era: "early-medieval",
    kind: "event",
    location: "Rome",
    context:
      "At the coronation of Emperor Henry II, Pope Benedict VIII allows the Creed to be sung at Rome with the words 'and the Son'.",
    significance:
      "Rome adopts the Filioque, which becomes a chief doctrinal grievance of the East.",
    citation: `${W}Filioque`,
  },
  // ---------------------------------------------------------------- High Middle Ages
  {
    slug: "great-schism-1054",
    title: "The Great Schism",
    year: 1054,
    date: "1054-07-16",
    precision: "day",
    era: "high-medieval",
    kind: "schism",
    tags: ["schism"],
    location: "Hagia Sophia, Constantinople",
    context:
      "Cardinal Humbert, legate of Pope Leo IX, lays a bull of excommunication against Patriarch Michael Cerularius on the altar of Hagia Sophia; the patriarch responds in kind.",
    significance:
      "The symbolic start of the split between East and West; the mutual anathemas were lifted in 1965.",
    citation: `${W}East–West_Schism`,
    links: { popes: ["pope-saint-leo-ix"] },
  },
  {
    slug: "papal-election-decree-1059",
    title: "In nomine Domini: cardinals elect the pope",
    year: 1059,
    date: "1059-04-13",
    precision: "day",
    era: "high-medieval",
    kind: "document",
    tags: ["reform"],
    location: "Rome",
    context:
      "Pope Nicholas II's decree takes the election of the pope out of the hands of emperors and Roman nobles and entrusts it to the cardinals.",
    significance: "The origin of the conclave.",
    citation: `${W}In_Nomine_Domini`,
  },
  {
    slug: "dictatus-papae",
    title: "Dictatus papae",
    year: 1075,
    precision: "year",
    era: "high-medieval",
    kind: "document",
    tags: ["reform"],
    location: "Rome",
    context:
      "Twenty-seven propositions on papal power recorded in the register of Pope Gregory VII.",
    significance:
      "A charter of the Gregorian Reform; the Investiture Controversy with the emperor follows.",
    citation: `${W}Dictatus_papae`,
    links: { popes: ["pope-saint-gregory-vii"] },
  },
  {
    slug: "walk-to-canossa",
    title: "Henry IV at Canossa",
    year: 1077,
    date: "1077-01-28",
    precision: "day",
    era: "high-medieval",
    kind: "event",
    tags: ["reform"],
    location: "Canossa",
    context:
      "After three days of penance in the snow outside the castle gate, the excommunicated Emperor Henry IV is absolved by Gregory VII.",
    significance: "An enduring emblem of spiritual authority over temporal power.",
    citation: `${W}Road_to_Canossa`,
    links: { popes: ["pope-saint-gregory-vii"] },
  },
  {
    slug: "founding-of-the-carthusians",
    title: "St Bruno founds the Grande Chartreuse",
    year: 1084,
    precision: "year",
    era: "high-medieval",
    kind: "order",
    location: "Chartreuse",
    context:
      "Bruno of Cologne and six companions settle in the Alpine valley of Chartreuse to live as hermits in community.",
    significance: "The Carthusian tradition, famously 'never reformed because never deformed'.",
    citation: `${W}Carthusians`,
    links: { saints: ["saint-bruno"] },
  },
  {
    slug: "council-of-clermont-first-crusade",
    title: "Council of Clermont: Urban II preaches the First Crusade",
    year: 1095,
    date: "1095-11-27",
    precision: "day",
    era: "high-medieval",
    kind: "event",
    tags: ["crusade"],
    location: "Clermont",
    context:
      "Pope Urban II calls Western knights to the aid of the Eastern Christians and the recovery of Jerusalem; the crowd answers, 'Deus vult'.",
    significance: "The crusading era begins.",
    citation: `${W}Council_of_Clermont`,
    links: { popes: ["pope-blessed-urban-ii"] },
  },
  {
    slug: "founding-of-citeaux",
    title: "Foundation of Cîteaux",
    year: 1098,
    date: "1098-03-21",
    precision: "day",
    era: "high-medieval",
    kind: "order",
    tags: ["reform"],
    location: "Burgundy",
    context:
      "Robert of Molesme and his companions found a 'New Monastery' to return to the strict observance of the Rule of St Benedict.",
    significance:
      "The Cistercian order is born; St Bernard enters around 1112 and carries it across Europe.",
    citation: `${W}Cîteaux_Abbey`,
  },
  {
    slug: "capture-of-jerusalem-1099",
    title: "Crusaders take Jerusalem",
    year: 1099,
    date: "1099-07-15",
    precision: "day",
    era: "high-medieval",
    kind: "event",
    tags: ["crusade"],
    location: "Jerusalem",
    context: "The armies of the First Crusade storm the city.",
    significance: "The Latin Kingdom of Jerusalem is established.",
    citation: `${W}Siege_of_Jerusalem_(1099)`,
  },
  {
    slug: "bernard-founds-clairvaux",
    title: "St Bernard founds Clairvaux",
    year: 1115,
    precision: "year",
    era: "high-medieval",
    kind: "order",
    location: "Champagne",
    context:
      "Sent from Cîteaux with a small band of monks, the young Bernard founds the abbey of Clairvaux and becomes the voice of twelfth-century Christendom.",
    significance:
      "Marian devotion, Cistercian expansion, and the preaching of the Second Crusade all bear his mark.",
    citation: `${W}Bernard_of_Clairvaux`,
    links: {
      saints: ["saint-bernard-of-clairvaux"],
      doctors: ["doctor-bernard-of-clairvaux"],
    },
  },
  {
    slug: "concordat-of-worms",
    title: "Concordat of Worms",
    year: 1122,
    date: "1122-09-23",
    precision: "day",
    era: "high-medieval",
    kind: "document",
    tags: ["reform"],
    location: "Worms",
    context:
      "Emperor Henry V renounces investing bishops with ring and staff; Pope Callixtus II concedes the emperor a presence at elections in Germany.",
    significance: "Ends the Investiture Controversy.",
    citation: `${W}Concordat_of_Worms`,
    links: { popes: ["pope-callixtus-ii"] },
  },
  {
    slug: "first-council-of-the-lateran",
    title: "First Lateran Council",
    year: 1123,
    date: "1123-03-18",
    precision: "day",
    era: "high-medieval",
    kind: "council",
    tags: ["reform"],
    location: "Rome",
    context: "The council confirms the Concordat of Worms and issues reform canons.",
    significance: "The first ecumenical council held in the West.",
    citation: `${W}First_Council_of_the_Lateran`,
    links: {
      documentSlug: "first-council-of-the-lateran",
      popes: ["pope-callixtus-ii"],
    },
  },
  {
    slug: "second-council-of-the-lateran",
    title: "Second Lateran Council",
    year: 1139,
    precision: "year",
    era: "high-medieval",
    kind: "council",
    tags: ["schism", "reform"],
    location: "Rome",
    context:
      "The council closes the schism of the antipope Anacletus II and issues canons on clerical celibacy.",
    significance: "Shapes the discipline of the Latin clergy for centuries.",
    citation: `${W}Second_Council_of_the_Lateran`,
    links: { documentSlug: "second-council-of-the-lateran" },
  },
  {
    slug: "gratians-decretum",
    title: "Gratian's Decretum",
    year: 1140,
    precision: "circa",
    era: "high-medieval",
    kind: "document",
    location: "Bologna",
    context: "The monk Gratian compiles a systematic, reasoned collection of the Church's canons.",
    significance: "The foundation of canon law until the Code of 1917.",
    citation: `${W}Decretum_Gratiani`,
  },
  {
    slug: "lombards-sentences",
    title: "Peter Lombard's Sentences",
    year: 1150,
    precision: "circa",
    era: "high-medieval",
    kind: "document",
    location: "Paris",
    context:
      "Peter Lombard arranges the teaching of Scripture and the Fathers into four books that become the standard theology textbook.",
    significance:
      "Provides the framework for scholastic theology; Aquinas and Bonaventure both wrote commentaries on it.",
    citation: `${W}Sentences`,
  },
  {
    slug: "martyrdom-of-thomas-becket",
    title: "Martyrdom of St Thomas Becket",
    year: 1170,
    date: "1170-12-29",
    precision: "day",
    era: "high-medieval",
    kind: "martyrdom",
    location: "Canterbury",
    context: "The Archbishop of Canterbury is killed in his cathedral by knights of King Henry II.",
    significance:
      "A witness to the liberty of the Church; Canterbury becomes one of Europe's great pilgrimage shrines.",
    citation: `${W}Thomas_Becket`,
    links: { saints: ["saint-thomas-becket"] },
  },
  {
    slug: "third-council-of-the-lateran",
    title: "Third Lateran Council",
    year: 1179,
    date: "1179-03-05",
    precision: "day",
    era: "high-medieval",
    kind: "council",
    location: "Rome",
    context:
      "Under Pope Alexander III the council requires a two-thirds majority of cardinals to elect a pope.",
    significance: "The two-thirds rule still governs conclaves.",
    citation: `${W}Third_Council_of_the_Lateran`,
    links: {
      documentSlug: "third-council-of-the-lateran",
      popes: ["pope-alexander-iii"],
    },
  },
  {
    slug: "ad-abolendam",
    title: "Ad abolendam condemns the Waldensians and Cathars",
    year: 1184,
    date: "1184-11-04",
    precision: "day",
    era: "high-medieval",
    kind: "document",
    location: "Verona",
    context:
      "Pope Lucius III, meeting with Emperor Frederick Barbarossa, condemns the heretical movements of the age and directs bishops to seek them out.",
    significance: "The beginning of the episcopal inquisition.",
    citation: `${W}Ad_abolendam`,
  },
  {
    slug: "saladin-takes-jerusalem",
    title: "Saladin retakes Jerusalem",
    year: 1187,
    date: "1187-10-02",
    precision: "day",
    era: "high-medieval",
    kind: "event",
    tags: ["crusade"],
    location: "Jerusalem",
    context: "The city surrenders to Saladin after his victory at Hattin.",
    significance: "Prompts the Third Crusade; the crusader states enter their long decline.",
    citation: `${W}Siege_of_Jerusalem_(1187)`,
  },
  {
    slug: "election-of-innocent-iii",
    title: "Innocent III elected",
    year: 1198,
    date: "1198-01-08",
    precision: "day",
    era: "high-medieval",
    kind: "pope",
    location: "Rome",
    context:
      "Lothar of Segni, aged thirty-seven, is elected pope; his reign marks the height of medieval papal power.",
    significance:
      "His pontificate brings the Fourth Lateran Council and the approval of the Franciscans and Dominicans.",
    citation: `${W}Pope_Innocent_III`,
    links: { popes: ["pope-innocent-iii"] },
  },
  {
    slug: "sack-of-constantinople-1204",
    title: "Fourth Crusade sacks Constantinople",
    year: 1204,
    date: "1204-04-12",
    precision: "day",
    era: "high-medieval",
    kind: "event",
    tags: ["crusade", "schism"],
    location: "Constantinople",
    context:
      "Diverted from the Holy Land, the crusaders storm and loot the Christian capital of the East.",
    significance:
      "Poisons relations between East and West for centuries; St John Paul II expressed sorrow for it in 2001.",
    citation: `${W}Sack_of_Constantinople`,
  },
  {
    slug: "franciscan-order-approved",
    title: "Innocent III approves the Franciscan rule",
    year: 1209,
    precision: "circa",
    era: "high-medieval",
    kind: "order",
    location: "Rome",
    context:
      "Francis and eleven companions receive the pope's oral approval of their simple way of life; the written rule is confirmed by bull in 1223.",
    significance:
      "The mendicant revolution: poverty and preaching carried into the growing cities.",
    citation: `${W}Franciscans`,
    links: {
      saints: ["saint-francis-of-assisi"],
      popes: ["pope-innocent-iii"],
    },
  },
  {
    slug: "fourth-council-of-the-lateran",
    title: "Fourth Lateran Council",
    year: 1215,
    date: "1215-11-11",
    precision: "day",
    era: "high-medieval",
    kind: "council",
    tags: ["dogma", "reform"],
    location: "Rome",
    context:
      "The council uses the word 'transubstantiation' for the Eucharistic change and requires annual confession and Easter Communion.",
    significance: "The most important council of the Middle Ages.",
    citation: `${W}Fourth_Council_of_the_Lateran`,
    links: {
      documentSlug: "fourth-council-of-the-lateran",
      popes: ["pope-innocent-iii"],
    },
  },
  {
    slug: "dominican-order-approved",
    title: "Dominican Order confirmed",
    year: 1216,
    date: "1216-12-22",
    precision: "day",
    era: "high-medieval",
    kind: "order",
    location: "Rome",
    context: "Pope Honorius III confirms St Dominic's Order of Preachers.",
    significance: "A tradition of preaching and theology, and the great promoters of the Rosary.",
    citation: `${W}Dominican_Order`,
    links: { saints: ["saint-dominic"] },
  },
  {
    slug: "carmelite-rule-confirmed",
    title: "Carmelite Rule confirmed",
    year: 1226,
    precision: "year",
    era: "high-medieval",
    kind: "order",
    location: "Rome",
    context:
      "Pope Honorius III confirms the Rule given to the hermits of Mount Carmel by St Albert of Jerusalem.",
    significance:
      "The Carmelites take their place among the orders of the West; Innocent IV's revision of 1247 makes them a mendicant order.",
    citation: `${W}Carmelites`,
  },
  {
    slug: "death-of-saint-francis",
    title: "Death of St Francis of Assisi",
    year: 1226,
    date: "1226-10-03",
    precision: "day",
    era: "high-medieval",
    kind: "saint",
    location: "Portiuncula, Assisi",
    context:
      "Francis dies at the Portiuncula as the brothers sing Psalm 141 (142), 'With my voice I cried to the Lord'.",
    significance: "Canonised in 1228; the basilica in his honour is begun the same year.",
    citation: `${W}Francis_of_Assisi`,
    links: { saints: ["saint-francis-of-assisi", "saint-clare-of-assisi"] },
  },
  {
    slug: "papal-inquisition-established",
    title: "Papal Inquisition established",
    year: 1231,
    precision: "year",
    era: "high-medieval",
    kind: "event",
    location: "Rome",
    context: "Pope Gregory IX entrusts the trial of heresy to papal judges, chiefly Dominicans.",
    significance: "The medieval Inquisition takes its lasting form.",
    citation: `${W}Medieval_Inquisition`,
    links: { popes: ["pope-gregory-ix"] },
  },
  {
    slug: "first-council-of-lyon",
    title: "First Council of Lyon",
    year: 1245,
    date: "1245-06-28",
    precision: "day",
    era: "high-medieval",
    kind: "council",
    location: "Lyon",
    context: "Pope Innocent IV and the council depose Emperor Frederick II.",
    significance: "The struggle of papacy and empire reaches its climax.",
    citation: `${W}First_Council_of_Lyon`,
    links: {
      documentSlug: "first-council-of-lyon",
      popes: ["pope-innocent-iv"],
    },
  },
  {
    slug: "feast-of-corpus-christi-instituted",
    title: "Corpus Christi extended to the universal Church",
    year: 1264,
    date: "1264-08-11",
    precision: "day",
    era: "high-medieval",
    kind: "event",
    location: "Orvieto",
    context:
      "By the bull Transiturus, Pope Urban IV extends the feast of the Body of Christ to the whole Church; St Thomas Aquinas is credited with composing its office.",
    significance: "Eucharistic devotion flowers in processions, hymns, and adoration.",
    citation: `${W}Corpus_Christi_(feast)`,
    links: { saints: ["saint-thomas-aquinas"] },
  },
  {
    slug: "aquinas-summa-theologiae",
    title: "St Thomas Aquinas writes the Summa Theologiae",
    year: 1265,
    precision: "circa",
    era: "high-medieval",
    kind: "document",
    location: "Rome, Paris, Naples",
    context:
      "Thomas begins his great summary of theology for beginners; it is still unfinished at his death on 7 March 1274.",
    significance:
      "The classic synthesis of faith and reason; Thomas is honoured as a Doctor of the Church.",
    citation: `${W}Summa_Theologica`,
    links: {
      saints: ["saint-thomas-aquinas"],
      doctors: ["doctor-thomas-aquinas"],
    },
  },
  {
    slug: "second-council-of-lyon",
    title: "Second Council of Lyon",
    year: 1274,
    date: "1274-05-07",
    precision: "day",
    era: "high-medieval",
    kind: "council",
    tags: ["schism"],
    location: "Lyon",
    context:
      "The council proclaims a short-lived union with the Greeks and lays down rules for the conclave.",
    significance: "St Bonaventure, a leading figure at the council, dies during its sessions.",
    citation: `${W}Second_Council_of_Lyon`,
    links: {
      documentSlug: "second-council-of-lyon",
      popes: ["pope-gregory-x"],
      doctors: ["doctor-bonaventure"],
    },
  },
  {
    slug: "abdication-of-celestine-v",
    title: "Celestine V abdicates",
    year: 1294,
    date: "1294-12-13",
    precision: "day",
    era: "high-medieval",
    kind: "pope",
    location: "Naples",
    context:
      "The hermit Peter of Morrone, elected pope in July, resigns the office after five months.",
    significance: "The precedent Benedict XVI would cite when he resigned in 2013.",
    citation: `${W}Pope_Celestine_V`,
    links: { popes: ["pope-saint-celestine-v"] },
  },
  {
    slug: "unam-sanctam",
    title: "Unam Sanctam",
    year: 1302,
    date: "1302-11-18",
    precision: "day",
    era: "high-medieval",
    kind: "document",
    tags: ["dogma"],
    location: "Rome",
    context:
      "Pope Boniface VIII, in conflict with King Philip IV of France, sets out the authority of the papacy over temporal rulers.",
    significance: "The peak claim of papal temporal power.",
    citation: `${W}Unam_sanctam`,
    links: { popes: ["pope-boniface-viii"] },
  },
  {
    slug: "outrage-of-anagni",
    title: "Outrage of Anagni",
    year: 1303,
    date: "1303-09-07",
    precision: "day",
    era: "high-medieval",
    kind: "event",
    location: "Anagni",
    context:
      "Agents of Philip IV seize and mistreat the aged Boniface VIII in his palace at Anagni; he dies weeks later.",
    significance: "The papacy is humbled by the French crown.",
    citation: `${W}Pope_Boniface_VIII`,
    links: { popes: ["pope-boniface-viii"] },
  },
  {
    slug: "avignon-papacy-begins",
    title: "Papacy moves to Avignon",
    year: 1309,
    precision: "year",
    era: "high-medieval",
    kind: "event",
    location: "Avignon",
    context: "Pope Clement V settles the papal court in France.",
    significance:
      "Seven popes reign from Avignon until 1377 — the period Petrarch called the 'Babylonian Captivity'.",
    citation: `${W}Avignon_Papacy`,
    links: { popes: ["pope-clement-v"] },
  },
  {
    slug: "council-of-vienne",
    title: "Council of Vienne",
    year: 1311,
    date: "1311-10-16",
    precision: "day",
    era: "high-medieval",
    kind: "council",
    tags: ["reform"],
    location: "Vienne",
    context:
      "The council suppresses the Knights Templar (Vox in excelso, 22 March 1312) and issues reform decrees.",
    significance: "The only ecumenical council held in France.",
    citation: `${W}Council_of_Vienne`,
    links: { documentSlug: "council-of-vienne", popes: ["pope-clement-v"] },
  },
  {
    slug: "black-death",
    title: "The Black Death",
    year: 1347,
    precision: "year",
    era: "high-medieval",
    kind: "event",
    location: "Europe",
    context:
      "Plague reaches Europe and kills perhaps a third of its people; losses among the clergy who tend the dying are immense.",
    significance:
      "Flagellant movements, pastoral collapse, and later impulses toward reform all trace back to it.",
    citation: `${W}Black_Death`,
  },
  {
    slug: "gregory-xi-returns-to-rome",
    title: "Gregory XI returns the papacy to Rome",
    year: 1377,
    date: "1377-01-17",
    precision: "day",
    era: "high-medieval",
    kind: "pope",
    location: "Rome",
    context: "Urged by St Catherine of Siena, Gregory XI leaves Avignon and enters Rome.",
    significance:
      "The end of the Avignon papacy; the Western Schism follows his death the next year.",
    citation: `${W}Pope_Gregory_XI`,
    links: {
      popes: ["pope-gregory-xi"],
      saints: ["saint-catherine-of-siena"],
    },
  },
  // ---------------------------------------------------- Western Schism & Renaissance
  {
    slug: "western-schism-begins",
    title: "Western Schism begins",
    year: 1378,
    date: "1378-09-20",
    precision: "day",
    era: "schism-renaissance",
    kind: "schism",
    tags: ["schism"],
    location: "Fondi",
    context: "Cardinals who repudiate the election of Urban VI in Rome elect Clement VII at Fondi.",
    significance: "Two, and later three, claimants divide the obedience of Christendom until 1417.",
    citation: `${W}Western_Schism`,
  },
  {
    slug: "council-of-pisa",
    title: "Council of Pisa",
    year: 1409,
    precision: "year",
    era: "schism-renaissance",
    kind: "event",
    tags: ["schism"],
    location: "Pisa",
    context:
      "Cardinals of both obediences attempt to end the schism by electing a new pope, but instead add a third claimant.",
    significance: "Shows the need for a true general council.",
    citation: `${W}Council_of_Pisa`,
  },
  {
    slug: "council-of-constance",
    title: "Council of Constance",
    year: 1414,
    date: "1414-11-05",
    precision: "day",
    era: "schism-renaissance",
    kind: "council",
    tags: ["schism", "reform"],
    location: "Constance",
    context:
      "The council ends the schism and condemns the teachings of Wycliffe and Hus; Hus is burned on 6 July 1415.",
    significance: "Martin V is elected on 11 November 1417 as the one pope.",
    citation: `${W}Council_of_Constance`,
    links: { documentSlug: "council-of-constance", popes: ["pope-martin-v"] },
  },
  {
    slug: "election-of-martin-v",
    title: "Election of Martin V ends the Western Schism",
    year: 1417,
    date: "1417-11-11",
    precision: "day",
    era: "schism-renaissance",
    kind: "pope",
    tags: ["schism"],
    location: "Constance",
    context: "Oddone Colonna is elected at Constance and recognised by all of Christendom.",
    significance: "One pope again; the papacy is restored to Rome.",
    citation: `${W}Pope_Martin_V`,
    links: { popes: ["pope-martin-v"] },
  },
  {
    slug: "imitation-of-christ",
    title: "The Imitation of Christ",
    year: 1420,
    precision: "circa",
    era: "schism-renaissance",
    kind: "document",
    location: "Low Countries",
    context: "Thomas à Kempis composes the classic of the Devotio Moderna.",
    significance: "Often called the most widely read Catholic book after the Bible.",
    citation: `${W}The_Imitation_of_Christ`,
  },
  {
    slug: "council-of-florence",
    title: "Council of Basel–Ferrara–Florence",
    year: 1431,
    date: "1431-07-23",
    precision: "day",
    era: "schism-renaissance",
    kind: "council",
    tags: ["schism", "dogma"],
    location: "Basel, Ferrara, Florence",
    context:
      "Opened at Basel and transferred by Pope Eugene IV to Ferrara and Florence, the council proclaims union with the Greeks in Laetentur caeli (6 July 1439).",
    significance: "Teaches on the Filioque, purgatory, and the primacy of the Roman pontiff.",
    citation: `${W}Council_of_Florence`,
    links: { documentSlug: "council-of-florence", popes: ["pope-eugene-iv"] },
  },
  {
    slug: "martyrdom-of-joan-of-arc",
    title: "St Joan of Arc burned at Rouen",
    year: 1431,
    date: "1431-05-30",
    precision: "day",
    era: "schism-renaissance",
    kind: "saint",
    location: "Rouen",
    context:
      "Condemned by a politically driven ecclesiastical court, Joan is burned at the stake; her sentence is annulled in 1456 and she is canonised in 1920.",
    significance: "Patroness of France.",
    citation: `${W}Joan_of_Arc`,
    links: { saints: ["saint-joan-of-arc"] },
  },
  {
    slug: "fall-of-constantinople",
    title: "Fall of Constantinople",
    year: 1453,
    date: "1453-05-29",
    precision: "day",
    era: "schism-renaissance",
    kind: "event",
    location: "Constantinople",
    context: "The Ottoman Turks take the city and end the Byzantine Empire.",
    significance:
      "Greek scholars flee west with their manuscripts; the Christian East passes under Islamic rule.",
    citation: `${W}Fall_of_Constantinople`,
  },
  {
    slug: "gutenberg-bible",
    title: "Gutenberg prints the Bible",
    year: 1455,
    precision: "circa",
    era: "schism-renaissance",
    kind: "event",
    location: "Mainz",
    context: "The first major book printed with movable type in Europe is the Latin Vulgate.",
    significance: "Printing transforms catechesis, scholarship, and, soon, religious controversy.",
    citation: `${W}Gutenberg_Bible`,
  },
  {
    slug: "spanish-inquisition-established",
    title: "Spanish Inquisition established",
    year: 1478,
    date: "1478-11-01",
    precision: "day",
    era: "schism-renaissance",
    kind: "event",
    location: "Rome and Castile",
    context:
      "Pope Sixtus IV authorises Ferdinand and Isabella to appoint inquisitors in their kingdoms.",
    significance: "A tribunal under royal control that endures until 1834.",
    citation: `${W}Spanish_Inquisition`,
    links: { popes: ["pope-sixtus-iv"] },
  },
  {
    slug: "christianity-reaches-the-americas",
    title: "Christianity reaches the Americas",
    year: 1492,
    date: "1492-10-12",
    precision: "day",
    era: "schism-renaissance",
    kind: "mission",
    tags: ["mission"],
    location: "Caribbean",
    context:
      "Columbus lands in the Caribbean; the first Mass in the New World is celebrated at La Isabela on 6 January 1494.",
    significance: "The evangelisation of the Americas begins.",
    citation: `${W}Christopher_Columbus`,
  },
  {
    slug: "execution-of-savonarola",
    title: "Savonarola executed",
    year: 1498,
    date: "1498-05-23",
    precision: "day",
    era: "schism-renaissance",
    kind: "event",
    location: "Florence",
    context:
      "The Dominican preacher and reformer, excommunicated by Alexander VI, is hanged and burned in the Piazza della Signoria.",
    significance: "A sign of the Renaissance papacy's crisis of credibility.",
    citation: `${W}Girolamo_Savonarola`,
    links: { popes: ["pope-alexander-vi"] },
  },
];
