export {
  registerSchema,
  loginSchema,
  adminLoginSchema,
  hashPassword,
  verifyPassword,
  createUser,
  findUserByEmail,
  authenticate,
  requireUser,
  verifyAdminCredentials,
  requireAdmin,
  getSession,
  sessionOptions,
  SESSION_COOKIE_NAME,
  issuePasswordResetToken,
  consumePasswordResetToken,
  issueEmailVerificationToken,
  consumeEmailVerificationToken,
  pruneExpiredTokens,
  verifyCurrentPassword,
  type RegisterInput,
  type LoginInput,
  type AdminLoginInput,
  type CreateUserInput,
  type AdminPrincipal,
  type SessionData,
  type UserRole,
  type IssuedToken,
  type ConsumePasswordResetResult,
  type ConsumeEmailVerificationResult,
} from "./auth/index";
