import type { CuratedEntry } from "./index";

const VATICAN = "https://www.vatican.va/";

function doc(
  slug: string,
  title: string,
  documentType:
    | "encyclical"
    | "apostolic_exhortation"
    | "apostolic_constitution"
    | "motu_proprio"
    | "apostolic_letter"
    | "decree"
    | "declaration"
    | "council_document"
    | "catechism_section"
    | "instruction"
    | "vatican_document"
    | "uscb_pastoral_letter",
  issuingAuthority: string,
  issuedDate: string,
  summary: string,
  keyThemes: string[],
  canonicalUrl: string,
): CuratedEntry {
  return {
    contentType: "CHURCH_DOCUMENT",
    slug,
    authorityLevel: "VATICAN",
    citations: [canonicalUrl, VATICAN],
    payload: {
      slug,
      title,
      documentType,
      issuingAuthority,
      issuedDate,
      summary,
      keyThemes,
      canonicalUrl,
      relatedDocuments: [],
      citations: [canonicalUrl, VATICAN],
    },
  };
}

export const churchDocumentKnowledge: CuratedEntry[] = [
  doc(
    "catechism-of-the-catholic-church",
    "Catechism of the Catholic Church",
    "catechism_section",
    "Pope John Paul II",
    "1992-10-11",
    "Promulgated by Pope John Paul II in 1992, the Catechism of the Catholic Church is the official synthesis of Catholic doctrine in four pillars: The Profession of Faith (the Creed), The Celebration of the Christian Mystery (the Sacraments), Life in Christ (the moral life), and Christian Prayer (the Our Father).",
    [
      "The Profession of Faith",
      "The Celebration of the Christian Mystery",
      "Life in Christ",
      "Christian Prayer",
    ],
    "https://www.vatican.va/archive/ENG0015/_INDEX.HTM",
  ),
  doc(
    "lumen-gentium",
    "Lumen Gentium",
    "council_document",
    "Pope Paul VI / Second Vatican Council",
    "1964-11-21",
    "The Dogmatic Constitution on the Church promulgated by the Second Vatican Council. Defines the Church as the Mystical Body of Christ, the People of God, and a sacrament of salvation. Treats the hierarchy, the laity, the universal call to holiness, religious life, and the Blessed Virgin Mary in the mystery of Christ and the Church.",
    [
      "The mystery of the Church",
      "The People of God",
      "The hierarchical structure of the Church",
      "The laity",
      "The universal call to holiness",
      "Religious life",
      "The pilgrim Church",
      "The Blessed Virgin Mary",
    ],
    "https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19641121_lumen-gentium_en.html",
  ),
  doc(
    "dei-verbum",
    "Dei Verbum",
    "council_document",
    "Pope Paul VI / Second Vatican Council",
    "1965-11-18",
    "The Dogmatic Constitution on Divine Revelation. Affirms that Tradition and Scripture, flowing from the same divine wellspring, are bound closely together; that the Magisterium serves the Word of God; and that Scripture must be read in the Spirit in whom it was written.",
    [
      "Divine Revelation itself",
      "The transmission of Divine Revelation",
      "Sacred Scripture: its inspiration and divine interpretation",
      "The Old Testament",
      "The New Testament",
      "Sacred Scripture in the life of the Church",
    ],
    "https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19651118_dei-verbum_en.html",
  ),
  doc(
    "sacrosanctum-concilium",
    "Sacrosanctum Concilium",
    "council_document",
    "Pope Paul VI / Second Vatican Council",
    "1963-12-04",
    "The Constitution on the Sacred Liturgy — the first major document of the Second Vatican Council. Calls for the full, conscious, and active participation of the faithful in the liturgy and authorizes the liturgical reform that produced the Roman Missal of 1969.",
    [
      "General principles for the restoration and promotion of the sacred liturgy",
      "The most sacred mystery of the Eucharist",
      "The other sacraments and the sacramentals",
      "The divine office",
      "The liturgical year",
      "Sacred music",
      "Sacred art and furnishings",
    ],
    "https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19631204_sacrosanctum-concilium_en.html",
  ),
  doc(
    "gaudium-et-spes",
    "Gaudium et Spes",
    "council_document",
    "Pope Paul VI / Second Vatican Council",
    "1965-12-07",
    "The Pastoral Constitution on the Church in the Modern World. The longest document of the Second Vatican Council. Treats the dignity of the human person, the community of mankind, human activity, the role of the Church in the modern world, and pressing problems (marriage and family, culture, economic and social life, political life, peace).",
    [
      "The dignity of the human person",
      "The community of mankind",
      "Human activity throughout the world",
      "The role of the Church in the modern world",
      "Marriage and the family",
      "The proper development of culture",
      "Economic and social life",
      "Political life",
      "The fostering of peace",
    ],
    "https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_cons_19651207_gaudium-et-spes_en.html",
  ),
  doc(
    "humanae-vitae",
    "Humanae Vitae",
    "encyclical",
    "Pope Paul VI",
    "1968-07-25",
    "Pope Paul VI's encyclical on the regulation of birth, reaffirming the Church's teaching that each and every marriage act must remain open to the transmission of life. Condemns contraception, sterilization, and abortion as intrinsically disordered.",
    [
      "The transmission of life",
      "The unitive and procreative meanings of the conjugal act",
      "Responsible parenthood",
      "Lawful and unlawful means of regulating birth",
    ],
    "https://www.vatican.va/content/paul-vi/en/encyclicals/documents/hf_p-vi_enc_25071968_humanae-vitae.html",
  ),
  doc(
    "veritatis-splendor",
    "Veritatis Splendor",
    "encyclical",
    "Pope John Paul II",
    "1993-08-06",
    "Pope John Paul II's foundational moral encyclical. Reaffirms the existence of universal and unchanging moral norms knowable by reason and confirmed by revelation. Critiques proportionalism and other forms of consequentialism.",
    [
      "The foundations of moral theology",
      "Intrinsically evil acts",
      "The relation between freedom and truth",
      "Faith and morality",
    ],
    "https://www.vatican.va/content/john-paul-ii/en/encyclicals/documents/hf_jp-ii_enc_06081993_veritatis-splendor.html",
  ),
  doc(
    "evangelium-vitae",
    "Evangelium Vitae",
    "encyclical",
    "Pope John Paul II",
    "1995-03-25",
    "Pope John Paul II's encyclical on the value and inviolability of human life. Definitively reaffirms the Church's teaching that the direct killing of an innocent human being is always gravely immoral. Condemns abortion, euthanasia, and the death penalty as applied today.",
    [
      "The Gospel of Life",
      "Threats to human life today",
      "The value of human life",
      "A new culture of life",
    ],
    "https://www.vatican.va/content/john-paul-ii/en/encyclicals/documents/hf_jp-ii_enc_25031995_evangelium-vitae.html",
  ),
  doc(
    "deus-caritas-est",
    "Deus Caritas Est",
    "encyclical",
    "Pope Benedict XVI",
    "2005-12-25",
    "Pope Benedict XVI's first encyclical. Reflects on God as love, the unity of love (eros and agape) in creation and salvation, and the practice of love by the Church as a community of love.",
    ["God is love", "Eros and agape", "Charity as the Church's mission"],
    "https://www.vatican.va/content/benedict-xvi/en/encyclicals/documents/hf_ben-xvi_enc_20051225_deus-caritas-est.html",
  ),
  doc(
    "laudato-si",
    "Laudato Si'",
    "encyclical",
    "Pope Francis",
    "2015-05-24",
    "Pope Francis's encyclical on care for our common home. Diagnoses the ecological and human crisis of our time, presents the Catholic doctrine of creation, and calls for an 'integral ecology' that joins concern for the environment to concern for the poor and for the dignity of every human person.",
    [
      "What is happening to our common home",
      "The Gospel of creation",
      "The human roots of the ecological crisis",
      "Integral ecology",
      "Lines of approach and action",
      "Ecological education and spirituality",
    ],
    "https://www.vatican.va/content/francesco/en/encyclicals/documents/papa-francesco_20150524_enciclica-laudato-si.html",
  ),
  doc(
    "evangelii-gaudium",
    "Evangelii Gaudium",
    "apostolic_exhortation",
    "Pope Francis",
    "2013-11-24",
    "Pope Francis's programmatic apostolic exhortation on the Church's mission of evangelization. Calls for missionary disciples who go out to the peripheries with joy and proclaim Jesus Christ.",
    [
      "The joy of the Gospel",
      "Missionary transformation of the Church",
      "Pastoral activity and conversion",
      "The proclamation of the Gospel",
      "Social dimension of evangelization",
    ],
    "https://www.vatican.va/content/francesco/en/apost_exhortations/documents/papa-francesco_esortazione-ap_20131124_evangelii-gaudium.html",
  ),
  doc(
    "rerum-novarum",
    "Rerum Novarum",
    "encyclical",
    "Pope Leo XIII",
    "1891-05-15",
    "The foundational document of modern Catholic social teaching. Pope Leo XIII addresses the condition of the working classes, affirming the dignity of labor, the right to private property, the right of workers to a just wage and to form associations, and rejecting both unrestrained capitalism and socialism.",
    [
      "The dignity of labor",
      "Private property",
      "The just wage",
      "Workers' associations",
      "The role of the State",
    ],
    "https://www.vatican.va/content/leo-xiii/en/encyclicals/documents/hf_l-xiii_enc_15051891_rerum-novarum.html",
  ),
  doc(
    "quadragesimo-anno",
    "Quadragesimo Anno",
    "encyclical",
    "Pope Pius XI",
    "1931-05-15",
    "Issued forty years after Rerum Novarum, this encyclical of Pope Pius XI develops Catholic social doctrine, articulating the principle of subsidiarity and calling for the reconstruction of the social order according to justice and charity.",
    [
      "Subsidiarity",
      "Social justice",
      "The reconstruction of the social order",
      "Capital and labor",
    ],
    "https://www.vatican.va/content/pius-xi/en/encyclicals/documents/hf_p-xi_enc_19310515_quadragesimo-anno.html",
  ),
  doc(
    "pacem-in-terris",
    "Pacem in Terris",
    "encyclical",
    "Pope Saint John XXIII",
    "1963-04-11",
    "Pope John XXIII's encyclical on establishing universal peace in truth, justice, charity, and liberty. The first encyclical addressed to 'all people of good will,' it sets out the rights and duties of persons and the ordering of relations between states.",
    ["Human rights and duties", "Order between states", "The common good", "Peace"],
    "https://www.vatican.va/content/john-xxiii/en/encyclicals/documents/hf_j-xxiii_enc_11041963_pacem.html",
  ),
  doc(
    "populorum-progressio",
    "Populorum Progressio",
    "encyclical",
    "Pope Saint Paul VI",
    "1967-03-26",
    "Pope Paul VI's encyclical on the development of peoples, teaching that authentic development must be integral — promoting the good of the whole person and of all people — and that 'development is the new name for peace.'",
    [
      "Integral human development",
      "Solidarity among peoples",
      "Justice in world trade",
      "Development as peace",
    ],
    "https://www.vatican.va/content/paul-vi/en/encyclicals/documents/hf_p-vi_enc_26031967_populorum.html",
  ),
  doc(
    "redemptor-hominis",
    "Redemptor Hominis",
    "encyclical",
    "Pope Saint John Paul II",
    "1979-03-04",
    "The inaugural encyclical of Pope John Paul II, proclaiming that Jesus Christ, the Redeemer of man, is the center of the cosmos and of history, and that the human person is 'the way of the Church.'",
    [
      "Christ the Redeemer",
      "The dignity of the human person",
      "Human rights",
      "The mission of the Church",
    ],
    "https://www.vatican.va/content/john-paul-ii/en/encyclicals/documents/hf_jp-ii_enc_04031979_redemptor-hominis.html",
  ),
  doc(
    "dives-in-misericordia",
    "Dives in Misericordia",
    "encyclical",
    "Pope Saint John Paul II",
    "1980-11-30",
    "Pope John Paul II's encyclical on the mercy of God the Father, revealed fully in Jesus Christ, and the Church's mission to profess and bring God's mercy into human life.",
    [
      "The mercy of God",
      "The parable of the prodigal son",
      "Mercy and justice",
      "The Church's witness to mercy",
    ],
    "https://www.vatican.va/content/john-paul-ii/en/encyclicals/documents/hf_jp-ii_enc_30111980_dives-in-misericordia.html",
  ),
  doc(
    "centesimus-annus",
    "Centesimus Annus",
    "encyclical",
    "Pope Saint John Paul II",
    "1991-05-01",
    "Marking the centenary of Rerum Novarum, Pope John Paul II reflects on the collapse of communism, the limits and proper role of the free economy, and the priority of the human person and the common good in social and economic life.",
    [
      "The events of 1989",
      "The free economy and its limits",
      "The State and culture",
      "The dignity of work",
    ],
    "https://www.vatican.va/content/john-paul-ii/en/encyclicals/documents/hf_jp-ii_enc_01051991_centesimus-annus.html",
  ),
  doc(
    "fides-et-ratio",
    "Fides et Ratio",
    "encyclical",
    "Pope Saint John Paul II",
    "1998-09-14",
    "Pope John Paul II's encyclical on the relationship between faith and reason, which he describes as 'two wings on which the human spirit rises to the contemplation of truth.' It defends the capacity of reason to know the truth and the harmony of philosophy with revealed faith.",
    ["Faith and reason", "The search for truth", "The role of philosophy", "Christian philosophy"],
    "https://www.vatican.va/content/john-paul-ii/en/encyclicals/documents/hf_jp-ii_enc_14091998_fides-et-ratio.html",
  ),
  doc(
    "spe-salvi",
    "Spe Salvi",
    "encyclical",
    "Pope Benedict XVI",
    "2007-11-30",
    "Pope Benedict XVI's encyclical on Christian hope, teaching that the hope which redeems is founded on faith in God, and distinguishing authentic hope from the false hopes of mere human progress.",
    [
      "Christian hope",
      "Faith as substance of hope",
      "Suffering and hope",
      "The Last Judgment and hope",
    ],
    "https://www.vatican.va/content/benedict-xvi/en/encyclicals/documents/hf_ben-xvi_enc_20071130_spe-salvi.html",
  ),
  doc(
    "caritas-in-veritate",
    "Caritas in Veritate",
    "encyclical",
    "Pope Benedict XVI",
    "2009-06-29",
    "Pope Benedict XVI's social encyclical on integral human development in charity and truth, addressing globalization, economic life, the environment, and the centrality of charity rooted in truth.",
    [
      "Charity in truth",
      "Integral human development",
      "Economy and ethics",
      "The development of peoples and technology",
    ],
    "https://www.vatican.va/content/benedict-xvi/en/encyclicals/documents/hf_ben-xvi_enc_20090629_caritas-in-veritate.html",
  ),
  doc(
    "divino-afflante-spiritu",
    "Divino Afflante Spiritu",
    "encyclical",
    "Pope Venerable Pius XII",
    "1943-09-30",
    "Pope Pius XII's encyclical on the promotion of biblical studies, encouraging the use of original languages and sound scholarship in the interpretation of Sacred Scripture. It opened a renewal of Catholic biblical study.",
    [
      "Sacred Scripture",
      "Biblical scholarship",
      "Original languages and textual criticism",
      "The senses of Scripture",
    ],
    "https://www.vatican.va/content/pius-xii/en/encyclicals/documents/hf_p-xii_enc_30091943_divino-afflante-spiritu.html",
  ),
  doc(
    "nostra-aetate",
    "Nostra Aetate",
    "council_document",
    "Second Vatican Council",
    "1965-10-28",
    "The Declaration of the Second Vatican Council on the relation of the Church to non-Christian religions, affirming what is true and holy in other religions while proclaiming Christ as the way, the truth, and the life, and repudiating all hatred and persecution.",
    [
      "The unity of the human family",
      "Other religions",
      "The Church and the Jewish people",
      "Universal brotherhood",
    ],
    "https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decl_19651028_nostra-aetate_en.html",
  ),
  doc(
    "dignitatis-humanae",
    "Dignitatis Humanae",
    "council_document",
    "Second Vatican Council",
    "1965-12-07",
    "The Declaration of the Second Vatican Council on religious freedom, teaching that the human person has a right to immunity from coercion in religious matters, grounded in the dignity of the person and the truth that the act of faith must be free.",
    [
      "Religious freedom",
      "The dignity of the human person",
      "Freedom of the act of faith",
      "The duties of government",
    ],
    "https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decl_19651207_dignitatis-humanae_en.html",
  ),
  doc(
    "unitatis-redintegratio",
    "Unitatis Redintegratio",
    "council_document",
    "Second Vatican Council",
    "1964-11-21",
    "The Decree of the Second Vatican Council on ecumenism, committing the Catholic Church to the restoration of unity among all Christians through prayer, conversion of heart, and dialogue grounded in truth and charity.",
    ["Christian unity", "Ecumenism", "Spiritual ecumenism", "Dialogue with separated brethren"],
    "https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decree_19641121_unitatis-redintegratio_en.html",
  ),
  doc(
    "aeterni-patris",
    "Aeterni Patris",
    "encyclical",
    "Pope Leo XIII",
    "1879-08-04",
    "The encyclical of Pope Leo XIII calling for the restoration of Christian philosophy according to the mind of Saint Thomas Aquinas, affirming the harmony of faith and reason.",
    ["Faith and reason", "Scholastic philosophy", "Saint Thomas Aquinas", "Thomism"],
    "https://www.vatican.va/content/leo-xiii/en/encyclicals.index.html",
  ),
  doc(
    "providentissimus-deus",
    "Providentissimus Deus",
    "encyclical",
    "Pope Leo XIII",
    "1893-11-18",
    "The encyclical of Pope Leo XIII on the study of Sacred Scripture, defending its divine inspiration and inerrancy and encouraging sound biblical scholarship.",
    ["Sacred Scripture", "Biblical inspiration", "Inerrancy", "Biblical studies"],
    "https://www.vatican.va/content/leo-xiii/en/encyclicals.index.html",
  ),
  doc(
    "pascendi-dominici-gregis",
    "Pascendi Dominici Gregis",
    "encyclical",
    "Pope Saint Pius X",
    "1907-09-08",
    "The encyclical of Pope Saint Pius X analyzing and condemning the errors of Modernism, which he called 'the synthesis of all heresies.'",
    ["Modernism", "Defense of doctrine", "Faith and reason"],
    "https://www.vatican.va/content/pius-x/en/encyclicals.index.html",
  ),
  doc(
    "quas-primas",
    "Quas Primas",
    "encyclical",
    "Pope Pius XI",
    "1925-12-11",
    "The encyclical of Pope Pius XI instituting the Feast of Christ the King, proclaiming the kingship of Jesus Christ over individuals, families, and nations.",
    ["Christ the King", "Social kingship of Christ", "Liturgical feast"],
    "https://www.vatican.va/content/pius-xi/en/encyclicals.index.html",
  ),
  doc(
    "casti-connubii",
    "Casti Connubii",
    "encyclical",
    "Pope Pius XI",
    "1930-12-31",
    "The encyclical of Pope Pius XI on Christian marriage, upholding its sanctity, indissolubility, and openness to life against the errors of the age.",
    ["Christian marriage", "Indissolubility", "Openness to life", "Family"],
    "https://www.vatican.va/content/pius-xi/en/encyclicals.index.html",
  ),
  doc(
    "mit-brennender-sorge",
    "Mit Brennender Sorge",
    "encyclical",
    "Pope Pius XI",
    "1937-03-14",
    "The encyclical of Pope Pius XI, written in German and read from the pulpits of Germany, condemning the neo-paganism and racial ideology of National Socialism.",
    ["Against Nazism", "Human dignity", "Religious freedom", "Defense of the faith"],
    "https://www.vatican.va/content/pius-xi/en/encyclicals.index.html",
  ),
  doc(
    "divini-redemptoris",
    "Divini Redemptoris",
    "encyclical",
    "Pope Pius XI",
    "1937-03-19",
    "The encyclical of Pope Pius XI on atheistic communism, exposing its errors and reaffirming the Church's social teaching and the dignity of the human person.",
    ["Atheistic communism", "Social doctrine", "Human dignity", "Justice"],
    "https://www.vatican.va/content/pius-xi/en/encyclicals.index.html",
  ),
  doc(
    "mystici-corporis-christi",
    "Mystici Corporis Christi",
    "encyclical",
    "Pope Pius XII",
    "1943-06-29",
    "The encyclical of Pope Pius XII on the Church as the Mystical Body of Christ, illuminating the union of the faithful with Christ their Head.",
    ["Mystical Body of Christ", "Ecclesiology", "Communion of saints"],
    "https://www.vatican.va/content/pius-xii/en/encyclicals.index.html",
  ),
  doc(
    "mediator-dei",
    "Mediator Dei",
    "encyclical",
    "Pope Pius XII",
    "1947-11-20",
    "The encyclical of Pope Pius XII on the sacred liturgy, often called the charter of the liturgical movement, teaching that the liturgy is the public worship of the whole Mystical Body.",
    ["Sacred liturgy", "Public worship", "Liturgical movement", "Active participation"],
    "https://www.vatican.va/content/pius-xii/en/encyclicals.index.html",
  ),
  doc(
    "humani-generis",
    "Humani Generis",
    "encyclical",
    "Pope Pius XII",
    "1950-08-12",
    "The encyclical of Pope Pius XII concerning false opinions threatening to undermine the foundations of Catholic doctrine, addressing evolution, relativism, and the limits of theological speculation.",
    ["Defense of doctrine", "Faith and science", "Truth", "Theological method"],
    "https://www.vatican.va/content/pius-xii/en/encyclicals.index.html",
  ),
  doc(
    "mater-et-magistra",
    "Mater et Magistra",
    "encyclical",
    "Pope Saint John XXIII",
    "1961-05-15",
    "The encyclical of Pope Saint John XXIII on Christianity and social progress, developing the Church's social teaching on work, the common good, and global solidarity.",
    ["Social doctrine", "Common good", "Solidarity", "Just wages"],
    "https://www.vatican.va/content/john-xxiii/en/encyclicals.index.html",
  ),
  doc(
    "ecclesiam-suam",
    "Ecclesiam Suam",
    "encyclical",
    "Pope Saint Paul VI",
    "1964-08-06",
    "The first encyclical of Pope Saint Paul VI, on the paths the Church must follow in fulfilling her mission, centered on self-awareness, renewal, and dialogue with the world.",
    ["The Church", "Dialogue", "Renewal", "Evangelization"],
    "https://www.vatican.va/content/paul-vi/en/encyclicals.index.html",
  ),
  doc(
    "mysterium-fidei",
    "Mysterium Fidei",
    "encyclical",
    "Pope Saint Paul VI",
    "1965-09-03",
    "The encyclical of Pope Saint Paul VI on the Holy Eucharist, defending the doctrines of the Real Presence and transubstantiation and the worship due to the Blessed Sacrament.",
    ["Holy Eucharist", "Real Presence", "Transubstantiation", "Eucharistic adoration"],
    "https://www.vatican.va/content/paul-vi/en/encyclicals.index.html",
  ),
  doc(
    "sacerdotalis-caelibatus",
    "Sacerdotalis Caelibatus",
    "encyclical",
    "Pope Saint Paul VI",
    "1967-06-24",
    "The encyclical of Pope Saint Paul VI on priestly celibacy, expounding its meaning and value as a gift of self in imitation of Christ for the sake of the Kingdom.",
    ["Priestly celibacy", "Priesthood", "Consecration", "Discipleship"],
    "https://www.vatican.va/content/paul-vi/en/encyclicals.index.html",
  ),
  doc(
    "dominum-et-vivificantem",
    "Dominum et Vivificantem",
    "encyclical",
    "Pope Saint John Paul II",
    "1986-05-18",
    "The encyclical of Pope Saint John Paul II on the Holy Spirit in the life of the Church and the world, the third panel of his Trinitarian triptych.",
    ["Holy Spirit", "The Trinity", "Grace", "Sanctification"],
    "https://www.vatican.va/content/john-paul-ii/en/encyclicals.index.html",
  ),
  doc(
    "redemptoris-mater",
    "Redemptoris Mater",
    "encyclical",
    "Pope Saint John Paul II",
    "1987-03-25",
    "The encyclical of Pope Saint John Paul II on the Blessed Virgin Mary in the life of the pilgrim Church, contemplating her faith and maternal mediation.",
    ["Blessed Virgin Mary", "Marian devotion", "Faith", "Pilgrim Church"],
    "https://www.vatican.va/content/john-paul-ii/en/encyclicals.index.html",
  ),
  doc(
    "redemptoris-missio",
    "Redemptoris Missio",
    "encyclical",
    "Pope Saint John Paul II",
    "1990-12-07",
    "The encyclical of Pope Saint John Paul II on the permanent validity of the Church's missionary mandate, calling for a renewed commitment to the proclamation of Christ.",
    ["Mission", "Evangelization", "Proclamation of Christ", "Missio ad gentes"],
    "https://www.vatican.va/content/john-paul-ii/en/encyclicals.index.html",
  ),
  doc(
    "ut-unum-sint",
    "Ut Unum Sint",
    "encyclical",
    "Pope Saint John Paul II",
    "1995-05-25",
    "The encyclical of Pope Saint John Paul II on commitment to ecumenism, affirming that the search for Christian unity is an irreversible duty of the whole Church.",
    ["Ecumenism", "Christian unity", "Dialogue", "Prayer for unity"],
    "https://www.vatican.va/content/john-paul-ii/en/encyclicals.index.html",
  ),
  doc(
    "ecclesia-de-eucharistia",
    "Ecclesia de Eucharistia",
    "encyclical",
    "Pope Saint John Paul II",
    "2003-04-17",
    "The encyclical of Pope Saint John Paul II on the Eucharist in its relationship to the Church, teaching that the Church draws her life from the Eucharist.",
    ["Holy Eucharist", "The Church", "Eucharistic sacrifice", "Communion"],
    "https://www.vatican.va/content/john-paul-ii/en/encyclicals.index.html",
  ),
  doc(
    "fratelli-tutti",
    "Fratelli Tutti",
    "encyclical",
    "Pope Francis",
    "2020-10-03",
    "The encyclical of Pope Francis on fraternity and social friendship, calling for a culture of encounter, solidarity, and care for every person across all borders.",
    ["Fraternity", "Social friendship", "Solidarity", "Peace and dialogue"],
    "https://www.vatican.va/content/francesco/en/encyclicals.index.html",
  ),
];
