import type { CuratedEntry } from "./index";

const VATICAN = "https://www.vatican.va/";
const USCCB = "https://www.usccb.org/prayer-and-worship/prayers-and-devotions/prayers";

function litany(slug: string, title: string, category: string, body: string): CuratedEntry {
  return {
    contentType: "PRAYER",
    slug,
    authorityLevel: "VATICAN",
    citations: [VATICAN, USCCB],
    payload: {
      slug,
      title,
      body,
      prayerType: "litany",
      category,
      language: "en",
      occasions: ["devotion"],
      relatedSaints: [],
      citations: [VATICAN, USCCB],
    },
  };
}

/**
 * Approved Catholic litanies — sustained sequences of invocations and
 * responses. Curated as PRAYER entries with prayerType "litany" so they
 * surface on the /litanies tab (categorizePrayer routes any litany there).
 * Texts are the traditional approved forms, reproduced verbatim. Ground-truth
 * content the worker can publish without a live fetch.
 */
export const litanyKnowledge: CuratedEntry[] = [
  litany(
    "litany-of-the-blessed-virgin-mary",
    "Litany of the Blessed Virgin Mary (Litany of Loreto)",
    "marian",
    [
      "Lord, have mercy. Christ, have mercy. Lord, have mercy.",
      "Christ, hear us. Christ, graciously hear us.",
      "God the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the world, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "",
      "Holy Mary, pray for us.",
      "Holy Mother of God, pray for us.",
      "Holy Virgin of virgins, pray for us.",
      "Mother of Christ, pray for us.",
      "Mother of the Church, pray for us.",
      "Mother of divine grace, pray for us.",
      "Mother most pure, pray for us.",
      "Mother most chaste, pray for us.",
      "Mother inviolate, pray for us.",
      "Mother undefiled, pray for us.",
      "Mother most amiable, pray for us.",
      "Mother most admirable, pray for us.",
      "Mother of good counsel, pray for us.",
      "Mother of our Creator, pray for us.",
      "Mother of our Savior, pray for us.",
      "Virgin most prudent, pray for us.",
      "Virgin most venerable, pray for us.",
      "Virgin most renowned, pray for us.",
      "Virgin most powerful, pray for us.",
      "Virgin most merciful, pray for us.",
      "Virgin most faithful, pray for us.",
      "Mirror of justice, pray for us.",
      "Seat of wisdom, pray for us.",
      "Cause of our joy, pray for us.",
      "Spiritual vessel, pray for us.",
      "Vessel of honor, pray for us.",
      "Singular vessel of devotion, pray for us.",
      "Mystical rose, pray for us.",
      "Tower of David, pray for us.",
      "Tower of ivory, pray for us.",
      "House of gold, pray for us.",
      "Ark of the covenant, pray for us.",
      "Gate of heaven, pray for us.",
      "Morning star, pray for us.",
      "Health of the sick, pray for us.",
      "Refuge of sinners, pray for us.",
      "Comforter of the afflicted, pray for us.",
      "Help of Christians, pray for us.",
      "Queen of angels, pray for us.",
      "Queen of patriarchs, pray for us.",
      "Queen of prophets, pray for us.",
      "Queen of apostles, pray for us.",
      "Queen of martyrs, pray for us.",
      "Queen of confessors, pray for us.",
      "Queen of virgins, pray for us.",
      "Queen of all saints, pray for us.",
      "Queen conceived without original sin, pray for us.",
      "Queen assumed into heaven, pray for us.",
      "Queen of the most holy Rosary, pray for us.",
      "Queen of peace, pray for us.",
      "",
      "Lamb of God, who take away the sins of the world, spare us, O Lord.",
      "Lamb of God, who take away the sins of the world, graciously hear us, O Lord.",
      "Lamb of God, who take away the sins of the world, have mercy on us.",
    ].join("\n"),
  ),
  litany(
    "litany-of-the-sacred-heart-of-jesus",
    "Litany of the Sacred Heart of Jesus",
    "christological",
    [
      "Lord, have mercy. Christ, have mercy. Lord, have mercy.",
      "Christ, hear us. Christ, graciously hear us.",
      "God the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the world, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "",
      "Heart of Jesus, Son of the Eternal Father, have mercy on us.",
      "Heart of Jesus, formed by the Holy Spirit in the womb of the Virgin Mother, have mercy on us.",
      "Heart of Jesus, substantially united to the Word of God, have mercy on us.",
      "Heart of Jesus, of infinite majesty, have mercy on us.",
      "Heart of Jesus, holy temple of God, have mercy on us.",
      "Heart of Jesus, tabernacle of the Most High, have mercy on us.",
      "Heart of Jesus, house of God and gate of heaven, have mercy on us.",
      "Heart of Jesus, burning furnace of charity, have mercy on us.",
      "Heart of Jesus, abode of justice and love, have mercy on us.",
      "Heart of Jesus, full of goodness and love, have mercy on us.",
      "Heart of Jesus, abyss of all virtues, have mercy on us.",
      "Heart of Jesus, most worthy of all praise, have mercy on us.",
      "Heart of Jesus, king and center of all hearts, have mercy on us.",
      "Heart of Jesus, in whom are all the treasures of wisdom and knowledge, have mercy on us.",
      "Heart of Jesus, in whom dwells the fullness of divinity, have mercy on us.",
      "Heart of Jesus, in whom the Father was well pleased, have mercy on us.",
      "Heart of Jesus, of whose fullness we have all received, have mercy on us.",
      "Heart of Jesus, desire of the everlasting hills, have mercy on us.",
      "Heart of Jesus, patient and most merciful, have mercy on us.",
      "Heart of Jesus, enriching all who invoke you, have mercy on us.",
      "Heart of Jesus, fountain of life and holiness, have mercy on us.",
      "Heart of Jesus, propitiation for our sins, have mercy on us.",
      "Heart of Jesus, filled with reproaches, have mercy on us.",
      "Heart of Jesus, bruised for our offenses, have mercy on us.",
      "Heart of Jesus, obedient unto death, have mercy on us.",
      "Heart of Jesus, pierced with a lance, have mercy on us.",
      "Heart of Jesus, source of all consolation, have mercy on us.",
      "Heart of Jesus, our life and resurrection, have mercy on us.",
      "Heart of Jesus, our peace and reconciliation, have mercy on us.",
      "Heart of Jesus, victim for our sins, have mercy on us.",
      "Heart of Jesus, salvation of those who hope in you, have mercy on us.",
      "Heart of Jesus, hope of those who die in you, have mercy on us.",
      "Heart of Jesus, delight of all the saints, have mercy on us.",
      "",
      "Lamb of God, who take away the sins of the world, spare us, O Lord.",
      "Lamb of God, who take away the sins of the world, graciously hear us, O Lord.",
      "Lamb of God, who take away the sins of the world, have mercy on us.",
    ].join("\n"),
  ),
  litany(
    "litany-of-saint-joseph",
    "Litany of Saint Joseph",
    "saints",
    [
      "Lord, have mercy. Christ, have mercy. Lord, have mercy.",
      "Christ, hear us. Christ, graciously hear us.",
      "God the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the world, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "",
      "Holy Mary, pray for us.",
      "Saint Joseph, pray for us.",
      "Renowned offspring of David, pray for us.",
      "Light of patriarchs, pray for us.",
      "Spouse of the Mother of God, pray for us.",
      "Chaste guardian of the Virgin, pray for us.",
      "Foster father of the Son of God, pray for us.",
      "Diligent protector of Christ, pray for us.",
      "Head of the Holy Family, pray for us.",
      "Joseph most just, pray for us.",
      "Joseph most chaste, pray for us.",
      "Joseph most prudent, pray for us.",
      "Joseph most strong, pray for us.",
      "Joseph most obedient, pray for us.",
      "Joseph most faithful, pray for us.",
      "Mirror of patience, pray for us.",
      "Lover of poverty, pray for us.",
      "Model of workers, pray for us.",
      "Glory of home life, pray for us.",
      "Guardian of virgins, pray for us.",
      "Pillar of families, pray for us.",
      "Solace of the afflicted, pray for us.",
      "Hope of the sick, pray for us.",
      "Patron of the dying, pray for us.",
      "Terror of demons, pray for us.",
      "Protector of Holy Church, pray for us.",
      "",
      "Lamb of God, who take away the sins of the world, spare us, O Lord.",
      "Lamb of God, who take away the sins of the world, graciously hear us, O Lord.",
      "Lamb of God, who take away the sins of the world, have mercy on us.",
    ].join("\n"),
  ),
  litany(
    "litany-of-humility",
    "Litany of Humility",
    "general",
    [
      "O Jesus, meek and humble of heart, hear me.",
      "",
      "From the desire of being esteemed, deliver me, Jesus.",
      "From the desire of being loved, deliver me, Jesus.",
      "From the desire of being extolled, deliver me, Jesus.",
      "From the desire of being honored, deliver me, Jesus.",
      "From the desire of being praised, deliver me, Jesus.",
      "From the desire of being preferred to others, deliver me, Jesus.",
      "From the desire of being consulted, deliver me, Jesus.",
      "From the desire of being approved, deliver me, Jesus.",
      "From the fear of being humiliated, deliver me, Jesus.",
      "From the fear of being despised, deliver me, Jesus.",
      "From the fear of suffering rebukes, deliver me, Jesus.",
      "From the fear of being calumniated, deliver me, Jesus.",
      "From the fear of being forgotten, deliver me, Jesus.",
      "From the fear of being ridiculed, deliver me, Jesus.",
      "From the fear of being wronged, deliver me, Jesus.",
      "From the fear of being suspected, deliver me, Jesus.",
      "",
      "That others may be loved more than I, Jesus, grant me the grace to desire it.",
      "That others may be esteemed more than I, Jesus, grant me the grace to desire it.",
      "That, in the opinion of the world, others may increase and I may decrease, Jesus, grant me the grace to desire it.",
      "That others may be chosen and I set aside, Jesus, grant me the grace to desire it.",
      "That others may be praised and I unnoticed, Jesus, grant me the grace to desire it.",
      "That others may be preferred to me in everything, Jesus, grant me the grace to desire it.",
      "That others may become holier than I, provided that I may become as holy as I should, Jesus, grant me the grace to desire it.",
    ].join("\n"),
  ),
];
