import type { CuratedEntry } from "./index";

const VATICAN = "https://www.vatican.va/";
const USCCB = "https://www.usccb.org/";

function feast(
  slug: string,
  title: string,
  kind:
    | "feast"
    | "solemnity"
    | "memorial"
    | "optional_memorial"
    | "liturgical_season"
    | "liturgical_year"
    | "mass_structure"
    | "marriage_rite"
    | "funeral_rite"
    | "ordination_rite"
    | "council_event"
    | "symbolism"
    | "glossary_term",
  summary: string,
  body: string,
  feastDate?: string,
  movableFeast = false,
  season?: "advent" | "christmas" | "ordinary_time" | "lent" | "triduum" | "easter" | "n/a",
): CuratedEntry {
  return {
    contentType: "LITURGICAL",
    slug,
    authorityLevel: "LITURGICAL_BOOK",
    citations: [VATICAN, USCCB],
    payload: {
      slug,
      title,
      kind,
      ...(season ? { season } : {}),
      summary,
      body,
      ...(feastDate ? { feastDate } : {}),
      movableFeast,
      associatedSaintSlugs: [],
      associatedReadings: [],
      citations: [VATICAN, USCCB],
    },
  };
}

export const liturgicalKnowledge: CuratedEntry[] = [
  feast(
    "solemnity-christmas",
    "Solemnity of the Nativity of the Lord (Christmas)",
    "solemnity",
    "The principal feast of the Incarnation, celebrating the birth of Jesus Christ.",
    "Christmas (December 25) is the second-greatest solemnity of the liturgical year after Easter. It opens the Christmas Octave and the Christmas Season, which continues until the Baptism of the Lord. Three Masses are traditionally celebrated: at the Vigil, at Midnight (Mass during the Night), at Dawn, and during the Day.",
    "12-25",
    false,
    "christmas",
  ),
  feast(
    "solemnity-easter",
    "Solemnity of the Resurrection of the Lord (Easter)",
    "solemnity",
    "The Solemnity of solemnities — the celebration of the Resurrection of Jesus Christ from the dead.",
    "Easter is the feast of feasts, the heart of the liturgical year. The date is movable: the first Sunday after the first full moon following the spring equinox. The Easter Vigil, celebrated on Holy Saturday night, is the mother of all vigils. The Easter Octave is celebrated as a single day; the Easter Season continues for fifty days through Pentecost.",
    undefined,
    true,
    "easter",
  ),
  feast(
    "solemnity-pentecost",
    "Solemnity of Pentecost",
    "solemnity",
    "The fiftieth day of Easter — the descent of the Holy Spirit on Mary and the Apostles, the birth of the Church.",
    "Pentecost falls fifty days after Easter Sunday. It closes the Easter Season and inaugurates the second part of Ordinary Time. The Sequence Veni Sancte Spiritus is sung at Mass.",
    undefined,
    true,
    "easter",
  ),
  feast(
    "solemnity-most-holy-trinity",
    "Solemnity of the Most Holy Trinity",
    "solemnity",
    "Honors the central mystery of Christian faith: one God in three Persons, Father, Son, and Holy Spirit.",
    "Celebrated on the Sunday after Pentecost. Made universal by Pope John XXII in 1334.",
    undefined,
    true,
    "ordinary_time",
  ),
  feast(
    "solemnity-corpus-christi",
    "Solemnity of the Body and Blood of Christ (Corpus Christi)",
    "solemnity",
    "Celebrates the gift of the Holy Eucharist, the Real Presence of Christ under the appearances of bread and wine.",
    "Established by Pope Urban IV in 1264 (Transiturus de hoc mundo). Sequence Lauda Sion (St. Thomas Aquinas) sung at Mass. Celebrated on the Thursday after Trinity Sunday or, where transferred, on the following Sunday. The traditional Corpus Christi procession is a public profession of faith in the Real Presence.",
    undefined,
    true,
    "ordinary_time",
  ),
  feast(
    "solemnity-sacred-heart",
    "Solemnity of the Most Sacred Heart of Jesus",
    "solemnity",
    "Adoration of the wounded Heart of Christ as the symbol and source of his redeeming love.",
    "Celebrated on the Friday after the Second Sunday after Pentecost. Established as a universal feast by Pope Pius IX in 1856. Pope Pius XI raised it to a Solemnity in 1928.",
    undefined,
    true,
    "ordinary_time",
  ),
  feast(
    "solemnity-immaculate-conception",
    "Solemnity of the Immaculate Conception of the Blessed Virgin Mary",
    "solemnity",
    "Celebrates the dogma defined by Pope Pius IX in 1854: that Mary was preserved free from original sin in the first moment of her conception.",
    "Celebrated on December 8 (nine months before the Nativity of Mary on September 8). Patronal Feast of the United States of America.",
    "12-08",
    false,
    "advent",
  ),
  feast(
    "solemnity-assumption",
    "Solemnity of the Assumption of the Blessed Virgin Mary",
    "solemnity",
    "Celebrates the dogma defined by Pope Pius XII in 1950: that Mary, having completed the course of her earthly life, was assumed body and soul into heavenly glory.",
    "Celebrated on August 15. A Holy Day of Obligation in the universal Church.",
    "08-15",
    false,
    "ordinary_time",
  ),
  feast(
    "solemnity-all-saints",
    "Solemnity of All Saints",
    "solemnity",
    "Honors all the saints in heaven, known and unknown, who together with the angels make up the Church Triumphant.",
    "Celebrated on November 1. A Holy Day of Obligation in many countries (including the United States, except when it falls on a Monday or Saturday).",
    "11-01",
    false,
    "ordinary_time",
  ),
  feast(
    "solemnity-christ-the-king",
    "Solemnity of Our Lord Jesus Christ, King of the Universe",
    "solemnity",
    "Proclaims the universal kingship of Christ over all creation, every nation, every person, every aspect of life.",
    "Established by Pope Pius XI in the encyclical Quas Primas (1925) in response to growing secularism. Moved to the last Sunday of the liturgical year by Pope Paul VI in 1969.",
    undefined,
    true,
    "ordinary_time",
  ),
  feast(
    "solemnity-annunciation",
    "Solemnity of the Annunciation of the Lord",
    "solemnity",
    "Celebrates the announcement by the Angel Gabriel to Mary that she would conceive the Son of God by the power of the Holy Spirit (Luke 1:26-38).",
    "Celebrated on March 25 (nine months before Christmas). When it falls in Holy Week or the Easter Octave, it is transferred. A Marian solemnity that is fundamentally Christological — the celebration of the Incarnation.",
    "03-25",
    false,
    "ordinary_time",
  ),
  feast(
    "season-advent",
    "Season of Advent",
    "liturgical_season",
    "The four-week season of preparation for the celebration of Christmas, marked by joyful expectation of the Lord's coming.",
    "Begins on the Sunday closest to November 30 (Feast of St. Andrew) and ends on December 24. The liturgical color is violet (rose on Gaudete Sunday, the Third Sunday of Advent). Advent has two characters: it directs hearts to await Christ's second coming and prepares us to celebrate his historical coming at Christmas.",
    undefined,
    false,
    "advent",
  ),
  feast(
    "season-christmas",
    "Christmas Season",
    "liturgical_season",
    "The Christmas Octave and Season, from Christmas Eve through the Feast of the Baptism of the Lord.",
    "The Christmas Season begins with the Vigil of Christmas and ends with the Feast of the Baptism of the Lord (the Sunday after Epiphany). Includes the Solemnity of Mary, Mother of God (January 1), Epiphany, the Holy Family, and the Baptism of the Lord.",
    undefined,
    false,
    "christmas",
  ),
  feast(
    "season-lent",
    "Season of Lent",
    "liturgical_season",
    "The forty-day season of penitential preparation for Easter through prayer, fasting, and almsgiving.",
    "Begins on Ash Wednesday and ends at the Mass of the Lord's Supper on Holy Thursday. The liturgical color is violet (rose on Laetare Sunday). The faithful prepare for Easter through prayer, fasting, almsgiving, and the discipline of self-denial. The 'Alleluia' is suppressed throughout Lent.",
    undefined,
    true,
    "lent",
  ),
  feast(
    "season-triduum",
    "The Sacred Paschal Triduum",
    "liturgical_season",
    "The three holiest days of the liturgical year: from the Mass of the Lord's Supper on Holy Thursday through Easter Vespers on Easter Sunday.",
    "The Triduum is one continuous liturgy celebrated over three days: the Evening Mass of the Lord's Supper (Holy Thursday), the Celebration of the Lord's Passion (Good Friday), and the Easter Vigil (Holy Saturday night). The high point of the entire liturgical year.",
    undefined,
    true,
    "triduum",
  ),
  feast(
    "season-easter",
    "Easter Season",
    "liturgical_season",
    "The fifty-day Easter Season culminating in Pentecost — celebrated as 'one great Sunday.'",
    "Begins with the Easter Vigil and ends on the Sunday of Pentecost. The liturgical color is white. The Paschal Candle burns at every liturgy of the Easter Season. The 'Alleluia' returns and is sung with abundance.",
    undefined,
    true,
    "easter",
  ),
  feast(
    "season-ordinary-time",
    "Ordinary Time",
    "liturgical_season",
    "The two periods of the liturgical year not specifically devoted to a season of celebration or preparation. Far from being 'ordinary,' it is the time in which the mystery of Christ in all its aspects is celebrated.",
    "First period: from the Monday after the Feast of the Baptism of the Lord through Shrove Tuesday. Second period: from the Monday after Pentecost through the Saturday before the First Sunday of Advent. The liturgical color is green.",
    undefined,
    false,
    "ordinary_time",
  ),
  feast(
    "structure-roman-rite-mass",
    "The Structure of the Roman Rite Mass",
    "mass_structure",
    "The Mass has two principal parts: the Liturgy of the Word and the Liturgy of the Eucharist, framed by Introductory Rites and Concluding Rites.",
    "Introductory Rites: Entrance, Greeting, Penitential Act, Gloria (on Sundays outside Lent/Advent), Collect. Liturgy of the Word: First Reading, Responsorial Psalm, Second Reading (on Sundays/Solemnities), Gospel Acclamation, Gospel, Homily, Profession of Faith (Creed), Universal Prayer. Liturgy of the Eucharist: Preparation of the Gifts, Eucharistic Prayer (Preface, Sanctus, Institution Narrative and Consecration, Memorial Acclamation, Amen), Communion Rite (Our Father, Sign of Peace, Lamb of God, Communion). Concluding Rites: Blessing, Dismissal.",
    undefined,
    false,
    "n/a",
  ),
  feast(
    "solemnity-mary-mother-of-god",
    "Solemnity of Mary, the Holy Mother of God",
    "solemnity",
    "The oldest Marian feast of the Roman liturgy, celebrating Mary's divine motherhood (Theotokos) on the Octave Day of Christmas.",
    "Celebrated on January 1, the Octave Day of Christmas, this solemnity honors Mary under the title Mother of God, defined at the Council of Ephesus in 431. It is also the World Day of Peace and a holy day of obligation in many places.",
    "01-01",
    false,
    "christmas",
  ),
  feast(
    "solemnity-epiphany",
    "Solemnity of the Epiphany of the Lord",
    "solemnity",
    "The manifestation of Christ to the nations, traditionally commemorating the visit of the Magi to the infant Jesus.",
    "Epiphany, celebrated on January 6 (or the Sunday between January 2 and 8 where it is transferred), manifests Christ to the world in the adoration of the Magi, his Baptism in the Jordan, and the wedding at Cana. The blessing of homes with chalk is a traditional Epiphany custom.",
    "01-06",
    false,
    "christmas",
  ),
  feast(
    "feast-baptism-of-the-lord",
    "Feast of the Baptism of the Lord",
    "feast",
    "The feast that closes the Christmas Season, commemorating the baptism of Jesus by John in the Jordan.",
    "Celebrated on the Sunday after Epiphany, this feast marks the beginning of Christ's public ministry, when the Father's voice proclaimed him the beloved Son and the Holy Spirit descended upon him. It closes the Christmas Season; Ordinary Time begins the next day.",
    undefined,
    true,
    "christmas",
  ),
  feast(
    "feast-holy-family",
    "Feast of the Holy Family of Jesus, Mary and Joseph",
    "feast",
    "A feast honoring the Holy Family of Nazareth as the model of Christian family life.",
    "Celebrated on the Sunday within the Octave of Christmas (or December 30 when Christmas falls on a Sunday), this feast holds up Jesus, Mary, and Joseph as the model and patrons of every Christian household.",
    undefined,
    true,
    "christmas",
  ),
  feast(
    "feast-presentation-of-the-lord",
    "Feast of the Presentation of the Lord (Candlemas)",
    "feast",
    "The presentation of the infant Jesus in the Temple forty days after his birth, when Simeon and Anna recognized him.",
    "Celebrated on February 2, forty days after Christmas, this feast recalls the presentation of Jesus in the Temple and Simeon's proclamation of him as 'a light to the nations.' Candles are blessed and carried in procession, giving the day its traditional name, Candlemas.",
    "02-02",
    false,
    "ordinary_time",
  ),
  feast(
    "solemnity-ascension",
    "Solemnity of the Ascension of the Lord",
    "solemnity",
    "The glorious ascension of the risen Christ into heaven forty days after Easter.",
    "Celebrated forty days after Easter (on Thursday, or transferred to the Seventh Sunday of Easter in many places), the Ascension commemorates Christ taking his place at the right hand of the Father and his promise to send the Holy Spirit, completing the work of redemption.",
    undefined,
    true,
    "easter",
  ),
  feast(
    "solemnity-nativity-of-john-the-baptist",
    "Solemnity of the Nativity of Saint John the Baptist",
    "solemnity",
    "The birth of John the Baptist, the forerunner of the Lord, six months before Christmas.",
    "Celebrated on June 24, this is one of the few birthdays kept in the liturgical calendar. John the Baptist, the last and greatest of the prophets, prepared the way for Christ and pointed him out as the Lamb of God.",
    "06-24",
    false,
    "ordinary_time",
  ),
  feast(
    "solemnity-saints-peter-and-paul",
    "Solemnity of Saints Peter and Paul, Apostles",
    "solemnity",
    "The joint solemnity of the two great apostles and martyrs of Rome, the pillars of the Church.",
    "Celebrated on June 29, this solemnity honors Saint Peter, the rock and first pope, and Saint Paul, the Apostle to the Gentiles, both martyred at Rome. On this day the pope traditionally blesses the pallia for new metropolitan archbishops.",
    "06-29",
    false,
    "ordinary_time",
  ),
  feast(
    "feast-transfiguration",
    "Feast of the Transfiguration of the Lord",
    "feast",
    "The revelation of Christ's divine glory on the mountain before Peter, James, and John.",
    "Celebrated on August 6, the Transfiguration recalls how Jesus was transfigured in glory before three of his apostles, with Moses and Elijah, and the Father's voice declaring him the beloved Son. It strengthens hope in the glory to which the faithful are called.",
    "08-06",
    false,
    "ordinary_time",
  ),
  feast(
    "feast-exaltation-of-the-holy-cross",
    "Feast of the Exaltation of the Holy Cross",
    "feast",
    "A feast glorying in the Cross of Christ as the instrument of salvation.",
    "Celebrated on September 14, this feast commemorates the finding of the True Cross by Saint Helena and the dedication of the Basilica of the Holy Sepulchre, glorying in the Cross by which Christ redeemed the world.",
    "09-14",
    false,
    "ordinary_time",
  ),
  feast(
    "memorial-our-lady-of-sorrows",
    "Memorial of Our Lady of Sorrows",
    "memorial",
    "A memorial of the sufferings of the Blessed Virgin Mary in union with the Passion of her Son.",
    "Celebrated on September 15, the day after the Exaltation of the Holy Cross, this memorial honors the Seven Sorrows of Mary, who stood faithfully at the foot of the Cross and shared in the redemptive suffering of Christ.",
    "09-15",
    false,
    "ordinary_time",
  ),
  feast(
    "glossary-liturgical-colors",
    "The Liturgical Colors",
    "glossary_term",
    "The colors of the vestments and altar cloths that mark the seasons and feasts of the liturgical year.",
    "White (or gold) is used for Christmas and Easter, feasts of the Lord, Mary, and non-martyr saints, expressing joy and glory. Red marks Passion celebrations, Pentecost, and feasts of martyrs and apostles. Green is worn in Ordinary Time. Violet is used in Advent and Lent and for the dead. Rose may be used on Gaudete and Laetare Sundays.",
    undefined,
    false,
    "n/a",
  ),
];
