import type { CuratedEntry } from "./index";

const VATICAN = "https://www.vatican.va/";
const USCCB = "https://www.usccb.org/";

function title(
  slug: string,
  name: string,
  summary: string,
  origin: string,
  theology: string,
  feastDay?: string,
): CuratedEntry {
  return {
    contentType: "MARIAN_TITLE",
    slug,
    authorityLevel: "VATICAN",
    citations: [VATICAN, USCCB],
    payload: {
      slug,
      title: name,
      summary,
      origin,
      ...(feastDay ? { feastDay } : {}),
      theologicalSignificance: theology,
      associatedPrayers: [],
      citations: [VATICAN, USCCB],
    },
  };
}

export const marianTitleKnowledge: CuratedEntry[] = [
  title(
    "mother-of-god",
    "Mother of God (Theotokos)",
    "Mary is honored as the Mother of God because the one she bore is the eternal Son of God made man. This is the most fundamental of all Marian titles.",
    "Defined as dogma at the Council of Ephesus in 431 against the Nestorian heresy, which sought to separate the divinity and humanity of Christ.",
    "The title Theotokos affirms that Jesus Christ is one Divine Person with two natures (divine and human), so the woman who bore him truly bore God-made-man. The dogma protects the unity of Christ's person.",
    "01-01",
  ),
  title(
    "immaculate-conception",
    "Immaculate Conception",
    "Mary, in the first moment of her conception, by a singular grace and privilege of Almighty God, in view of the merits of Jesus Christ, was preserved free from all stain of original sin.",
    "Defined as dogma by Pope Pius IX in the apostolic constitution Ineffabilis Deus, December 8, 1854. Mary herself confirmed the title to St. Bernadette at Lourdes in 1858: 'I am the Immaculate Conception.'",
    "The dogma affirms that Mary's freedom from original sin was a singular grace of God in view of the merits of Christ. She is the most perfectly redeemed of the redeemed.",
    "12-08",
  ),
  title(
    "assumption-of-mary",
    "Assumption of Mary",
    "The Immaculate Mother of God, the ever-Virgin Mary, having completed the course of her earthly life, was assumed body and soul into heavenly glory.",
    "Defined as dogma by Pope Pius XII in the apostolic constitution Munificentissimus Deus, November 1, 1950. The faith of the Church in Mary's Assumption is attested from the earliest centuries.",
    "The Assumption manifests the fullness of Christ's victory over death. Mary, sharing perfectly in the Paschal Mystery of her Son, anticipates the resurrection promised to all the faithful.",
    "08-15",
  ),
  title(
    "perpetual-virginity",
    "Perpetual Virginity of Mary",
    "Mary remained a virgin in conceiving her Son, a virgin in giving birth to him, a virgin in carrying him, a virgin in nursing him at her breast, always a virgin.",
    "Affirmed in the Apostles' and Nicene Creeds and by the Lateran Council of 649. The Church has always confessed Mary's virginity ante partum, in partu, et post partum.",
    "Mary's virginity is the sign that her Son is God: born of a woman but not of the will of man. Her virginity also signifies the Church's undivided love of Christ.",
  ),
  title(
    "queen-of-heaven",
    "Queen of Heaven",
    "Mary is crowned Queen of Heaven and Earth because she is the Mother of the King of kings and shares in the glory of her Son.",
    "Affirmed by Pope Pius XII in the encyclical Ad Caeli Reginam (1954), which established the Memorial of the Queenship of Mary.",
    "Mary's queenship is participated, not autonomous: she reigns as Mother of the King and as the woman whose total obedience to God brings her to share in Christ's royal mediation.",
    "08-22",
  ),
  title(
    "our-lady-of-guadalupe",
    "Our Lady of Guadalupe",
    "Patroness of the Americas. Mary appeared to St. Juan Diego in 1531 at Tepeyac, leaving her image miraculously imprinted on his tilma.",
    "The apparitions of December 1531 led to the conversion of millions of indigenous peoples in the Americas. The tilma is preserved in the Basilica of Our Lady of Guadalupe in Mexico City.",
    "The image presents Mary as a pregnant mestiza woman, indicating the universal motherhood of God's people and the Christological centrality of the Incarnation.",
    "12-12",
  ),
  title(
    "our-lady-of-sorrows",
    "Our Lady of Sorrows",
    "Mary as Mater Dolorosa, the Sorrowful Mother, who shared in her Son's Passion. Seven sorrows are traditionally honored.",
    "The devotion is rooted in Simeon's prophecy (Luke 2:35): 'a sword will pierce through your own soul also.' The Servite Order spread the Seven Sorrows devotion in the 13th century.",
    "Mary's sorrows reveal her perfect union with the redeeming Passion of Christ and her motherhood of all the suffering members of his Body.",
    "09-15",
  ),
  title(
    "our-lady-of-the-rosary",
    "Our Lady of the Rosary",
    "Mary venerated under the title of the Rosary, the great Marian psalter of the Latin Church.",
    "Pope St. Pius V established the feast in 1573 in thanksgiving for the Christian victory at the Battle of Lepanto (October 7, 1571), attributed to the prayer of the Rosary.",
    "The Rosary is a Christ-centered prayer, meditating on the mysteries of Christ's life in the company of his Mother. Pope John Paul II added the Luminous Mysteries in 2002.",
    "10-07",
  ),
  title(
    "our-lady-of-mount-carmel",
    "Our Lady of Mount Carmel",
    "Mary venerated as patroness of the Carmelite Order and giver of the Brown Scapular.",
    "The title honors the Blessed Virgin's patronage of the hermits who settled on Mount Carmel in the Holy Land. Tradition holds that she gave the Brown Scapular to Saint Simon Stock in 1251.",
    "The Scapular is a sign of consecration to Mary and of her maternal protection, worn as a habit in miniature and a pledge of perseverance in grace.",
    "07-16",
  ),
  title(
    "our-lady-of-lourdes",
    "Our Lady of Lourdes",
    "Mary venerated under the title given at her 1858 apparitions at Lourdes, where she declared, 'I am the Immaculate Conception.'",
    "In 1858 the Blessed Virgin appeared eighteen times to Saint Bernadette Soubirous at the grotto of Massabielle in Lourdes, France, calling for prayer and penance and revealing a healing spring.",
    "The title confirms the dogma of the Immaculate Conception defined in 1854 and expresses Mary's maternal care for the sick, whom the Church especially commends to her on this feast.",
    "02-11",
  ),
  title(
    "our-lady-of-fatima",
    "Our Lady of Fátima",
    "Mary venerated under the title given at her 1917 apparitions to three shepherd children at Fátima, Portugal.",
    "In 1917 the Blessed Virgin appeared six times at Fátima, calling for the daily Rosary, penance, and reparation, and entrusting a message centered on prayer for the conversion of sinners and peace in the world.",
    "The Fátima message renews the Gospel call to conversion and intercession and fostered devotion to the Immaculate Heart of Mary.",
    "05-13",
  ),
  title(
    "immaculate-heart-of-mary",
    "The Immaculate Heart of Mary",
    "Devotion to the heart of the Blessed Virgin Mary as the symbol of her interior life, her love for God and for all people.",
    "Rooted in the Gospel image of Mary 'keeping all these things in her heart' (Luke 2:19, 51), the devotion was promoted by Saint John Eudes and spread widely after the Fátima apparitions. Pope Pius XII consecrated the world to the Immaculate Heart in 1942.",
    "The Immaculate Heart, united to the Sacred Heart of Jesus, models perfect charity and draws the faithful to Christ through his Mother.",
  ),
  title(
    "our-lady-of-perpetual-help",
    "Our Lady of Perpetual Help",
    "Mary venerated through the celebrated Byzantine-style icon entrusted to the Redemptorist order.",
    "The ancient icon, of Cretan origin, depicts the Christ Child sheltered by his Mother while angels display the instruments of the Passion. Pope Pius IX entrusted it to the Redemptorists in 1866 to 'make her known.'",
    "The image teaches confident recourse to Mary's unfailing intercession in every need.",
    "06-27",
  ),
  title(
    "our-lady-of-the-miraculous-medal",
    "Our Lady of the Miraculous Medal",
    "Mary venerated under the title revealed in 1830 through the medal she requested of Saint Catherine Labouré.",
    "In 1830 the Blessed Virgin appeared to Saint Catherine Labouré in the Rue du Bac in Paris and asked that a medal be struck bearing the invocation, 'O Mary, conceived without sin, pray for us who have recourse to thee.'",
    "The medal, soon called 'miraculous' for the graces attached to it, proclaims the Immaculate Conception and Mary's mediation of grace.",
    "11-27",
  ),
  title(
    "our-lady-of-czestochowa",
    "Our Lady of Częstochowa",
    "Mary venerated through the ancient icon enshrined at the Jasna Góra monastery in Poland, known as the Black Madonna and honored as Queen of Poland.",
    "The revered icon, traditionally attributed to Saint Luke and enshrined at the Jasna Góra monastery in 1382, became a national shrine of Poland; the Blessed Virgin was solemnly proclaimed Queen of Poland in 1656.",
    "Darkened by age and marked by two scars on the Virgin's cheek, the image is a sign of Mary's maternal protection over the Polish nation and a destination of pilgrimage for centuries.",
    "08-26",
  ),
  title(
    "our-lady-help-of-christians",
    "Our Lady Help of Christians",
    "Mary invoked as the help and defense of the Christian people, a title given fresh prominence by Saint John Bosco, who made it the patronal title of his Salesian work.",
    "The invocation 'Auxilium Christianorum' was honored after the victory of Lepanto in 1571 and confirmed by Pope Pius VII, who established the feast on May 24 in thanksgiving for the Church's deliverance.",
    "The title proclaims Mary's powerful intercession on behalf of the Church in times of trial and her role as protectress of Christians.",
    "05-24",
  ),
  title(
    "our-lady-star-of-the-sea",
    "Our Lady, Star of the Sea (Stella Maris)",
    "Mary honored under the ancient title Stella Maris, the guiding star who leads the faithful safely across the sea of this life to the harbor of salvation.",
    "The title Stella Maris was developed by the Fathers and sung in the medieval hymn 'Ave Maris Stella'; it became the favored title of seafarers and those who minister to them.",
    "As a star guides the mariner, so Mary guides Christians amid the storms of life to Christ her Son; the Church commends sailors and travelers to her protection.",
  ),
  title(
    "our-lady-of-good-counsel",
    "Our Lady of Good Counsel",
    "Mary venerated under the image enshrined at Genazzano, Italy, invoked by those who seek wisdom and right judgment in the decisions of life.",
    "The fresco of Our Lady of Good Counsel at Genazzano, venerated since 1467, was widely propagated; Pope Leo XIII added the invocation 'Mater boni consilii' to the Litany of Loreto.",
    "Under this title Mary is honored as the Mother of Good Counsel who obtains for her children the gift of wisdom to follow the will of God.",
    "04-26",
  ),
  title(
    "our-lady-of-la-salette",
    "Our Lady of La Salette",
    "Mary venerated as the weeping Mother who appeared at La Salette, France, calling her people to conversion, prayer, and the keeping of the Lord's Day.",
    "On September 19, 1846, the Blessed Virgin appeared in tears to two shepherd children, Mélanie Calvat and Maximin Giraud, on a mountainside at La Salette; the apparition was approved by the Bishop of Grenoble in 1851.",
    "Under this title Mary is honored as the Reconciler of sinners, whose tears call her children back from sin to penance and the mercy of her Son.",
    "09-19",
  ),
  title(
    "our-lady-of-knock",
    "Our Lady of Knock",
    "Mary venerated under the silent apparition at Knock, Ireland, where she appeared with Saint Joseph, Saint John, and the Lamb upon an altar.",
    "On August 21, 1879, the Blessed Virgin appeared silently at the gable of the parish church in Knock, County Mayo, to fifteen witnesses; the apparition has been honored by the Church and Knock is a national Marian shrine of Ireland.",
    "The silent apparition, centred on the Lamb upon the altar, draws the faithful to the Eucharist and to confidence in Mary's intercession amid suffering.",
    "08-17",
  ),
  title(
    "our-lady-seat-of-wisdom",
    "Our Lady, Seat of Wisdom (Sedes Sapientiae)",
    "Mary honored under the ancient title Seat of Wisdom, the throne upon which the Incarnate Wisdom of God, her Son, took his place.",
    "The title Sedes Sapientiae arose in the patristic and medieval Church and is invoked in the Litany of Loreto; it inspired a celebrated type of Romanesque image of the Virgin enthroned with the Child.",
    "As the one who bore the Eternal Wisdom in her womb, Mary is honored as the throne of Wisdom and the patroness of Catholic universities and study.",
  ),
  title(
    "our-lady-of-the-snows",
    "Our Lady of the Snows (Dedication of Saint Mary Major)",
    "Mary venerated under the title commemorated by the dedication of the Basilica of Saint Mary Major in Rome, the greatest of her churches in the West.",
    "Tradition holds that in the fourth century the Blessed Virgin indicated the site of her basilica on the Esquiline Hill in Rome by a miraculous summer snowfall; the dedication of Saint Mary Major is kept on August 5.",
    "Under this title Mary is honored in the first great church of the West dedicated to her, a sign of her unique place in the mystery of the Incarnation and the life of the Church.",
    "08-05",
  ),
  title(
    "our-lady-of-the-pillar",
    "Our Lady of the Pillar",
    "Mary venerated at Zaragoza in Spain, where ancient tradition holds she appeared to the Apostle Saint James while still living, standing upon a pillar of jasper.",
    "Pious tradition records that around AD 40 the Blessed Virgin came to encourage Saint James the Greater as he evangelized Spain, leaving a marble pillar on which her image is still venerated in the basilica at Zaragoza — among the oldest of all Marian shrines.",
    "Honoring Mary's maternal care for the Church's mission, the title celebrates her as the firm pillar and support of the faith in times of trial.",
    "10-12",
  ),
  title(
    "our-lady-of-loreto",
    "Our Lady of Loreto",
    "Mary honored in the Holy House of Loreto, revered as the home of Nazareth where the Annunciation took place and the Word became flesh.",
    "Since the late thirteenth century the small stone Holy House has been venerated at Loreto in Italy as the dwelling of the Holy Family; the shrine became one of Christendom's great pilgrimage sites, and Our Lady of Loreto is the patroness of aviators.",
    "The title draws the faithful to the mystery of the Incarnation in the very setting of Nazareth, honoring Mary as the dwelling place prepared for the Son of God.",
    "12-10",
  ),
  title(
    "our-lady-of-mercy",
    "Our Lady of Mercy (Our Lady of Ransom)",
    "Mary invoked as the merciful Mother who moves her children to free captives, under whose patronage the Mercedarian Order was founded.",
    "In 1218 the Blessed Virgin is said to have inspired Saint Peter Nolasco to found the Order of Our Lady of Mercy (the Mercedarians) for the ransom of Christians held captive, whose members vowed even to give themselves in exchange for prisoners.",
    "The title celebrates Mary's maternal mercy and her care for the oppressed, drawing the faithful to works of liberation and charity in her name.",
    "09-24",
  ),
  title(
    "our-lady-undoer-of-knots",
    "Mary, Undoer of Knots",
    "Mary invoked as the one who, by her intercession, patiently unties the knots of sin, difficulty, and broken relationships in the lives of her children.",
    "The devotion takes its name from a baroque painting in Augsburg, Germany, depicting Mary smoothing out a long ribbon full of knots; it was popularized in Latin America and beyond and is especially dear to Pope Francis.",
    "Drawing on the Fathers' image of Mary undoing by her obedience the knot tied by Eve's disobedience, the title invites trust in her intercession amid life's entanglements.",
  ),
  title(
    "our-lady-queen-of-peace",
    "Our Lady, Queen of Peace",
    "Mary invoked as Queen of Peace, the Mother who brings forth the Prince of Peace and intercedes for reconciliation among peoples.",
    "Among the invocations of the Litany of Loreto, this title gained prominence in the modern era as the Church entrusted to Mary her prayers for an end to war and division; Pope Benedict XV added the invocation during the First World War.",
    "The title honors Mary's share in her Son's gift of peace, encouraging the faithful to seek through her the peace that the world cannot give.",
  ),
  title(
    "our-lady-of-walsingham",
    "Our Lady of Walsingham",
    "Mary venerated at the English shrine of Walsingham, long called 'England's Nazareth,' commemorating the mystery of the Annunciation.",
    "In 1061 a noblewoman, Richeldis de Faverches, is said to have been shown the house of Nazareth in a vision and to have built its replica at Walsingham, which became one of medieval Europe's foremost pilgrimage shrines and was restored in modern times.",
    "Under this title Mary is honored as the Virgin of the Annunciation, calling England and all the faithful to renew their 'yes' to God in imitation of her.",
  ),
  title(
    "our-lady-of-aparecida",
    "Our Lady of Aparecida",
    "Mary venerated under the title of the small dark image of the Immaculate Conception found by fishermen in the Paraíba River, principal patroness of Brazil.",
    "In 1717 three fishermen drew from the river a broken terracotta statue of Our Lady, after which their nets filled to overflowing; devotion spread swiftly, and the great Basilica of Aparecida is today one of the largest Marian shrines in the world.",
    "The title honors Mary's nearness to the poor and humble, who under her patronage as the Immaculate Conception draws a whole nation to her Son.",
    "10-12",
  ),
  title(
    "our-lady-of-charity",
    "Our Lady of Charity of El Cobre",
    "Mary venerated as the patroness of Cuba under the title of Charity, from the image found floating in the Bay of Nipe and enshrined at El Cobre.",
    "In the early seventeenth century two brothers and a boy were saved from a storm at sea and found a small statue of the Virgin bearing the Child Jesus, inscribed 'I am the Virgin of Charity'; her shrine at El Cobre became the heart of Cuban Catholic devotion.",
    "Under this title Mary is honored as the Mother of Charity who protects her people and binds them together in faith and love.",
    "09-08",
  ),
  title(
    "our-lady-of-good-help",
    "Our Lady of Good Help",
    "Mary venerated at Champion, Wisconsin, the site of the first and only approved Marian apparition in the United States.",
    "In 1859 the Blessed Virgin appeared to Adele Brise, asking that the children of the region be gathered and taught the truths of the faith; the apparition was formally approved by the local bishop in 2010.",
    "The title honors Mary's call to catechesis and conversion, presenting her as the Help of those who labor to hand on the faith.",
    "10-09",
  ),
  title(
    "our-lady-of-prompt-succor",
    "Our Lady of Prompt Succor",
    "Mary invoked as the swift helper of New Orleans and Louisiana, credited with sparing the city from fire and from defeat in battle.",
    "Brought to New Orleans by the Ursuline nuns in the early nineteenth century, the devotion grew after the city was spared a great fire and after the unexpected American victory at the Battle of New Orleans in 1815, attributed to Mary's intercession.",
    "The title honors Mary's ready and powerful help in urgent need, encouraging confident recourse to her in every danger.",
    "01-08",
  ),
  title(
    "our-lady-of-pompeii",
    "Our Lady of the Rosary of Pompeii",
    "Mary venerated in the great shrine of Pompeii, the center of devotion to the Holy Rosary built by Blessed Bartolo Longo.",
    "In the late nineteenth century the former occultist and convert Bartolo Longo enshrined an image of Our Lady of the Rosary in the Italian town near the ancient ruins of Pompeii, composing the celebrated Supplication to the Queen of the Holy Rosary prayed by millions.",
    "The title binds Marian devotion to the contemplation of Christ's mysteries in the Rosary, honoring Mary as the Queen of Victories who leads sinners to conversion.",
    "05-08",
  ),
  title(
    "our-lady-of-victory",
    "Our Lady of Victory",
    "Mary invoked as the cause of victory through the power of the Holy Rosary, especially commemorating the deliverance of Christendom at the Battle of Lepanto in 1571.",
    "Pope Saint Pius V attributed the Christian victory at Lepanto to the Rosaries prayed throughout Europe and instituted a commemoration of Our Lady of Victory, later kept as the feast of Our Lady of the Rosary.",
    "The title celebrates the triumph of grace won through Mary's intercession and the contemplation of her Son's mysteries in the Rosary.",
    "10-07",
  ),
];
