import type { CuratedEntry } from "./index";

import { novenaGroupOne } from "./novenas/group-1";
import { novenaGroupTwo } from "./novenas/group-2";

/**
 * The three novenas that predate the per-group files.
 *
 * All three used to be generated by a `nineDays(theme)` string function that
 * emitted nine identical days ("Heavenly Father, on this Nth day of prayer…"),
 * published under `authorityLevel: "VATICAN"` against the bare roots
 * vatican.va and usccb.org. Nothing behind that text was received, and no page
 * was actually being cited. The template is gone.
 *
 * Two of the three now carry a received public-domain form, in the same shape
 * the group files use: the traditional novena prayer to the Sacred Heart
 * ("Divine Jesus, You have said, 'Ask and you shall receive…'", which recalls
 * the promises made to St Margaret Mary) repeated on each of the nine days,
 * and the nine distinct day-prayers of the traditional novena to St Theresa of
 * the Child Jesus. Both are reproduced from the cited page; nothing is
 * paraphrased or composed.
 *
 * The Divine Mercy novena is deliberately NOT reproduced. Its received daily
 * texts are Diary 1209-1229 of St Faustina Kowalska, and the English of them
 * in circulation is the Marian Fathers' 1987 translation, still under
 * copyright — the same reason `./novenas/group-1.ts` refuses to vendor the
 * USCCB Sacred Heart novena and `./prayers/batch-8.ts` gives the Divine Mercy
 * chaplet formulas without the Diary accounts around them. What is given here
 * is what is not anyone's expression: the nine daily intentions, stated in the
 * editors' own words, and the chaplet that is prayed for them on each day.
 * The Diary text is omitted rather than paraphrased.
 */

const CD_SACRED_HEART = "https://www.catholicdoors.com/prayers/novenas/p00043.htm";
const CD_THERESE = "https://www.catholicdoors.com/prayers/novenas/p00078.htm";
const HAURIETIS_AQUAS =
  "https://www.vatican.va/content/pius-xii/en/encyclicals/documents/hf_p-xii_enc_15051956_haurietis-aquas.html";
const DIVINI_AMORIS_SCIENTIA =
  "https://www.vatican.va/content/john-paul-ii/en/apost_letters/1997/documents/hf_jp-ii_apl_19101997_divini-amoris.html";
const EWTN_CHAPLET = "https://www.ewtn.com/catholicism/devotions/chaplet-of-the-divine-mercy-387";
const JPII_FAUSTINA_CANONIZATION =
  "https://www.vatican.va/content/john-paul-ii/en/homilies/2000/documents/hf_jp-ii_hom_20000430_faustina.html";

/** The chaplet prayed on each day of the Divine Mercy novena (EWTN's form). */
const DIVINE_MERCY_CHAPLET =
  'Pray the Chaplet of the Divine Mercy for the day\'s souls. Begin with the Sign of the Cross, one Our Father, one Hail Mary and the Apostles\' Creed. On each Our Father bead: "Eternal Father, I offer You the Body and Blood, Soul and Divinity of Your dearly beloved Son, Our Lord Jesus Christ, in atonement for our sins and those of the whole world." On each of the ten Hail Mary beads: "For the sake of His sorrowful Passion, have mercy on us and on the whole world." After the five decades, three times: "Holy God, Holy Mighty One, Holy Immortal One, have mercy on us and on the whole world."';

/** Nine days that repeat one received prayer, distinguished by their subject. */
function repeatedPrayerDays(
  prayerText: string,
  subjects: ReadonlyArray<{ title: string; meditation: string; intentionPrompt?: string }>,
): Array<{
  day: number;
  title: string;
  meditation: string;
  prayerText: string;
  intentionPrompt?: string;
}> {
  return subjects.map((s, i) => ({
    day: i + 1,
    title: s.title,
    meditation: s.meditation,
    prayerText,
    ...(s.intentionPrompt ? { intentionPrompt: s.intentionPrompt } : {}),
  }));
}

const SACRED_HEART_NOVENA_PRAYER =
  'Divine Jesus, You have said, "Ask and you shall receive; seek and you shall find; knock and it shall be opened to you." Behold me kneeling at Your feet, filled with a lively faith and confidence in the promises dictated by Your Sacred Heart to Saint Margaret Mary. I come to ask this favour: (here name your request).\n\nTo whom can I turn if not to You, Whose Heart is the source of all graces and merits? Where should I seek if not in the treasure which contains all the riches of Your kindness and mercy? Where should I knock if not at the door through which God gives Himself to us and through which we go to God? I have recourse to You, Heart of Jesus. In You I find consolation when afflicted, protection when persecuted, strength when burdened with trials, and light in doubt and darkness.\n\nDear Jesus, I firmly believe that You can grant me the grace I implore, even though it should require a miracle. You have only to will it and my prayer will be granted. I admit that I am most unworthy of Your favours, but this is not a reason for me to be discouraged. You are the God of mercy, and You will not refuse a contrite heart. Cast upon me a look of mercy, I beg of You, and Your kind Heart will find in my miseries and weakness a reason for granting my prayer.\n\nSacred Heart, whatever may be Your decision with regard to my request, I will never stop adoring, loving, praising, and serving You. My Jesus, be pleased to accept this my act of perfect resignation to the decrees of Your adorable Heart, which I sincerely desire may be fulfilled in and by me and all Your creatures forever.\n\nGrant me the grace for which I humbly implore You through the Immaculate Heart of Your most sorrowful Mother. You entrusted me to her as her child, and her prayers are all-powerful with You. Amen.';

const LEGACY: CuratedEntry[] = [
  {
    contentType: "NOVENA",
    slug: "divine-mercy-novena",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [EWTN_CHAPLET, JPII_FAUSTINA_CANONIZATION],
    payload: {
      slug: "divine-mercy-novena",
      title: "Divine Mercy Novena",
      summary:
        "The novena kept from Good Friday through the Saturday before Divine Mercy Sunday, in which a different group of souls is brought to Christ on each of the nine days and the Chaplet of the Divine Mercy is prayed for them.",
      background:
        "The nine daily intentions were recorded by Saint Faustina Kowalska in 1937 in her Diary, at entries 1209 to 1229, and the received prayer for each day is part of that text. The Diary and its standard English translation are under copyright and are not reproduced here; what follows names the day's intention in the editors' own words and gives the chaplet, whose formulas are public. The full received day-prayers should be read in an authorised edition of the Diary or on the Marian Fathers' Divine Mercy pages. Pope John Paul II canonised Saint Faustina on 30 April 2000 and on the same day established the Second Sunday of Easter as Divine Mercy Sunday for the universal Church.",
      intentionTheme: "the mercy of God poured out on every kind of soul",
      days: repeatedPrayerDays(DIVINE_MERCY_CHAPLET, [
        {
          title: "All mankind, especially sinners",
          meditation:
            "The novena begins as wide as it possibly can: the whole human race, and within it those who have most obviously wandered. Nobody is prayed for on a later day who was not already prayed for on this one.",
          intentionPrompt: "Whom do I quietly think of as beyond mercy?",
        },
        {
          title: "The souls of priests and religious",
          meditation:
            "The second day asks mercy for those through whom mercy ordinarily reaches everyone else. Their fruitfulness is not their own achievement, and the Church prays for it rather than assuming it.",
          intentionPrompt: "When did I last pray for the priest who absolves me?",
        },
        {
          title: "All devout and faithful souls",
          meditation:
            "The devout are not exempt from needing mercy; they are simply people who already know they need it. The third day asks that the faithful be strengthened in the perseverance they cannot manufacture.",
          intentionPrompt: "Where am I trusting my own steadiness rather than God's?",
        },
        {
          title: "Those who do not believe in God and those who do not yet know Christ",
          meditation:
            "The fourth day looks outside the visible Church entirely, to unbelief and to simple ignorance of Christ, and asks light for both without confusing the two.",
          intentionPrompt: "Do I pray for the people I argue with?",
        },
        {
          title: "Those who have separated themselves from the Church",
          meditation:
            "The fifth day prays for Christians divided from Catholic communion, and for those who have walked away from it, asking not that they be defeated but that they be drawn back into unity.",
          intentionPrompt: "Is there someone whose leaving I have written off?",
        },
        {
          title: "The meek and humble souls and the souls of little children",
          meditation:
            "The sixth day prays for those the Gospel calls closest to the Kingdom. It is the one day of the novena that asks mercy chiefly by way of thanksgiving.",
          intentionPrompt: "What would it cost me to be genuinely meek this week?",
        },
        {
          title: "Those who especially venerate and glorify God's mercy",
          meditation:
            "The seventh day prays for the devotees of Divine Mercy themselves — a reminder that promoting a devotion is not the same as living from it.",
          intentionPrompt: "Do I preach mercy more readily than I practise it?",
        },
        {
          title: "The souls detained in purgatory",
          meditation:
            "The eighth day turns to the Church suffering, who can no longer merit for themselves and depend entirely on the prayer of the living.",
          intentionPrompt: "Whose name among my dead have I stopped saying?",
        },
        {
          title: "Souls who have become lukewarm",
          meditation:
            "The novena ends with the hardest case: not open rejection but indifference. It is placed last because it is the condition most likely to belong to the person praying.",
          intentionPrompt: "Where has my faith gone tepid without my noticing?",
        },
      ]),
      durationDays: 9,
      structure: "nine_days",
      typicalStartDate: "Good Friday, ending on the Saturday before Divine Mercy Sunday",
      associatedSaintSlug: "saint-faustina-kowalska",
      citations: [EWTN_CHAPLET, JPII_FAUSTINA_CANONIZATION],
    },
  },
  {
    contentType: "NOVENA",
    slug: "novena-sacred-heart-of-jesus",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [CD_SACRED_HEART, HAURIETIS_AQUAS],
    payload: {
      slug: "novena-sacred-heart-of-jesus",
      title: "Novena to the Sacred Heart of Jesus",
      summary:
        "Nine days of prayer in preparation for the Solemnity of the Most Sacred Heart of Jesus. The received prayer appeals to the promises made to Saint Margaret Mary Alacoque and asks one particular favour with confidence, ending in perfect resignation to whatever the Heart of Jesus decides.",
      background:
        "Devotion to the Sacred Heart was spread from the apparitions to Saint Margaret Mary Alacoque at Paray-le-Monial between 1673 and 1675, and received its fullest magisterial exposition in Pius XII's encyclical Haurietis Aquas of 15 May 1956, which grounds the devotion in the wounded side of Christ rather than in private revelation. This novena is a private devotion prepared for the solemnity; its received form repeats the one prayer on each of the nine days, and the printed text adds a daily Offering of one's prayers, works, joys and sufferings in union with the Sacred Heart. The day-by-day subjects below are editorial and are not part of the prayer.",
      intentionTheme: "confidence in the Sacred Heart of Jesus and one particular petition",
      days: repeatedPrayerDays(SACRED_HEART_NOVENA_PRAYER, [
        {
          title: "Ask and you shall receive",
          meditation:
            "The novena opens by holding Christ to His own words. Petition is not presumption when the promise being invoked is His.",
          intentionPrompt: "What am I actually asking for, in one plain sentence?",
        },
        {
          title: "The promises made to Saint Margaret Mary",
          meditation:
            "The prayer appeals to the promises dictated to a Visitation nun of Paray-le-Monial. Haurietis Aquas is careful to say the devotion rests on Scripture and the pierced side of Christ; the promises encourage it, they do not found it.",
          intentionPrompt: "Do I trust the Heart of Christ, or only the promises attached to it?",
        },
        {
          title: "The source of all graces",
          meditation:
            "To whom can I turn if not to You? The third day makes the question its own answer: there is no second treasury.",
          intentionPrompt: "Where do I go first when something goes wrong?",
        },
        {
          title: "The door through which God gives Himself",
          meditation:
            "The Heart is named as the door in both directions — God comes to us through it and we go to God through it. That is the doctrine of the mediation of Christ, prayed rather than argued.",
          intentionPrompt: "Am I trying to reach God around Christ rather than through Him?",
        },
        {
          title: "Consolation when afflicted",
          meditation:
            "The prayer lists what it has found in that Heart: consolation, protection, strength, light. It is a report, not a hope.",
          intentionPrompt: "Which of those four do I most need named for me today?",
        },
        {
          title: "Even though it should require a miracle",
          meditation:
            "The sixth day refuses to make the petition small in order to make it likelier. You have only to will it, and my prayer will be granted.",
          intentionPrompt: "Have I shrunk my prayer to what I think God can manage?",
        },
        {
          title: "Unworthy, and not discouraged",
          meditation:
            "Unworthiness is admitted and then explicitly refused as a reason to stop asking. Our miseries become the reason for granting rather than the obstacle.",
          intentionPrompt: "What shame is keeping me from asking plainly?",
        },
        {
          title: "Whatever may be Your decision",
          meditation:
            "The eighth day is the hinge of the whole novena. Adoration, love, praise and service are promised in advance of the answer, and therefore regardless of it.",
          intentionPrompt: "Would I still pray this novena if I knew the answer were no?",
        },
        {
          title: "Through the Immaculate Heart of His Mother",
          meditation:
            "The novena closes as the devotion always does, by handing the petition to the Mother given to us from the Cross.",
          intentionPrompt: "Have I asked Our Lady to carry this for me?",
        },
      ]),
      durationDays: 9,
      structure: "nine_days",
      typicalStartDate:
        "The nine days before the Solemnity of the Most Sacred Heart of Jesus, the Friday after the Second Sunday after Pentecost",
      relatedFeastSlug: "solemnity-sacred-heart",
      citations: [CD_SACRED_HEART, HAURIETIS_AQUAS],
    },
  },
  {
    contentType: "NOVENA",
    slug: "novena-saint-therese",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [CD_THERESE, DIVINI_AMORIS_SCIENTIA],
    payload: {
      slug: "novena-saint-therese",
      title: "Novena to Saint Thérèse of Lisieux",
      summary:
        "The traditional nine-day novena to Saint Theresa of the Child Jesus, with a distinct received prayer for each day: sanctifying grace, the graces of light and fortitude, growth in virtue, patience in trial, the Blessed Sacrament, devotion to Our Lady, veneration of the saints, our temporal needs, and final perseverance.",
      background:
        "Saint Thérèse Martin of Lisieux (1873-1897), a Carmelite who taught the little way of spiritual childhood, was canonised by Pius XI in 1925, named a patroness of the missions in 1927, and declared a Doctor of the Church by John Paul II in the apostolic letter Divini Amoris Scientia of 19 October 1997. The nine prayers below are the received form of the traditional novena as printed in the older prayer books; each day addresses the Father first and then asks the saint's intercession. Obvious scanning slips in the transcribed source have been silently corrected; no wording has been changed.",
      intentionTheme:
        "the intercession of Saint Thérèse and the grace of her little way of confidence",
      days: [
        {
          day: 1,
          title: "Sanctifying grace",
          meditation:
            "The first day asks for the gift that makes everything else possible: the state of grace, kept in the middle of the ordinary dangers of a life lived in the world.",
          prayerText:
            "O Heavenly Father, Who in Thine ineffable goodness didst place in the soul of Saint Theresa of the Child Jesus the precious treasure of sanctifying grace, and didst grant her ever to keep it in the midst of earthly dangers, we pray Thee to grant to us for our part the happiness of never losing this inestimable gift whereby we become Thine adopted children, the brothers and sisters of Thy Son Jesus, the temples of the Holy Spirit and the heirs of Heaven. Enable us, to this end, carefully to avoid mortal sin which would rob us of this grace more to be desired than all the wealth of the world, to fly the occasions of sin, and to resist temptation. We implore these graces through the intercession of the one who was ever Thy faithful child and whose memory we venerate.\n\nSaint Theresa of the Child Jesus, who would have preferred to die rather than lose God's grace, vouchsafe to obtain for us all the help necessary to avoid the misfortune of committing mortal sin, incompatible with this divine grace. Obtain for us the favours we crave and implore through your powerful intercession. Amen.",
          intentionPrompt: "What occasion of sin am I still choosing not to avoid?",
        },
        {
          day: 2,
          title: "The graces of light and fortitude",
          meditation:
            "The second day asks for actual grace — the daily supernatural help without which, as the prayer says, no one can even utter the name of Jesus.",
          prayerText:
            "O Heavenly Father, Who to assure our advancement in the right path dost never cease to multiply the supernatural means of help which we need, and which Thou hast divinely poured out upon Saint Theresa of the Child Jesus, we beg of Thee, through this Saint so dear to Thy Heart, all the graces of light and of fortitude necessary or helpful to fulfil Thine adorable will. Thy grace ever went before Saint Theresa and Thou didst uphold her at each moment, for Thou didst give to her both to will and to do, and without Thee none can even utter the name of Jesus whereby we may be saved. Father, shed abroad in our minds and hearts those graces won by the merits of our Saviour and which Saint Theresa asks for us.\n\nSaint Theresa of the Child Jesus, upon whom so many divine graces were showered, we pray you to intercede with our Heavenly Father, so that through the merits of our Saviour and your merits, He may vouchsafe to give to our souls all the graces needful for the perfect fulfilment of our duty. Obtain for us the favours we crave and implore through your powerful intercession. Amen.",
          intentionPrompt: "What duty am I trying to do on willpower alone?",
        },
        {
          day: 3,
          title: "Growth in virtue",
          meditation:
            "The third day names the virtues the little way is actually made of — humility, simplicity, patience, confidence, zeal and love — and asks for them as gifts joined to real effort.",
          prayerText:
            "O Heavenly Father, Who didst dispose the soul of Saint Theresa of the Child Jesus to ascend by such wonderful steps and didst make this lovable saint to rise from virtue to virtue, aiding her so admirably to practise humility, simplicity, patience, confidence, zeal and love, we beseech Thee to place in our hearts dispositions like to hers and to grant us to resemble her, that we may hence become conformable to Thy Son Jesus, our Model and the Divine Example of Thine adorable perfections. These virtues are so needful for us, for without them we cannot be happy here below; without them we cannot gain for Thee the glory that Thou dost look for from us. Vouchsafe, O Father, to help us to make these virtues ours. May Thy numerous graces, joined to our generous efforts, bring forth, as in Saint Theresa, true and lasting virtue.\n\nSaint Theresa of the Child Jesus, who to please God ever wonderfully grew in virtue each day of your life, obtain for us to resemble you and generously to practise those virtues of which you have left us such a beautiful example. Obtain for us the favours we crave and implore through your powerful intercession. Amen.",
          intentionPrompt: "Which one of those six virtues would cost me most today?",
        },
        {
          day: 4,
          title: "Patience in trial",
          meditation:
            "The fourth day asks for fortitude and consolation in suffering, and for the harder grace of understanding what suffering is for.",
          prayerText:
            "O Heavenly Father, Who in Thine infinite wisdom dost permit the just to be tried upon earth, like gold in the furnace, hereafter to crown them gloriously in Heaven, we beseech Thee to grant us, through the intercession of Saint Theresa of the Child Jesus, all the graces of fortitude and consolation which we urgently need in the difficulties we encounter here below. Thou dost order all things for the good of those who love Thee; nothing befalls without Thy permission, and Thou knowest how to draw good out of evil. May these consoling truths be our support in the midst of our sorrows. Sweeten for us all that is bitter by the unction of Thy grace. Permit not, O Father, that impatience shall possess our heart or murmurs rise to our lips. Make us understand the providential use of sorrow, as it was understood by Saint Theresa, who owned to finding happiness in the midst of suffering.\n\nSaint Theresa of the Child Jesus, who suffered much here below and knew how to find joy in every bitterness, intercede for us with God that so He may help us to bear patiently all our crosses, and console our hearts saddened by the trials of earth's exile. Obtain for us the favours we crave and implore through your powerful intercession. Amen.",
          intentionPrompt: "What am I murmuring about that I have not yet offered?",
        },
        {
          day: 5,
          title: "The Blessed Sacrament",
          meditation:
            "The fifth day turns to the Eucharist, which Thérèse longed for, and asks for frequent Communion made with the dispositions she brought to it.",
          prayerText:
            "O Heavenly Father, Who so loved men that Thou didst give them Thine Only-begotten Son to be their Redeemer upon the Cross, and Food in the Divine Sacrament of the Altar, we beseech Thee to grant us, through the prayers of Saint Theresa of the Child Jesus, so inflamed with love for this Adorable Sacrament and so eager to receive It, the grace for our part to draw near very often to the Holy Table. Following the example of Saint Theresa of the Child Jesus, may we bring to it the best dispositions: a right intention, hearts filled with lively faith, sincere humility, deep confidence, ardent charity. Father, make us truly understand that this Divine Bread is no less needful to our soul than material bread is to our body, and that we cannot abstain from It without hurt to our soul.\n\nSaint Theresa of the Child Jesus, who so much loved the Divine Sacrament of the Altar and so greatly longed to unite yourself to It through Holy Communion, obtain for us from God a love like to yours for this Adorable Sacrament and a fervent longing often to receive It in our hearts. Obtain for us the favours we crave and implore through your powerful intercession. Amen.",
          intentionPrompt: "When did I last go to Communion actually wanting to?",
        },
        {
          day: 6,
          title: "Devotion to the Blessed Virgin",
          meditation:
            "The sixth day recalls the smile of Our Lady that Thérèse saw as a sick child, and asks for a share in her tender devotion to the Mother of God.",
          prayerText:
            "O Heavenly Father, Who bestowed upon the Blessed Virgin Mary the greatest and most precious graces and privileges, and called her to become the Mother of Thy Son Jesus, also giving her to be our Mother, we beseech Thee, through the intercession of Saint Theresa of the Child Jesus, ever so faithful to honour this beloved Virgin, whose radiant countenance and gracious smile she one day beheld, to grant us too the inestimable favour of being the very loving children of this Holy Mother. We need her maternal mediation, for this good Mother is the way that leads to Jesus, and she is the treasurer of all the graces that our Saviour acquired for us by the shedding of His Precious Blood. We thank Thee, O Father, for having given us the Blessed Virgin to be our Mother and our guide along our life's path, and we beseech Thee that, like Saint Theresa of the Child Jesus, we may be true imitators of her virtues: of her perfect humility, her immaculate purity, and her ardent love. We look to her for the greatest succour now and at the hour of our death.\n\nSaint Theresa of the Child Jesus, who ever manifested a great love for the One you named the Immaculate Virgin, and from whom you received so many benefits, we ask you to obtain for us the grace to imitate your tender devotion towards her and to help us to reproduce her beautiful and admirable virtues even as you yourself did. Obtain for us the favours we crave and implore through your powerful intercession. Amen.",
          intentionPrompt: "Is Our Lady a doctrine to me, or a mother?",
        },
        {
          day: 7,
          title: "Veneration of the saints",
          meditation:
            "The seventh day asks for a devotion that is well ordered and constant — one that sanctifies, and that returns in the end to God, to whom all honour paid to the saints belongs.",
          prayerText:
            "O Heavenly Father, Who hast bestowed upon us so many benefits through the intercession of Saint Theresa of the Child Jesus, and willest that we should honour this lovable saint with a special devotion, we earnestly implore Thee of Thy fatherly loving-kindness the grace to be ever faithful in venerating her, invoking her and imitating her virtues. It is good for us to pay honour to the Saints. Thou hast placed these blessed Saints as powerful mediators between ourselves and Thee, that so Thou mayest bestow upon us more ready and more abundant aids. That which our prayer cannot obtain, theirs will obtain for us. Thou hast willed that the Saints should be our models. They were once what we are; we can with Thy grace become what they are; what they have done, we can do in our turn. Father, give us a true and lasting devotion towards Saint Theresa of the Child Jesus, a devotion well ordered and constant, a devotion that will sanctify us and lead us to Thee, to Whom all the homage we pay to the Saints returns.\n\nSaint Theresa of the Child Jesus, placed by the Church upon our altars to be our protectress with God and model in Christian life, obtain for us, we ask of you, ever to have you in honour, to venerate you, to invoke you, to imitate you, for the greater glory of God and the greater good of our souls. Obtain for us the favours we crave and implore through your powerful intercession. Amen.",
          intentionPrompt: "Do I ask the saints for favours more than I imitate them?",
        },
        {
          day: 8,
          title: "Our temporal needs",
          meditation:
            "The eighth day asks plainly for what this life requires, and in the same breath for the detachment that keeps those things from becoming the point.",
          prayerText:
            "O Heavenly Father, Who hast created all the good things of earth for the use of man and dost measure them out to him with marvellous bounty, we beg Thee, through the intercession of Saint Theresa of the Child Jesus, to give us all those things of which we have need for the preservation of our life here below. Teach us to use these things with the moderation befitting Christians; let us not attach our heart to them; may they serve not to keep us from Thee, the Only True Good to be desired and the Giver of all that is good in this world. Give us, as Thou gavest to Thy faithful handmaid Saint Theresa of the Child Jesus, to make a holy use of earthly things and to make them serve for Thy glory. Father, Who dost feed the birds of the air and clothe the lilies of the valley, forsake not the souls of those who trust in Thee.\n\nSaint Theresa of the Child Jesus, who ever used the things of this world according to the order willed by God, you who made earthly gifts serve to merit those that are heavenly, we ask you to obtain for us all that is necessary for us during our life upon earth. Obtain for us the favours we crave and implore through your powerful intercession. Amen.",
          intentionPrompt: "Which of my possessions would I find hardest to lose?",
        },
        {
          day: 9,
          title: "Final perseverance",
          meditation:
            "The novena ends where every novena ends: asking for the grace of graces, which no one can merit and which decides everything.",
          prayerText:
            "O Heavenly Father, Who hast prepared for us a glorious reward after the labours of this life, and hast promised to crown with honour and glory those who are faithful to the end in Thy love, we beseech Thee to grant us, through the intercession of Saint Theresa of the Child Jesus, the grace to be faithful to Thy Commandments, to those of the Holy Church, and to Thy holy inspirations until the hour of our death. Father, grant that, after the example of Saint Theresa of the Child Jesus, we may not recoil from labours, that temptations may not keep us from Thee, that trials may not cause us to lose courage. May neither the world, nor the devil, nor our own inclinations separate us from Thee, to Whom we desire to belong for ever, as we promised Thee on the day of our Baptism and on the day of our First Communion. Perseverance in grace is a grace; we beseech Thee to grant it to us, and in Thy merciful love not to refuse us the grace of graces, that of final perseverance, which will unite us to Thee for evermore and will give us to contemplate during all Eternity Thine adorable Face. Father, uphold us in the midst of our combats until the day when we shall gain the victory, when Thou Thyself wilt triumph in us.\n\nSaint Theresa of the Child Jesus, who persevered throughout your life in exact fidelity to God's grace, you who saw your perseverance crowned on the glorious day of your death, obtain for us to be fully faithful to God's law and never to separate ourselves from His holy love. Obtain for us the favours we crave and implore through your powerful intercession. Amen.",
          intentionPrompt:
            "If today were the last day, what would I want to have been faithful in?",
        },
      ],
      durationDays: 9,
      structure: "nine_days",
      typicalStartDate: "The nine days before her memorial on 1 October",
      associatedSaintSlug: "saint-therese-of-lisieux",
      citations: [CD_THERESE, DIVINI_AMORIS_SCIENTIA],
    },
  },
];

/**
 * The novena registry: the hand-written entries above plus every per-group
 * file under `./novenas/`. The group files are imported by their full explicit
 * path so the bare `./novenas` specifier keeps resolving to THIS file (see the
 * module-resolution note in `./guides.ts`).
 */
export const novenaKnowledge: CuratedEntry[] = [...LEGACY, ...novenaGroupOne, ...novenaGroupTwo];
