import type { CuratedEntry } from "./index";

const VATICAN = "https://www.vatican.va/";
const NEWADVENT = "https://www.newadvent.org/cathen/";

function pope(
  slug: string,
  title: string,
  papacyStart: string,
  papacyEnd: string | undefined,
  birthName: string,
  background: string,
): CuratedEntry {
  const payload: Record<string, unknown> = {
    slug,
    title,
    papacyStart,
    birthName,
    background,
    summary: `${title}, who reigned as Roman Pontiff from ${papacyStart}${
      papacyEnd ? `–${papacyEnd}` : " to the present"
    }.`,
    citations: [VATICAN, NEWADVENT],
  };
  if (papacyEnd) payload.papacyEnd = papacyEnd;
  return {
    contentType: "POPE",
    slug,
    authorityLevel: "VATICAN",
    citations: [VATICAN, NEWADVENT],
    payload,
  };
}

/**
 * Well-documented Roman Pontiffs anchoring the chronological list of popes.
 * `papacyStart` is the chronological sort key; `papacyEnd` is omitted only for
 * the currently reigning pope. Dates follow the Annuario Pontificio and
 * standard Catholic reference sources — ground-truth content the worker can
 * publish without a live fetch. The full line of 266 popes is expanded by the
 * worker from approved sources.
 */
export const popeKnowledge: CuratedEntry[] = [
  pope(
    "pope-saint-peter",
    "Pope Saint Peter",
    "30",
    "64",
    "Simon bar Jonah",
    "Saint Peter, chief of the Apostles, was appointed by Christ as the rock on which the Church is built (Matthew 16:18) and the first Bishop of Rome. He led the apostolic community after Pentecost and was martyred in Rome under Nero around AD 64; his tomb lies beneath the high altar of St. Peter's Basilica.",
  ),
  pope(
    "pope-saint-linus",
    "Pope Saint Linus",
    "67",
    "76",
    "Linus",
    "Saint Linus succeeded Saint Peter as Bishop of Rome and is named in the Roman Canon of the Mass. Early tradition, recorded by Irenaeus, lists him as the second pope.",
  ),
  pope(
    "pope-saint-clement-i",
    "Pope Saint Clement I",
    "88",
    "99",
    "Clement",
    "Saint Clement I, fourth Bishop of Rome and an Apostolic Father, wrote the Letter to the Corinthians (c. 96), the earliest surviving exercise of Roman authority over another church. Tradition holds that he was martyred under Trajan.",
  ),
  pope(
    "pope-saint-sylvester-i",
    "Pope Saint Sylvester I",
    "314",
    "335",
    "Sylvester",
    "Saint Sylvester I was Bishop of Rome during the reign of Constantine, when the Church emerged from persecution. His pontificate saw the First Council of Nicaea (325) and the building of the first great Roman basilicas.",
  ),
  pope(
    "pope-saint-damasus-i",
    "Pope Saint Damasus I",
    "366",
    "384",
    "Damasus",
    "Saint Damasus I commissioned Saint Jerome to revise the Latin Scriptures (the Vulgate), promoted the cult of the Roman martyrs, and affirmed the primacy of the Roman See.",
  ),
  pope(
    "pope-saint-leo-the-great",
    "Pope Saint Leo the Great",
    "440",
    "461",
    "Leo",
    "Pope Saint Leo I, one of only two popes called 'the Great' and a Doctor of the Church, defended the orthodox doctrine of the Incarnation in his Tome, accepted at the Council of Chalcedon (451), and famously persuaded Attila the Hun to spare Rome in 452.",
  ),
  pope(
    "pope-saint-gregory-the-great",
    "Pope Saint Gregory the Great",
    "590",
    "604",
    "Gregory",
    "Pope Saint Gregory I, a Doctor of the Church, reformed the liturgy and Church administration, sent Augustine of Canterbury to evangelize England, cared for the poor of Rome, and wrote the Pastoral Rule. Gregorian chant bears his name.",
  ),
  pope(
    "pope-saint-gregory-vii",
    "Pope Saint Gregory VII",
    "1073",
    "1085",
    "Hildebrand of Sovana",
    "Pope Saint Gregory VII led the Gregorian Reform against simony and lay investiture, asserting the freedom of the Church from secular control in the famous conflict with Emperor Henry IV at Canossa.",
  ),
  pope(
    "pope-blessed-urban-ii",
    "Pope Blessed Urban II",
    "1088",
    "1099",
    "Odo of Châtillon",
    "Blessed Pope Urban II continued the Gregorian Reform and, at the Council of Clermont in 1095, preached the First Crusade to aid the Eastern Christians and recover the Holy Land.",
  ),
  pope(
    "pope-innocent-iii",
    "Pope Innocent III",
    "1198",
    "1216",
    "Lotario dei Conti di Segni",
    "Pope Innocent III brought the medieval papacy to the height of its influence, approved the new orders of Saint Francis and Saint Dominic, and convened the Fourth Lateran Council (1215), which defined transubstantiation and reformed Church discipline.",
  ),
  pope(
    "pope-boniface-viii",
    "Pope Boniface VIII",
    "1294",
    "1303",
    "Benedetto Caetani",
    "Pope Boniface VIII proclaimed the first Holy Year (Jubilee) in 1300 and asserted papal authority in the bull Unam Sanctam during his conflict with King Philip IV of France.",
  ),
  pope(
    "pope-saint-pius-v",
    "Pope Saint Pius V",
    "1566",
    "1572",
    "Antonio Ghislieri",
    "Pope Saint Pius V, a Dominican, implemented the reforms of the Council of Trent, promulgated the Roman Catechism, Breviary, and Missal (the Tridentine Mass), and organized the Holy League whose victory at Lepanto in 1571 he attributed to the Rosary.",
  ),
  pope(
    "pope-gregory-xiii",
    "Pope Gregory XIII",
    "1572",
    "1585",
    "Ugo Boncompagni",
    "Pope Gregory XIII reformed the calendar in 1582, producing the Gregorian calendar still in use today, and was a great patron of the Jesuit colleges and the Catholic Reformation.",
  ),
  pope(
    "pope-pius-ix",
    "Pope Blessed Pius IX",
    "1846",
    "1878",
    "Giovanni Maria Mastai-Ferretti",
    "Blessed Pope Pius IX had the longest verified pontificate in history. He defined the dogma of the Immaculate Conception (1854), convened the First Vatican Council (1869-70), which defined papal infallibility, and witnessed the loss of the Papal States.",
  ),
  pope(
    "pope-leo-xiii",
    "Pope Leo XIII",
    "1878",
    "1903",
    "Vincenzo Gioacchino Pecci",
    "Pope Leo XIII inaugurated modern Catholic social teaching with the encyclical Rerum Novarum (1891) on the rights of workers, promoted the revival of Thomistic philosophy (Aeterni Patris), and fostered devotion to the Rosary.",
  ),
  pope(
    "pope-saint-pius-x",
    "Pope Saint Pius X",
    "1903",
    "1914",
    "Giuseppe Melchiorre Sarto",
    "Pope Saint Pius X promoted frequent and early Holy Communion, reformed the liturgy and sacred music, initiated the codification of canon law, and firmly opposed the errors of Modernism.",
  ),
  pope(
    "pope-benedict-xv",
    "Pope Benedict XV",
    "1914",
    "1922",
    "Giacomo della Chiesa",
    "Pope Benedict XV guided the Church through the First World War, tirelessly pursuing peace and organizing humanitarian relief, and promulgated the first Code of Canon Law in 1917.",
  ),
  pope(
    "pope-pius-xi",
    "Pope Pius XI",
    "1922",
    "1939",
    "Achille Ratti",
    "Pope Pius XI signed the Lateran Treaty (1929) establishing Vatican City, instituted the feast of Christ the King, and issued landmark encyclicals on marriage, social order, and against the totalitarian ideologies of his day.",
  ),
  pope(
    "pope-venerable-pius-xii",
    "Pope Venerable Pius XII",
    "1939",
    "1958",
    "Eugenio Pacelli",
    "Pope Pius XII led the Church through the Second World War, defined the dogma of the Assumption of the Blessed Virgin Mary (1950), and issued influential encyclicals on Scripture (Divino Afflante Spiritu) and the liturgy (Mediator Dei).",
  ),
  pope(
    "pope-saint-john-xxiii",
    "Pope Saint John XXIII",
    "1958",
    "1963",
    "Angelo Giuseppe Roncalli",
    "Pope Saint John XXIII, called 'the Good Pope,' convened the Second Vatican Council (1962) and wrote the encyclicals Mater et Magistra and Pacem in Terris. Canonized in 2014.",
  ),
  pope(
    "pope-saint-paul-vi",
    "Pope Saint Paul VI",
    "1963",
    "1978",
    "Giovanni Battista Montini",
    "Pope Saint Paul VI brought the Second Vatican Council to completion and oversaw its implementation, promulgated the revised Roman Missal, and issued the encyclical Humanae Vitae (1968). Canonized in 2018.",
  ),
  pope(
    "pope-john-paul-i",
    "Pope John Paul I",
    "1978",
    "1978",
    "Albino Luciani",
    "Pope John Paul I, 'the Smiling Pope,' reigned only thirty-three days in 1978 before his sudden death. He was the first pope to take a double name. Beatified in 2022.",
  ),
  pope(
    "pope-saint-john-paul-ii",
    "Pope Saint John Paul II",
    "1978",
    "2005",
    "Karol Józef Wojtyła",
    "Pope Saint John Paul II, the first Polish pope and first non-Italian in 455 years, reigned for nearly twenty-seven years. He helped bring down communism in Eastern Europe, founded World Youth Day, promulgated the Catechism of the Catholic Church, and canonized more saints than any predecessor. Canonized in 2014.",
  ),
  pope(
    "pope-benedict-xvi",
    "Pope Benedict XVI",
    "2005",
    "2013",
    "Joseph Aloisius Ratzinger",
    "Pope Benedict XVI, a distinguished theologian, wrote the encyclicals Deus Caritas Est, Spe Salvi, and Caritas in Veritate and the Jesus of Nazareth trilogy. In 2013 he became the first pope in nearly six centuries to resign the papacy.",
  ),
  pope(
    "pope-francis",
    "Pope Francis",
    "2013",
    "2025",
    "Jorge Mario Bergoglio",
    "Pope Francis, the first pope from the Americas and the first Jesuit pope, emphasized mercy, care for the poor, and care for creation in the encyclicals Laudato Si' and Fratelli Tutti. He convened the Synod on Synodality and proclaimed the Jubilee of Mercy. His pontificate ended with his death in 2025.",
  ),
  pope(
    "pope-leo-xiv",
    "Pope Leo XIV",
    "2025",
    undefined,
    "Robert Francis Prevost",
    "Pope Leo XIV, born in Chicago, is the first pope from the United States. An Augustinian friar who served for years as a missionary and bishop in Peru and then as Prefect of the Dicastery for Bishops, he was elected in 2025. He took the name Leo in continuity with Leo XIII and the Church's social teaching.",
  ),
  pope(
    "pope-saint-cornelius",
    "Pope Saint Cornelius",
    "251",
    "253",
    "Cornelius",
    "Pope Saint Cornelius led the Church during the persecution of Decius and upheld, with Saint Cyprian of Carthage, the readmission of repentant apostates against the rigorist schism of Novatian. He died in exile and is honored as a martyr; his name is in the Roman Canon.",
  ),
  pope(
    "pope-saint-leo-iii",
    "Pope Saint Leo III",
    "795",
    "816",
    "Leo",
    "Pope Saint Leo III crowned Charlemagne as Emperor in St. Peter's Basilica on Christmas Day in the year 800, a turning point for medieval Christendom that bound the papacy and the new Western empire together.",
  ),
  pope(
    "pope-saint-nicholas-i",
    "Pope Saint Nicholas I (the Great)",
    "858",
    "867",
    "Nicholas",
    "Pope Saint Nicholas I, one of the three popes called 'the Great,' vigorously defended the authority and moral teaching of the Roman See against powerful rulers and bishops, upholding the indissolubility of marriage and the rights of the Church.",
  ),
  pope(
    "pope-alexander-iii",
    "Pope Alexander III",
    "1159",
    "1181",
    "Rolando Bandinelli",
    "Pope Alexander III prevailed in a long struggle with Emperor Frederick Barbarossa and convened the Third Lateran Council (1179), which decreed that a two-thirds majority of the cardinals is required to elect a pope — the basis of conclave law ever since.",
  ),
  pope(
    "pope-sixtus-iv",
    "Pope Sixtus IV",
    "1471",
    "1484",
    "Francesco della Rovere",
    "Pope Sixtus IV, a Franciscan theologian, was a great patron of the arts who built the Sistine Chapel that bears his name and enlarged the Vatican Library. His pontificate also marked the height of Renaissance papal patronage in Rome.",
  ),
  pope(
    "pope-julius-ii",
    "Pope Julius II",
    "1503",
    "1513",
    "Giuliano della Rovere",
    "Pope Julius II, the 'Warrior Pope,' laid the cornerstone of the present St. Peter's Basilica in 1506 and was the patron of Michelangelo, who painted the Sistine Chapel ceiling, and of Raphael. He convened the Fifth Lateran Council.",
  ),
  pope(
    "pope-paul-iii",
    "Pope Paul III",
    "1534",
    "1549",
    "Alessandro Farnese",
    "Pope Paul III opened the Catholic Reformation: he approved the Society of Jesus (the Jesuits) in 1540 and convened the Council of Trent in 1545, the council that shaped Catholic doctrine and discipline for four centuries.",
  ),
  pope(
    "pope-urban-viii",
    "Pope Urban VIII",
    "1623",
    "1644",
    "Maffeo Barberini",
    "Pope Urban VIII, a patron of Bernini and of Baroque Rome, consecrated the new St. Peter's Basilica in 1626. His pontificate is also remembered for the trial of Galileo before the Roman Inquisition.",
  ),
  pope(
    "pope-benedict-xiv",
    "Pope Benedict XIV",
    "1740",
    "1758",
    "Prospero Lambertini",
    "Pope Benedict XIV, one of the most learned popes, reformed the process for canonizations, promoted the sciences and historical scholarship, and issued influential encyclicals. He was respected even by the leading thinkers of the Enlightenment.",
  ),
  pope(
    "pope-pius-vi",
    "Pope Pius VI",
    "1775",
    "1799",
    "Giovanni Angelo Braschi",
    "Pope Pius VI reigned through the upheaval of the French Revolution, which suppressed the Church in France. Taken prisoner by French forces, he died in captivity at Valence in 1799, faithful to the end.",
  ),
  pope(
    "pope-pius-vii",
    "Pope Pius VII",
    "1800",
    "1823",
    "Barnaba Chiaramonti",
    "Pope Pius VII signed the Concordat of 1801 restoring the Church in France, was imprisoned by Napoleon for years, and after his release restored the Society of Jesus in 1814. His patient endurance won wide admiration.",
  ),
  pope(
    "pope-gregory-xvi",
    "Pope Gregory XVI",
    "1831",
    "1846",
    "Bartolomeo Alberto Cappellari",
    "Pope Gregory XVI, a Camaldolese monk, strongly promoted the Church's worldwide missions and, in the bull In Supremo Apostolatus (1839), condemned the slave trade and the enslavement of peoples.",
  ),
  pope(
    "pope-saint-fabian",
    "Pope Saint Fabian",
    "236",
    "250",
    "Fabian",
    "Pope Saint Fabian organized the Church of Rome into deaconries and is said to have been chosen pope when a dove alighted on his head. He was martyred at the outbreak of the persecution of the Emperor Decius.",
  ),
  pope(
    "pope-saint-callixtus-i",
    "Pope Saint Callixtus I",
    "217",
    "222",
    "Callixtus",
    "Pope Saint Callixtus I, once a slave, became a deacon entrusted with the Christian cemetery on the Appian Way that still bears his name. As pope he showed mercy to repentant sinners and was martyred during a popular uprising.",
  ),
  pope(
    "pope-saint-sixtus-ii",
    "Pope Saint Sixtus II",
    "257",
    "258",
    "Sixtus",
    "Pope Saint Sixtus II was seized and beheaded while celebrating the liturgy in the catacombs during the persecution of the Emperor Valerian. His name is honored in the Roman Canon of the Mass.",
  ),
  pope(
    "pope-saint-gelasius-i",
    "Pope Saint Gelasius I",
    "492",
    "496",
    "Gelasius",
    "Pope Saint Gelasius I articulated the doctrine of the 'two powers' — the sacred authority of bishops and the royal power — that shaped relations between Church and state. He was a vigorous defender of the primacy of Rome.",
  ),
  pope(
    "pope-saint-leo-ix",
    "Pope Saint Leo IX",
    "1049",
    "1054",
    "Bruno of Egisheim-Dagsburg",
    "Pope Saint Leo IX was a leading reforming pope who travelled widely, holding synods against simony and clerical corruption. His pontificate saw the East-West Schism of 1054.",
  ),
  pope(
    "pope-adrian-iv",
    "Pope Adrian IV",
    "1154",
    "1159",
    "Nicholas Breakspear",
    "Pope Adrian IV remains the only Englishman ever to be elected pope. A former canon regular, he asserted papal authority during conflicts with the Roman commune and the Emperor Frederick Barbarossa.",
  ),
  pope(
    "pope-saint-celestine-v",
    "Pope Saint Celestine V",
    "1294",
    "1294",
    "Pietro Angelerio",
    "Pope Saint Celestine V was a holy hermit elected pope in old age who, after only five months, made the historic decision to resign the papacy, returning to solitude. He was canonized in 1313.",
  ),
  pope(
    "pope-clement-v",
    "Pope Clement V",
    "1305",
    "1314",
    "Raymond Bertrand de Got",
    "Pope Clement V moved the papal residence to Avignon, beginning the seventy-year 'Avignon Papacy,' and presided over the Council of Vienne and the suppression of the Knights Templar.",
  ),
  pope(
    "pope-gregory-xi",
    "Pope Gregory XI",
    "1370",
    "1378",
    "Pierre Roger de Beaufort",
    "Pope Gregory XI, urged by Saint Catherine of Siena, returned the papacy from Avignon to Rome in 1377, ending the Avignon Papacy. His death was followed by the Western Schism.",
  ),
  pope(
    "pope-martin-v",
    "Pope Martin V",
    "1417",
    "1431",
    "Oddone Colonna",
    "Pope Martin V was elected at the Council of Constance, ending the Western Schism that had divided the Church among rival claimants. He began the restoration of Rome and the papal administration.",
  ),
  pope(
    "pope-nicholas-v",
    "Pope Nicholas V",
    "1447",
    "1455",
    "Tommaso Parentucelli",
    "Pope Nicholas V, a humanist scholar, founded the Vatican Library and was a great patron of learning and the rebuilding of Rome at the dawn of the Renaissance.",
  ),
  pope(
    "pope-alexander-vi",
    "Pope Alexander VI",
    "1492",
    "1503",
    "Rodrigo Borgia",
    "Pope Alexander VI, of the Borgia family, reigned during the height of the Renaissance and drew the line of demarcation dividing the newly discovered lands between Spain and Portugal. His worldly conduct prompted later calls for reform.",
  ),
  pope(
    "pope-leo-x",
    "Pope Leo X",
    "1513",
    "1521",
    "Giovanni de' Medici",
    "Pope Leo X, a son of Lorenzo de' Medici, was a great patron of the arts whose pontificate saw the beginning of the Protestant Reformation; he excommunicated Martin Luther in 1521.",
  ),
  pope(
    "pope-clement-vii",
    "Pope Clement VII",
    "1523",
    "1534",
    "Giulio de' Medici",
    "Pope Clement VII reigned during the Sack of Rome (1527) and refused to annul the marriage of King Henry VIII of England, a refusal that led to the English schism.",
  ),
  pope(
    "pope-gregory-xv",
    "Pope Gregory XV",
    "1621",
    "1623",
    "Alessandro Ludovisi",
    "Pope Gregory XV founded the Congregation for the Propagation of the Faith (Propaganda Fide) to coordinate the Church's missions worldwide and canonized Saints Ignatius of Loyola, Francis Xavier, Teresa of Ávila, and Philip Neri.",
  ),
  pope(
    "pope-innocent-x",
    "Pope Innocent X",
    "1644",
    "1655",
    "Giovanni Battista Pamphilj",
    "Pope Innocent X condemned the errors of Jansenism and is remembered for the famous portrait of him by Diego Velázquez. He restored and adorned much of Baroque Rome.",
  ),
  pope(
    "pope-clement-xiv",
    "Pope Clement XIV",
    "1769",
    "1774",
    "Giovanni Vincenzo Antonio Ganganelli",
    "Pope Clement XIV, under heavy pressure from the Catholic monarchies, issued the brief Dominus ac Redemptor in 1773 suppressing the Society of Jesus; it would be restored in 1814.",
  ),
  pope(
    "pope-leo-xii",
    "Pope Leo XII",
    "1823",
    "1829",
    "Annibale della Genga",
    "Pope Leo XII proclaimed a Holy Year in 1825 and worked to restore Catholic life in Europe after the upheavals of the Napoleonic era.",
  ),
  pope(
    "pope-pius-viii",
    "Pope Pius VIII",
    "1829",
    "1830",
    "Francesco Saverio Castiglioni",
    "Pope Pius VIII reigned briefly, addressing in his encyclical Traditi Humilitati the defense of the faith, Christian marriage, and the formation of the clergy.",
  ),
  pope(
    "pope-saint-anacletus",
    "Pope Saint Anacletus",
    "c. 79",
    "c. 92",
    "Anacletus (Cletus)",
    "An early successor of Saint Peter and one of the first Bishops of Rome, named in the Roman Canon of the Mass and venerated as a martyr of the apostolic age.",
  ),
  pope(
    "pope-saint-evaristus",
    "Pope Saint Evaristus",
    "c. 99",
    "c. 107",
    "Evaristus",
    "An early Bishop of Rome of the apostolic age, traditionally credited with organizing the titular churches of Rome; he is venerated as a martyr.",
  ),
  pope(
    "pope-saint-telesphorus",
    "Pope Saint Telesphorus",
    "c. 125",
    "c. 136",
    "Telesphorus",
    "An early pope of Greek origin and a martyr, remembered in tradition for liturgical observances connected with the celebration of Easter and the Nativity.",
  ),
  pope(
    "pope-saint-pius-i",
    "Pope Saint Pius I",
    "c. 140",
    "c. 155",
    "Pius",
    "An early Bishop of Rome who, according to tradition, opposed the Gnostic and Marcionite heresies then troubling the Roman church; venerated as a martyr.",
  ),
  pope(
    "pope-saint-soter",
    "Pope Saint Soter",
    "c. 166",
    "c. 174",
    "Soter",
    "An early pope renowned for his charity, who sent generous aid to other churches; remembered as a defender of the faith and a martyr.",
  ),
  pope(
    "pope-saint-victor-i",
    "Pope Saint Victor I",
    "c. 189",
    "c. 199",
    "Victor",
    "The first Latin-speaking Bishop of Rome, who acted vigorously to settle the date of Easter and to defend the divinity of Christ against early heresies.",
  ),
  pope(
    "pope-saint-pontian",
    "Pope Saint Pontian",
    "230",
    "235",
    "Pontian",
    "Pope during the persecution under Maximinus Thrax; exiled to the mines of Sardinia, he abdicated so the Church could elect a successor and died a martyr.",
  ),
  pope(
    "pope-saint-stephen-i",
    "Pope Saint Stephen I",
    "254",
    "257",
    "Stephen",
    "Pope who upheld the validity of baptism administered by heretics, insisting that the sacrament's power comes from Christ and not from the minister.",
  ),
  pope(
    "pope-saint-dionysius",
    "Pope Saint Dionysius",
    "259",
    "268",
    "Dionysius",
    "Pope who reorganized and consoled the Roman church after fierce persecution, ransomed captives, and clarified Trinitarian doctrine against errors of his day.",
  ),
  pope(
    "pope-saint-marcellinus",
    "Pope Saint Marcellinus",
    "296",
    "304",
    "Marcellinus",
    "Pope during the Great Persecution under Diocletian, a period of intense suffering for the Roman church; he is venerated among the early martyr-popes.",
  ),
  pope(
    "pope-saint-miltiades",
    "Pope Saint Miltiades",
    "311",
    "314",
    "Miltiades",
    "Pope who saw the peace of the Church under Constantine after the Edict of Milan and received the Lateran Palace, which became the papal residence.",
  ),
  pope(
    "pope-saint-julius-i",
    "Pope Saint Julius I",
    "337",
    "352",
    "Julius",
    "Pope who staunchly defended Saint Athanasius and the Nicene faith against the Arians and asserted the right of appeal to the See of Rome.",
  ),
  pope(
    "pope-liberius",
    "Pope Liberius",
    "352",
    "366",
    "Liberius",
    "Pope through the turbulent Arian controversy, who endured exile under imperial pressure; he is associated with the founding of the Basilica of Saint Mary Major.",
  ),
  pope(
    "pope-saint-siricius",
    "Pope Saint Siricius",
    "384",
    "399",
    "Siricius",
    "Pope whose letters are among the earliest surviving papal decretals, giving authoritative rulings on discipline, clerical celibacy, and the ordering of the Church.",
  ),
  pope(
    "pope-saint-innocent-i",
    "Pope Saint Innocent I",
    "401",
    "417",
    "Innocent",
    "Pope who strengthened the authority of the Roman See and confirmed the condemnation of Pelagianism, prompting Saint Augustine's famous 'Roma locuta est.'",
  ),
  pope(
    "pope-saint-celestine-i",
    "Pope Saint Celestine I",
    "422",
    "432",
    "Celestine",
    "Pope who sent legates to the Council of Ephesus that proclaimed Mary as Theotokos, and who sent Palladius and supported missions to Ireland.",
  ),
  pope(
    "pope-saint-hilarius",
    "Pope Saint Hilarius",
    "461",
    "468",
    "Hilarius",
    "Pope who consolidated ecclesiastical discipline in Gaul and Spain and adorned the churches of Rome; a defender of the decrees of the Council of Chalcedon.",
  ),
  pope(
    "pope-saint-hormisdas",
    "Pope Saint Hormisdas",
    "514",
    "523",
    "Hormisdas",
    "Pope who healed the Acacian Schism between Rome and Constantinople through his celebrated Formula of Hormisdas affirming the faith of the Roman See.",
  ),
  pope(
    "pope-vigilius",
    "Pope Vigilius",
    "537",
    "555",
    "Vigilius",
    "Pope during the Three Chapters controversy and the Second Council of Constantinople, whose pontificate was marked by pressure from the emperor Justinian.",
  ),
  pope(
    "pope-saint-gregory-ii",
    "Pope Saint Gregory II",
    "715",
    "731",
    "Gregory",
    "Pope who resisted Byzantine iconoclasm and commissioned Saint Boniface to evangelize the Germanic peoples, advancing the conversion of central Europe.",
  ),
  pope(
    "pope-saint-zachary",
    "Pope Saint Zachary",
    "741",
    "752",
    "Zachary",
    "The last pope of Greek origin, a wise diplomat and friend of Saint Boniface who guided relations with the Franks at the dawn of the Carolingian age.",
  ),
  pope(
    "pope-adrian-i",
    "Pope Adrian I",
    "772",
    "795",
    "Hadrian",
    "Pope and close ally of Charlemagne whose long reign saw the Second Council of Nicaea uphold the veneration of sacred images against iconoclasm.",
  ),
  pope(
    "pope-saint-leo-iv",
    "Pope Saint Leo IV",
    "847",
    "855",
    "Leo",
    "Pope who fortified Rome against Saracen raids by building the Leonine Wall around the Vatican, encircling Saint Peter's Basilica.",
  ),
  pope(
    "pope-sylvester-ii",
    "Pope Sylvester II",
    "999",
    "1003",
    "Gerbert of Aurillac",
    "The first French pope, a celebrated scholar, teacher, and mathematician who reintroduced the abacus and the armillary sphere to the Latin West.",
  ),
  pope(
    "pope-paschal-ii",
    "Pope Paschal II",
    "1099",
    "1118",
    "Raniero Ranieri",
    "Pope through much of the Investiture Controversy, a Benedictine reformer who contended with emperors over the right to appoint bishops.",
  ),
  pope(
    "pope-callixtus-ii",
    "Pope Callixtus II",
    "1119",
    "1124",
    "Guy of Burgundy",
    "Pope who ended the Investiture Controversy with the Concordat of Worms and convened the First Lateran Council, the first general council in the West.",
  ),
  pope(
    "pope-eugene-iii",
    "Pope Blessed Eugene III",
    "1145",
    "1153",
    "Bernardo Pignatelli",
    "The first Cistercian pope, a disciple of Saint Bernard of Clairvaux, who promoted reform and the Second Crusade; he is honored as Blessed.",
  ),
  pope(
    "pope-gregory-ix",
    "Pope Gregory IX",
    "1227",
    "1241",
    "Ugolino di Conti",
    "Pope who canonized Saint Francis of Assisi and Saint Dominic, was a friend of the friars, and promulgated an authoritative collection of canon law.",
  ),
  pope(
    "pope-innocent-iv",
    "Pope Innocent IV",
    "1243",
    "1254",
    "Sinibaldo Fieschi",
    "Pope and canon lawyer who convened the First Council of Lyon and sent the first papal missions to the Mongol court in the Far East.",
  ),
  pope(
    "pope-gregory-x",
    "Pope Blessed Gregory X",
    "1271",
    "1276",
    "Tedaldo Visconti",
    "Pope who convened the Second Council of Lyon, briefly reuniting the Greek and Latin Churches, and established the rules of the papal conclave; honored as Blessed.",
  ),
  pope(
    "pope-eugene-iv",
    "Pope Eugene IV",
    "1431",
    "1447",
    "Gabriele Condulmer",
    "Pope of the Council of Florence, which achieved a short-lived reunion with the Eastern churches and proclaimed the truths of the faith on the Trinity and the sacraments.",
  ),
  pope(
    "pope-pius-ii",
    "Pope Pius II",
    "1458",
    "1464",
    "Enea Silvio Piccolomini",
    "A humanist scholar before his election, Pope Pius II labored to organize a crusade to defend Christendom and left celebrated memoirs of his age.",
  ),
  pope(
    "pope-pius-iv",
    "Pope Pius IV",
    "1559",
    "1565",
    "Giovanni Angelo Medici",
    "Pope who brought the Council of Trent to its successful conclusion and promulgated its decrees, setting in motion the Catholic Reformation.",
  ),
  pope(
    "pope-paul-v",
    "Pope Paul V",
    "1605",
    "1621",
    "Camillo Borghese",
    "Pope who completed the nave and facade of Saint Peter's Basilica and was a noted patron of the arts and defender of the rights of the Church.",
  ),
  pope(
    "pope-blessed-innocent-xi",
    "Pope Blessed Innocent XI",
    "1676",
    "1689",
    "Benedetto Odescalchi",
    "A reforming pope of great personal austerity who helped rally the defense of Europe at the Siege of Vienna in 1683; he was beatified in 1956.",
  ),
  pope(
    "pope-clement-xi",
    "Pope Clement XI",
    "1700",
    "1721",
    "Giovanni Francesco Albani",
    "Pope who confronted Jansenism with the bull Unigenitus and extended the universal celebration of several feasts in the Church's calendar.",
  ),
  pope(
    "pope-clement-xiii",
    "Pope Clement XIII",
    "1758",
    "1769",
    "Carlo della Torre Rezzonico",
    "Pope who staunchly defended the Society of Jesus against the pressure of the Catholic monarchs and promoted devotion to the Sacred Heart of Jesus.",
  ),
];
