import type { CuratedEntry } from "./index";
import { PRAYER_TRANSLATIONS } from "./prayer-translations";

const VATICAN_CCC_PRAYERS = "https://www.vatican.va/archive/ENG0015/__P9.HTM";
const USCCB_PRAYERS = "https://www.usccb.org/prayer-and-worship/prayers-and-devotions/prayers";

const RAW_PRAYERS: CuratedEntry[] = [
  {
    contentType: "PRAYER",
    slug: "our-father",
    authorityLevel: "VATICAN",
    citations: [VATICAN_CCC_PRAYERS, USCCB_PRAYERS],
    payload: {
      slug: "our-father",
      title: "Our Father",
      body: "Our Father, who art in heaven,\nhallowed be thy name;\nthy kingdom come;\nthy will be done\non earth as it is in heaven.\nGive us this day our daily bread,\nand forgive us our trespasses,\nas we forgive those who trespass against us;\nand lead us not into temptation,\nbut deliver us from evil.\nAmen.",
      officialPrayer:
        "Our Father, who art in heaven, hallowed be thy name; thy kingdom come; thy will be done on earth as it is in heaven. Give us this day our daily bread, and forgive us our trespasses, as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil. Amen.",
      prayerType: "general",
      category: "dominical",
      language: "en",
      summary:
        "The prayer Christ himself taught the disciples (Matthew 6:9-13, Luke 11:2-4). The foundation of all Christian prayer.",
      occasions: ["daily", "rosary", "mass", "morning", "evening"],
      relatedSaints: [],
      citations: [VATICAN_CCC_PRAYERS, USCCB_PRAYERS],
    },
  },
  {
    contentType: "PRAYER",
    slug: "hail-mary",
    authorityLevel: "VATICAN",
    citations: [VATICAN_CCC_PRAYERS, USCCB_PRAYERS],
    payload: {
      slug: "hail-mary",
      title: "Hail Mary",
      body: "Hail Mary, full of grace,\nthe Lord is with thee;\nblessed art thou among women,\nand blessed is the fruit of thy womb, Jesus.\nHoly Mary, Mother of God,\npray for us sinners,\nnow and at the hour of our death.\nAmen.",
      officialPrayer:
        "Hail Mary, full of grace, the Lord is with thee; blessed art thou among women, and blessed is the fruit of thy womb, Jesus. Holy Mary, Mother of God, pray for us sinners, now and at the hour of our death. Amen.",
      prayerType: "marian",
      category: "marian",
      language: "en",
      summary:
        "The angelic salutation, combining the words of the Angel Gabriel and Elizabeth (Luke 1:28, 1:42) with the Church's petition.",
      occasions: ["rosary", "angelus", "daily"],
      relatedSaints: [],
      citations: [VATICAN_CCC_PRAYERS, USCCB_PRAYERS],
    },
  },
  {
    contentType: "PRAYER",
    slug: "glory-be",
    authorityLevel: "VATICAN",
    citations: [VATICAN_CCC_PRAYERS, USCCB_PRAYERS],
    payload: {
      slug: "glory-be",
      title: "Glory Be",
      body: "Glory be to the Father, and to the Son, and to the Holy Spirit,\nas it was in the beginning, is now, and ever shall be,\nworld without end. Amen.",
      officialPrayer:
        "Glory be to the Father, and to the Son, and to the Holy Spirit, as it was in the beginning, is now, and ever shall be, world without end. Amen.",
      prayerType: "general",
      category: "doxology",
      language: "en",
      summary: "The lesser doxology — praise of the Holy Trinity used throughout Catholic prayer.",
      occasions: ["rosary", "daily"],
      relatedSaints: [],
      citations: [VATICAN_CCC_PRAYERS, USCCB_PRAYERS],
    },
  },
  {
    contentType: "PRAYER",
    slug: "apostles-creed",
    authorityLevel: "CATECHISM",
    citations: [
      "https://www.vatican.va/archive/ENG0015/__P16.HTM",
      "https://www.usccb.org/prayers/apostles-creed",
    ],
    payload: {
      slug: "apostles-creed",
      title: "Apostles' Creed",
      body: "I believe in God, the Father almighty,\nCreator of heaven and earth,\nand in Jesus Christ, his only Son, our Lord,\nwho was conceived by the Holy Spirit,\nborn of the Virgin Mary,\nsuffered under Pontius Pilate,\nwas crucified, died and was buried;\nhe descended into hell;\non the third day he rose again from the dead;\nhe ascended into heaven,\nand is seated at the right hand of God the Father almighty;\nfrom there he will come to judge the living and the dead.\nI believe in the Holy Spirit,\nthe holy catholic Church,\nthe communion of saints,\nthe forgiveness of sins,\nthe resurrection of the body,\nand life everlasting.\nAmen.",
      prayerType: "general",
      category: "creed",
      language: "en",
      summary:
        "The ancient baptismal creed of the Roman Church, summarizing the apostolic faith in twelve articles.",
      occasions: ["rosary", "baptism", "vigils"],
      relatedSaints: [],
      citations: [
        "https://www.vatican.va/archive/ENG0015/__P16.HTM",
        "https://www.usccb.org/prayers/apostles-creed",
      ],
    },
  },
  {
    contentType: "PRAYER",
    slug: "nicene-creed",
    authorityLevel: "CATECHISM",
    citations: ["https://www.vatican.va/archive/ENG0015/__P17.HTM"],
    payload: {
      slug: "nicene-creed",
      title: "Nicene Creed",
      body: "I believe in one God,\nthe Father almighty,\nmaker of heaven and earth,\nof all things visible and invisible.\nI believe in one Lord Jesus Christ,\nthe Only Begotten Son of God,\nborn of the Father before all ages.\nGod from God, Light from Light,\ntrue God from true God,\nbegotten, not made, consubstantial with the Father;\nthrough him all things were made.\nFor us men and for our salvation\nhe came down from heaven,\nand by the Holy Spirit was incarnate of the Virgin Mary,\nand became man.\nFor our sake he was crucified under Pontius Pilate,\nhe suffered death and was buried,\nand rose again on the third day in accordance with the Scriptures.\nHe ascended into heaven\nand is seated at the right hand of the Father.\nHe will come again in glory to judge the living and the dead\nand his kingdom will have no end.\nI believe in the Holy Spirit, the Lord, the giver of life,\nwho proceeds from the Father and the Son,\nwho with the Father and the Son is adored and glorified,\nwho has spoken through the prophets.\nI believe in one, holy, catholic and apostolic Church.\nI confess one Baptism for the forgiveness of sins\nand I look forward to the resurrection of the dead\nand the life of the world to come. Amen.",
      prayerType: "general",
      category: "creed",
      language: "en",
      summary:
        "The Niceno-Constantinopolitan Creed (325/381) — proclaimed every Sunday at Mass throughout the Latin Church.",
      occasions: ["mass", "solemnities"],
      relatedSaints: [],
      citations: ["https://www.vatican.va/archive/ENG0015/__P17.HTM"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "act-of-contrition",
    authorityLevel: "USCCB",
    citations: ["https://www.usccb.org/prayers/act-contrition"],
    payload: {
      slug: "act-of-contrition",
      title: "Act of Contrition",
      body: "O my God, I am heartily sorry for having offended Thee,\nand I detest all my sins because of Thy just punishments,\nbut most of all because they offend Thee, my God,\nwho art all-good and deserving of all my love.\nI firmly resolve, with the help of Thy grace,\nto sin no more and to avoid the near occasion of sin.\nAmen.",
      prayerType: "act",
      category: "penitential",
      language: "en",
      summary: "The traditional act of contrition prayed in the Sacrament of Reconciliation.",
      occasions: ["confession", "examen", "evening"],
      relatedSaints: [],
      citations: ["https://www.usccb.org/prayers/act-contrition"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "act-of-faith",
    authorityLevel: "USCCB",
    citations: ["https://www.usccb.org/prayers/act-faith"],
    payload: {
      slug: "act-of-faith",
      title: "Act of Faith",
      body: "O my God, I firmly believe that you are one God in three Divine Persons,\nFather, Son, and Holy Spirit.\nI believe that your Divine Son became man\nand died for our sins, and that he will come\nto judge the living and the dead.\nI believe these and all the truths which the Holy Catholic Church teaches,\nbecause you have revealed them, who are eternal truth and wisdom,\nwho can neither deceive nor be deceived.\nIn this faith I intend to live and die. Amen.",
      prayerType: "act",
      category: "theological-virtue",
      language: "en",
      summary: "An act of the theological virtue of faith.",
      occasions: ["morning", "daily"],
      relatedSaints: [],
      citations: ["https://www.usccb.org/prayers/act-faith"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "act-of-hope",
    authorityLevel: "USCCB",
    citations: ["https://www.usccb.org/prayers/act-hope"],
    payload: {
      slug: "act-of-hope",
      title: "Act of Hope",
      body: "O Lord God, I hope by your grace for the pardon of all my sins\nand after life here to gain eternal happiness\nbecause you have promised it,\nwho are infinitely powerful, faithful, kind, and merciful.\nIn this hope I intend to live and die. Amen.",
      prayerType: "act",
      category: "theological-virtue",
      language: "en",
      summary: "An act of the theological virtue of hope.",
      occasions: ["morning", "daily"],
      relatedSaints: [],
      citations: ["https://www.usccb.org/prayers/act-hope"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "act-of-love",
    authorityLevel: "USCCB",
    citations: ["https://www.usccb.org/prayers/act-love"],
    payload: {
      slug: "act-of-love",
      title: "Act of Love",
      body: "O Lord God, I love you above all things\nand I love my neighbor for your sake\nbecause you are the highest, infinite and perfect good,\nworthy of all my love.\nIn this love I intend to live and die. Amen.",
      prayerType: "act",
      category: "theological-virtue",
      language: "en",
      summary: "An act of the theological virtue of charity (love).",
      occasions: ["morning", "daily"],
      relatedSaints: [],
      citations: ["https://www.usccb.org/prayers/act-love"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "memorare",
    authorityLevel: "VATICAN",
    citations: [USCCB_PRAYERS, "https://www.vatican.va/"],
    payload: {
      slug: "memorare",
      title: "Memorare",
      body: "Remember, O most gracious Virgin Mary,\nthat never was it known that anyone who fled to thy protection,\nimplored thy help, or sought thy intercession was left unaided.\nInspired by this confidence, I fly unto thee,\nO Virgin of virgins, my Mother;\nto thee do I come, before thee I stand, sinful and sorrowful.\nO Mother of the Word Incarnate, despise not my petitions,\nbut in thy mercy hear and answer me. Amen.",
      prayerType: "marian",
      category: "marian-intercession",
      language: "en",
      summary:
        "A confident appeal to the intercession of the Blessed Virgin Mary, popularized by St. Bernard of Clairvaux.",
      occasions: ["daily", "marian-devotion"],
      relatedSaints: ["saint-bernard-of-clairvaux"],
      citations: [USCCB_PRAYERS, "https://www.vatican.va/"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "angelus",
    authorityLevel: "VATICAN",
    citations: [USCCB_PRAYERS],
    payload: {
      slug: "angelus",
      title: "The Angelus",
      body: "V. The Angel of the Lord declared unto Mary.\nR. And she conceived of the Holy Spirit.\n(Hail Mary)\nV. Behold the handmaid of the Lord.\nR. Be it done unto me according to thy word.\n(Hail Mary)\nV. And the Word was made flesh.\nR. And dwelt among us.\n(Hail Mary)\nV. Pray for us, O Holy Mother of God.\nR. That we may be made worthy of the promises of Christ.\nLet us pray:\nPour forth, we beseech Thee, O Lord, Thy grace into our hearts;\nthat we, to whom the Incarnation of Christ Thy Son was made known\nby the message of an Angel, may by His Passion and Cross\nbe brought to the glory of His Resurrection,\nthrough the same Christ Our Lord. Amen.",
      prayerType: "marian",
      category: "marian",
      language: "en",
      summary:
        "A traditional Marian prayer commemorating the Incarnation, prayed at 6 a.m., noon, and 6 p.m.",
      occasions: ["morning", "midday", "evening"],
      relatedSaints: [],
      citations: [USCCB_PRAYERS],
    },
  },
  {
    contentType: "PRAYER",
    slug: "regina-caeli",
    authorityLevel: "VATICAN",
    citations: [USCCB_PRAYERS],
    payload: {
      slug: "regina-caeli",
      title: "Regina Caeli",
      body: "Queen of Heaven, rejoice, alleluia.\nFor He whom you did merit to bear, alleluia,\nHas risen as He said, alleluia.\nPray for us to God, alleluia.\nV. Rejoice and be glad, O Virgin Mary, alleluia.\nR. For the Lord is truly risen, alleluia.\nLet us pray:\nO God, who through the resurrection of your Son, our Lord Jesus Christ,\ndid vouchsafe to give joy to the world;\ngrant, we beseech you, that through his Mother, the Virgin Mary,\nwe may obtain the joys of everlasting life,\nthrough the same Christ our Lord. Amen.",
      prayerType: "marian",
      category: "marian-seasonal",
      language: "en",
      summary:
        "The Easter-season Marian anthem replacing the Angelus from Easter Sunday through Pentecost.",
      occasions: ["easter-season"],
      relatedSaints: [],
      citations: [USCCB_PRAYERS],
    },
  },
  {
    contentType: "PRAYER",
    slug: "salve-regina",
    authorityLevel: "VATICAN",
    citations: [USCCB_PRAYERS],
    payload: {
      slug: "salve-regina",
      title: "Hail Holy Queen (Salve Regina)",
      body: "Hail, holy Queen, Mother of Mercy,\nour life, our sweetness and our hope.\nTo thee do we cry, poor banished children of Eve;\nto thee do we send up our sighs,\nmourning and weeping in this valley of tears.\nTurn then, most gracious Advocate,\nthine eyes of mercy toward us;\nand after this our exile,\nshow unto us the blessed fruit of thy womb, Jesus.\nO clement, O loving, O sweet Virgin Mary!\nV. Pray for us, O holy Mother of God.\nR. That we may be made worthy of the promises of Christ.",
      prayerType: "marian",
      category: "marian-antiphon",
      language: "en",
      summary:
        "A traditional Marian anthem prayed at the close of Compline and the rosary, attributed to Hermann of Reichenau.",
      occasions: ["rosary", "compline"],
      relatedSaints: [],
      citations: [USCCB_PRAYERS],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-michael",
    authorityLevel: "VATICAN",
    citations: ["https://www.vatican.va/", USCCB_PRAYERS],
    payload: {
      slug: "prayer-to-saint-michael",
      title: "Prayer to Saint Michael the Archangel",
      body: "Saint Michael the Archangel, defend us in battle.\nBe our defense against the wickedness and snares of the Devil.\nMay God rebuke him, we humbly pray;\nand do thou, O Prince of the heavenly host,\nby the power of God, cast into hell Satan and all the evil spirits\nwho prowl about the world seeking the ruin of souls. Amen.",
      prayerType: "intercession",
      category: "angelic",
      language: "en",
      summary:
        "Composed by Pope Leo XIII in 1886. Prayed after Low Mass in the Latin liturgy until 1964 and widely restored today.",
      occasions: ["daily", "spiritual-warfare"],
      relatedSaints: [],
      citations: ["https://www.vatican.va/", USCCB_PRAYERS],
    },
  },
  {
    contentType: "PRAYER",
    slug: "morning-offering",
    authorityLevel: "USCCB",
    citations: ["https://www.usccb.org/prayers/morning-offering"],
    payload: {
      slug: "morning-offering",
      title: "Morning Offering",
      body: "O Jesus, through the Immaculate Heart of Mary,\nI offer You my prayers, works, joys, and sufferings of this day\nin union with the Holy Sacrifice of the Mass throughout the world.\nI offer them for all the intentions of Your Sacred Heart:\nthe salvation of souls, reparation for sin, the reunion of all Christians.\nI offer them for the intentions of our bishops\nand of all members of the Apostleship of Prayer,\nand in particular for those recommended by our Holy Father this month.\nAmen.",
      prayerType: "morning",
      category: "morning",
      language: "en",
      summary:
        "The traditional Apostleship of Prayer morning offering, dedicating the day's actions to the Sacred Heart of Jesus through Mary.",
      occasions: ["morning"],
      relatedSaints: [],
      citations: ["https://www.usccb.org/prayers/morning-offering"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "grace-before-meals",
    authorityLevel: "USCCB",
    citations: ["https://www.usccb.org/prayers/grace-before-meals"],
    payload: {
      slug: "grace-before-meals",
      title: "Grace Before Meals",
      body: "Bless us, O Lord, and these Thy gifts,\nwhich we are about to receive from Thy bounty,\nthrough Christ our Lord. Amen.",
      prayerType: "meal",
      category: "meal",
      language: "en",
      summary: "The traditional Catholic blessing prayed before meals.",
      occasions: ["meal"],
      relatedSaints: [],
      citations: ["https://www.usccb.org/prayers/grace-before-meals"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "grace-after-meals",
    authorityLevel: "USCCB",
    citations: ["https://www.usccb.org/prayers/grace-after-meals"],
    payload: {
      slug: "grace-after-meals",
      title: "Grace After Meals",
      body: "We give Thee thanks for all Thy benefits,\nO Almighty God, who livest and reignest world without end.\nAmen.\nMay the souls of the faithful departed,\nthrough the mercy of God, rest in peace. Amen.",
      prayerType: "meal",
      category: "meal",
      language: "en",
      summary: "The traditional Catholic thanksgiving after meals.",
      occasions: ["meal"],
      relatedSaints: [],
      citations: ["https://www.usccb.org/prayers/grace-after-meals"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "anima-christi",
    authorityLevel: "VATICAN",
    citations: ["https://www.vatican.va/"],
    payload: {
      slug: "anima-christi",
      title: "Anima Christi (Soul of Christ)",
      body: "Soul of Christ, sanctify me.\nBody of Christ, save me.\nBlood of Christ, inebriate me.\nWater from the side of Christ, wash me.\nPassion of Christ, strengthen me.\nO good Jesus, hear me.\nWithin Thy wounds hide me.\nSuffer me not to be separated from Thee.\nFrom the malicious enemy defend me.\nIn the hour of my death call me.\nAnd bid me come unto Thee,\nThat with Thy saints I may praise Thee\nFor ever and ever. Amen.",
      prayerType: "general",
      category: "eucharistic",
      language: "en",
      summary:
        "A 14th-century Eucharistic prayer beloved by St. Ignatius of Loyola, prayed in thanksgiving after Holy Communion.",
      occasions: ["after-communion"],
      relatedSaints: ["saint-ignatius-of-loyola"],
      citations: ["https://www.vatican.va/"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "magnificat",
    authorityLevel: "VATICAN",
    citations: ["https://www.vatican.va/"],
    payload: {
      slug: "magnificat",
      title: "Magnificat",
      body: "My soul proclaims the greatness of the Lord,\nmy spirit rejoices in God my Savior\nfor he has looked with favor on his lowly servant.\nFrom this day all generations will call me blessed:\nthe Almighty has done great things for me,\nand holy is his Name.\nHe has mercy on those who fear him\nin every generation.\nHe has shown the strength of his arm,\nhe has scattered the proud in their conceit.\nHe has cast down the mighty from their thrones,\nand has lifted up the lowly.\nHe has filled the hungry with good things,\nand the rich he has sent away empty.\nHe has come to the help of his servant Israel\nfor he has remembered his promise of mercy,\nthe promise he made to our fathers,\nto Abraham and his children for ever.",
      prayerType: "marian",
      category: "canticle",
      language: "en",
      summary:
        "Mary's song of praise (Luke 1:46-55), the canticle of Evening Prayer in the Divine Office.",
      occasions: ["vespers", "marian"],
      relatedSaints: [],
      citations: ["https://www.vatican.va/"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "confiteor",
    authorityLevel: "LITURGICAL_BOOK",
    citations: ["https://www.icel.org/", USCCB_PRAYERS],
    payload: {
      slug: "confiteor",
      title: "Confiteor",
      body: "I confess to almighty God and to you, my brothers and sisters,\nthat I have greatly sinned in my thoughts and in my words,\nin what I have done and in what I have failed to do,\nthrough my fault, through my fault, through my most grievous fault;\ntherefore I ask blessed Mary ever-Virgin,\nall the Angels and Saints,\nand you, my brothers and sisters,\nto pray for me to the Lord our God.",
      prayerType: "general",
      category: "penitential",
      language: "en",
      summary: "The penitential act prayed in the Penitential Rite of the Holy Mass.",
      occasions: ["mass", "examen"],
      relatedSaints: [],
      citations: ["https://www.icel.org/", USCCB_PRAYERS],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-of-saint-francis",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.usccb.org/"],
    payload: {
      slug: "prayer-of-saint-francis",
      title: "Prayer of Saint Francis",
      body: "Lord, make me an instrument of your peace:\nwhere there is hatred, let me sow love;\nwhere there is injury, pardon;\nwhere there is doubt, faith;\nwhere there is despair, hope;\nwhere there is darkness, light;\nwhere there is sadness, joy.\nO divine Master, grant that I may not so much seek\nto be consoled as to console,\nto be understood as to understand,\nto be loved as to love.\nFor it is in giving that we receive,\nit is in pardoning that we are pardoned,\nand it is in dying that we are born to eternal life. Amen.",
      prayerType: "general",
      category: "peace",
      language: "en",
      summary:
        "Popularly attributed to St. Francis of Assisi, though the prayer appears to date from the early twentieth century. Loved across Christian traditions.",
      occasions: ["daily"],
      relatedSaints: ["saint-francis-of-assisi"],
      citations: ["https://www.usccb.org/"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "te-deum",
    authorityLevel: "LITURGICAL_BOOK",
    citations: ["https://www.vatican.va/"],
    payload: {
      slug: "te-deum",
      title: "Te Deum",
      body: "We praise you, O God: we acclaim you as the Lord.\nEverlasting Father, all the world bows down before you.\nAll the angels sing your praise,\nthe hosts of heaven and all the angelic powers,\nall the cherubim and seraphim call out to you in unending song:\nHoly, Holy, Holy, is the Lord God of angel hosts!\nThe heavens and the earth are filled with your majesty and glory.\nThe glorious band of apostles,\nthe noble company of prophets,\nthe white-robed army who shed their blood for Christ,\nall sing your praise.\nAnd to the ends of the earth\nyour holy Church proclaims her faith in you:\nFather, whose majesty is boundless,\nyour true and only Son, who is to be adored,\nthe Holy Spirit sent to be our Advocate.",
      prayerType: "general",
      category: "hymn",
      language: "en",
      summary:
        "An ancient Christian hymn of praise traditionally attributed to St. Ambrose and St. Augustine. Sung at solemn occasions of thanksgiving.",
      occasions: ["thanksgiving", "solemnity"],
      relatedSaints: [],
      citations: ["https://www.vatican.va/"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "veni-creator-spiritus",
    authorityLevel: "LITURGICAL_BOOK",
    citations: ["https://www.vatican.va/"],
    payload: {
      slug: "veni-creator-spiritus",
      title: "Veni Creator Spiritus (Come, Holy Spirit)",
      body: "Come, Holy Spirit, Creator blest,\nand in our hearts take up Thy rest;\ncome with Thy grace and heavenly aid\nto fill the hearts which Thou hast made.\nO Comforter, to Thee we cry,\nThou heavenly gift of God most high,\nThou Fount of life and Fire of love,\nand sweet anointing from above.\nThou in Thy sevenfold gifts art known;\nThou, finger of God's hand we own;\nThou, promise of the Father, Thou\nwho dost the tongue with power endow.\nKindle our senses from above,\nand make our hearts o'erflow with love;\nwith patience firm and virtue high\nthe weakness of our flesh supply.\nFar from us drive the foe we dread,\nand grant us Thy peace instead;\nso shall we not, with Thee for guide,\nturn from the path of life aside.\nOh, may Thy grace on us bestow\nthe Father and the Son to know,\nand Thee through endless times confessed,\nof both the eternal Spirit blest.\nAll glory while the ages run\nbe to the Father and the Son\nwho rose from death; the same to Thee,\nO Holy Ghost, eternally. Amen.",
      prayerType: "general",
      category: "pentecost",
      language: "en",
      summary:
        "A 9th-century hymn invoking the Holy Spirit, sung at Pentecost, at ordinations, and at the opening of councils and synods.",
      occasions: ["pentecost", "ordination"],
      relatedSaints: [],
      citations: ["https://www.vatican.va/"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "divine-praises",
    authorityLevel: "LITURGICAL_BOOK",
    citations: ["https://www.vatican.va/"],
    payload: {
      slug: "divine-praises",
      title: "The Divine Praises",
      body: "Blessed be God.\nBlessed be His Holy Name.\nBlessed be Jesus Christ, true God and true Man.\nBlessed be the Name of Jesus.\nBlessed be His Most Sacred Heart.\nBlessed be His Most Precious Blood.\nBlessed be Jesus in the Most Holy Sacrament of the Altar.\nBlessed be the Holy Spirit, the Paraclete.\nBlessed be the great Mother of God, Mary most Holy.\nBlessed be her Holy and Immaculate Conception.\nBlessed be her Glorious Assumption.\nBlessed be the Name of Mary, Virgin and Mother.\nBlessed be Saint Joseph, her most chaste Spouse.\nBlessed be God in His angels and in His saints.",
      prayerType: "general",
      category: "eucharistic",
      language: "en",
      summary:
        "Acclamations of praise traditionally prayed at the conclusion of Eucharistic Benediction.",
      occasions: ["benediction", "adoration"],
      relatedSaints: [],
      citations: ["https://www.vatican.va/"],
    },
  },
];

/**
 * Merge the curated liturgical (Latin/Greek) translations into each prayer's
 * payload so the worker publishes them and the language toggle renders them.
 * Prayers without a curated translation are left as-is (a content-custody check
 * flags them for a curator).
 */
export const prayerKnowledge: CuratedEntry[] = RAW_PRAYERS.map((entry) => {
  const t = PRAYER_TRANSLATIONS[entry.slug];
  if (!t) return entry;
  return {
    ...entry,
    payload: {
      ...entry.payload,
      ...(t.latin ? { latin: t.latin } : {}),
      ...(t.greek ? { greek: t.greek } : {}),
    },
  };
});
