import type { CuratedEntry } from "./index";

const VATICAN = "https://www.vatican.va/";
const NEWADVENT = "https://www.newadvent.org/cathen/";

function saint(
  slug: string,
  canonicalName: string,
  feastDay: string,
  saintType:
    | "martyr"
    | "doctor_of_the_church"
    | "virgin"
    | "confessor"
    | "religious"
    | "lay"
    | "bishop"
    | "pope"
    | "apostle"
    | "evangelist"
    | "founder"
    | "missionary"
    | "other",
  canonizationStatus: "canonized" | "beatified" | "venerable" | "servant_of_god",
  patronages: string[],
  biography: string,
): CuratedEntry {
  const [mm, dd] = feastDay.split("-").map((s) => parseInt(s, 10));
  return {
    contentType: "SAINT",
    slug,
    authorityLevel: "VATICAN",
    citations: [VATICAN, NEWADVENT],
    payload: {
      slug,
      canonicalName,
      feastDay,
      feastMonth: mm,
      feastDayOfMonth: dd,
      patronages,
      biography,
      saintType,
      canonizationStatus,
      relatedPrayers: [],
      relatedDevotions: [],
      citations: [VATICAN, NEWADVENT],
    },
  };
}

export const saintKnowledge: CuratedEntry[] = [
  saint(
    "saint-joseph",
    "Saint Joseph",
    "03-19",
    "confessor",
    "canonized",
    ["the universal Church", "workers", "fathers", "a happy death"],
    "Saint Joseph was the foster father of Jesus Christ and the chaste spouse of the Blessed Virgin Mary. A descendant of King David, he was a carpenter in Nazareth. The Gospels of Matthew and Luke record his obedience to the angel's messages and his protective care of the Holy Family. Pope Pius IX declared him patron of the universal Church in 1870. Pope Pius XII established the feast of St. Joseph the Worker on May 1 in 1955. Pope Francis added his name to all the Eucharistic Prayers of the Roman Missal in 2013.",
  ),
  saint(
    "saint-peter",
    "Saint Peter the Apostle",
    "06-29",
    "apostle",
    "canonized",
    ["the papacy", "fishermen", "Rome"],
    "Simon Peter was the brother of Andrew, a fisherman of Bethsaida. Jesus called him to be the first of the Twelve Apostles and renamed him Peter (Cephas, 'rock'), telling him: 'Upon this rock I will build my Church' (Matthew 16:18). After Pentecost he led the apostolic community, was the first bishop of Rome, and was martyred there during the persecution of Nero around AD 64. His tomb lies beneath the high altar of St. Peter's Basilica.",
  ),
  saint(
    "saint-paul",
    "Saint Paul the Apostle",
    "06-29",
    "apostle",
    "canonized",
    ["missionaries", "evangelists", "writers"],
    "Saul of Tarsus, a Pharisee and persecutor of the early Church, was converted on the road to Damascus by a vision of the risen Christ (Acts 9). Taking the name Paul, he became the Apostle to the Gentiles, founding churches throughout the eastern Mediterranean and writing the letters that form a large part of the New Testament. He was martyred in Rome around AD 67.",
  ),
  saint(
    "saint-john-the-baptist",
    "Saint John the Baptist",
    "06-24",
    "martyr",
    "canonized",
    ["converts", "monastic life", "Canada"],
    "Saint John the Baptist was the prophet of the Most High, kinsman of the Lord Jesus, and the immediate precursor of the Messiah. Born of Zechariah and Elizabeth, he preached repentance in the wilderness of Judea and baptized Jesus in the Jordan. Imprisoned and beheaded by Herod Antipas, Jesus said of him: 'Among those born of women there has risen no one greater than John the Baptist' (Matthew 11:11).",
  ),
  saint(
    "saint-mary-magdalene",
    "Saint Mary Magdalene",
    "07-22",
    "other",
    "canonized",
    ["converts", "penitents", "contemplative life"],
    "Saint Mary Magdalene, from whom the Lord cast out seven demons (Luke 8:2), followed Jesus and his disciples, stood beneath the Cross, and was the first witness of the Resurrection on Easter morning (John 20). The Church Fathers honor her as 'Apostle to the Apostles' for bringing the news of the risen Lord to the Twelve. Pope Francis raised her commemoration to the dignity of a feast in 2016.",
  ),
  saint(
    "saint-augustine-of-hippo",
    "Saint Augustine of Hippo",
    "08-28",
    "doctor_of_the_church",
    "canonized",
    ["theologians", "printers", "brewers"],
    "Saint Augustine (354-430) was bishop of Hippo Regius in Roman North Africa and one of the most important Latin Fathers of the Church. Born to St. Monica, he converted after years of intellectual searching, baptized by St. Ambrose in 387. His Confessions, City of God, and treatises on grace and the Trinity shaped Western Christian theology for the next 1600 years. Declared a Doctor of the Church.",
  ),
  saint(
    "saint-thomas-aquinas",
    "Saint Thomas Aquinas",
    "01-28",
    "doctor_of_the_church",
    "canonized",
    ["students", "universities", "philosophers", "Catholic schools"],
    "Saint Thomas Aquinas (1225-1274), a Dominican friar, was the greatest theologian of the High Middle Ages. His Summa Theologiae remains the most comprehensive synthesis of Christian doctrine. Pope Leo XIII (Aeterni Patris, 1879) made his thought normative for Catholic philosophy and theology. He is honored as the Angelic Doctor.",
  ),
  saint(
    "saint-francis-of-assisi",
    "Saint Francis of Assisi",
    "10-04",
    "founder",
    "canonized",
    ["Italy", "animals", "ecology", "merchants"],
    "Saint Francis of Assisi (1181/82-1226) founded the Order of Friars Minor (the Franciscans) after a dramatic conversion from the life of a wealthy merchant's son. Marked by literal imitation of the Gospel, embrace of holy poverty, devotion to the Eucharist and Mary, and tenderness toward all creation, he received the stigmata at La Verna in 1224 — the first recorded stigmatic in the Church.",
  ),
  saint(
    "saint-therese-of-lisieux",
    "Saint Therese of Lisieux",
    "10-01",
    "doctor_of_the_church",
    "canonized",
    ["missions", "florists", "France", "AIDS sufferers"],
    "Saint Therese of the Child Jesus and the Holy Face (1873-1897) was a Discalced Carmelite nun of Lisieux who died at twenty-four. Her autobiography, Story of a Soul, taught the 'Little Way' of trust and confidence in God's merciful love. Pope Pius XI canonized her in 1925, Pope Pius XI named her co-patroness of the missions, and Pope John Paul II declared her a Doctor of the Church in 1997.",
  ),
  saint(
    "saint-padre-pio",
    "Saint Padre Pio of Pietrelcina",
    "09-23",
    "confessor",
    "canonized",
    ["civil defense workers", "adolescents", "stress relief"],
    "Saint Pio of Pietrelcina (1887-1968), a Capuchin Franciscan friar, bore the visible stigmata for fifty years. Known for his long hours in the confessional, mystical gifts, and intense devotion to the Mass, he founded the Home for the Relief of Suffering hospital in San Giovanni Rotondo. Beatified by Pope John Paul II in 1999 and canonized in 2002.",
  ),
  saint(
    "saint-john-paul-ii",
    "Saint Pope John Paul II",
    "10-22",
    "pope",
    "canonized",
    ["young people", "families", "World Youth Day"],
    "Karol Józef Wojtyła (1920-2005) was elected Pope on 16 October 1978 — the first non-Italian Pope in 455 years and the first from Poland. His twenty-six-year pontificate witnessed the fall of communism in Eastern Europe, the establishment of World Youth Day, the publication of the Catechism of the Catholic Church, and the canonization of more saints than any pope before him. Canonized by Pope Francis in 2014.",
  ),
  saint(
    "saint-faustina-kowalska",
    "Saint Faustina Kowalska",
    "10-05",
    "religious",
    "canonized",
    ["mercy"],
    "Saint Maria Faustina Kowalska (1905-1938) was a Polish Sister of Our Lady of Mercy. The Lord Jesus entrusted her with the message of Divine Mercy, recorded in her Diary. Pope John Paul II canonized her in 2000 — the first saint of the new millennium — and established Divine Mercy Sunday for the universal Church.",
  ),
  saint(
    "saint-maximilian-kolbe",
    "Saint Maximilian Kolbe",
    "08-14",
    "martyr",
    "canonized",
    ["prisoners", "the pro-life movement", "drug addicts"],
    "Saint Maximilian Maria Kolbe (1894-1941) was a Polish Conventual Franciscan friar who founded the Militia Immaculatae (Knights of the Immaculata) and the Marian publishing apostolate at Niepokalanów. Imprisoned at Auschwitz, he volunteered to die in place of a stranger, Franciszek Gajowniczek, and was murdered with a phenol injection on 14 August 1941. Canonized as a martyr by Pope John Paul II in 1982.",
  ),
  saint(
    "saint-mother-teresa-of-calcutta",
    "Saint Mother Teresa of Calcutta",
    "09-05",
    "founder",
    "canonized",
    ["World Youth Day", "Missionaries of Charity"],
    "Saint Teresa of Calcutta (Anjezë Gonxhe Bojaxhiu, 1910-1997) was an Albanian-Indian Catholic nun who founded the Missionaries of Charity in 1950. The order serves 'the poorest of the poor' in over 130 countries. Awarded the Nobel Peace Prize in 1979. Beatified by Pope John Paul II in 2003 and canonized by Pope Francis in 2016.",
  ),
  saint(
    "saint-anthony-of-padua",
    "Saint Anthony of Padua",
    "06-13",
    "doctor_of_the_church",
    "canonized",
    ["lost things", "the poor", "Portugal"],
    "Saint Anthony of Padua (1195-1231), born Fernando Martins in Lisbon, joined the Franciscans and became one of the greatest preachers of the Middle Ages. Canonized within a year of his death by Pope Gregory IX. Declared a Doctor of the Church by Pope Pius XII in 1946. His tomb in Padua draws millions of pilgrims annually.",
  ),
  saint(
    "saint-patrick",
    "Saint Patrick",
    "03-17",
    "bishop",
    "canonized",
    ["Ireland", "Nigeria", "engineers"],
    "Saint Patrick (c. 385-461) was the apostle of Ireland. Born in Roman Britain, captured by Irish raiders as a teenager and enslaved for six years, he escaped, became a priest and bishop, and returned to evangelize Ireland. He used the shamrock to explain the Trinity. His Confessio and Letter to the Soldiers of Coroticus survive.",
  ),
  saint(
    "saint-benedict-of-nursia",
    "Saint Benedict of Nursia",
    "07-11",
    "founder",
    "canonized",
    ["Europe", "monastics", "students"],
    "Saint Benedict (c. 480-547) is the patriarch of Western monasticism. His Rule for monasteries — 'pray and work' — became the foundational document for monastic life in Europe and shaped Western Christian culture. Pope Paul VI named him patron of Europe in 1964.",
  ),
  saint(
    "saint-catherine-of-siena",
    "Saint Catherine of Siena",
    "04-29",
    "doctor_of_the_church",
    "canonized",
    ["Italy", "Europe", "nurses"],
    "Saint Catherine of Siena (1347-1380), a Dominican tertiary, was an influential mystic, theologian, and reformer who urged Pope Gregory XI to return the papacy from Avignon to Rome. Her Dialogue of Divine Providence is a masterpiece of mystical theology. Declared a Doctor of the Church by Pope Paul VI in 1970 and co-patroness of Europe by Pope John Paul II.",
  ),
  saint(
    "saint-ignatius-of-loyola",
    "Saint Ignatius of Loyola",
    "07-31",
    "founder",
    "canonized",
    ["soldiers", "retreats", "the Society of Jesus"],
    "Saint Ignatius of Loyola (1491-1556), Basque nobleman turned mystic and reformer, founded the Society of Jesus (the Jesuits) in 1540. His Spiritual Exercises, composed during his convalescence at Manresa, remain one of the most influential works of Western spirituality. Canonized in 1622.",
  ),
  saint(
    "saint-teresa-of-avila",
    "Saint Teresa of Avila",
    "10-15",
    "doctor_of_the_church",
    "canonized",
    ["Spain", "headache sufferers", "writers"],
    "Saint Teresa of Jesus (1515-1582), Discalced Carmelite reformer, mystic, and author of The Interior Castle and the Autobiography. With St. John of the Cross she renewed the Carmelite Order. Declared the first woman Doctor of the Church by Pope Paul VI in 1970.",
  ),
  saint(
    "saint-john-of-the-cross",
    "Saint John of the Cross",
    "12-14",
    "doctor_of_the_church",
    "canonized",
    ["mystics", "contemplative life", "Spanish poets"],
    "Saint John of the Cross (1542-1591), Discalced Carmelite priest, poet, and mystic. Co-founder with St. Teresa of Avila of the reformed Carmelite Order. Author of The Dark Night of the Soul, The Ascent of Mount Carmel, and The Spiritual Canticle. Declared a Doctor of the Church in 1926.",
  ),
  saint(
    "saint-andrew-the-apostle",
    "Saint Andrew the Apostle",
    "11-30",
    "apostle",
    "canonized",
    ["Scotland", "Greece", "fishermen"],
    "Saint Andrew, brother of Simon Peter and a fisherman of Bethsaida, was the first-called of the Apostles. After Pentecost he preached in Greece and Asia Minor and was martyred at Patras on an X-shaped cross, which bears his name. He is the patron of Scotland, Greece, and Russia.",
  ),
  saint(
    "saint-james-the-greater",
    "Saint James the Greater",
    "07-25",
    "apostle",
    "canonized",
    ["Spain", "pilgrims", "laborers"],
    "Saint James, son of Zebedee and brother of John, was one of the three apostles closest to Jesus. He was the first apostle to be martyred, beheaded by Herod Agrippa around AD 44 (Acts 12). His shrine at Santiago de Compostela in Spain has drawn pilgrims for over a thousand years.",
  ),
  saint(
    "saint-thomas-the-apostle",
    "Saint Thomas the Apostle",
    "07-03",
    "apostle",
    "canonized",
    ["India", "architects", "those who doubt"],
    "Saint Thomas, called Didymus, at first doubted the Resurrection but then confessed the risen Christ as 'My Lord and my God' (John 20:28). Tradition holds that he carried the Gospel to India, where the Saint Thomas Christians revere him as their founder, and was martyred near Chennai.",
  ),
  saint(
    "saint-matthew",
    "Saint Matthew",
    "09-21",
    "apostle",
    "canonized",
    ["accountants", "tax collectors", "bankers"],
    "Saint Matthew, also called Levi, was a tax collector whom Jesus called from his customs post to follow him (Matthew 9:9). One of the Twelve Apostles, he is traditionally honored as the author of the first Gospel, written for Jewish Christians.",
  ),
  saint(
    "saint-mark-the-evangelist",
    "Saint Mark the Evangelist",
    "04-25",
    "evangelist",
    "canonized",
    ["Venice", "notaries", "Egypt"],
    "Saint Mark, a companion of Saints Peter and Paul, wrote the second Gospel, drawing on Peter's preaching. Tradition holds that he founded the Church of Alexandria and was martyred there. His relics rest in the Basilica of San Marco in Venice, of which he is patron.",
  ),
  saint(
    "saint-luke-the-evangelist",
    "Saint Luke the Evangelist",
    "10-18",
    "evangelist",
    "canonized",
    ["physicians", "surgeons", "artists"],
    "Saint Luke, a physician and companion of Saint Paul, wrote the third Gospel and the Acts of the Apostles, preserving the infancy narratives and many parables found nowhere else. By tradition a painter of the Blessed Virgin, he is the patron of physicians and artists.",
  ),
  saint(
    "saint-stephen",
    "Saint Stephen",
    "12-26",
    "martyr",
    "canonized",
    ["deacons", "bricklayers"],
    "Saint Stephen, one of the seven deacons chosen by the Apostles, was the first martyr of the Church (the protomartyr). Filled with the Holy Spirit, he preached boldly and was stoned to death, praying for his persecutors as he died (Acts 6-7). Saul of Tarsus stood by, consenting.",
  ),
  saint(
    "saint-lawrence",
    "Saint Lawrence",
    "08-10",
    "martyr",
    "canonized",
    ["cooks", "the poor", "deacons"],
    "Saint Lawrence was a deacon of Rome martyred in 258 under Valerian. Charged to surrender the Church's treasures, he presented the poor, saying, 'These are the treasures of the Church.' Tradition holds he was martyred on a gridiron. He is honored among the most celebrated Roman martyrs.",
  ),
  saint(
    "saint-sebastian",
    "Saint Sebastian",
    "01-20",
    "martyr",
    "canonized",
    ["athletes", "soldiers", "archers"],
    "Saint Sebastian was a Roman soldier martyred under Diocletian around 288. Condemned to be shot with arrows for professing Christ, he survived and confronted the emperor before being killed. He is among the most venerated early martyrs and a patron of athletes and soldiers.",
  ),
  saint(
    "saint-agnes",
    "Saint Agnes",
    "01-21",
    "martyr",
    "canonized",
    ["young girls", "chastity", "the Children of Mary"],
    "Saint Agnes was a Roman virgin martyred about 304 at the age of twelve or thirteen for consecrating her virginity to Christ. One of the most honored of the early Roman martyrs, her name is in the Roman Canon, and lambs blessed on her feast provide wool for the pallium.",
  ),
  saint(
    "saint-cecilia",
    "Saint Cecilia",
    "11-22",
    "martyr",
    "canonized",
    ["musicians", "music", "poets"],
    "Saint Cecilia, a Roman virgin and martyr of the early Church, is honored as the patroness of music and musicians, traditionally said to have sung to God in her heart. Her name is included in the Roman Canon of the Mass.",
  ),
  saint(
    "saint-lucy",
    "Saint Lucy",
    "12-13",
    "martyr",
    "canonized",
    ["the blind", "eye disorders", "Sicily"],
    "Saint Lucy was a virgin of Syracuse in Sicily, martyred about 304 under Diocletian. Her name (Lucia, 'light') and her patronage of the blind have made her feast, near the winter solstice, a festival of light. Her name appears in the Roman Canon.",
  ),
  saint(
    "saint-nicholas",
    "Saint Nicholas",
    "12-06",
    "bishop",
    "canonized",
    ["children", "sailors", "the falsely accused"],
    "Saint Nicholas was the fourth-century Bishop of Myra in Asia Minor, renowned for his secret gifts to the poor and his defense of the faith. His generosity gave rise to the figure of Santa Claus. He is the patron of children, sailors, and many nations.",
  ),
  saint(
    "saint-monica",
    "Saint Monica",
    "08-27",
    "lay",
    "canonized",
    ["mothers", "wives", "victims of abuse"],
    "Saint Monica (331-387), mother of Saint Augustine, prayed and wept for years for the conversion of her wayward son, who was baptized by Saint Ambrose in 387. A model of Christian motherhood and persevering prayer, she died at Ostia as she and Augustine journeyed home.",
  ),
  saint(
    "saint-dominic",
    "Saint Dominic",
    "08-08",
    "founder",
    "canonized",
    ["astronomers", "preachers", "the Dominican Republic"],
    "Saint Dominic de Guzmán (1170-1221) founded the Order of Preachers (the Dominicans) to combat heresy and preach the Gospel with learning and poverty. Devotion to the Rosary is closely associated with him and his order.",
  ),
  saint(
    "saint-clare-of-assisi",
    "Saint Clare of Assisi",
    "08-11",
    "founder",
    "canonized",
    ["television", "eye disease", "the Poor Clares"],
    "Saint Clare of Assisi (1194-1253), inspired by Saint Francis, left her noble family to embrace radical poverty and founded the Order of Poor Ladies (the Poor Clares). She defended her sisters and her city through prayer before the Blessed Sacrament.",
  ),
  saint(
    "saint-vincent-de-paul",
    "Saint Vincent de Paul",
    "09-27",
    "founder",
    "canonized",
    ["charitable societies", "the poor", "hospitals"],
    "Saint Vincent de Paul (1581-1660) devoted his life to the poor, founding the Congregation of the Mission (the Vincentians) and, with Saint Louise de Marillac, the Daughters of Charity. He is the patron of all works of Christian charity.",
  ),
  saint(
    "saint-philip-neri",
    "Saint Philip Neri",
    "05-26",
    "founder",
    "canonized",
    ["Rome", "joy", "the Oratory"],
    "Saint Philip Neri (1515-1595), the 'Apostle of Rome,' founded the Congregation of the Oratory and renewed the faith of the city through joy, confession, and prayer. Famous for his humor and holiness, he drew countless souls back to God.",
  ),
  saint(
    "saint-john-bosco",
    "Saint John Bosco",
    "01-31",
    "founder",
    "canonized",
    ["youth", "editors", "apprentices"],
    "Saint John Bosco (1815-1888), known as Don Bosco, devoted his life to poor and abandoned boys in Turin, founding the Salesians and, with Saint Mary Mazzarello, the Salesian Sisters. His 'preventive system' of education rested on reason, religion, and loving-kindness.",
  ),
  saint(
    "saint-joan-of-arc",
    "Saint Joan of Arc",
    "05-30",
    "martyr",
    "canonized",
    ["France", "soldiers", "captives"],
    "Saint Joan of Arc (1412-1431), the Maid of Orléans, was a peasant girl who, led by heavenly voices, rallied the French army during the Hundred Years' War. Captured and tried by an ecclesiastical court under English control, she was burned at the stake at nineteen and later fully vindicated. Canonized in 1920, she is a patroness of France.",
  ),
  saint(
    "saint-rita-of-cascia",
    "Saint Rita of Cascia",
    "05-22",
    "religious",
    "canonized",
    ["impossible causes", "difficult marriages", "parenthood"],
    "Saint Rita of Cascia (1381-1457), after a difficult marriage and the loss of her husband and sons, became an Augustinian nun. Renowned for her penance and a wound she received from the crown of thorns, she is invoked as the patroness of impossible and desperate causes.",
  ),
  saint(
    "saint-martin-de-porres",
    "Saint Martin de Porres",
    "11-03",
    "religious",
    "canonized",
    ["social justice", "mixed-race people", "barbers"],
    "Saint Martin de Porres (1579-1639) of Lima, Peru, a Dominican lay brother of mixed Spanish and African descent, served the sick and poor with heroic charity and was known for miracles and care of animals. Canonized in 1962, he is a patron of social justice.",
  ),
  saint(
    "saint-rose-of-lima",
    "Saint Rose of Lima",
    "08-23",
    "religious",
    "canonized",
    ["Latin America", "the Philippines", "gardeners"],
    "Saint Rose of Lima (1586-1617), a Dominican tertiary of Peru, lived a life of intense penance and care for the poor and indigenous of Lima. In 1671 she became the first canonized saint of the Americas.",
  ),
  saint(
    "saint-elizabeth-ann-seton",
    "Saint Elizabeth Ann Seton",
    "01-04",
    "founder",
    "canonized",
    ["Catholic schools", "widows", "the United States"],
    "Saint Elizabeth Ann Seton (1774-1821), a convert and widow, founded the Sisters of Charity and the first Catholic parochial school system in the United States. In 1975 she became the first native-born citizen of the United States to be canonized.",
  ),
  saint(
    "saint-juan-diego",
    "Saint Juan Diego",
    "12-09",
    "lay",
    "canonized",
    ["indigenous peoples", "the Americas"],
    "Saint Juan Diego (1474-1548) was the humble Aztec convert to whom the Blessed Virgin Mary appeared at Tepeyac in 1531 as Our Lady of Guadalupe, leaving her image on his tilma. Canonized in 2002, he is honored as a model of humility and faith.",
  ),
  saint(
    "saint-jude-thaddeus",
    "Saint Jude Thaddeus",
    "10-28",
    "apostle",
    "canonized",
    ["desperate situations", "hopeless causes", "hospitals"],
    "Saint Jude Thaddeus was one of the Twelve Apostles, traditionally identified as a relative of the Lord. He preached the Gospel in Judea, Mesopotamia, and Persia, where he was martyred with the Apostle Simon. He is universally invoked as the patron of desperate and hopeless causes.",
  ),
  saint(
    "saint-bartholomew",
    "Saint Bartholomew the Apostle",
    "08-24",
    "apostle",
    "canonized",
    ["tanners", "plasterers"],
    "Saint Bartholomew, often identified with Nathanael in the Gospel of John, was one of the Twelve Apostles. Tradition holds that he carried the Gospel to Armenia, where he was flayed and beheaded for the faith. His relics are venerated in Rome on the Tiber Island.",
  ),
  saint(
    "saint-matthias",
    "Saint Matthias the Apostle",
    "05-14",
    "apostle",
    "canonized",
    ["carpenters", "perseverance"],
    "Saint Matthias was chosen by the eleven Apostles, by the casting of lots after prayer, to take the place of Judas Iscariot among the Twelve (Acts 1:15-26). Having been a disciple of the Lord from the baptism of John, he preached the Gospel and, by tradition, was martyred for the faith.",
  ),
  saint(
    "saint-barnabas",
    "Saint Barnabas the Apostle",
    "06-11",
    "apostle",
    "canonized",
    ["Cyprus", "peacemakers"],
    "Saint Barnabas, a Levite of Cyprus, was surnamed Barnabas ('son of encouragement') by the Apostles. He introduced the newly converted Saul to the disciples and accompanied Saint Paul on his first missionary journey. Venerated as an apostle, tradition holds he was martyred at Salamis on Cyprus.",
  ),
  saint(
    "saint-john-vianney",
    "Saint John Vianney",
    "08-04",
    "confessor",
    "canonized",
    ["parish priests"],
    "Saint John Marie Vianney (1786-1859), the Curé of Ars, was a French parish priest renowned for his holiness, his long hours in the confessional, and his pastoral zeal. Pope Pius XI canonized him in 1925 and declared him the patron of parish priests.",
  ),
  saint(
    "saint-ignatius-of-antioch",
    "Saint Ignatius of Antioch",
    "10-17",
    "martyr",
    "canonized",
    ["the Church in the East"],
    "Saint Ignatius (c. 35-c. 108), bishop of Antioch and a disciple of the Apostles, was condemned to the beasts at Rome under the Emperor Trajan. On the journey to martyrdom he wrote seven letters that are among the earliest witnesses to the Eucharist, the episcopacy, and the unity of the Church.",
  ),
  saint(
    "saint-polycarp",
    "Saint Polycarp of Smyrna",
    "02-23",
    "martyr",
    "canonized",
    ["against earache"],
    "Saint Polycarp (c. 69-c. 155), bishop of Smyrna, was a disciple of Saint John the Apostle and a link between the apostolic age and the early Fathers. Arrested in old age, he refused to renounce Christ, saying, 'Eighty-six years I have served him, and he has done me no wrong,' and was burned at the stake.",
  ),
  saint(
    "saint-george",
    "Saint George",
    "04-23",
    "martyr",
    "canonized",
    ["England", "soldiers", "scouts"],
    "Saint George (died c. 303) was a soldier in the Roman army martyred for his faith under the Emperor Diocletian. Venerated since antiquity in both East and West, he is celebrated in legend for slaying a dragon and is the patron of England, soldiers, and many nations.",
  ),
  saint(
    "saint-blaise",
    "Saint Blaise",
    "02-03",
    "bishop",
    "canonized",
    ["throat ailments", "wool combers"],
    "Saint Blaise (died c. 316), bishop of Sebaste in Armenia, was martyred during the persecutions of the early fourth century. He is remembered for miraculously saving a boy choking on a fishbone, and the Church blesses throats on his feast with two crossed candles.",
  ),
  saint(
    "saint-agatha",
    "Saint Agatha",
    "02-05",
    "virgin",
    "canonized",
    ["breast cancer patients", "Sicily", "against fire"],
    "Saint Agatha (died c. 251) was a young woman of Sicily who consecrated her virginity to Christ and suffered a cruel martyrdom under the persecution of Decius rather than renounce her faith. One of the most venerated virgin martyrs of antiquity, her name is named in the Roman Canon of the Mass.",
  ),
  saint(
    "saint-maria-goretti",
    "Saint Maria Goretti",
    "07-06",
    "virgin",
    "canonized",
    ["youth", "purity", "victims of assault"],
    "Saint Maria Goretti (1890-1902) was an Italian peasant girl who, at the age of eleven, was fatally stabbed while resisting an assault and who forgave her attacker before she died. Canonized in 1950 by Pope Pius XII, she is honored as a martyr of purity and a model for the young.",
  ),
  saint(
    "saint-bernadette-soubirous",
    "Saint Bernadette Soubirous",
    "04-16",
    "virgin",
    "canonized",
    ["the sick", "shepherds", "Lourdes"],
    "Saint Bernadette Soubirous (1844-1879) was the humble French girl to whom the Blessed Virgin Mary appeared eighteen times at Lourdes in 1858, identifying herself as the Immaculate Conception. She later became a Sister of Charity at Nevers, where she died; her body remains incorrupt.",
  ),
  saint(
    "saint-josephine-bakhita",
    "Saint Josephine Bakhita",
    "02-08",
    "religious",
    "canonized",
    ["Sudan", "victims of human trafficking"],
    "Saint Josephine Bakhita (c. 1869-1947) was born in Darfur, kidnapped and sold into slavery as a child, and eventually freed in Italy, where she became a Canossian Sister. Canonized in 2000, she is a witness to forgiveness and a patron of victims of human trafficking.",
  ),
  saint(
    "saint-kateri-tekakwitha",
    "Saint Kateri Tekakwitha",
    "07-14",
    "virgin",
    "canonized",
    ["ecology", "indigenous peoples", "the environment"],
    "Saint Kateri Tekakwitha (1656-1680), the 'Lily of the Mohawks,' was a Mohawk-Algonquin woman of present-day New York who embraced the Catholic faith and consecrated her virginity to Christ amid great opposition. Canonized in 2012, she is the first Native American saint.",
  ),
  saint(
    "saint-frances-xavier-cabrini",
    "Saint Frances Xavier Cabrini",
    "11-13",
    "religious",
    "canonized",
    ["immigrants", "hospital administrators"],
    "Saint Frances Xavier Cabrini (1850-1917), foundress of the Missionary Sisters of the Sacred Heart of Jesus, emigrated from Italy to the United States and established schools, hospitals, and orphanages for immigrants. Canonized in 1946, she was the first United States citizen to be canonized.",
  ),
  saint(
    "saint-katharine-drexel",
    "Saint Katharine Drexel",
    "03-03",
    "religious",
    "canonized",
    ["racial justice", "philanthropists"],
    "Saint Katharine Drexel (1858-1955), heiress of a wealthy Philadelphia family, gave her fortune to found the Sisters of the Blessed Sacrament and to establish schools and missions for Native Americans and African Americans, including Xavier University in New Orleans. She was canonized in 2000.",
  ),
  saint(
    "saint-damien-of-molokai",
    "Saint Damien of Molokai",
    "05-10",
    "religious",
    "canonized",
    ["lepers", "outcasts"],
    "Saint Damien of Molokai (1840-1889), a Belgian priest of the Congregation of the Sacred Hearts, ministered to the abandoned lepers of the Hawaiian island of Molokai, eventually contracting and dying of the disease himself. Canonized in 2009, he is a patron of those afflicted with leprosy.",
  ),
  saint(
    "saint-francis-xavier",
    "Saint Francis Xavier",
    "12-03",
    "missionary",
    "canonized",
    ["missions", "navigators"],
    "Saint Francis Xavier (1506-1552), one of the first companions of Saint Ignatius of Loyola and a co-founder of the Society of Jesus, was the great missionary to India, the East Indies, and Japan, baptizing tens of thousands. He died off the coast of China and is honored as patron of the missions.",
  ),
  saint(
    "saint-aloysius-gonzaga",
    "Saint Aloysius Gonzaga",
    "06-21",
    "religious",
    "canonized",
    ["youth", "students"],
    "Saint Aloysius Gonzaga (1568-1591), an Italian nobleman who renounced his inheritance to enter the Society of Jesus, died at the age of twenty-three after contracting plague while nursing the sick in Rome. Canonized in 1726, he is a patron of Catholic youth and students.",
  ),
  saint(
    "saint-charles-borromeo",
    "Saint Charles Borromeo",
    "11-04",
    "bishop",
    "canonized",
    ["bishops", "catechists", "seminarians"],
    "Saint Charles Borromeo (1538-1584), Cardinal Archbishop of Milan, was a leading reformer who implemented the Council of Trent, founded seminaries, promoted catechesis, and served his people heroically during the plague of 1576. Canonized in 1610, he is a patron of bishops and catechists.",
  ),
  saint(
    "saint-john-neumann",
    "Saint John Neumann",
    "01-05",
    "bishop",
    "canonized",
    ["Catholic education", "immigrants"],
    "Saint John Neumann (1811-1860), a Redemptorist and the fourth bishop of Philadelphia, organized the first diocesan system of Catholic schools in the United States. Canonized in 1977, he was the first American bishop to be raised to the altars.",
  ),
  saint(
    "saint-helena",
    "Saint Helena",
    "08-18",
    "lay",
    "canonized",
    ["archaeologists", "converts"],
    "Saint Helena (c. 248-c. 330), mother of the Emperor Constantine, was a devout convert who, in her old age, made a pilgrimage to the Holy Land, where tradition holds she discovered the True Cross of Christ. She built churches on the holy sites and is venerated for her piety and charity.",
  ),
  saint(
    "saint-elizabeth-of-hungary",
    "Saint Elizabeth of Hungary",
    "11-17",
    "lay",
    "canonized",
    ["the poor", "widows", "Third Order Franciscans"],
    "Saint Elizabeth of Hungary (1207-1231), a princess and wife of the Landgrave of Thuringia, devoted herself after her husband's death to Franciscan poverty and the care of the sick and the poor, founding a hospital where she served personally. She was canonized in 1235.",
  ),
  saint(
    "saint-gianna-molla",
    "Saint Gianna Beretta Molla",
    "04-28",
    "lay",
    "canonized",
    ["mothers", "physicians", "the unborn"],
    "Saint Gianna Beretta Molla (1922-1962) was an Italian pediatrician, wife, and mother who, during her fourth pregnancy, refused procedures that would have ended her child's life and died shortly after the birth. Canonized in 2004, she is a patron of mothers, physicians, and the unborn.",
  ),
  saint(
    "saint-oscar-romero",
    "Saint Oscar Romero",
    "03-24",
    "martyr",
    "canonized",
    ["El Salvador", "persecuted Christians"],
    "Saint Oscar Romero (1917-1980), Archbishop of San Salvador, was a courageous defender of the poor and an outspoken voice against violence and injustice, who was assassinated while celebrating Mass. Canonized in 2018, he is honored as a martyr for the faith.",
  ),
  saint(
    "saint-perpetua-and-felicity",
    "Saints Perpetua and Felicity",
    "03-07",
    "martyr",
    "canonized",
    ["mothers", "expectant mothers"],
    "Saints Perpetua, a young noblewoman, and Felicity, her slave, were martyred together at Carthage in AD 203 during the persecution of Septimius Severus. Perpetua's prison diary is one of the earliest Christian texts written by a woman; their names are included in the Roman Canon of the Mass.",
  ),
  saint(
    "saint-justin-martyr",
    "Saint Justin Martyr",
    "06-01",
    "martyr",
    "canonized",
    ["philosophers", "apologists"],
    "Saint Justin (c. 100-c. 165) was a philosopher who, converting to Christianity, became the first great Christian apologist, defending the faith before the Roman authorities. His First Apology gives the earliest detailed description of the Sunday Eucharist. He was beheaded at Rome with several companions.",
  ),
  saint(
    "saint-cyprian-of-carthage",
    "Saint Cyprian of Carthage",
    "09-16",
    "martyr",
    "canonized",
    ["North Africa"],
    "Saint Cyprian (c. 210-258), bishop of Carthage and a Father of the Church, guided his people through persecution and controversy over the lapsed, writing influential treatises on the unity of the Church. He was martyred under the Emperor Valerian and is commemorated with Pope St. Cornelius.",
  ),
  saint(
    "saint-thomas-becket",
    "Saint Thomas Becket",
    "12-29",
    "martyr",
    "canonized",
    ["clergy", "against the abuse of power"],
    "Saint Thomas Becket (1118-1170), Archbishop of Canterbury, defended the liberty of the Church against King Henry II of England and was murdered by the king's knights in his own cathedral. Canonized in 1173, his shrine became one of the great pilgrimage destinations of medieval Europe.",
  ),
  saint(
    "saint-thomas-more",
    "Saint Thomas More",
    "06-22",
    "martyr",
    "canonized",
    ["statesmen", "lawyers", "politicians"],
    "Saint Thomas More (1478-1535), Lord Chancellor of England and author of Utopia, refused to acknowledge King Henry VIII as head of the Church in England and was beheaded for his fidelity to the pope and his conscience. Canonized in 1935, he is a patron of statesmen and lawyers.",
  ),
  saint(
    "saint-john-fisher",
    "Saint John Fisher",
    "06-22",
    "martyr",
    "canonized",
    ["bishops"],
    "Saint John Fisher (1469-1535), Bishop of Rochester and a renowned theologian, was the only English bishop to refuse the Oath of Supremacy under King Henry VIII, and was beheaded for it. Canonized in 1935, he is commemorated with his friend St. Thomas More.",
  ),
  saint(
    "saint-isidore-the-farmer",
    "Saint Isidore the Farmer",
    "05-15",
    "lay",
    "canonized",
    ["farmers", "laborers", "rural communities"],
    "Saint Isidore (c. 1070-1130) was a humble farm laborer near Madrid who, with his wife Maria, lived a life of prayer, hard work, and charity to the poor. Renowned for miracles, he was canonized in 1622 and is the patron of farmers and rural life.",
  ),
  saint(
    "saint-john-of-god",
    "Saint John of God",
    "03-08",
    "founder",
    "canonized",
    ["the sick", "hospitals", "nurses"],
    "Saint John of God (1495-1550), after a dramatic conversion in Granada, devoted his life to caring for the sick and the poor, founding the Brothers Hospitallers. Canonized in 1690, he is a patron of hospitals, nurses, and the dying.",
  ),
  saint(
    "saint-camillus-de-lellis",
    "Saint Camillus de Lellis",
    "07-18",
    "founder",
    "canonized",
    ["the sick", "nurses", "hospitals"],
    "Saint Camillus de Lellis (1550-1614), a former soldier and gambler, converted and founded the Camillians (the Ministers of the Sick) to care for the sick and dying with great tenderness. Canonized in 1746, he is a patron of the sick, nurses, and hospitals.",
  ),
  saint(
    "saint-bridget-of-sweden",
    "Saint Bridget of Sweden",
    "07-23",
    "founder",
    "canonized",
    ["Sweden", "Europe", "widows"],
    "Saint Bridget of Sweden (1303-1373), a noblewoman, wife, and mother, received celebrated mystical revelations and founded the Bridgettine Order. Canonized in 1391, she is a co-patroness of Europe.",
  ),
  saint(
    "saint-catherine-laboure",
    "Saint Catherine Labouré",
    "11-28",
    "religious",
    "canonized",
    ["the elderly"],
    "Saint Catherine Labouré (1806-1876), a Daughter of Charity in Paris, received the apparitions of the Blessed Virgin in 1830 that gave the Church the Miraculous Medal. She lived the rest of her life in hidden humility; canonized in 1947, her body remains incorrupt.",
  ),
  saint(
    "saint-margaret-mary-alacoque",
    "Saint Margaret Mary Alacoque",
    "10-16",
    "religious",
    "canonized",
    ["devotees of the Sacred Heart"],
    "Saint Margaret Mary Alacoque (1647-1690), a Visitation nun at Paray-le-Monial, received the revelations of the Sacred Heart of Jesus that spread the devotion and the Nine First Fridays throughout the Church. She was canonized in 1920.",
  ),
  saint(
    "saint-andre-bessette",
    "Saint André Bessette",
    "01-06",
    "religious",
    "canonized",
    ["the sick", "Montreal"],
    "Saint André Bessette (1845-1937), a humble Holy Cross brother and doorkeeper in Montreal, became renowned for his devotion to Saint Joseph and the countless healings attributed to his intercession. He inspired the building of Saint Joseph's Oratory and was canonized in 2010.",
  ),
  saint(
    "saint-anthony-mary-claret",
    "Saint Anthony Mary Claret",
    "10-24",
    "bishop",
    "canonized",
    ["weavers", "Catholic press"],
    "Saint Anthony Mary Claret (1807-1870), Archbishop of Santiago de Cuba and founder of the Claretian Missionaries, was a tireless preacher and writer. Canonized in 1950, he is honored for his missionary zeal and promotion of the Catholic press.",
  ),
  saint(
    "saint-paul-of-the-cross",
    "Saint Paul of the Cross",
    "10-19",
    "founder",
    "canonized",
    ["preachers"],
    "Saint Paul of the Cross (1694-1775) founded the Passionists, devoted to keeping alive the memory of the Passion of Christ. A great mystic and preacher of missions, he was canonized in 1867.",
  ),
  saint(
    "saint-teresa-benedicta-of-the-cross",
    "Saint Teresa Benedicta of the Cross (Edith Stein)",
    "08-09",
    "martyr",
    "canonized",
    ["Europe", "converts", "martyrs"],
    "Saint Teresa Benedicta of the Cross (Edith Stein, 1891-1942), a Jewish philosopher who converted to Catholicism and became a Discalced Carmelite nun, was killed at Auschwitz. Canonized in 1998, she is a co-patroness of Europe and a witness against the horrors of the twentieth century.",
  ),
  saint(
    "saint-josemaria-escriva",
    "Saint Josemaría Escrivá",
    "06-26",
    "founder",
    "canonized",
    ["ordinary work", "the laity"],
    "Saint Josemaría Escrivá (1902-1975), a Spanish priest, founded Opus Dei to spread the call to holiness in ordinary work and daily life. Canonized in 2002, he taught that the sanctification of work is at the heart of the Christian vocation.",
  ),
  saint(
    "saint-john-baptist-de-la-salle",
    "Saint John Baptist de la Salle",
    "04-07",
    "founder",
    "canonized",
    ["teachers", "educators"],
    "Saint John Baptist de la Salle (1651-1719), a French priest, founded the Brothers of the Christian Schools and pioneered methods of education for the poor. Canonized in 1900, he is the patron of teachers.",
  ),
  saint(
    "saint-peter-claver",
    "Saint Peter Claver",
    "09-09",
    "missionary",
    "canonized",
    ["enslaved peoples", "racial justice", "Colombia"],
    "Saint Peter Claver (1580-1654), a Spanish Jesuit at Cartagena, devoted forty years to the bodily and spiritual care of the enslaved Africans arriving in the New World, baptizing some three hundred thousand. Canonized in 1888, he called himself 'the slave of the slaves.'",
  ),
  saint(
    "saint-turibius-of-mogrovejo",
    "Saint Turibius of Mogrovejo",
    "03-23",
    "bishop",
    "canonized",
    ["Latin American bishops", "Peru"],
    "Saint Turibius of Mogrovejo (1538-1606), Archbishop of Lima, was a tireless reformer and defender of the indigenous peoples of Peru, confirming and catechizing across vast territories. Canonized in 1726, he is a patron of the bishops of Latin America.",
  ),
  saint(
    "saint-louis-de-montfort",
    "Saint Louis de Montfort",
    "04-28",
    "founder",
    "canonized",
    ["preachers", "Marian devotion"],
    "Saint Louis de Montfort (1673-1716), a French priest and preacher, wrote 'True Devotion to the Blessed Virgin Mary,' which shaped modern Marian spirituality and the practice of total consecration to Jesus through Mary. He was canonized in 1947.",
  ),
  saint(
    "saint-wenceslaus",
    "Saint Wenceslaus",
    "09-28",
    "martyr",
    "canonized",
    ["the Czech people", "Bohemia"],
    "Saint Wenceslaus (c. 907-935), Duke of Bohemia, was a just and devout ruler murdered by his brother for the faith. Honored as the patron and heavenly protector of the Czech nation, he is the 'Good King Wenceslas' of the Christmas carol.",
  ),
  saint(
    "saint-casimir",
    "Saint Casimir",
    "03-04",
    "lay",
    "canonized",
    ["Poland", "Lithuania", "young people"],
    "Saint Casimir (1458-1484), a prince of Poland and Lithuania, lived a short life marked by prayer, chastity, and devotion to the Blessed Virgin and the poor, refusing a throne won by unjust war. Canonized in 1521, he is a patron of Poland and Lithuania.",
  ),
  saint(
    "saint-bruno",
    "Saint Bruno",
    "10-06",
    "founder",
    "canonized",
    ["Carthusians"],
    "Saint Bruno (c. 1030-1101), a renowned teacher at Reims, withdrew to the mountains of the Chartreuse and founded the Carthusian Order, devoted to silence, solitude, and contemplation. His feast is kept on October 6.",
  ),
  saint(
    "saint-norbert",
    "Saint Norbert",
    "06-06",
    "founder",
    "canonized",
    ["Magdeburg"],
    "Saint Norbert (c. 1080-1134), after a worldly youth and sudden conversion, founded the Premonstratensian Canons (Norbertines) and became Archbishop of Magdeburg, promoting reform of the clergy and devotion to the Blessed Sacrament. He was canonized in 1582.",
  ),
  saint(
    "saint-anthony-the-abbot",
    "Saint Anthony the Abbot",
    "01-17",
    "religious",
    "canonized",
    ["monks", "skin diseases", "domestic animals"],
    "Saint Anthony of Egypt (c. 251-356), often called the Father of Monasticism, gave away his inheritance and withdrew to the Egyptian desert to live in prayer and asceticism, where he was famously tempted by demons. His example drew countless others to the solitary life, and his biography by Saint Athanasius spread monasticism throughout the Church.",
  ),
  saint(
    "saint-scholastica",
    "Saint Scholastica",
    "02-10",
    "virgin",
    "canonized",
    ["nuns", "convulsive children", "against storms"],
    "Saint Scholastica (c. 480-543) was the twin sister of Saint Benedict of Nursia and is regarded as the first Benedictine nun. She founded a community of women near Monte Cassino and met her brother once a year for holy conversation. Saint Gregory the Great recounts that at their last meeting she obtained by prayer a storm that kept Benedict with her, and she died three days later.",
  ),
  saint(
    "saint-apollonia",
    "Saint Apollonia",
    "02-09",
    "martyr",
    "canonized",
    ["dentists", "against toothache"],
    "Saint Apollonia (died 249) was an aged deaconess of Alexandria martyred during an anti-Christian riot under the emperor Decius. Her persecutors broke and knocked out her teeth, then threatened to burn her alive unless she renounced Christ; she leapt into the fire of her own accord rather than blaspheme. She is invoked against toothache and is the patron of dentists.",
  ),
  saint(
    "saint-valentine",
    "Saint Valentine",
    "02-14",
    "martyr",
    "canonized",
    ["engaged couples", "love", "epilepsy", "beekeepers"],
    "Saint Valentine was a third-century Roman priest (and, by some accounts, a bishop of Terni) martyred under the emperor Claudius II, traditionally for aiding persecuted Christians and witnessing marriages. He was beheaded around 269 and buried on the Via Flaminia. His feast has long been associated with devoted love and the blessing of engaged couples.",
  ),
  saint(
    "saint-christopher",
    "Saint Christopher",
    "07-25",
    "martyr",
    "canonized",
    ["travelers", "motorists", "against storms"],
    "Saint Christopher was a third-century martyr venerated in both East and West. Pious legend tells that this giant of a man sought to serve the greatest king, and a hermit taught him to carry travelers across a dangerous river; one day he bore a child who grew unbearably heavy — Christ carrying the weight of the world — and so received the name Christopher ('Christ-bearer'). He is the beloved patron of travelers.",
  ),
  saint(
    "saint-dymphna",
    "Saint Dymphna",
    "05-15",
    "martyr",
    "canonized",
    ["mental illness", "anxiety", "emotional disorders"],
    "Saint Dymphna was a seventh-century Irish princess who fled to Geel in Belgium to escape her pagan father after the death of her mother. When he found her and she refused his sinful demands, he beheaded her around the age of fifteen. Her shrine at Geel became a renowned center of compassionate care for the mentally ill, and she is the patron of those who suffer mental and emotional illness.",
  ),
  saint(
    "saint-gerard-majella",
    "Saint Gerard Majella",
    "10-16",
    "religious",
    "canonized",
    ["expectant mothers", "childbirth", "the unborn"],
    "Saint Gerard Majella (1726-1755) was a Redemptorist lay brother of remarkable holiness, known for ecstasies, bilocation, and reading of hearts. Falsely accused and bearing it in silence, he was later vindicated. Through an incident with a handkerchief he gave to a family, he became the celebrated patron of expectant mothers and a great intercessor for safe childbirth.",
  ),
  saint(
    "saint-roch",
    "Saint Roch",
    "08-16",
    "confessor",
    "canonized",
    ["against plague and epidemics", "the sick", "dogs"],
    "Saint Roch (c. 1295-1327) was a French pilgrim who tended plague victims in Italy and was himself stricken; he withdrew to a forest where, tradition holds, a dog brought him bread each day and licked his wounds until he recovered. Imprisoned on his return home and unrecognized, he died in captivity. He is invoked against plague and contagious disease.",
  ),
  saint(
    "saint-genevieve",
    "Saint Genevieve",
    "01-03",
    "virgin",
    "canonized",
    ["Paris", "against disasters"],
    "Saint Genevieve (c. 420-512) consecrated herself to God as a young girl and became the spiritual patroness of Paris. By her prayers and counsel she is credited with sparing the city from Attila and the Huns in 451 and with organizing relief during a later siege. Her tireless charity and influence with kings made her one of the great figures of early Gaul.",
  ),
  saint(
    "saint-bernard-of-clairvaux",
    "Saint Bernard of Clairvaux",
    "08-20",
    "doctor_of_the_church",
    "canonized",
    ["Cistercians", "beekeepers", "candlemakers"],
    "Saint Bernard of Clairvaux (1090-1153) was the great Cistercian abbot, mystic, and Doctor of the Church known as the 'Mellifluous Doctor.' He founded the monastery of Clairvaux, preached the Second Crusade, defended the Church against the errors of his day, and wrote luminous works on the love of God and the Blessed Virgin Mary. He was canonized in 1174.",
  ),
  saint(
    "saint-hildegard-of-bingen",
    "Saint Hildegard of Bingen",
    "09-17",
    "doctor_of_the_church",
    "canonized",
    ["musicians", "writers"],
    "Saint Hildegard of Bingen (1098-1179) was a German Benedictine abbess, mystic, composer, and polymath who recorded her visions in works such as the Scivias. She corresponded with popes and emperors, composed sacred music of striking beauty, and wrote on theology, medicine, and the natural world. Pope Benedict XVI named her a Doctor of the Church in 2012.",
  ),
  saint(
    "saint-gertrude-the-great",
    "Saint Gertrude the Great",
    "11-16",
    "virgin",
    "canonized",
    ["the souls in purgatory", "the West Indies"],
    "Saint Gertrude the Great (1256-1302) was a Benedictine nun of Helfta and one of the great mystics of the Church, favored with profound revelations of the Sacred Heart of Jesus. Her Herald of Divine Love records her intimate union with Christ. She is especially invoked for the souls in purgatory, for whom she prayed unceasingly.",
  ),
  saint(
    "saint-john-henry-newman",
    "Saint John Henry Newman",
    "10-09",
    "confessor",
    "canonized",
    ["seekers of truth", "educators"],
    "Saint John Henry Newman (1801-1890) was a leading Anglican theologian of the Oxford Movement who, after long study of the early Church, was received into the Catholic Church in 1845. A priest, founder of the Oratory in England, and later cardinal, he wrote masterworks such as the Apologia Pro Vita Sua and the Essay on the Development of Christian Doctrine. He was canonized in 2019.",
  ),
  saint(
    "saint-charles-lwanga",
    "Saint Charles Lwanga and Companions",
    "06-03",
    "martyr",
    "canonized",
    ["Africa", "youth", "converts"],
    "Saint Charles Lwanga (c. 1860-1886) was a chief page at the court of King Mwanga of Buganda who, with a group of young companions, was put to death for his Christian faith and for protecting the pages from the king's abuse. Many were burned alive at Namugongo. These Ugandan Martyrs, canonized in 1964, are patrons of African youth.",
  ),
  saint(
    "saint-paul-miki",
    "Saint Paul Miki and Companions",
    "02-06",
    "martyr",
    "canonized",
    ["Japan"],
    "Saint Paul Miki (c. 1562-1597) was a Japanese Jesuit and gifted preacher who, with twenty-five companions — priests, religious, and laymen including children — was crucified at Nagasaki during the persecution under Toyotomi Hideyoshi. From his cross Paul Miki preached forgiveness of his executioners. The Martyrs of Japan were canonized in 1862.",
  ),
  saint(
    "saint-andrew-kim-taegon",
    "Saint Andrew Kim Taegon and Companions",
    "09-20",
    "martyr",
    "canonized",
    ["Korea", "clergy"],
    "Saint Andrew Kim Taegon (1821-1846) was the first native Korean Catholic priest, ordained after perilous study abroad. He returned to minister to the persecuted Church in Korea and was beheaded near Seoul at the age of twenty-five. With Saint Paul Chong Hasang and many lay companions, the Korean Martyrs were canonized by Saint John Paul II in Seoul in 1984.",
  ),
  saint(
    "saint-lorenzo-ruiz",
    "Saint Lorenzo Ruiz",
    "09-28",
    "martyr",
    "canonized",
    ["the Philippines", "Filipino youth", "those falsely accused"],
    "Saint Lorenzo Ruiz (c. 1600-1637) was a Filipino layman, husband, and father who fled to Japan and was caught up in the persecution there. Subjected to brutal torture at Nagasaki, he declared he would die a thousand deaths for God rather than renounce his faith. He is the first canonized Filipino saint, raised to the altars in 1987.",
  ),
  saint(
    "saint-junipero-serra",
    "Saint Junipero Serra",
    "07-01",
    "missionary",
    "canonized",
    ["California", "vocations", "Hispanic Americans"],
    "Saint Junipero Serra (1713-1784) was a Spanish Franciscan friar who founded the first nine of the California missions, evangelizing and baptizing thousands of Native Americans along the Pacific coast. Tireless despite a chronic leg ailment, he is remembered as the Apostle of California. He was canonized by Pope Francis in Washington in 2015.",
  ),
  saint(
    "saint-marianne-cope",
    "Saint Marianne Cope",
    "01-23",
    "religious",
    "canonized",
    ["lepers", "outcasts", "Hawaii"],
    "Saint Marianne Cope (1838-1918) was a German-born Franciscan sister and hospital administrator in New York who answered a call to serve in Hawaii. For thirty years she cared for those afflicted with leprosy on Molokai, continuing the work of Saint Damien, and not one of her sisters contracted the disease. She was canonized in 2012.",
  ),
  saint(
    "saint-rose-philippine-duchesne",
    "Saint Rose Philippine Duchesne",
    "11-18",
    "missionary",
    "canonized",
    ["the frontier", "perseverance amid adversity"],
    "Saint Rose Philippine Duchesne (1769-1852) was a French Religious of the Sacred Heart who at the age of forty-nine sailed to the American frontier, founding schools and serving in Missouri. Late in life she prayed so constantly among the Potawatomi that they named her 'Woman Who Prays Always.' She was canonized in 1988.",
  ),
  saint(
    "saint-anne",
    "Saint Anne",
    "07-26",
    "other",
    "canonized",
    ["mothers", "grandmothers", "homemakers"],
    "Saint Anne, honored by ancient tradition as the mother of the Blessed Virgin Mary and grandmother of Jesus, is venerated together with her husband Saint Joachim. Though not named in the Scriptures, their memory has been cherished since the early Church. Saint Anne is the beloved patron of mothers and grandmothers, invoked especially by those longing for children.",
  ),
  saint(
    "saint-martha",
    "Saint Martha",
    "07-29",
    "other",
    "canonized",
    ["cooks", "homemakers", "hospitality", "servers"],
    "Saint Martha of Bethany was the sister of Mary and Lazarus and a friend of Jesus, who welcomed him into her home. The Gospels recall her busy hospitality, her profound profession of faith before the raising of Lazarus ('You are the Christ, the Son of God'), and her place among the Lord's closest friends. She is the patron of cooks and homemakers.",
  ),
  saint(
    "saint-athanasius",
    "Saint Athanasius",
    "05-02",
    "doctor_of_the_church",
    "canonized",
    ["theologians", "against heresy"],
    "Saint Athanasius (c. 296-373), Bishop of Alexandria and Doctor of the Church, was the great champion of orthodoxy against the Arian heresy, defending the full divinity of Christ at and after the Council of Nicaea. Exiled five times for the faith, he wrote On the Incarnation and the life of Saint Anthony. He is called the Father of Orthodoxy.",
  ),
  saint(
    "saint-jerome",
    "Saint Jerome",
    "09-30",
    "doctor_of_the_church",
    "canonized",
    ["biblical scholars", "translators", "librarians"],
    "Saint Jerome (c. 347-420), Doctor of the Church, was the greatest biblical scholar of the early Church, who translated the Scriptures into Latin to produce the Vulgate. A monk and ascetic who settled in Bethlehem, he wrote extensive commentaries and famously declared that 'ignorance of Scripture is ignorance of Christ.' He is the patron of biblical scholars.",
  ),
  saint(
    "saint-john-chrysostom",
    "Saint John Chrysostom",
    "09-13",
    "doctor_of_the_church",
    "canonized",
    ["preachers", "orators", "Constantinople"],
    "Saint John Chrysostom (c. 347-407), Archbishop of Constantinople and Doctor of the Church, was surnamed 'Golden-Mouthed' for his eloquent preaching. He called the faithful to charity and reform, denounced abuses of wealth and power, and gave his name to the principal Divine Liturgy of the Byzantine Church. He died in exile for his fearless witness.",
  ),
  saint(
    "saint-ambrose",
    "Saint Ambrose",
    "12-07",
    "doctor_of_the_church",
    "canonized",
    ["bees", "beekeepers", "learning"],
    "Saint Ambrose (c. 340-397), Bishop of Milan and Doctor of the Church, was a Roman governor acclaimed bishop by the people while still a catechumen. A powerful preacher whose words helped convert Saint Augustine, he defended the Church's freedom against imperial power and enriched the liturgy with hymns. He is one of the four great Latin Doctors.",
  ),
  saint(
    "saint-alphonsus-liguori",
    "Saint Alphonsus Liguori",
    "08-01",
    "doctor_of_the_church",
    "canonized",
    ["moral theologians", "confessors", "the scrupulous"],
    "Saint Alphonsus Liguori (1696-1787), Bishop and Doctor of the Church, abandoned a legal career to become a priest and founded the Redemptorists to preach to the poor and abandoned. A gentle confessor and the father of modern moral theology, he wrote enduring works of devotion such as The Glories of Mary. He was canonized in 1839.",
  ),
  saint(
    "saint-francis-de-sales",
    "Saint Francis de Sales",
    "01-24",
    "doctor_of_the_church",
    "canonized",
    ["writers", "journalists", "the deaf"],
    "Saint Francis de Sales (1567-1622), Bishop of Geneva and Doctor of the Church, won back many to the faith by his patience and gentleness. With Saint Jane Frances de Chantal he founded the Visitation Order, and his Introduction to the Devout Life taught that holiness is for every state of life. He is the patron of writers and the Catholic press.",
  ),
  saint(
    "saint-bonaventure",
    "Saint Bonaventure",
    "07-15",
    "doctor_of_the_church",
    "canonized",
    ["theologians", "Franciscans"],
    "Saint Bonaventure (c. 1217-1274), the 'Seraphic Doctor,' was a Franciscan theologian, minister general of his order, and cardinal. A friend of Saint Thomas Aquinas, he united deep learning with mystical devotion in works such as The Journey of the Mind to God and his life of Saint Francis. He helped reconcile the Greeks at the Council of Lyon, where he died.",
  ),
  saint(
    "saint-anselm",
    "Saint Anselm of Canterbury",
    "04-21",
    "doctor_of_the_church",
    "canonized",
    ["theologians", "philosophers"],
    "Saint Anselm of Canterbury (1033-1109), Doctor of the Church, was a Benedictine monk and Archbishop of Canterbury who is called the Father of Scholasticism. He sought 'faith seeking understanding' and is famous for the ontological argument for God's existence and for Cur Deus Homo, on the meaning of the Incarnation and redemption.",
  ),
  saint(
    "saint-leo-the-great",
    "Saint Leo the Great",
    "11-10",
    "pope",
    "canonized",
    ["the papacy", "against heresy"],
    "Saint Leo the Great (c. 400-461) was Pope and Doctor of the Church whose Tome clarified the Catholic faith in the two natures of Christ at the Council of Chalcedon in 451. He famously persuaded Attila the Hun to spare Rome and strengthened the authority and unity of the Church. He is one of only a few popes called 'the Great.'",
  ),
  saint(
    "saint-gregory-the-great",
    "Saint Gregory the Great",
    "09-03",
    "pope",
    "canonized",
    ["musicians", "singers", "teachers"],
    "Saint Gregory the Great (c. 540-604), Pope and Doctor of the Church, left the life of a monk to govern the Church through famine, plague, and invasion. He reformed the liturgy, sent missionaries to England, cared tirelessly for the poor, and wrote enduring works of pastoral wisdom. The Church honors him among the four great Latin Doctors.",
  ),
];
