import type { CuratedEntry } from "./index";

const VATICAN = "https://www.vatican.va/";
const NEWADVENT = "https://www.newadvent.org/cathen/";

function saint(
  slug: string,
  canonicalName: string,
  feastDay: string,
  saintType:
    | "martyr"
    | "doctor_of_the_church"
    | "virgin"
    | "confessor"
    | "religious"
    | "lay"
    | "bishop"
    | "pope"
    | "apostle"
    | "evangelist"
    | "founder"
    | "missionary"
    | "other",
  canonizationStatus: "canonized" | "beatified" | "venerable" | "servant_of_god",
  patronages: string[],
  biography: string,
): CuratedEntry {
  const [mm, dd] = feastDay.split("-").map((s) => parseInt(s, 10));
  return {
    contentType: "SAINT",
    slug,
    authorityLevel: "VATICAN",
    citations: [VATICAN, NEWADVENT],
    payload: {
      slug,
      canonicalName,
      feastDay,
      feastMonth: mm,
      feastDayOfMonth: dd,
      patronages,
      biography,
      saintType,
      canonizationStatus,
      relatedPrayers: [],
      relatedDevotions: [],
      citations: [VATICAN, NEWADVENT],
    },
  };
}

export const saintKnowledge: CuratedEntry[] = [
  saint(
    "saint-joseph",
    "Saint Joseph",
    "03-19",
    "confessor",
    "canonized",
    ["the universal Church", "workers", "fathers", "a happy death"],
    "Saint Joseph was the foster father of Jesus Christ and the chaste spouse of the Blessed Virgin Mary. A descendant of King David, he was a carpenter in Nazareth. The Gospels of Matthew and Luke record his obedience to the angel's messages and his protective care of the Holy Family. Pope Pius IX declared him patron of the universal Church in 1870. Pope Pius XII established the feast of St. Joseph the Worker on May 1 in 1955. Pope Francis added his name to all the Eucharistic Prayers of the Roman Missal in 2013.",
  ),
  saint(
    "saint-peter",
    "Saint Peter the Apostle",
    "06-29",
    "apostle",
    "canonized",
    ["the papacy", "fishermen", "Rome"],
    "Simon Peter was the brother of Andrew, a fisherman of Bethsaida. Jesus called him to be the first of the Twelve Apostles and renamed him Peter (Cephas, 'rock'), telling him: 'Upon this rock I will build my Church' (Matthew 16:18). After Pentecost he led the apostolic community, was the first bishop of Rome, and was martyred there during the persecution of Nero around AD 64. His tomb lies beneath the high altar of St. Peter's Basilica.",
  ),
  saint(
    "saint-paul",
    "Saint Paul the Apostle",
    "06-29",
    "apostle",
    "canonized",
    ["missionaries", "evangelists", "writers"],
    "Saul of Tarsus, a Pharisee and persecutor of the early Church, was converted on the road to Damascus by a vision of the risen Christ (Acts 9). Taking the name Paul, he became the Apostle to the Gentiles, founding churches throughout the eastern Mediterranean and writing the letters that form a large part of the New Testament. He was martyred in Rome around AD 67.",
  ),
  saint(
    "saint-john-the-baptist",
    "Saint John the Baptist",
    "06-24",
    "martyr",
    "canonized",
    ["converts", "monastic life", "Canada"],
    "Saint John the Baptist was the prophet of the Most High, kinsman of the Lord Jesus, and the immediate precursor of the Messiah. Born of Zechariah and Elizabeth, he preached repentance in the wilderness of Judea and baptized Jesus in the Jordan. Imprisoned and beheaded by Herod Antipas, Jesus said of him: 'Among those born of women there has risen no one greater than John the Baptist' (Matthew 11:11).",
  ),
  saint(
    "saint-mary-magdalene",
    "Saint Mary Magdalene",
    "07-22",
    "other",
    "canonized",
    ["converts", "penitents", "contemplative life"],
    "Saint Mary Magdalene, from whom the Lord cast out seven demons (Luke 8:2), followed Jesus and his disciples, stood beneath the Cross, and was the first witness of the Resurrection on Easter morning (John 20). The Church Fathers honor her as 'Apostle to the Apostles' for bringing the news of the risen Lord to the Twelve. Pope Francis raised her commemoration to the dignity of a feast in 2016.",
  ),
  saint(
    "saint-augustine-of-hippo",
    "Saint Augustine of Hippo",
    "08-28",
    "doctor_of_the_church",
    "canonized",
    ["theologians", "printers", "brewers"],
    "Saint Augustine (354-430) was bishop of Hippo Regius in Roman North Africa and one of the most important Latin Fathers of the Church. Born to St. Monica, he converted after years of intellectual searching, baptized by St. Ambrose in 387. His Confessions, City of God, and treatises on grace and the Trinity shaped Western Christian theology for the next 1600 years. Declared a Doctor of the Church.",
  ),
  saint(
    "saint-thomas-aquinas",
    "Saint Thomas Aquinas",
    "01-28",
    "doctor_of_the_church",
    "canonized",
    ["students", "universities", "philosophers", "Catholic schools"],
    "Saint Thomas Aquinas (1225-1274), a Dominican friar, was the greatest theologian of the High Middle Ages. His Summa Theologiae remains the most comprehensive synthesis of Christian doctrine. Pope Leo XIII (Aeterni Patris, 1879) made his thought normative for Catholic philosophy and theology. He is honored as the Angelic Doctor.",
  ),
  saint(
    "saint-francis-of-assisi",
    "Saint Francis of Assisi",
    "10-04",
    "founder",
    "canonized",
    ["Italy", "animals", "ecology", "merchants"],
    "Saint Francis of Assisi (1181/82-1226) founded the Order of Friars Minor (the Franciscans) after a dramatic conversion from the life of a wealthy merchant's son. Marked by literal imitation of the Gospel, embrace of holy poverty, devotion to the Eucharist and Mary, and tenderness toward all creation, he received the stigmata at La Verna in 1224 — the first recorded stigmatic in the Church.",
  ),
  saint(
    "saint-therese-of-lisieux",
    "Saint Therese of Lisieux",
    "10-01",
    "doctor_of_the_church",
    "canonized",
    ["missions", "florists", "France", "AIDS sufferers"],
    "Saint Therese of the Child Jesus and the Holy Face (1873-1897) was a Discalced Carmelite nun of Lisieux who died at twenty-four. Her autobiography, Story of a Soul, taught the 'Little Way' of trust and confidence in God's merciful love. Pope Pius XI canonized her in 1925, Pope Pius XI named her co-patroness of the missions, and Pope John Paul II declared her a Doctor of the Church in 1997.",
  ),
  saint(
    "saint-padre-pio",
    "Saint Padre Pio of Pietrelcina",
    "09-23",
    "confessor",
    "canonized",
    ["civil defense workers", "adolescents", "stress relief"],
    "Saint Pio of Pietrelcina (1887-1968), a Capuchin Franciscan friar, bore the visible stigmata for fifty years. Known for his long hours in the confessional, mystical gifts, and intense devotion to the Mass, he founded the Home for the Relief of Suffering hospital in San Giovanni Rotondo. Beatified by Pope John Paul II in 1999 and canonized in 2002.",
  ),
  saint(
    "saint-john-paul-ii",
    "Saint Pope John Paul II",
    "10-22",
    "pope",
    "canonized",
    ["young people", "families", "World Youth Day"],
    "Karol Józef Wojtyła (1920-2005) was elected Pope on 16 October 1978 — the first non-Italian Pope in 455 years and the first from Poland. His twenty-six-year pontificate witnessed the fall of communism in Eastern Europe, the establishment of World Youth Day, the publication of the Catechism of the Catholic Church, and the canonization of more saints than any pope before him. Canonized by Pope Francis in 2014.",
  ),
  saint(
    "saint-faustina-kowalska",
    "Saint Faustina Kowalska",
    "10-05",
    "religious",
    "canonized",
    ["mercy"],
    "Saint Maria Faustina Kowalska (1905-1938) was a Polish Sister of Our Lady of Mercy. The Lord Jesus entrusted her with the message of Divine Mercy, recorded in her Diary. Pope John Paul II canonized her in 2000 — the first saint of the new millennium — and established Divine Mercy Sunday for the universal Church.",
  ),
  saint(
    "saint-maximilian-kolbe",
    "Saint Maximilian Kolbe",
    "08-14",
    "martyr",
    "canonized",
    ["prisoners", "the pro-life movement", "drug addicts"],
    "Saint Maximilian Maria Kolbe (1894-1941) was a Polish Conventual Franciscan friar who founded the Militia Immaculatae (Knights of the Immaculata) and the Marian publishing apostolate at Niepokalanów. Imprisoned at Auschwitz, he volunteered to die in place of a stranger, Franciszek Gajowniczek, and was murdered with a phenol injection on 14 August 1941. Canonized as a martyr by Pope John Paul II in 1982.",
  ),
  saint(
    "saint-mother-teresa-of-calcutta",
    "Saint Mother Teresa of Calcutta",
    "09-05",
    "founder",
    "canonized",
    ["World Youth Day", "Missionaries of Charity"],
    "Saint Teresa of Calcutta (Anjezë Gonxhe Bojaxhiu, 1910-1997) was an Albanian-Indian Catholic nun who founded the Missionaries of Charity in 1950. The order serves 'the poorest of the poor' in over 130 countries. Awarded the Nobel Peace Prize in 1979. Beatified by Pope John Paul II in 2003 and canonized by Pope Francis in 2016.",
  ),
  saint(
    "saint-anthony-of-padua",
    "Saint Anthony of Padua",
    "06-13",
    "doctor_of_the_church",
    "canonized",
    ["lost things", "the poor", "Portugal"],
    "Saint Anthony of Padua (1195-1231), born Fernando Martins in Lisbon, joined the Franciscans and became one of the greatest preachers of the Middle Ages. Canonized within a year of his death by Pope Gregory IX. Declared a Doctor of the Church by Pope Pius XII in 1946. His tomb in Padua draws millions of pilgrims annually.",
  ),
  saint(
    "saint-patrick",
    "Saint Patrick",
    "03-17",
    "bishop",
    "canonized",
    ["Ireland", "Nigeria", "engineers"],
    "Saint Patrick (c. 385-461) was the apostle of Ireland. Born in Roman Britain, captured by Irish raiders as a teenager and enslaved for six years, he escaped, became a priest and bishop, and returned to evangelize Ireland. He used the shamrock to explain the Trinity. His Confessio and Letter to the Soldiers of Coroticus survive.",
  ),
  saint(
    "saint-benedict-of-nursia",
    "Saint Benedict of Nursia",
    "07-11",
    "founder",
    "canonized",
    ["Europe", "monastics", "students"],
    "Saint Benedict (c. 480-547) is the patriarch of Western monasticism. His Rule for monasteries — 'pray and work' — became the foundational document for monastic life in Europe and shaped Western Christian culture. Pope Paul VI named him patron of Europe in 1964.",
  ),
  saint(
    "saint-catherine-of-siena",
    "Saint Catherine of Siena",
    "04-29",
    "doctor_of_the_church",
    "canonized",
    ["Italy", "Europe", "nurses"],
    "Saint Catherine of Siena (1347-1380), a Dominican tertiary, was an influential mystic, theologian, and reformer who urged Pope Gregory XI to return the papacy from Avignon to Rome. Her Dialogue of Divine Providence is a masterpiece of mystical theology. Declared a Doctor of the Church by Pope Paul VI in 1970 and co-patroness of Europe by Pope John Paul II.",
  ),
  saint(
    "saint-ignatius-of-loyola",
    "Saint Ignatius of Loyola",
    "07-31",
    "founder",
    "canonized",
    ["soldiers", "retreats", "the Society of Jesus"],
    "Saint Ignatius of Loyola (1491-1556), Basque nobleman turned mystic and reformer, founded the Society of Jesus (the Jesuits) in 1540. His Spiritual Exercises, composed during his convalescence at Manresa, remain one of the most influential works of Western spirituality. Canonized in 1622.",
  ),
  saint(
    "saint-teresa-of-avila",
    "Saint Teresa of Avila",
    "10-15",
    "doctor_of_the_church",
    "canonized",
    ["Spain", "headache sufferers", "writers"],
    "Saint Teresa of Jesus (1515-1582), Discalced Carmelite reformer, mystic, and author of The Interior Castle and the Autobiography. With St. John of the Cross she renewed the Carmelite Order. Declared the first woman Doctor of the Church by Pope Paul VI in 1970.",
  ),
  saint(
    "saint-john-of-the-cross",
    "Saint John of the Cross",
    "12-14",
    "doctor_of_the_church",
    "canonized",
    ["mystics", "contemplative life", "Spanish poets"],
    "Saint John of the Cross (1542-1591), Discalced Carmelite priest, poet, and mystic. Co-founder with St. Teresa of Avila of the reformed Carmelite Order. Author of The Dark Night of the Soul, The Ascent of Mount Carmel, and The Spiritual Canticle. Declared a Doctor of the Church in 1926.",
  ),
  saint(
    "saint-andrew-the-apostle",
    "Saint Andrew the Apostle",
    "11-30",
    "apostle",
    "canonized",
    ["Scotland", "Greece", "fishermen"],
    "Saint Andrew, brother of Simon Peter and a fisherman of Bethsaida, was the first-called of the Apostles. After Pentecost he preached in Greece and Asia Minor and was martyred at Patras on an X-shaped cross, which bears his name. He is the patron of Scotland, Greece, and Russia.",
  ),
  saint(
    "saint-james-the-greater",
    "Saint James the Greater",
    "07-25",
    "apostle",
    "canonized",
    ["Spain", "pilgrims", "laborers"],
    "Saint James, son of Zebedee and brother of John, was one of the three apostles closest to Jesus. He was the first apostle to be martyred, beheaded by Herod Agrippa around AD 44 (Acts 12). His shrine at Santiago de Compostela in Spain has drawn pilgrims for over a thousand years.",
  ),
  saint(
    "saint-thomas-the-apostle",
    "Saint Thomas the Apostle",
    "07-03",
    "apostle",
    "canonized",
    ["India", "architects", "those who doubt"],
    "Saint Thomas, called Didymus, at first doubted the Resurrection but then confessed the risen Christ as 'My Lord and my God' (John 20:28). Tradition holds that he carried the Gospel to India, where the Saint Thomas Christians revere him as their founder, and was martyred near Chennai.",
  ),
  saint(
    "saint-matthew",
    "Saint Matthew",
    "09-21",
    "apostle",
    "canonized",
    ["accountants", "tax collectors", "bankers"],
    "Saint Matthew, also called Levi, was a tax collector whom Jesus called from his customs post to follow him (Matthew 9:9). One of the Twelve Apostles, he is traditionally honored as the author of the first Gospel, written for Jewish Christians.",
  ),
  saint(
    "saint-mark-the-evangelist",
    "Saint Mark the Evangelist",
    "04-25",
    "evangelist",
    "canonized",
    ["Venice", "notaries", "Egypt"],
    "Saint Mark, a companion of Saints Peter and Paul, wrote the second Gospel, drawing on Peter's preaching. Tradition holds that he founded the Church of Alexandria and was martyred there. His relics rest in the Basilica of San Marco in Venice, of which he is patron.",
  ),
  saint(
    "saint-luke-the-evangelist",
    "Saint Luke the Evangelist",
    "10-18",
    "evangelist",
    "canonized",
    ["physicians", "surgeons", "artists"],
    "Saint Luke, a physician and companion of Saint Paul, wrote the third Gospel and the Acts of the Apostles, preserving the infancy narratives and many parables found nowhere else. By tradition a painter of the Blessed Virgin, he is the patron of physicians and artists.",
  ),
  saint(
    "saint-stephen",
    "Saint Stephen",
    "12-26",
    "martyr",
    "canonized",
    ["deacons", "bricklayers"],
    "Saint Stephen, one of the seven deacons chosen by the Apostles, was the first martyr of the Church (the protomartyr). Filled with the Holy Spirit, he preached boldly and was stoned to death, praying for his persecutors as he died (Acts 6-7). Saul of Tarsus stood by, consenting.",
  ),
  saint(
    "saint-lawrence",
    "Saint Lawrence",
    "08-10",
    "martyr",
    "canonized",
    ["cooks", "the poor", "deacons"],
    "Saint Lawrence was a deacon of Rome martyred in 258 under Valerian. Charged to surrender the Church's treasures, he presented the poor, saying, 'These are the treasures of the Church.' Tradition holds he was martyred on a gridiron. He is honored among the most celebrated Roman martyrs.",
  ),
  saint(
    "saint-sebastian",
    "Saint Sebastian",
    "01-20",
    "martyr",
    "canonized",
    ["athletes", "soldiers", "archers"],
    "Saint Sebastian was a Roman soldier martyred under Diocletian around 288. Condemned to be shot with arrows for professing Christ, he survived and confronted the emperor before being killed. He is among the most venerated early martyrs and a patron of athletes and soldiers.",
  ),
  saint(
    "saint-agnes",
    "Saint Agnes",
    "01-21",
    "martyr",
    "canonized",
    ["young girls", "chastity", "the Children of Mary"],
    "Saint Agnes was a Roman virgin martyred about 304 at the age of twelve or thirteen for consecrating her virginity to Christ. One of the most honored of the early Roman martyrs, her name is in the Roman Canon, and lambs blessed on her feast provide wool for the pallium.",
  ),
  saint(
    "saint-cecilia",
    "Saint Cecilia",
    "11-22",
    "martyr",
    "canonized",
    ["musicians", "music", "poets"],
    "Saint Cecilia, a Roman virgin and martyr of the early Church, is honored as the patroness of music and musicians, traditionally said to have sung to God in her heart. Her name is included in the Roman Canon of the Mass.",
  ),
  saint(
    "saint-lucy",
    "Saint Lucy",
    "12-13",
    "martyr",
    "canonized",
    ["the blind", "eye disorders", "Sicily"],
    "Saint Lucy was a virgin of Syracuse in Sicily, martyred about 304 under Diocletian. Her name (Lucia, 'light') and her patronage of the blind have made her feast, near the winter solstice, a festival of light. Her name appears in the Roman Canon.",
  ),
  saint(
    "saint-nicholas",
    "Saint Nicholas",
    "12-06",
    "bishop",
    "canonized",
    ["children", "sailors", "the falsely accused"],
    "Saint Nicholas was the fourth-century Bishop of Myra in Asia Minor, renowned for his secret gifts to the poor and his defense of the faith. His generosity gave rise to the figure of Santa Claus. He is the patron of children, sailors, and many nations.",
  ),
  saint(
    "saint-monica",
    "Saint Monica",
    "08-27",
    "lay",
    "canonized",
    ["mothers", "wives", "victims of abuse"],
    "Saint Monica (331-387), mother of Saint Augustine, prayed and wept for years for the conversion of her wayward son, who was baptized by Saint Ambrose in 387. A model of Christian motherhood and persevering prayer, she died at Ostia as she and Augustine journeyed home.",
  ),
  saint(
    "saint-dominic",
    "Saint Dominic",
    "08-08",
    "founder",
    "canonized",
    ["astronomers", "preachers", "the Dominican Republic"],
    "Saint Dominic de Guzmán (1170-1221) founded the Order of Preachers (the Dominicans) to combat heresy and preach the Gospel with learning and poverty. Devotion to the Rosary is closely associated with him and his order.",
  ),
  saint(
    "saint-clare-of-assisi",
    "Saint Clare of Assisi",
    "08-11",
    "founder",
    "canonized",
    ["television", "eye disease", "the Poor Clares"],
    "Saint Clare of Assisi (1194-1253), inspired by Saint Francis, left her noble family to embrace radical poverty and founded the Order of Poor Ladies (the Poor Clares). She defended her sisters and her city through prayer before the Blessed Sacrament.",
  ),
  saint(
    "saint-vincent-de-paul",
    "Saint Vincent de Paul",
    "09-27",
    "founder",
    "canonized",
    ["charitable societies", "the poor", "hospitals"],
    "Saint Vincent de Paul (1581-1660) devoted his life to the poor, founding the Congregation of the Mission (the Vincentians) and, with Saint Louise de Marillac, the Daughters of Charity. He is the patron of all works of Christian charity.",
  ),
  saint(
    "saint-philip-neri",
    "Saint Philip Neri",
    "05-26",
    "founder",
    "canonized",
    ["Rome", "joy", "the Oratory"],
    "Saint Philip Neri (1515-1595), the 'Apostle of Rome,' founded the Congregation of the Oratory and renewed the faith of the city through joy, confession, and prayer. Famous for his humor and holiness, he drew countless souls back to God.",
  ),
  saint(
    "saint-john-bosco",
    "Saint John Bosco",
    "01-31",
    "founder",
    "canonized",
    ["youth", "editors", "apprentices"],
    "Saint John Bosco (1815-1888), known as Don Bosco, devoted his life to poor and abandoned boys in Turin, founding the Salesians and, with Saint Mary Mazzarello, the Salesian Sisters. His 'preventive system' of education rested on reason, religion, and loving-kindness.",
  ),
  saint(
    "saint-joan-of-arc",
    "Saint Joan of Arc",
    "05-30",
    "martyr",
    "canonized",
    ["France", "soldiers", "captives"],
    "Saint Joan of Arc (1412-1431), the Maid of Orléans, was a peasant girl who, led by heavenly voices, rallied the French army during the Hundred Years' War. Captured and tried by an ecclesiastical court under English control, she was burned at the stake at nineteen and later fully vindicated. Canonized in 1920, she is a patroness of France.",
  ),
  saint(
    "saint-rita-of-cascia",
    "Saint Rita of Cascia",
    "05-22",
    "religious",
    "canonized",
    ["impossible causes", "difficult marriages", "parenthood"],
    "Saint Rita of Cascia (1381-1457), after a difficult marriage and the loss of her husband and sons, became an Augustinian nun. Renowned for her penance and a wound she received from the crown of thorns, she is invoked as the patroness of impossible and desperate causes.",
  ),
  saint(
    "saint-martin-de-porres",
    "Saint Martin de Porres",
    "11-03",
    "religious",
    "canonized",
    ["social justice", "mixed-race people", "barbers"],
    "Saint Martin de Porres (1579-1639) of Lima, Peru, a Dominican lay brother of mixed Spanish and African descent, served the sick and poor with heroic charity and was known for miracles and care of animals. Canonized in 1962, he is a patron of social justice.",
  ),
  saint(
    "saint-rose-of-lima",
    "Saint Rose of Lima",
    "08-23",
    "religious",
    "canonized",
    ["Latin America", "the Philippines", "gardeners"],
    "Saint Rose of Lima (1586-1617), a Dominican tertiary of Peru, lived a life of intense penance and care for the poor and indigenous of Lima. In 1671 she became the first canonized saint of the Americas.",
  ),
  saint(
    "saint-elizabeth-ann-seton",
    "Saint Elizabeth Ann Seton",
    "01-04",
    "founder",
    "canonized",
    ["Catholic schools", "widows", "the United States"],
    "Saint Elizabeth Ann Seton (1774-1821), a convert and widow, founded the Sisters of Charity and the first Catholic parochial school system in the United States. In 1975 she became the first native-born citizen of the United States to be canonized.",
  ),
  saint(
    "saint-juan-diego",
    "Saint Juan Diego",
    "12-09",
    "lay",
    "canonized",
    ["indigenous peoples", "the Americas"],
    "Saint Juan Diego (1474-1548) was the humble Aztec convert to whom the Blessed Virgin Mary appeared at Tepeyac in 1531 as Our Lady of Guadalupe, leaving her image on his tilma. Canonized in 2002, he is honored as a model of humility and faith.",
  ),
  saint(
    "saint-jude-thaddeus",
    "Saint Jude Thaddeus",
    "10-28",
    "apostle",
    "canonized",
    ["desperate situations", "hopeless causes", "hospitals"],
    "Saint Jude Thaddeus was one of the Twelve Apostles, traditionally identified as a relative of the Lord. He preached the Gospel in Judea, Mesopotamia, and Persia, where he was martyred with the Apostle Simon. He is universally invoked as the patron of desperate and hopeless causes.",
  ),
  saint(
    "saint-bartholomew",
    "Saint Bartholomew the Apostle",
    "08-24",
    "apostle",
    "canonized",
    ["tanners", "plasterers"],
    "Saint Bartholomew, often identified with Nathanael in the Gospel of John, was one of the Twelve Apostles. Tradition holds that he carried the Gospel to Armenia, where he was flayed and beheaded for the faith. His relics are venerated in Rome on the Tiber Island.",
  ),
  saint(
    "saint-matthias",
    "Saint Matthias the Apostle",
    "05-14",
    "apostle",
    "canonized",
    ["carpenters", "perseverance"],
    "Saint Matthias was chosen by the eleven Apostles, by the casting of lots after prayer, to take the place of Judas Iscariot among the Twelve (Acts 1:15-26). Having been a disciple of the Lord from the baptism of John, he preached the Gospel and, by tradition, was martyred for the faith.",
  ),
  saint(
    "saint-barnabas",
    "Saint Barnabas the Apostle",
    "06-11",
    "apostle",
    "canonized",
    ["Cyprus", "peacemakers"],
    "Saint Barnabas, a Levite of Cyprus, was surnamed Barnabas ('son of encouragement') by the Apostles. He introduced the newly converted Saul to the disciples and accompanied Saint Paul on his first missionary journey. Venerated as an apostle, tradition holds he was martyred at Salamis on Cyprus.",
  ),
  saint(
    "saint-john-vianney",
    "Saint John Vianney",
    "08-04",
    "confessor",
    "canonized",
    ["parish priests"],
    "Saint John Marie Vianney (1786-1859), the Curé of Ars, was a French parish priest renowned for his holiness, his long hours in the confessional, and his pastoral zeal. Pope Pius XI canonized him in 1925 and declared him the patron of parish priests.",
  ),
  saint(
    "saint-ignatius-of-antioch",
    "Saint Ignatius of Antioch",
    "10-17",
    "martyr",
    "canonized",
    ["the Church in the East"],
    "Saint Ignatius (c. 35-c. 108), bishop of Antioch and a disciple of the Apostles, was condemned to the beasts at Rome under the Emperor Trajan. On the journey to martyrdom he wrote seven letters that are among the earliest witnesses to the Eucharist, the episcopacy, and the unity of the Church.",
  ),
  saint(
    "saint-polycarp",
    "Saint Polycarp of Smyrna",
    "02-23",
    "martyr",
    "canonized",
    ["against earache"],
    "Saint Polycarp (c. 69-c. 155), bishop of Smyrna, was a disciple of Saint John the Apostle and a link between the apostolic age and the early Fathers. Arrested in old age, he refused to renounce Christ, saying, 'Eighty-six years I have served him, and he has done me no wrong,' and was burned at the stake.",
  ),
  saint(
    "saint-george",
    "Saint George",
    "04-23",
    "martyr",
    "canonized",
    ["England", "soldiers", "scouts"],
    "Saint George (died c. 303) was a soldier in the Roman army martyred for his faith under the Emperor Diocletian. Venerated since antiquity in both East and West, he is celebrated in legend for slaying a dragon and is the patron of England, soldiers, and many nations.",
  ),
  saint(
    "saint-blaise",
    "Saint Blaise",
    "02-03",
    "bishop",
    "canonized",
    ["throat ailments", "wool combers"],
    "Saint Blaise (died c. 316), bishop of Sebaste in Armenia, was martyred during the persecutions of the early fourth century. He is remembered for miraculously saving a boy choking on a fishbone, and the Church blesses throats on his feast with two crossed candles.",
  ),
  saint(
    "saint-agatha",
    "Saint Agatha",
    "02-05",
    "virgin",
    "canonized",
    ["breast cancer patients", "Sicily", "against fire"],
    "Saint Agatha (died c. 251) was a young woman of Sicily who consecrated her virginity to Christ and suffered a cruel martyrdom under the persecution of Decius rather than renounce her faith. One of the most venerated virgin martyrs of antiquity, her name is named in the Roman Canon of the Mass.",
  ),
  saint(
    "saint-maria-goretti",
    "Saint Maria Goretti",
    "07-06",
    "virgin",
    "canonized",
    ["youth", "purity", "victims of assault"],
    "Saint Maria Goretti (1890-1902) was an Italian peasant girl who, at the age of eleven, was fatally stabbed while resisting an assault and who forgave her attacker before she died. Canonized in 1950 by Pope Pius XII, she is honored as a martyr of purity and a model for the young.",
  ),
  saint(
    "saint-bernadette-soubirous",
    "Saint Bernadette Soubirous",
    "04-16",
    "virgin",
    "canonized",
    ["the sick", "shepherds", "Lourdes"],
    "Saint Bernadette Soubirous (1844-1879) was the humble French girl to whom the Blessed Virgin Mary appeared eighteen times at Lourdes in 1858, identifying herself as the Immaculate Conception. She later became a Sister of Charity at Nevers, where she died; her body remains incorrupt.",
  ),
  saint(
    "saint-josephine-bakhita",
    "Saint Josephine Bakhita",
    "02-08",
    "religious",
    "canonized",
    ["Sudan", "victims of human trafficking"],
    "Saint Josephine Bakhita (c. 1869-1947) was born in Darfur, kidnapped and sold into slavery as a child, and eventually freed in Italy, where she became a Canossian Sister. Canonized in 2000, she is a witness to forgiveness and a patron of victims of human trafficking.",
  ),
  saint(
    "saint-kateri-tekakwitha",
    "Saint Kateri Tekakwitha",
    "07-14",
    "virgin",
    "canonized",
    ["ecology", "indigenous peoples", "the environment"],
    "Saint Kateri Tekakwitha (1656-1680), the 'Lily of the Mohawks,' was a Mohawk-Algonquin woman of present-day New York who embraced the Catholic faith and consecrated her virginity to Christ amid great opposition. Canonized in 2012, she is the first Native American saint.",
  ),
  saint(
    "saint-frances-xavier-cabrini",
    "Saint Frances Xavier Cabrini",
    "11-13",
    "religious",
    "canonized",
    ["immigrants", "hospital administrators"],
    "Saint Frances Xavier Cabrini (1850-1917), foundress of the Missionary Sisters of the Sacred Heart of Jesus, emigrated from Italy to the United States and established schools, hospitals, and orphanages for immigrants. Canonized in 1946, she was the first United States citizen to be canonized.",
  ),
  saint(
    "saint-katharine-drexel",
    "Saint Katharine Drexel",
    "03-03",
    "religious",
    "canonized",
    ["racial justice", "philanthropists"],
    "Saint Katharine Drexel (1858-1955), heiress of a wealthy Philadelphia family, gave her fortune to found the Sisters of the Blessed Sacrament and to establish schools and missions for Native Americans and African Americans, including Xavier University in New Orleans. She was canonized in 2000.",
  ),
  saint(
    "saint-damien-of-molokai",
    "Saint Damien of Molokai",
    "05-10",
    "religious",
    "canonized",
    ["lepers", "outcasts"],
    "Saint Damien of Molokai (1840-1889), a Belgian priest of the Congregation of the Sacred Hearts, ministered to the abandoned lepers of the Hawaiian island of Molokai, eventually contracting and dying of the disease himself. Canonized in 2009, he is a patron of those afflicted with leprosy.",
  ),
  saint(
    "saint-francis-xavier",
    "Saint Francis Xavier",
    "12-03",
    "missionary",
    "canonized",
    ["missions", "navigators"],
    "Saint Francis Xavier (1506-1552), one of the first companions of Saint Ignatius of Loyola and a co-founder of the Society of Jesus, was the great missionary to India, the East Indies, and Japan, baptizing tens of thousands. He died off the coast of China and is honored as patron of the missions.",
  ),
  saint(
    "saint-aloysius-gonzaga",
    "Saint Aloysius Gonzaga",
    "06-21",
    "religious",
    "canonized",
    ["youth", "students"],
    "Saint Aloysius Gonzaga (1568-1591), an Italian nobleman who renounced his inheritance to enter the Society of Jesus, died at the age of twenty-three after contracting plague while nursing the sick in Rome. Canonized in 1726, he is a patron of Catholic youth and students.",
  ),
  saint(
    "saint-charles-borromeo",
    "Saint Charles Borromeo",
    "11-04",
    "bishop",
    "canonized",
    ["bishops", "catechists", "seminarians"],
    "Saint Charles Borromeo (1538-1584), Cardinal Archbishop of Milan, was a leading reformer who implemented the Council of Trent, founded seminaries, promoted catechesis, and served his people heroically during the plague of 1576. Canonized in 1610, he is a patron of bishops and catechists.",
  ),
  saint(
    "saint-john-neumann",
    "Saint John Neumann",
    "01-05",
    "bishop",
    "canonized",
    ["Catholic education", "immigrants"],
    "Saint John Neumann (1811-1860), a Redemptorist and the fourth bishop of Philadelphia, organized the first diocesan system of Catholic schools in the United States. Canonized in 1977, he was the first American bishop to be raised to the altars.",
  ),
  saint(
    "saint-helena",
    "Saint Helena",
    "08-18",
    "lay",
    "canonized",
    ["archaeologists", "converts"],
    "Saint Helena (c. 248-c. 330), mother of the Emperor Constantine, was a devout convert who, in her old age, made a pilgrimage to the Holy Land, where tradition holds she discovered the True Cross of Christ. She built churches on the holy sites and is venerated for her piety and charity.",
  ),
  saint(
    "saint-elizabeth-of-hungary",
    "Saint Elizabeth of Hungary",
    "11-17",
    "lay",
    "canonized",
    ["the poor", "widows", "Third Order Franciscans"],
    "Saint Elizabeth of Hungary (1207-1231), a princess and wife of the Landgrave of Thuringia, devoted herself after her husband's death to Franciscan poverty and the care of the sick and the poor, founding a hospital where she served personally. She was canonized in 1235.",
  ),
  saint(
    "saint-gianna-molla",
    "Saint Gianna Beretta Molla",
    "04-28",
    "lay",
    "canonized",
    ["mothers", "physicians", "the unborn"],
    "Saint Gianna Beretta Molla (1922-1962) was an Italian pediatrician, wife, and mother who, during her fourth pregnancy, refused procedures that would have ended her child's life and died shortly after the birth. Canonized in 2004, she is a patron of mothers, physicians, and the unborn.",
  ),
  saint(
    "saint-oscar-romero",
    "Saint Oscar Romero",
    "03-24",
    "martyr",
    "canonized",
    ["El Salvador", "persecuted Christians"],
    "Saint Oscar Romero (1917-1980), Archbishop of San Salvador, was a courageous defender of the poor and an outspoken voice against violence and injustice, who was assassinated while celebrating Mass. Canonized in 2018, he is honored as a martyr for the faith.",
  ),
  saint(
    "saint-perpetua-and-felicity",
    "Saints Perpetua and Felicity",
    "03-07",
    "martyr",
    "canonized",
    ["mothers", "expectant mothers"],
    "Saints Perpetua, a young noblewoman, and Felicity, her slave, were martyred together at Carthage in AD 203 during the persecution of Septimius Severus. Perpetua's prison diary is one of the earliest Christian texts written by a woman; their names are included in the Roman Canon of the Mass.",
  ),
  saint(
    "saint-justin-martyr",
    "Saint Justin Martyr",
    "06-01",
    "martyr",
    "canonized",
    ["philosophers", "apologists"],
    "Saint Justin (c. 100-c. 165) was a philosopher who, converting to Christianity, became the first great Christian apologist, defending the faith before the Roman authorities. His First Apology gives the earliest detailed description of the Sunday Eucharist. He was beheaded at Rome with several companions.",
  ),
  saint(
    "saint-cyprian-of-carthage",
    "Saint Cyprian of Carthage",
    "09-16",
    "martyr",
    "canonized",
    ["North Africa"],
    "Saint Cyprian (c. 210-258), bishop of Carthage and a Father of the Church, guided his people through persecution and controversy over the lapsed, writing influential treatises on the unity of the Church. He was martyred under the Emperor Valerian and is commemorated with Pope St. Cornelius.",
  ),
  saint(
    "saint-thomas-becket",
    "Saint Thomas Becket",
    "12-29",
    "martyr",
    "canonized",
    ["clergy", "against the abuse of power"],
    "Saint Thomas Becket (1118-1170), Archbishop of Canterbury, defended the liberty of the Church against King Henry II of England and was murdered by the king's knights in his own cathedral. Canonized in 1173, his shrine became one of the great pilgrimage destinations of medieval Europe.",
  ),
  saint(
    "saint-thomas-more",
    "Saint Thomas More",
    "06-22",
    "martyr",
    "canonized",
    ["statesmen", "lawyers", "politicians"],
    "Saint Thomas More (1478-1535), Lord Chancellor of England and author of Utopia, refused to acknowledge King Henry VIII as head of the Church in England and was beheaded for his fidelity to the pope and his conscience. Canonized in 1935, he is a patron of statesmen and lawyers.",
  ),
  saint(
    "saint-john-fisher",
    "Saint John Fisher",
    "06-22",
    "martyr",
    "canonized",
    ["bishops"],
    "Saint John Fisher (1469-1535), Bishop of Rochester and a renowned theologian, was the only English bishop to refuse the Oath of Supremacy under King Henry VIII, and was beheaded for it. Canonized in 1935, he is commemorated with his friend St. Thomas More.",
  ),
  saint(
    "saint-isidore-the-farmer",
    "Saint Isidore the Farmer",
    "05-15",
    "lay",
    "canonized",
    ["farmers", "laborers", "rural communities"],
    "Saint Isidore (c. 1070-1130) was a humble farm laborer near Madrid who, with his wife Maria, lived a life of prayer, hard work, and charity to the poor. Renowned for miracles, he was canonized in 1622 and is the patron of farmers and rural life.",
  ),
  saint(
    "saint-john-of-god",
    "Saint John of God",
    "03-08",
    "founder",
    "canonized",
    ["the sick", "hospitals", "nurses"],
    "Saint John of God (1495-1550), after a dramatic conversion in Granada, devoted his life to caring for the sick and the poor, founding the Brothers Hospitallers. Canonized in 1690, he is a patron of hospitals, nurses, and the dying.",
  ),
  saint(
    "saint-camillus-de-lellis",
    "Saint Camillus de Lellis",
    "07-18",
    "founder",
    "canonized",
    ["the sick", "nurses", "hospitals"],
    "Saint Camillus de Lellis (1550-1614), a former soldier and gambler, converted and founded the Camillians (the Ministers of the Sick) to care for the sick and dying with great tenderness. Canonized in 1746, he is a patron of the sick, nurses, and hospitals.",
  ),
  saint(
    "saint-bridget-of-sweden",
    "Saint Bridget of Sweden",
    "07-23",
    "founder",
    "canonized",
    ["Sweden", "Europe", "widows"],
    "Saint Bridget of Sweden (1303-1373), a noblewoman, wife, and mother, received celebrated mystical revelations and founded the Bridgettine Order. Canonized in 1391, she is a co-patroness of Europe.",
  ),
  saint(
    "saint-catherine-laboure",
    "Saint Catherine Labouré",
    "11-28",
    "religious",
    "canonized",
    ["the elderly"],
    "Saint Catherine Labouré (1806-1876), a Daughter of Charity in Paris, received the apparitions of the Blessed Virgin in 1830 that gave the Church the Miraculous Medal. She lived the rest of her life in hidden humility; canonized in 1947, her body remains incorrupt.",
  ),
  saint(
    "saint-margaret-mary-alacoque",
    "Saint Margaret Mary Alacoque",
    "10-16",
    "religious",
    "canonized",
    ["devotees of the Sacred Heart"],
    "Saint Margaret Mary Alacoque (1647-1690), a Visitation nun at Paray-le-Monial, received the revelations of the Sacred Heart of Jesus that spread the devotion and the Nine First Fridays throughout the Church. She was canonized in 1920.",
  ),
  saint(
    "saint-andre-bessette",
    "Saint André Bessette",
    "01-06",
    "religious",
    "canonized",
    ["the sick", "Montreal"],
    "Saint André Bessette (1845-1937), a humble Holy Cross brother and doorkeeper in Montreal, became renowned for his devotion to Saint Joseph and the countless healings attributed to his intercession. He inspired the building of Saint Joseph's Oratory and was canonized in 2010.",
  ),
  saint(
    "saint-anthony-mary-claret",
    "Saint Anthony Mary Claret",
    "10-24",
    "bishop",
    "canonized",
    ["weavers", "Catholic press"],
    "Saint Anthony Mary Claret (1807-1870), Archbishop of Santiago de Cuba and founder of the Claretian Missionaries, was a tireless preacher and writer. Canonized in 1950, he is honored for his missionary zeal and promotion of the Catholic press.",
  ),
  saint(
    "saint-paul-of-the-cross",
    "Saint Paul of the Cross",
    "10-19",
    "founder",
    "canonized",
    ["preachers"],
    "Saint Paul of the Cross (1694-1775) founded the Passionists, devoted to keeping alive the memory of the Passion of Christ. A great mystic and preacher of missions, he was canonized in 1867.",
  ),
  saint(
    "saint-teresa-benedicta-of-the-cross",
    "Saint Teresa Benedicta of the Cross (Edith Stein)",
    "08-09",
    "martyr",
    "canonized",
    ["Europe", "converts", "martyrs"],
    "Saint Teresa Benedicta of the Cross (Edith Stein, 1891-1942), a Jewish philosopher who converted to Catholicism and became a Discalced Carmelite nun, was killed at Auschwitz. Canonized in 1998, she is a co-patroness of Europe and a witness against the horrors of the twentieth century.",
  ),
  saint(
    "saint-josemaria-escriva",
    "Saint Josemaría Escrivá",
    "06-26",
    "founder",
    "canonized",
    ["ordinary work", "the laity"],
    "Saint Josemaría Escrivá (1902-1975), a Spanish priest, founded Opus Dei to spread the call to holiness in ordinary work and daily life. Canonized in 2002, he taught that the sanctification of work is at the heart of the Christian vocation.",
  ),
  saint(
    "saint-john-baptist-de-la-salle",
    "Saint John Baptist de la Salle",
    "04-07",
    "founder",
    "canonized",
    ["teachers", "educators"],
    "Saint John Baptist de la Salle (1651-1719), a French priest, founded the Brothers of the Christian Schools and pioneered methods of education for the poor. Canonized in 1900, he is the patron of teachers.",
  ),
  saint(
    "saint-peter-claver",
    "Saint Peter Claver",
    "09-09",
    "missionary",
    "canonized",
    ["enslaved peoples", "racial justice", "Colombia"],
    "Saint Peter Claver (1580-1654), a Spanish Jesuit at Cartagena, devoted forty years to the bodily and spiritual care of the enslaved Africans arriving in the New World, baptizing some three hundred thousand. Canonized in 1888, he called himself 'the slave of the slaves.'",
  ),
  saint(
    "saint-turibius-of-mogrovejo",
    "Saint Turibius of Mogrovejo",
    "03-23",
    "bishop",
    "canonized",
    ["Latin American bishops", "Peru"],
    "Saint Turibius of Mogrovejo (1538-1606), Archbishop of Lima, was a tireless reformer and defender of the indigenous peoples of Peru, confirming and catechizing across vast territories. Canonized in 1726, he is a patron of the bishops of Latin America.",
  ),
  saint(
    "saint-louis-de-montfort",
    "Saint Louis de Montfort",
    "04-28",
    "founder",
    "canonized",
    ["preachers", "Marian devotion"],
    "Saint Louis de Montfort (1673-1716), a French priest and preacher, wrote 'True Devotion to the Blessed Virgin Mary,' which shaped modern Marian spirituality and the practice of total consecration to Jesus through Mary. He was canonized in 1947.",
  ),
  saint(
    "saint-wenceslaus",
    "Saint Wenceslaus",
    "09-28",
    "martyr",
    "canonized",
    ["the Czech people", "Bohemia"],
    "Saint Wenceslaus (c. 907-935), Duke of Bohemia, was a just and devout ruler murdered by his brother for the faith. Honored as the patron and heavenly protector of the Czech nation, he is the 'Good King Wenceslas' of the Christmas carol.",
  ),
  saint(
    "saint-casimir",
    "Saint Casimir",
    "03-04",
    "lay",
    "canonized",
    ["Poland", "Lithuania", "young people"],
    "Saint Casimir (1458-1484), a prince of Poland and Lithuania, lived a short life marked by prayer, chastity, and devotion to the Blessed Virgin and the poor, refusing a throne won by unjust war. Canonized in 1521, he is a patron of Poland and Lithuania.",
  ),
  saint(
    "saint-bruno",
    "Saint Bruno",
    "10-06",
    "founder",
    "canonized",
    ["Carthusians"],
    "Saint Bruno (c. 1030-1101), a renowned teacher at Reims, withdrew to the mountains of the Chartreuse and founded the Carthusian Order, devoted to silence, solitude, and contemplation. His feast is kept on October 6.",
  ),
  saint(
    "saint-norbert",
    "Saint Norbert",
    "06-06",
    "founder",
    "canonized",
    ["Magdeburg"],
    "Saint Norbert (c. 1080-1134), after a worldly youth and sudden conversion, founded the Premonstratensian Canons (Norbertines) and became Archbishop of Magdeburg, promoting reform of the clergy and devotion to the Blessed Sacrament. He was canonized in 1582.",
  ),
];
