import type { CuratedEntry } from "./index";

const VATICAN = "https://www.vatican.va/";
const NEWADVENT = "https://www.newadvent.org/cathen/";

function saint(
  slug: string,
  canonicalName: string,
  feastDay: string,
  saintType:
    | "martyr"
    | "doctor_of_the_church"
    | "virgin"
    | "confessor"
    | "religious"
    | "lay"
    | "bishop"
    | "pope"
    | "apostle"
    | "evangelist"
    | "founder"
    | "missionary"
    | "other",
  canonizationStatus: "canonized" | "beatified" | "venerable" | "servant_of_god",
  patronages: string[],
  biography: string,
): CuratedEntry {
  const [mm, dd] = feastDay.split("-").map((s) => parseInt(s, 10));
  return {
    contentType: "SAINT",
    slug,
    authorityLevel: "VATICAN",
    citations: [VATICAN, NEWADVENT],
    payload: {
      slug,
      canonicalName,
      feastDay,
      feastMonth: mm,
      feastDayOfMonth: dd,
      patronages,
      biography,
      saintType,
      canonizationStatus,
      relatedPrayers: [],
      relatedDevotions: [],
      citations: [VATICAN, NEWADVENT],
    },
  };
}

export const saintKnowledge: CuratedEntry[] = [
  saint(
    "saint-joseph",
    "Saint Joseph",
    "03-19",
    "confessor",
    "canonized",
    ["the universal Church", "workers", "fathers", "a happy death"],
    "Saint Joseph was the foster father of Jesus Christ and the chaste spouse of the Blessed Virgin Mary. A descendant of King David, he was a carpenter in Nazareth. The Gospels of Matthew and Luke record his obedience to the angel's messages and his protective care of the Holy Family. Pope Pius IX declared him patron of the universal Church in 1870. Pope Pius XII established the feast of St. Joseph the Worker on May 1 in 1955. Pope Francis added his name to all the Eucharistic Prayers of the Roman Missal in 2013.",
  ),
  saint(
    "saint-peter",
    "Saint Peter the Apostle",
    "06-29",
    "apostle",
    "canonized",
    ["the papacy", "fishermen", "Rome"],
    "Simon Peter was the brother of Andrew, a fisherman of Bethsaida. Jesus called him to be the first of the Twelve Apostles and renamed him Peter (Cephas, 'rock'), telling him: 'Upon this rock I will build my Church' (Matthew 16:18). After Pentecost he led the apostolic community, was the first bishop of Rome, and was martyred there during the persecution of Nero around AD 64. His tomb lies beneath the high altar of St. Peter's Basilica.",
  ),
  saint(
    "saint-paul",
    "Saint Paul the Apostle",
    "06-29",
    "apostle",
    "canonized",
    ["missionaries", "evangelists", "writers"],
    "Saul of Tarsus, a Pharisee and persecutor of the early Church, was converted on the road to Damascus by a vision of the risen Christ (Acts 9). Taking the name Paul, he became the Apostle to the Gentiles, founding churches throughout the eastern Mediterranean and writing the letters that form a large part of the New Testament. He was martyred in Rome around AD 67.",
  ),
  saint(
    "saint-john-the-baptist",
    "Saint John the Baptist",
    "06-24",
    "martyr",
    "canonized",
    ["converts", "monastic life", "Canada"],
    "Saint John the Baptist was the prophet of the Most High, kinsman of the Lord Jesus, and the immediate precursor of the Messiah. Born of Zechariah and Elizabeth, he preached repentance in the wilderness of Judea and baptized Jesus in the Jordan. Imprisoned and beheaded by Herod Antipas, Jesus said of him: 'Among those born of women there has risen no one greater than John the Baptist' (Matthew 11:11).",
  ),
  saint(
    "saint-mary-magdalene",
    "Saint Mary Magdalene",
    "07-22",
    "other",
    "canonized",
    ["converts", "penitents", "contemplative life"],
    "Saint Mary Magdalene, from whom the Lord cast out seven demons (Luke 8:2), followed Jesus and his disciples, stood beneath the Cross, and was the first witness of the Resurrection on Easter morning (John 20). The Church Fathers honor her as 'Apostle to the Apostles' for bringing the news of the risen Lord to the Twelve. Pope Francis raised her commemoration to the dignity of a feast in 2016.",
  ),
  saint(
    "saint-augustine-of-hippo",
    "Saint Augustine of Hippo",
    "08-28",
    "doctor_of_the_church",
    "canonized",
    ["theologians", "printers", "brewers"],
    "Saint Augustine (354-430) was bishop of Hippo Regius in Roman North Africa and one of the most important Latin Fathers of the Church. Born to St. Monica, he converted after years of intellectual searching, baptized by St. Ambrose in 387. His Confessions, City of God, and treatises on grace and the Trinity shaped Western Christian theology for the next 1600 years. Declared a Doctor of the Church.",
  ),
  saint(
    "saint-thomas-aquinas",
    "Saint Thomas Aquinas",
    "01-28",
    "doctor_of_the_church",
    "canonized",
    ["students", "universities", "philosophers", "Catholic schools"],
    "Saint Thomas Aquinas (1225-1274), a Dominican friar, was the greatest theologian of the High Middle Ages. His Summa Theologiae remains the most comprehensive synthesis of Christian doctrine. Pope Leo XIII (Aeterni Patris, 1879) made his thought normative for Catholic philosophy and theology. He is honored as the Angelic Doctor.",
  ),
  saint(
    "saint-francis-of-assisi",
    "Saint Francis of Assisi",
    "10-04",
    "founder",
    "canonized",
    ["Italy", "animals", "ecology", "merchants"],
    "Saint Francis of Assisi (1181/82-1226) founded the Order of Friars Minor (the Franciscans) after a dramatic conversion from the life of a wealthy merchant's son. Marked by literal imitation of the Gospel, embrace of holy poverty, devotion to the Eucharist and Mary, and tenderness toward all creation, he received the stigmata at La Verna in 1224 — the first recorded stigmatic in the Church.",
  ),
  saint(
    "saint-therese-of-lisieux",
    "Saint Therese of Lisieux",
    "10-01",
    "doctor_of_the_church",
    "canonized",
    ["missions", "florists", "France", "AIDS sufferers"],
    "Saint Therese of the Child Jesus and the Holy Face (1873-1897) was a Discalced Carmelite nun of Lisieux who died at twenty-four. Her autobiography, Story of a Soul, taught the 'Little Way' of trust and confidence in God's merciful love. Pope Pius XI canonized her in 1925, Pope Pius XI named her co-patroness of the missions, and Pope John Paul II declared her a Doctor of the Church in 1997.",
  ),
  saint(
    "saint-padre-pio",
    "Saint Padre Pio of Pietrelcina",
    "09-23",
    "confessor",
    "canonized",
    ["civil defense workers", "adolescents", "stress relief"],
    "Saint Pio of Pietrelcina (1887-1968), a Capuchin Franciscan friar, bore the visible stigmata for fifty years. Known for his long hours in the confessional, mystical gifts, and intense devotion to the Mass, he founded the Home for the Relief of Suffering hospital in San Giovanni Rotondo. Beatified by Pope John Paul II in 1999 and canonized in 2002.",
  ),
  saint(
    "saint-john-paul-ii",
    "Saint Pope John Paul II",
    "10-22",
    "pope",
    "canonized",
    ["young people", "families", "World Youth Day"],
    "Karol Józef Wojtyła (1920-2005) was elected Pope on 16 October 1978 — the first non-Italian Pope in 455 years and the first from Poland. His twenty-six-year pontificate witnessed the fall of communism in Eastern Europe, the establishment of World Youth Day, the publication of the Catechism of the Catholic Church, and the canonization of more saints than any pope before him. Canonized by Pope Francis in 2014.",
  ),
  saint(
    "saint-faustina-kowalska",
    "Saint Faustina Kowalska",
    "10-05",
    "religious",
    "canonized",
    ["mercy"],
    "Saint Maria Faustina Kowalska (1905-1938) was a Polish Sister of Our Lady of Mercy. The Lord Jesus entrusted her with the message of Divine Mercy, recorded in her Diary. Pope John Paul II canonized her in 2000 — the first saint of the new millennium — and established Divine Mercy Sunday for the universal Church.",
  ),
  saint(
    "saint-maximilian-kolbe",
    "Saint Maximilian Kolbe",
    "08-14",
    "martyr",
    "canonized",
    ["prisoners", "the pro-life movement", "drug addicts"],
    "Saint Maximilian Maria Kolbe (1894-1941) was a Polish Conventual Franciscan friar who founded the Militia Immaculatae (Knights of the Immaculata) and the Marian publishing apostolate at Niepokalanów. Imprisoned at Auschwitz, he volunteered to die in place of a stranger, Franciszek Gajowniczek, and was murdered with a phenol injection on 14 August 1941. Canonized as a martyr by Pope John Paul II in 1982.",
  ),
  saint(
    "saint-mother-teresa-of-calcutta",
    "Saint Mother Teresa of Calcutta",
    "09-05",
    "founder",
    "canonized",
    ["World Youth Day", "Missionaries of Charity"],
    "Saint Teresa of Calcutta (Anjezë Gonxhe Bojaxhiu, 1910-1997) was an Albanian-Indian Catholic nun who founded the Missionaries of Charity in 1950. The order serves 'the poorest of the poor' in over 130 countries. Awarded the Nobel Peace Prize in 1979. Beatified by Pope John Paul II in 2003 and canonized by Pope Francis in 2016.",
  ),
  saint(
    "saint-anthony-of-padua",
    "Saint Anthony of Padua",
    "06-13",
    "doctor_of_the_church",
    "canonized",
    ["lost things", "the poor", "Portugal"],
    "Saint Anthony of Padua (1195-1231), born Fernando Martins in Lisbon, joined the Franciscans and became one of the greatest preachers of the Middle Ages. Canonized within a year of his death by Pope Gregory IX. Declared a Doctor of the Church by Pope Pius XII in 1946. His tomb in Padua draws millions of pilgrims annually.",
  ),
  saint(
    "saint-patrick",
    "Saint Patrick",
    "03-17",
    "bishop",
    "canonized",
    ["Ireland", "Nigeria", "engineers"],
    "Saint Patrick (c. 385-461) was the apostle of Ireland. Born in Roman Britain, captured by Irish raiders as a teenager and enslaved for six years, he escaped, became a priest and bishop, and returned to evangelize Ireland. He used the shamrock to explain the Trinity. His Confessio and Letter to the Soldiers of Coroticus survive.",
  ),
  saint(
    "saint-benedict-of-nursia",
    "Saint Benedict of Nursia",
    "07-11",
    "founder",
    "canonized",
    ["Europe", "monastics", "students"],
    "Saint Benedict (c. 480-547) is the patriarch of Western monasticism. His Rule for monasteries — 'pray and work' — became the foundational document for monastic life in Europe and shaped Western Christian culture. Pope Paul VI named him patron of Europe in 1964.",
  ),
  saint(
    "saint-catherine-of-siena",
    "Saint Catherine of Siena",
    "04-29",
    "doctor_of_the_church",
    "canonized",
    ["Italy", "Europe", "nurses"],
    "Saint Catherine of Siena (1347-1380), a Dominican tertiary, was an influential mystic, theologian, and reformer who urged Pope Gregory XI to return the papacy from Avignon to Rome. Her Dialogue of Divine Providence is a masterpiece of mystical theology. Declared a Doctor of the Church by Pope Paul VI in 1970 and co-patroness of Europe by Pope John Paul II.",
  ),
  saint(
    "saint-ignatius-of-loyola",
    "Saint Ignatius of Loyola",
    "07-31",
    "founder",
    "canonized",
    ["soldiers", "retreats", "the Society of Jesus"],
    "Saint Ignatius of Loyola (1491-1556), Basque nobleman turned mystic and reformer, founded the Society of Jesus (the Jesuits) in 1540. His Spiritual Exercises, composed during his convalescence at Manresa, remain one of the most influential works of Western spirituality. Canonized in 1622.",
  ),
  saint(
    "saint-teresa-of-avila",
    "Saint Teresa of Avila",
    "10-15",
    "doctor_of_the_church",
    "canonized",
    ["Spain", "headache sufferers", "writers"],
    "Saint Teresa of Jesus (1515-1582), Discalced Carmelite reformer, mystic, and author of The Interior Castle and the Autobiography. With St. John of the Cross she renewed the Carmelite Order. Declared the first woman Doctor of the Church by Pope Paul VI in 1970.",
  ),
  saint(
    "saint-john-of-the-cross",
    "Saint John of the Cross",
    "12-14",
    "doctor_of_the_church",
    "canonized",
    ["mystics", "contemplative life", "Spanish poets"],
    "Saint John of the Cross (1542-1591), Discalced Carmelite priest, poet, and mystic. Co-founder with St. Teresa of Avila of the reformed Carmelite Order. Author of The Dark Night of the Soul, The Ascent of Mount Carmel, and The Spiritual Canticle. Declared a Doctor of the Church in 1926.",
  ),
  saint(
    "saint-andrew-the-apostle",
    "Saint Andrew the Apostle",
    "11-30",
    "apostle",
    "canonized",
    ["Scotland", "Greece", "fishermen"],
    "Saint Andrew, brother of Simon Peter and a fisherman of Bethsaida, was the first-called of the Apostles. After Pentecost he preached in Greece and Asia Minor and was martyred at Patras on an X-shaped cross, which bears his name. He is the patron of Scotland, Greece, and Russia.",
  ),
  saint(
    "saint-james-the-greater",
    "Saint James the Greater",
    "07-25",
    "apostle",
    "canonized",
    ["Spain", "pilgrims", "laborers"],
    "Saint James, son of Zebedee and brother of John, was one of the three apostles closest to Jesus. He was the first apostle to be martyred, beheaded by Herod Agrippa around AD 44 (Acts 12). His shrine at Santiago de Compostela in Spain has drawn pilgrims for over a thousand years.",
  ),
  saint(
    "saint-thomas-the-apostle",
    "Saint Thomas the Apostle",
    "07-03",
    "apostle",
    "canonized",
    ["India", "architects", "those who doubt"],
    "Saint Thomas, called Didymus, at first doubted the Resurrection but then confessed the risen Christ as 'My Lord and my God' (John 20:28). Tradition holds that he carried the Gospel to India, where the Saint Thomas Christians revere him as their founder, and was martyred near Chennai.",
  ),
  saint(
    "saint-matthew",
    "Saint Matthew",
    "09-21",
    "apostle",
    "canonized",
    ["accountants", "tax collectors", "bankers"],
    "Saint Matthew, also called Levi, was a tax collector whom Jesus called from his customs post to follow him (Matthew 9:9). One of the Twelve Apostles, he is traditionally honored as the author of the first Gospel, written for Jewish Christians.",
  ),
  saint(
    "saint-mark-the-evangelist",
    "Saint Mark the Evangelist",
    "04-25",
    "evangelist",
    "canonized",
    ["Venice", "notaries", "Egypt"],
    "Saint Mark, a companion of Saints Peter and Paul, wrote the second Gospel, drawing on Peter's preaching. Tradition holds that he founded the Church of Alexandria and was martyred there. His relics rest in the Basilica of San Marco in Venice, of which he is patron.",
  ),
  saint(
    "saint-luke-the-evangelist",
    "Saint Luke the Evangelist",
    "10-18",
    "evangelist",
    "canonized",
    ["physicians", "surgeons", "artists"],
    "Saint Luke, a physician and companion of Saint Paul, wrote the third Gospel and the Acts of the Apostles, preserving the infancy narratives and many parables found nowhere else. By tradition a painter of the Blessed Virgin, he is the patron of physicians and artists.",
  ),
  saint(
    "saint-stephen",
    "Saint Stephen",
    "12-26",
    "martyr",
    "canonized",
    ["deacons", "bricklayers"],
    "Saint Stephen, one of the seven deacons chosen by the Apostles, was the first martyr of the Church (the protomartyr). Filled with the Holy Spirit, he preached boldly and was stoned to death, praying for his persecutors as he died (Acts 6-7). Saul of Tarsus stood by, consenting.",
  ),
  saint(
    "saint-lawrence",
    "Saint Lawrence",
    "08-10",
    "martyr",
    "canonized",
    ["cooks", "the poor", "deacons"],
    "Saint Lawrence was a deacon of Rome martyred in 258 under Valerian. Charged to surrender the Church's treasures, he presented the poor, saying, 'These are the treasures of the Church.' Tradition holds he was martyred on a gridiron. He is honored among the most celebrated Roman martyrs.",
  ),
  saint(
    "saint-sebastian",
    "Saint Sebastian",
    "01-20",
    "martyr",
    "canonized",
    ["athletes", "soldiers", "archers"],
    "Saint Sebastian was a Roman soldier martyred under Diocletian around 288. Condemned to be shot with arrows for professing Christ, he survived and confronted the emperor before being killed. He is among the most venerated early martyrs and a patron of athletes and soldiers.",
  ),
  saint(
    "saint-agnes",
    "Saint Agnes",
    "01-21",
    "martyr",
    "canonized",
    ["young girls", "chastity", "the Children of Mary"],
    "Saint Agnes was a Roman virgin martyred about 304 at the age of twelve or thirteen for consecrating her virginity to Christ. One of the most honored of the early Roman martyrs, her name is in the Roman Canon, and lambs blessed on her feast provide wool for the pallium.",
  ),
  saint(
    "saint-cecilia",
    "Saint Cecilia",
    "11-22",
    "martyr",
    "canonized",
    ["musicians", "music", "poets"],
    "Saint Cecilia, a Roman virgin and martyr of the early Church, is honored as the patroness of music and musicians, traditionally said to have sung to God in her heart. Her name is included in the Roman Canon of the Mass.",
  ),
  saint(
    "saint-lucy",
    "Saint Lucy",
    "12-13",
    "martyr",
    "canonized",
    ["the blind", "eye disorders", "Sicily"],
    "Saint Lucy was a virgin of Syracuse in Sicily, martyred about 304 under Diocletian. Her name (Lucia, 'light') and her patronage of the blind have made her feast, near the winter solstice, a festival of light. Her name appears in the Roman Canon.",
  ),
  saint(
    "saint-nicholas",
    "Saint Nicholas",
    "12-06",
    "bishop",
    "canonized",
    ["children", "sailors", "the falsely accused"],
    "Saint Nicholas was the fourth-century Bishop of Myra in Asia Minor, renowned for his secret gifts to the poor and his defense of the faith. His generosity gave rise to the figure of Santa Claus. He is the patron of children, sailors, and many nations.",
  ),
  saint(
    "saint-monica",
    "Saint Monica",
    "08-27",
    "lay",
    "canonized",
    ["mothers", "wives", "victims of abuse"],
    "Saint Monica (331-387), mother of Saint Augustine, prayed and wept for years for the conversion of her wayward son, who was baptized by Saint Ambrose in 387. A model of Christian motherhood and persevering prayer, she died at Ostia as she and Augustine journeyed home.",
  ),
  saint(
    "saint-dominic",
    "Saint Dominic",
    "08-08",
    "founder",
    "canonized",
    ["astronomers", "preachers", "the Dominican Republic"],
    "Saint Dominic de Guzmán (1170-1221) founded the Order of Preachers (the Dominicans) to combat heresy and preach the Gospel with learning and poverty. Devotion to the Rosary is closely associated with him and his order.",
  ),
  saint(
    "saint-clare-of-assisi",
    "Saint Clare of Assisi",
    "08-11",
    "founder",
    "canonized",
    ["television", "eye disease", "the Poor Clares"],
    "Saint Clare of Assisi (1194-1253), inspired by Saint Francis, left her noble family to embrace radical poverty and founded the Order of Poor Ladies (the Poor Clares). She defended her sisters and her city through prayer before the Blessed Sacrament.",
  ),
  saint(
    "saint-vincent-de-paul",
    "Saint Vincent de Paul",
    "09-27",
    "founder",
    "canonized",
    ["charitable societies", "the poor", "hospitals"],
    "Saint Vincent de Paul (1581-1660) devoted his life to the poor, founding the Congregation of the Mission (the Vincentians) and, with Saint Louise de Marillac, the Daughters of Charity. He is the patron of all works of Christian charity.",
  ),
  saint(
    "saint-philip-neri",
    "Saint Philip Neri",
    "05-26",
    "founder",
    "canonized",
    ["Rome", "joy", "the Oratory"],
    "Saint Philip Neri (1515-1595), the 'Apostle of Rome,' founded the Congregation of the Oratory and renewed the faith of the city through joy, confession, and prayer. Famous for his humor and holiness, he drew countless souls back to God.",
  ),
  saint(
    "saint-john-bosco",
    "Saint John Bosco",
    "01-31",
    "founder",
    "canonized",
    ["youth", "editors", "apprentices"],
    "Saint John Bosco (1815-1888), known as Don Bosco, devoted his life to poor and abandoned boys in Turin, founding the Salesians and, with Saint Mary Mazzarello, the Salesian Sisters. His 'preventive system' of education rested on reason, religion, and loving-kindness.",
  ),
  saint(
    "saint-joan-of-arc",
    "Saint Joan of Arc",
    "05-30",
    "martyr",
    "canonized",
    ["France", "soldiers", "captives"],
    "Saint Joan of Arc (1412-1431), the Maid of Orléans, was a peasant girl who, led by heavenly voices, rallied the French army during the Hundred Years' War. Captured and tried by an ecclesiastical court under English control, she was burned at the stake at nineteen and later fully vindicated. Canonized in 1920, she is a patroness of France.",
  ),
  saint(
    "saint-rita-of-cascia",
    "Saint Rita of Cascia",
    "05-22",
    "religious",
    "canonized",
    ["impossible causes", "difficult marriages", "parenthood"],
    "Saint Rita of Cascia (1381-1457), after a difficult marriage and the loss of her husband and sons, became an Augustinian nun. Renowned for her penance and a wound she received from the crown of thorns, she is invoked as the patroness of impossible and desperate causes.",
  ),
  saint(
    "saint-martin-de-porres",
    "Saint Martin de Porres",
    "11-03",
    "religious",
    "canonized",
    ["social justice", "mixed-race people", "barbers"],
    "Saint Martin de Porres (1579-1639) of Lima, Peru, a Dominican lay brother of mixed Spanish and African descent, served the sick and poor with heroic charity and was known for miracles and care of animals. Canonized in 1962, he is a patron of social justice.",
  ),
  saint(
    "saint-rose-of-lima",
    "Saint Rose of Lima",
    "08-23",
    "religious",
    "canonized",
    ["Latin America", "the Philippines", "gardeners"],
    "Saint Rose of Lima (1586-1617), a Dominican tertiary of Peru, lived a life of intense penance and care for the poor and indigenous of Lima. In 1671 she became the first canonized saint of the Americas.",
  ),
  saint(
    "saint-elizabeth-ann-seton",
    "Saint Elizabeth Ann Seton",
    "01-04",
    "founder",
    "canonized",
    ["Catholic schools", "widows", "the United States"],
    "Saint Elizabeth Ann Seton (1774-1821), a convert and widow, founded the Sisters of Charity and the first Catholic parochial school system in the United States. In 1975 she became the first native-born citizen of the United States to be canonized.",
  ),
  saint(
    "saint-juan-diego",
    "Saint Juan Diego",
    "12-09",
    "lay",
    "canonized",
    ["indigenous peoples", "the Americas"],
    "Saint Juan Diego (1474-1548) was the humble Aztec convert to whom the Blessed Virgin Mary appeared at Tepeyac in 1531 as Our Lady of Guadalupe, leaving her image on his tilma. Canonized in 2002, he is honored as a model of humility and faith.",
  ),
];
