import type { ChecklistSeed } from "./index";

export const prayersChecklist: ChecklistSeed[] = [
  {
    canonicalName: "Our Father",
    canonicalSlug: "our-father",
    aliases: ["The Lord's Prayer", "Pater Noster"],
    priority: 10,
    authorityLevelHint: "VATICAN",
    summary:
      "The prayer Christ taught the disciples. Foundational Catholic prayer recorded in Matthew 6 and Luke 11.",
    seedCitations: [
      {
        sourceUrl: "https://www.vatican.va/archive/ENG0015/__P9.HTM",
        authorityLevel: "CATECHISM",
        title: "CCC: The Our Father",
      },
    ],
  },
  {
    canonicalName: "Hail Mary",
    canonicalSlug: "hail-mary",
    aliases: ["Ave Maria"],
    priority: 10,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Glory Be",
    canonicalSlug: "glory-be",
    aliases: ["Doxology", "Gloria Patri"],
    priority: 15,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Apostles' Creed",
    canonicalSlug: "apostles-creed",
    priority: 20,
    authorityLevelHint: "CATECHISM",
  },
  {
    canonicalName: "Nicene Creed",
    canonicalSlug: "nicene-creed",
    priority: 20,
    authorityLevelHint: "CATECHISM",
  },
  {
    canonicalName: "Act of Contrition",
    canonicalSlug: "act-of-contrition",
    priority: 25,
    authorityLevelHint: "USCCB",
  },
  {
    canonicalName: "Act of Faith",
    canonicalSlug: "act-of-faith",
    priority: 30,
    authorityLevelHint: "USCCB",
  },
  {
    canonicalName: "Act of Hope",
    canonicalSlug: "act-of-hope",
    priority: 30,
    authorityLevelHint: "USCCB",
  },
  {
    canonicalName: "Act of Love",
    canonicalSlug: "act-of-love",
    aliases: ["Act of Charity"],
    priority: 30,
    authorityLevelHint: "USCCB",
  },
  {
    canonicalName: "Memorare",
    canonicalSlug: "memorare",
    priority: 30,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Angelus",
    canonicalSlug: "angelus",
    priority: 25,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Regina Caeli",
    canonicalSlug: "regina-caeli",
    aliases: ["Queen of Heaven"],
    priority: 30,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Salve Regina",
    canonicalSlug: "salve-regina",
    aliases: ["Hail Holy Queen"],
    priority: 30,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Prayer to St. Michael the Archangel",
    canonicalSlug: "prayer-to-saint-michael",
    aliases: ["Saint Michael Prayer", "Leonine Prayer"],
    priority: 25,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Anima Christi",
    canonicalSlug: "anima-christi",
    aliases: ["Soul of Christ"],
    priority: 35,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Prayer of St. Francis",
    canonicalSlug: "prayer-of-saint-francis",
    aliases: ["Peace Prayer", "Make me a channel of your peace"],
    priority: 40,
    notes:
      "Attribution to St. Francis is traditional but not historically certain — note this in body.",
  },
  {
    canonicalName: "Magnificat",
    canonicalSlug: "magnificat",
    priority: 25,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Te Deum",
    canonicalSlug: "te-deum",
    priority: 35,
    authorityLevelHint: "LITURGICAL_BOOK",
  },
  {
    canonicalName: "Veni Creator Spiritus",
    canonicalSlug: "veni-creator-spiritus",
    aliases: ["Come Holy Spirit"],
    priority: 35,
    authorityLevelHint: "LITURGICAL_BOOK",
  },
  {
    canonicalName: "Litany of the Sacred Heart of Jesus",
    canonicalSlug: "litany-of-the-sacred-heart",
    priority: 40,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Litany of the Blessed Virgin Mary",
    canonicalSlug: "litany-of-the-blessed-virgin-mary",
    aliases: ["Litany of Loreto"],
    priority: 40,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Litany of the Saints",
    canonicalSlug: "litany-of-the-saints",
    priority: 40,
    authorityLevelHint: "LITURGICAL_BOOK",
  },
  {
    canonicalName: "Litany of Humility",
    canonicalSlug: "litany-of-humility",
    priority: 50,
    authorityLevelHint: "TRUSTED_PUBLISHER",
  },
  {
    canonicalName: "Litany of St. Joseph",
    canonicalSlug: "litany-of-saint-joseph",
    priority: 40,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Morning Offering",
    canonicalSlug: "morning-offering",
    priority: 30,
    authorityLevelHint: "USCCB",
  },
  {
    canonicalName: "Grace Before Meals",
    canonicalSlug: "grace-before-meals",
    priority: 35,
    authorityLevelHint: "USCCB",
  },
  {
    canonicalName: "Grace After Meals",
    canonicalSlug: "grace-after-meals",
    priority: 35,
    authorityLevelHint: "USCCB",
  },
  {
    canonicalName: "Prayer Before the Crucifix",
    canonicalSlug: "prayer-before-the-crucifix",
    aliases: ["En Ego, O bone et dulcissime Iesu"],
    priority: 45,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Adoro Te Devote",
    canonicalSlug: "adoro-te-devote",
    aliases: ["Hidden God Devoutly I Adore Thee"],
    priority: 45,
    authorityLevelHint: "VATICAN",
  },
  {
    canonicalName: "Pange Lingua",
    canonicalSlug: "pange-lingua",
    priority: 45,
    authorityLevelHint: "LITURGICAL_BOOK",
  },
  {
    canonicalName: "Tantum Ergo",
    canonicalSlug: "tantum-ergo",
    priority: 45,
    authorityLevelHint: "LITURGICAL_BOOK",
  },
  {
    canonicalName: "Confiteor",
    canonicalSlug: "confiteor",
    priority: 25,
    authorityLevelHint: "LITURGICAL_BOOK",
  },
  {
    canonicalName: "Divine Praises",
    canonicalSlug: "divine-praises",
    priority: 45,
    authorityLevelHint: "LITURGICAL_BOOK",
  },
];
