/**
 * Deterministic content-subtitle generation. Produces a short, accurate
 * descriptive subtitle from a content type + the fields already present in
 * that type's content schema — generated by the worker, stored on
 * PublishedContent.subtitle, and rendered under the title. Pure +
 * deterministic: no AI, no network, no fields outside the schemas.
 *
 * Examples:
 *   Saint Peter           -> "Apostle, patron of the papacy · Feast June 29"
 *   Pope St John Paul II  -> "Pope from 1978 to 2005"
 *   St Thomas Aquinas     -> "Religious · Doctor of the Church — Angelic Doctor · Feast January 28"
 *   Lourdes               -> "Church-approved Marian apparition · Lourdes, France, 1858"
 *   Rerum Novarum         -> "Encyclical of Pope Leo XIII (1891)"
 *   Christmas             -> "Solemnity · December 25 · Christmas season"
 *   St Peter's Basilica   -> "Major basilica · Vatican City, Vatican City State · Diocese of Rome"
 */

export interface SubtitleInput {
  contentType: string;
  contentSubtype?: string | null;
  title?: string | null;
  fields?: Record<string, unknown>;
}

type Fields = Record<string, unknown>;

function str(v: unknown): string {
  return typeof v === "string" ? v.trim() : "";
}

function num(v: unknown): number | null {
  if (typeof v === "number" && Number.isFinite(v)) return v;
  if (typeof v === "string" && /^\d+$/.test(v.trim())) return parseInt(v, 10);
  return null;
}

function arr(v: unknown): unknown[] {
  return Array.isArray(v) ? v : [];
}

const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

/** "06-29" -> "June 29"; anything else is returned trimmed as-is. */
export function formatFeastDate(value: unknown): string {
  const s = str(value);
  const m = /^(\d{2})-(\d{2})$/.exec(s);
  if (!m) return s;
  const month = MONTHS[parseInt(m[1], 10) - 1];
  const day = parseInt(m[2], 10);
  if (!month || !day) return s;
  return `${month} ${day}`;
}

/** "1891-05-15" -> "1891"; "0325-01-01" -> "325"; "1978" -> "1978". */
function yearOf(value: unknown): string {
  const s = str(value);
  const m = /^(\d{1,4})(?:-\d{2}-\d{2})?$/.exec(s);
  if (!m) return "";
  return String(parseInt(m[1], 10));
}

/** "saint-faustina-kowalska" -> "Saint Faustina Kowalska". */
function humanizeSlug(slug: string): string {
  return slug
    .split("-")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function ordinal(n: number): string {
  const mod100 = n % 100;
  if (mod100 >= 11 && mod100 <= 13) return `${n}th`;
  switch (n % 10) {
    case 1:
      return `${n}st`;
    case 2:
      return `${n}nd`;
    case 3:
      return `${n}rd`;
    default:
      return `${n}th`;
  }
}

// ---------------------------------------------------------------------------
// SAINT
// ---------------------------------------------------------------------------

const SAINT_TYPE_LABELS: Record<string, string> = {
  apostle: "Apostle",
  evangelist: "Evangelist",
  martyr: "Martyr",
  doctor_of_the_church: "Doctor of the Church",
  virgin: "Virgin",
  bishop: "Bishop",
  pope: "Pope",
  founder: "Religious founder",
  missionary: "Missionary",
  religious: "Religious",
  lay: "Lay faithful",
  confessor: "Confessor",
  other: "Saint",
};

const CANONIZATION_PREFIX: Record<string, string> = {
  beatified: "Blessed",
  venerable: "Venerable",
  servant_of_god: "Servant of God",
};

function saintSubtitle(f: Fields): string {
  const typeLabel = SAINT_TYPE_LABELS[str(f.saintType)];
  const prefix = CANONIZATION_PREFIX[str(f.canonizationStatus)] ?? "";
  const patron = str(arr(f.patronages)[0]);
  const feast = formatFeastDate(f.feastDay);
  if (!typeLabel && !patron && !feast) {
    // Legacy payloads (role / patronage) and the bare fallback.
    const legacy = str(f.role) || str(f.patronage);
    return legacy ? `Saint — ${legacy}` : "A saint of the Catholic Church";
  }
  const head = `${prefix ? `${prefix} · ` : ""}${typeLabel ?? "Saint"}`;
  return `${head}${patron ? `, patron of ${patron}` : ""}${feast ? ` · Feast ${feast}` : ""}`;
}

// ---------------------------------------------------------------------------
// POPE
// ---------------------------------------------------------------------------

function popeSubtitle(f: Fields): string {
  const start = str(f.papacyStart);
  const rawEnd = str(f.papacyEnd);
  const end = rawEnd && rawEnd.toLowerCase() !== "present" ? rawEnd : "";
  const ord = num(f.ordinal);
  if (!start) return "Pope, Bishop of Rome";
  if (ord != null) return `${ordinal(ord)} Pope · ${start}–${end || "present"}`;
  return end ? `Pope from ${start} to ${end}` : `Pope since ${start}`;
}

// ---------------------------------------------------------------------------
// DOCTOR
// ---------------------------------------------------------------------------

const ECCLESIAL_ROLE_LABELS: Record<string, string> = {
  pope: "Pope",
  bishop: "Bishop",
  priest: "Priest",
  deacon: "Deacon",
  religious: "Religious",
  lay: "Lay faithful",
};

function doctorSubtitle(f: Fields): string {
  const epithet = str(f.doctorTitle);
  const role = ECCLESIAL_ROLE_LABELS[str(f.ecclesialRole)] ?? "";
  const feast = formatFeastDate(f.feastDay);
  const core =
    epithet && epithet.toLowerCase() !== "doctor of the church"
      ? `Doctor of the Church — ${epithet}`
      : "Doctor of the Church";
  return `${role ? `${role} · ` : ""}${core}${feast ? ` · Feast ${feast}` : ""}`;
}

// ---------------------------------------------------------------------------
// APPARITION
// ---------------------------------------------------------------------------

function apparitionStatusLabel(status: string, subjectWord: string): string {
  switch (status) {
    case "approved":
    case "constat_de_supernaturalitate":
      return `Church-approved ${subjectWord}`;
    case "nihil_obstat":
      return `${subjectWord.charAt(0).toUpperCase()}${subjectWord.slice(1)} granted nihil obstat`;
    case "under_investigation":
    case "not_yet_judged":
    case "prae_oculis_habeatur":
    case "curatur":
    case "sub_mandato":
      return `${subjectWord.charAt(0).toUpperCase()}${subjectWord.slice(1)} under Church review`;
    case "non_constat":
      return `${subjectWord.charAt(0).toUpperCase()}${subjectWord.slice(1)} not confirmed by the Church`;
    case "not_supernatural":
    case "declaratio_de_non_supernaturalitate":
      return "Reported apparition judged not supernatural";
    case "prohibetur_et_obstruatur":
      return "Reported apparition not permitted by the Church";
    case "private_revelation":
      return "Private revelation";
    default:
      return "";
  }
}

function apparitionSubtitle(f: Fields): string {
  const subject = str(f.subject);
  const subjectWord =
    subject === "christ"
      ? "apparition of Christ"
      : subject === "saint"
        ? "apparition of a saint"
        : subject === "angel"
          ? "apparition of an angel"
          : "Marian apparition";
  const schemaStatus = str(f.approvedStatus).toLowerCase();
  let label = apparitionStatusLabel(schemaStatus, subjectWord);
  if (!label) {
    // Legacy field names (approvalStatus / status) carry free text.
    const legacy = str(f.approvalStatus ?? f.status).toLowerCase();
    if (legacy.includes("approv")) label = `Church-approved ${subjectWord}`;
    else if (legacy.includes("condemn"))
      label = `${subjectWord.charAt(0).toUpperCase()}${subjectWord.slice(1)} not approved by the Church`;
    else if (legacy.includes("review"))
      label = `${subjectWord.charAt(0).toUpperCase()}${subjectWord.slice(1)} under Church review`;
    else label = `Reported ${subjectWord}`;
  }
  const where = [str(f.location), str(f.country)].filter(Boolean);
  const year = num(f.yearOfApparition);
  const tail = [...where, year != null ? String(year) : ""].filter(Boolean).join(", ");
  return tail ? `${label} · ${tail}` : label;
}

// ---------------------------------------------------------------------------
// MARIAN_TITLE
// ---------------------------------------------------------------------------

/** The four Marian dogmas, keyed by curated slug, with the year each was defined. */
export const MARIAN_DOGMA_YEARS: Readonly<Record<string, number>> = {
  "mother-of-god": 431,
  "immaculate-conception": 1854,
  "assumption-of-mary": 1950,
  "perpetual-virginity": 649,
};

function marianTitleSubtitle(f: Fields): string {
  const slug = str(f.slug);
  const dogmaYear = num(f.dogmaDefinedYear) ?? MARIAN_DOGMA_YEARS[slug] ?? null;
  if (dogmaYear != null) return `Marian dogma · defined ${dogmaYear}`;
  const feast = formatFeastDate(f.feastDay);
  const region = str(f.region);
  return `Title of the Blessed Virgin Mary${feast ? ` · Feast ${feast}` : ""}${region ? ` · ${region}` : ""}`;
}

// ---------------------------------------------------------------------------
// SACRAMENT
// ---------------------------------------------------------------------------

const SACRAMENT_GROUP: Record<string, string> = {
  baptism: "Sacrament of Christian Initiation",
  confirmation: "Sacrament of Christian Initiation",
  eucharist: "Sacrament of Christian Initiation",
  reconciliation: "Sacrament of Healing",
  anointing_of_the_sick: "Sacrament of Healing",
  holy_orders: "Sacrament at the Service of Communion",
  matrimony: "Sacrament at the Service of Communion",
};

function sacramentSubtitle(f: Fields): string {
  return SACRAMENT_GROUP[str(f.sacramentKey)] ?? "One of the seven sacraments of the Church";
}

// ---------------------------------------------------------------------------
// PRAYER / LITANY
// ---------------------------------------------------------------------------

function prayerSubtypeSubtitle(subtype: string | null): string {
  switch (subtype) {
    case "marian_prayer":
      return "A Marian prayer of the Catholic Church";
    case "eucharistic_prayer":
      return "A Eucharistic prayer of the Catholic Church";
    case "saint_prayer":
      return "A prayer to a saint of the Church";
    case "liturgical_prayer":
      return "A prayer of the sacred liturgy";
    case "litany_invocation":
    case "full_litany":
      return "A litany of the Catholic Church";
    default:
      return "A prayer of the Catholic Church";
  }
}

const PRAYER_TYPE_LABELS: Record<string, string> = {
  morning: "Morning prayer",
  evening: "Evening prayer",
  meal: "Grace before/after meals",
  litany: "Litany — invocations and responses",
  novena: "Novena prayer",
  rosary: "Rosary prayer",
  marian: "Marian prayer",
  intercession: "Prayer of intercession",
  consecration: "Act of consecration",
  chaplet: "Chaplet prayer",
  psalm: "Psalm",
  canticle: "Canticle",
  hymn: "Hymn of the Church",
  general: "Catholic prayer",
};

function prayerSubtitle(f: Fields, subtype: string | null, title: string): string {
  const type = str(f.prayerType);
  let label: string;
  if (type === "act") {
    const m = /^act of (.+)$/i.exec(title.trim());
    label = m ? `Act of ${m[1].trim().toLowerCase()}` : "Act of devotion";
  } else {
    label = PRAYER_TYPE_LABELS[type] ?? "";
  }
  if (!label) return prayerSubtypeSubtitle(subtype);
  const translations = arr(f.translations).length;
  return `${label}${str(f.latin) ? " · Latin text" : ""}${translations > 0 ? ` · ${translations} translations` : ""}`;
}

// ---------------------------------------------------------------------------
// NOVENA
// ---------------------------------------------------------------------------

function novenaSubtitle(f: Fields): string {
  const duration = num(f.durationDays);
  const days = arr(f.days).length;
  const head =
    duration != null && duration !== 9
      ? `${duration}-day novena`
      : days > 9
        ? `${days}-day novena`
        : "Nine-day novena";
  const saintSlug = str(f.associatedSaintSlug);
  const saint = saintSlug ? humanizeSlug(saintSlug) : "";
  const start = str(f.typicalStartDate);
  const feastSlug = str(f.relatedFeastSlug);
  const feast = feastSlug
    ? humanizeSlug(feastSlug.replace(/^(solemnity|feast|memorial|optional-memorial)-/, ""))
    : "";
  const theme = str(f.intentionTheme);
  const to = saint ? ` to ${saint}` : "";
  if (start) return `${head}${to} · begins ${start}`;
  if (feast) return `${head}${to} · before ${feast}`;
  if (saint) return `${head}${to}`;
  return theme ? `${head} for ${theme}` : "A nine-day Catholic devotion";
}

// ---------------------------------------------------------------------------
// DEVOTION
// ---------------------------------------------------------------------------

const DEVOTION_TYPE_LABELS: Record<string, string> = {
  marian: "Marian devotion",
  eucharistic: "Eucharistic devotion",
  christological: "Devotion to Christ",
  passion: "Devotion to the Passion",
  reparation: "Devotion of reparation",
  angelic: "Devotion to the angels",
  liturgical: "Liturgical prayer of the Church",
  general: "Catholic devotion",
};

function devotionSubtitle(f: Fields): string {
  const label = DEVOTION_TYPE_LABELS[str(f.devotionType)] ?? "A devotion of the Catholic faithful";
  const minutes = num(f.durationMinutes);
  return `${label}${minutes != null && minutes > 0 ? ` · ${minutes} min` : ""}`;
}

// ---------------------------------------------------------------------------
// CHURCH_DOCUMENT
// ---------------------------------------------------------------------------

const DOCUMENT_TYPE_LABELS: Record<string, string> = {
  encyclical: "Encyclical",
  apostolic_exhortation: "Apostolic Exhortation",
  apostolic_constitution: "Apostolic Constitution",
  motu_proprio: "Motu Proprio",
  apostolic_letter: "Apostolic Letter",
  decree: "Decree",
  declaration: "Declaration",
  instruction: "Instruction",
  vatican_document: "Vatican document",
  uscb_pastoral_letter: "Pastoral letter",
  papal_bull: "Papal Bull",
  code_of_canon_law: "Code of Canon Law",
  // Subtype-derived kinds (when documentType is absent).
  council_constitution: "Constitution of an Ecumenical Council",
  council_decree: "Decree of an Ecumenical Council",
  council_declaration: "Declaration of an Ecumenical Council",
  catechism_paragraph: "Catechism of the Catholic Church",
};

function documentSubtitle(f: Fields, subtype: string | null): string {
  const docType = str(f.documentType) || subtype || "";
  const year = yearOf(f.issuedDate);
  const authority = str(f.issuingAuthority);
  const pope = str(f.pope ?? f.popeName ?? f.author);

  if (docType === "catechism_section" || docType === "catechism_paragraph") {
    return `Catechism of the Catholic Church${year ? ` · promulgated ${year}` : ""}`;
  }
  if (docType === "council_document") {
    // A document OF a council ("Second Vatican Council") vs the council itself.
    const councilMatch =
      /((?:first|second|third|fourth|fifth)?\s*[A-Za-z' ]*council[A-Za-z' ]*)/i.exec(authority);
    const council = councilMatch ? councilMatch[1].trim() : "";
    if (council && !/^catholic church$/i.test(authority)) {
      return `Document of the ${council}${year ? ` (${year})` : ""}`;
    }
    return `Ecumenical Council${year ? ` · ${year}` : ""}`;
  }

  const kind = DOCUMENT_TYPE_LABELS[docType] ?? "Document of the Catholic Church";
  const issuer = authority || (pope ? `Pope ${pope}` : "");
  return `${kind}${issuer ? ` of ${issuer}` : ""}${year ? ` (${year})` : ""}`;
}

// ---------------------------------------------------------------------------
// LITURGICAL
// ---------------------------------------------------------------------------

const LITURGICAL_RANK_LABELS: Record<string, string> = {
  solemnity: "Solemnity",
  feast: "Feast",
  memorial: "Memorial",
  optional_memorial: "Optional memorial",
};

const SEASON_LABELS: Record<string, string> = {
  advent: "Advent",
  christmas: "Christmas season",
  ordinary_time: "Ordinary Time",
  lent: "Lent",
  triduum: "Sacred Triduum",
  easter: "Easter season",
};

function liturgicalSubtitle(f: Fields, subtype: string | null): string {
  const kind = str(f.kind) || subtype || "";
  const rank = LITURGICAL_RANK_LABELS[kind];
  if (rank) {
    const date = formatFeastDate(f.feastDate);
    const movable = f.movableFeast === true;
    const season = SEASON_LABELS[str(f.season)] ?? "";
    return `${rank}${date ? ` · ${date}` : movable ? " · movable" : ""}${season ? ` · ${season}` : ""}`;
  }
  switch (kind) {
    case "liturgical_season":
      return "Season of the liturgical year";
    case "liturgical_year":
      return "The liturgical year";
    case "mass_structure":
      return "Order of Mass";
    case "marriage_rite":
    case "funeral_rite":
    case "ordination_rite":
      return "Liturgical rite";
    case "council_event":
      return "Council";
    case "symbolism":
      return "Liturgical symbolism";
    case "glossary_term":
      return "Liturgical glossary";
    default:
      return "A day of the liturgical calendar";
  }
}

// ---------------------------------------------------------------------------
// RITE
// ---------------------------------------------------------------------------

export type RiteFamily =
  | "latin"
  | "byzantine"
  | "alexandrian"
  | "west_syriac"
  | "east_syriac"
  | "armenian";
export type RiteEntryKind = "liturgical_rite" | "church_sui_iuris" | "latin_use";

const RITE_KEY_FAMILY: Record<string, RiteFamily> = {
  roman: "latin",
  latin: "latin",
  ambrosian: "latin",
  mozarabic: "latin",
  byzantine: "byzantine",
  melkite: "byzantine",
  ukrainian: "byzantine",
  ruthenian: "byzantine",
  maronite: "west_syriac",
  syroMalankara: "west_syriac",
  chaldean: "east_syriac",
  syroMalabar: "east_syriac",
  coptic: "alexandrian",
  ethiopic: "alexandrian",
  armenian: "armenian",
};

const RITE_KEY_ENTRY_KIND: Record<string, RiteEntryKind> = {
  roman: "liturgical_rite",
  latin: "liturgical_rite",
  byzantine: "liturgical_rite",
  ambrosian: "latin_use",
  mozarabic: "latin_use",
};

const RITE_FAMILY_LABELS: Record<RiteFamily, string> = {
  latin: "Latin",
  byzantine: "Byzantine",
  west_syriac: "West Syriac (Antiochene)",
  east_syriac: "East Syriac (Chaldean)",
  alexandrian: "Alexandrian",
  armenian: "Armenian",
};

const LATIN_USE_PLACE: Record<string, string> = {
  ambrosian: "Milan",
  mozarabic: "Toledo",
};

/** The liturgical family of a rite payload (explicit `family`, else derived from `riteKey`). */
export function deriveRiteFamily(f: Fields): RiteFamily | null {
  const explicit = str(f.family) as RiteFamily;
  if (explicit && explicit in RITE_FAMILY_LABELS) return explicit;
  return RITE_KEY_FAMILY[str(f.riteKey)] ?? null;
}

/** What a rite payload describes (explicit `entryKind`, else derived from `riteKey`). */
export function deriveRiteEntryKind(f: Fields): RiteEntryKind | null {
  const explicit = str(f.entryKind);
  if (explicit === "liturgical_rite" || explicit === "church_sui_iuris" || explicit === "latin_use")
    return explicit;
  const key = str(f.riteKey);
  if (!key) return null;
  return RITE_KEY_ENTRY_KIND[key] ?? (RITE_KEY_FAMILY[key] ? "church_sui_iuris" : null);
}

function riteSubtitle(f: Fields): string {
  const family = deriveRiteFamily(f);
  if (!family) return "A liturgical rite of the Catholic Church";
  const entryKind = deriveRiteEntryKind(f);
  const key = str(f.riteKey);
  if (entryKind === "latin_use") {
    const place = LATIN_USE_PLACE[key];
    return `Latin liturgical use${place ? ` · ${place}` : ""}`;
  }
  if (entryKind === "church_sui_iuris") {
    return `${RITE_FAMILY_LABELS[family]} tradition · Church sui iuris`;
  }
  if (family === "latin") return "Latin liturgical rite";
  if (family === "byzantine") return "Byzantine liturgical rite";
  return `${RITE_FAMILY_LABELS[family]} tradition`;
}

// ---------------------------------------------------------------------------
// PARISH
// ---------------------------------------------------------------------------

const DESIGNATION_LABELS: Record<string, string> = {
  parish: "Parish",
  shrine: "Shrine",
  cathedral: "Cathedral",
  "major-basilica": "Major basilica",
  "minor-basilica": "Minor basilica",
};

function parishSubtitle(f: Fields): string {
  const designation = DESIGNATION_LABELS[str(f.designation)] ?? "";
  const place = [str(f.city), str(f.state), str(f.country)].filter(Boolean).join(", ");
  const diocese = str(f.diocese);
  if (!designation && !place && !diocese) return "A Catholic parish";
  return [designation || "Parish", place, diocese].filter(Boolean).join(" · ");
}

// ---------------------------------------------------------------------------
// GUIDE
// ---------------------------------------------------------------------------

const GUIDE_KIND_SUBTITLES: Record<string, string> = {
  rosary: "How to pray the Rosary",
  chaplet: "How to pray a chaplet",
  confession: "Preparing for Confession",
  adoration: "Eucharistic Adoration",
  consecration: "Marian consecration",
  discernment: "Discernment",
  vocation: "Vocational discernment",
  lent_preparation: "Lenten guide",
  advent_preparation: "Advent guide",
  rcia: "Becoming Catholic (OCIA)",
  ocia: "Becoming Catholic (OCIA)",
  mass: "Attending Mass",
  liturgy_of_the_hours: "Liturgy of the Hours",
  funeral: "Catholic funeral",
  marriage: "Catholic marriage",
  family: "Family life",
  season: "Liturgical season",
  pilgrimage: "Pilgrimage",
  devotion: "Catholic devotion",
  sacramental: "Sacramentals",
  scripture: "Praying with Scripture",
};

const GUIDE_CATEGORY_SUBTITLES: Record<string, string> = {
  liturgy: "Mass and liturgy",
  devotion: "Catholic devotion",
  family: "Family life",
  funeral: "Catholic funeral",
  season: "Liturgical season",
  prayer: "Prayer",
};

const SACRAMENT_NAMES: Record<string, string> = {
  baptism: "Baptism",
  confirmation: "Confirmation",
  eucharist: "the Eucharist",
  reconciliation: "Confession",
  anointing_of_the_sick: "the Anointing of the Sick",
  holy_orders: "Holy Orders",
  matrimony: "Matrimony",
};

function guideSubtitle(f: Fields): string {
  const kind = str(f.kind);
  const sacrament = SACRAMENT_NAMES[str(f.sacramentKey)];
  // A specific kind wins; `general` / `sacramental_preparation` fall through to
  // the sacrament being prepared for, then the optional category, then "Guide".
  const label =
    GUIDE_KIND_SUBTITLES[kind] ||
    (sacrament ? `Preparing for ${sacrament}` : "") ||
    GUIDE_CATEGORY_SUBTITLES[str(f.category)] ||
    "Guide";
  const steps = arr(f.steps).length;
  if (!kind && !sacrament && steps === 0) return "A guide to Catholic life and practice";
  return `${label}${steps > 0 ? ` · ${steps} ${steps === 1 ? "step" : "steps"}` : ""}`;
}

// ---------------------------------------------------------------------------
// SPIRITUAL_PRACTICE
// ---------------------------------------------------------------------------

const PRACTICE_KIND_LABELS: Record<string, string> = {
  contemplative_prayer: "Contemplative prayer",
  lectio_divina: "Lectio divina",
  examen: "Daily examen",
  fasting: "Fasting",
  almsgiving: "Almsgiving",
  pilgrimage: "Pilgrimage",
  stations_of_the_cross: "Way of the Cross",
  spiritual_direction: "Spiritual direction",
  discernment: "Discernment",
  vocation: "Vocational discernment",
  mortification: "Mortification",
  vocal_prayer: "Vocal prayer",
  liturgy_of_the_hours: "Liturgy of the Hours",
  spiritual_reading: "Spiritual reading",
  penance: "Penance",
  eucharistic: "Eucharistic devotion",
  work: "Work as prayer",
  mercy: "Works of mercy",
  silence: "Silence and solitude",
  family: "Family prayer",
  other: "Spiritual practice",
};

function practiceSubtitle(f: Fields): string {
  const label = PRACTICE_KIND_LABELS[str(f.practiceKind)] ?? "";
  const tradition = str(f.tradition);
  if (!label) return "A practice of the spiritual life";
  return `${label}${tradition ? ` · ${tradition} tradition` : ""}`;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

export function generateContentSubtitle(input: SubtitleInput): string {
  const f = input.fields ?? {};
  const sub = input.contentSubtype ?? null;
  const title = input.title ?? str(f.title);

  switch (input.contentType) {
    case "DOCTOR":
      return doctorSubtitle(f);
    case "POPE":
      return popeSubtitle(f);
    case "SAINT":
      return saintSubtitle(f);
    case "MARIAN_TITLE":
      return marianTitleSubtitle(f);
    case "APPARITION":
      return apparitionSubtitle(f);
    case "SACRAMENT":
      return sacramentSubtitle(f);
    case "PRAYER":
    case "LITANY":
      return prayerSubtitle(f, sub, title);
    case "NOVENA":
      return novenaSubtitle(f);
    case "ROSARY":
      return "A devotion of the Holy Rosary";
    case "CONSECRATION":
      return "An act of consecration";
    case "DEVOTION":
      return devotionSubtitle(f);
    case "CHURCH_DOCUMENT":
    case "PAPAL_DOCUMENT":
    case "COUNCIL_DOCUMENT":
      return documentSubtitle(f, sub);
    case "CATECHISM_REFERENCE":
      return "A reference from the Catechism of the Catholic Church";
    case "CANON_LAW_REFERENCE":
      return "A canon of the Code of Canon Law";
    case "LITURGICAL_READING":
      return "The readings for Holy Mass";
    case "LITURGICAL":
    case "LITURGICAL_CALENDAR_DAY":
    case "FEAST_DAY":
    case "HOLY_DAY":
      return liturgicalSubtitle(f, sub);
    case "RITE":
      return riteSubtitle(f);
    case "PARISH":
      return parishSubtitle(f);
    case "DIOCESE":
      return "A Catholic diocese";
    case "RELIGIOUS_ORDER":
      return "A Catholic religious order";
    case "CHURCH_HISTORY_EVENT":
      return "An event in the history of the Church";
    case "CREED":
      return "A profession of the Catholic faith";
    case "GUIDE":
      return guideSubtitle(f);
    case "SPIRITUAL_PRACTICE":
      return practiceSubtitle(f);
    default:
      return "Catholic content";
  }
}

/** A short (≤ 40 char) subtitle for compact display (cards, lists). */
export function shortContentSubtitle(input: SubtitleInput): string {
  const full = generateContentSubtitle(input);
  return full.length <= 40 ? full : full.slice(0, 37).trimEnd() + "…";
}
