/**
 * Deterministic content-subtitle generation. Produces a short, accurate
 * descriptive subtitle from a content type (+ subtype and a few known fields)
 * — generated by the worker, stored on PublishedContent.subtitle, and rendered
 * under the title. Pure + deterministic: no AI, no network.
 *
 * Examples:
 *   Doctor              -> "Bishop, Doctor of the Church"
 *   Encyclical (Leo XIII) -> "Encyclical of Pope Leo XIII"
 *   Marian prayer       -> "A Marian prayer of the Catholic Church"
 */

export interface SubtitleInput {
  contentType: string;
  contentSubtype?: string | null;
  title?: string | null;
  fields?: Record<string, unknown>;
}

function str(v: unknown): string {
  return typeof v === "string" ? v.trim() : "";
}

function prayerSubtitle(subtype: string | null): string {
  switch (subtype) {
    case "marian_prayer":
      return "A Marian prayer of the Catholic Church";
    case "eucharistic_prayer":
      return "A Eucharistic prayer of the Catholic Church";
    case "saint_prayer":
      return "A prayer to a saint of the Church";
    case "liturgical_prayer":
      return "A prayer of the sacred liturgy";
    case "litany_invocation":
    case "full_litany":
      return "A litany of the Catholic Church";
    default:
      return "A prayer of the Catholic Church";
  }
}

function documentSubtitle(subtype: string | null, pope: string): string {
  const kind =
    subtype === "encyclical"
      ? "Encyclical"
      : subtype === "apostolic_exhortation"
        ? "Apostolic Exhortation"
        : subtype === "apostolic_constitution"
          ? "Apostolic Constitution"
          : subtype === "motu_proprio"
            ? "Motu Proprio"
            : subtype === "council_constitution"
              ? "Constitution of an Ecumenical Council"
              : subtype === "council_decree"
                ? "Decree of an Ecumenical Council"
                : subtype === "council_declaration"
                  ? "Declaration of an Ecumenical Council"
                  : "Document of the Catholic Church";
  return pope ? `${kind} of Pope ${pope}` : kind;
}

function apparitionSubtitle(fields: Record<string, unknown>): string {
  const status = str(fields.approvalStatus ?? fields.status).toLowerCase();
  if (status.includes("approv")) return "A Church-approved Marian apparition";
  if (status.includes("condemn")) return "A Marian apparition not approved by the Church";
  if (status.includes("review")) return "A Marian apparition under Church review";
  return "A reported Marian apparition";
}

function liturgicalSubtitle(subtype: string | null): string {
  switch (subtype) {
    case "solemnity":
      return "A solemnity of the liturgical calendar";
    case "memorial":
      return "A memorial of the liturgical calendar";
    case "optional_memorial":
      return "An optional memorial of the liturgical calendar";
    case "feast":
      return "A feast of the liturgical calendar";
    case "liturgical_season":
      return "A season of the liturgical year";
    default:
      return "A day of the liturgical calendar";
  }
}

export function generateContentSubtitle(input: SubtitleInput): string {
  const f = input.fields ?? {};
  const sub = input.contentSubtype ?? null;
  const pope = str(f.pope ?? f.popeName ?? f.author);

  switch (input.contentType) {
    case "DOCTOR":
      return "Bishop, Doctor of the Church";
    case "POPE":
      return "Pope, Bishop of Rome";
    case "SAINT":
      return str(f.role) || str(f.patronage)
        ? `Saint — ${str(f.role) || str(f.patronage)}`
        : "A saint of the Catholic Church";
    case "MARIAN_TITLE":
      return "A title of the Blessed Virgin Mary";
    case "APPARITION":
      return apparitionSubtitle(f);
    case "SACRAMENT":
      return "One of the seven sacraments of the Church";
    case "PRAYER":
    case "LITANY":
      return prayerSubtitle(sub);
    case "NOVENA":
      return "A nine-day Catholic devotion";
    case "ROSARY":
      return "A devotion of the Holy Rosary";
    case "CONSECRATION":
      return "An act of consecration";
    case "DEVOTION":
      return "A devotion of the Catholic faithful";
    case "CHURCH_DOCUMENT":
    case "PAPAL_DOCUMENT":
    case "COUNCIL_DOCUMENT":
      return documentSubtitle(sub, pope);
    case "CATECHISM_REFERENCE":
      return "A reference from the Catechism of the Catholic Church";
    case "CANON_LAW_REFERENCE":
      return "A canon of the Code of Canon Law";
    case "LITURGICAL_READING":
      return "The readings for Holy Mass";
    case "LITURGICAL":
    case "LITURGICAL_CALENDAR_DAY":
    case "FEAST_DAY":
    case "HOLY_DAY":
      return liturgicalSubtitle(sub);
    case "RITE":
      return "A liturgical rite of the Catholic Church";
    case "PARISH":
      return "A Catholic parish";
    case "DIOCESE":
      return "A Catholic diocese";
    case "RELIGIOUS_ORDER":
      return "A Catholic religious order";
    case "CHURCH_HISTORY_EVENT":
      return "An event in the history of the Church";
    case "CREED":
      return "A profession of the Catholic faith";
    case "GUIDE":
      return "A guide to Catholic life and practice";
    case "SPIRITUAL_PRACTICE":
      return "A practice of the spiritual life";
    default:
      return "Catholic content";
  }
}

/** A short (≤ 40 char) subtitle for compact display (cards, lists). */
export function shortContentSubtitle(input: SubtitleInput): string {
  const full = generateContentSubtitle(input);
  return full.length <= 40 ? full : full.slice(0, 37).trimEnd() + "…";
}
