import type { CuratedEntry } from "../index";

/**
 * Batch 7 of the curated prayer catalogue: the psalms and scriptural canticles
 * the Church prays in the Liturgy of the Hours and in popular devotion.
 *
 * Every body is the Douay-Rheims (Challoner, 1899 American edition) text,
 * public domain, copied verse for verse from the cited drbo.org chapter page
 * with one verse to a line and nothing added, omitted or modernised — each
 * chapter was compared line by line with that page before it was vendored.
 * Psalms carry the Douay (Vulgate) number first and the modern number in
 * brackets; a psalm's superscription stands as the Douay prints it, and where
 * the page keeps an old reading ("in the name Lord", Psalm 117:26) it is left
 * as printed rather than silently corrected. No Latin is vendored here: the
 * Douay translates the Clementine Vulgate, and no received Latin text of
 * these psalms was verified for this batch.
 */
export const prayerBatch7: CuratedEntry[] = [
  {
    contentType: "PRAYER",
    slug: "psalm-8",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21008.htm"],
    payload: {
      slug: "psalm-8",
      title: "Psalm 8: O Lord our Lord, how admirable is thy name",
      body: "Unto the end, for the presses: a psalm of David.\nO Lord our Lord, how admirable is thy name in the whole earth! For thy magnificence is elevated above the heavens.\nOut of the mouth of infants and of sucklings thou hast perfected praise, because of thy enemies, that thou mayst destroy the enemy and the avenger.\nFor I will behold thy heavens, the works of thy fingers: the moon and the stars which thou hast founded.\nWhat is man that thou art mindful of him? or the son of man that thou visitest him?\nThou hast made him a little less than the angels, thou hast crowned him with glory and honour:\nAnd hast set him over the works of thy hands.\nThou hast subjected all things under his feet, all sheep and oxen: moreover the beasts also of the fields.\nThe birds of the air, and the fishes of the sea, that pass through the paths of the sea.\nO Lord our Lord, how admirable is thy name in all the earth!",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "David's hymn on the majesty of God's name in the heavens and on the dignity he has given to man; the Letter to the Hebrews reads it of Christ (Hebrews 2:6-9). The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["lauds", "creation", "thanksgiving"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21008.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-15",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21015.htm"],
    payload: {
      slug: "psalm-15",
      title: "Psalm 15 (16): Preserve me, O Lord",
      body: "The inscription of a title to David himself. Preserve me, O Lord, for I have put my trust in thee.\nI have said to the Lord, thou art my God, for thou hast no need of my goods.\nTo the saints, who are in his land, he hath made wonderful all my desires in them.\nTheir infirmities were multiplied: afterwards they made haste. I will not gather together their meetings for blood offerings: nor will I be mindful of their names by my lips.\nThe Lord is the portion of my inheritance and of my cup: it is thou that wilt restore my inheritance to me.\nThe lines are fallen unto me in goodly places: for my inheritance is goodly to me.\nI will bless the Lord, who hath given me understanding: moreover my reins also have corrected me even till night.\nI set the Lord always in my sight: for he is at my right hand, that I be not moved.\nTherefore my heart hath been glad, and my tongue hath rejoiced: moreover my flesh also shall rest in hope.\nBecause thou wilt not leave my soul in hell; nor wilt thou give thy holy one to see corruption.\nThou hast made known to me the ways of life, thou shalt fill me with joy with thy countenance: at thy right hand are delights even to the end.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The psalm of the faithful soul whose portion is the Lord; Saint Peter cites its closing verses at Pentecost as a prophecy of the Resurrection (Acts 2:25-28). The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["trust", "easter"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21015.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-18",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21018.htm"],
    payload: {
      slug: "psalm-18",
      title: "Psalm 18 (19): The heavens shew forth the glory of God",
      body: "Unto the end. A psalm for David.\nThe heavens shew forth the glory of God, and the firmament declareth the work of his hands.\nDay to day uttereth speech, and night to night sheweth knowledge.\nThere are no speeches nor languages, where their voices are not heard.\nTheir sound hath gone forth into all the earth: and their words unto the ends of the world.\nHe hath set his tabernacle in the sun: and he, as a bridegroom coming out of his bride chamber, Hath rejoiced as a giant to run the way:\nHis going out is from the end of heaven, And his circuit even to the end thereof: and there is no one that can hide himself from his heat.\nThe law of the Lord is unspotted, converting souls: the testimony of the Lord is faithful, giving wisdom to little ones.\nThe justices of the Lord are right, rejoicing hearts: the commandment of the Lord is lightsome, enlightening the eyes.\nThe fear of the Lord is holy, enduring for ever and ever: the judgments of the Lord are true, justified in themselves.\nMore to be desired than gold and many precious stones: and sweeter than honey and the honeycomb.\nFor thy servant keepeth them, and in keeping them there is a great reward.\nWho can understand sins? from my secret ones cleanse me, O Lord:\nAnd from those of others spare thy servant. If they shall have no dominion over me, then shall I be without spot: and I shall be cleansed from the greatest sin.\nAnd the words of my mouth shall be such as may please: and the meditation of my heart always in thy sight. O Lord, my helper, and my redeemer.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "Two songs joined in one psalm: the wordless preaching of the heavens, and the praise of the law of the Lord that enlightens the eyes. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["lauds", "creation"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21018.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-21",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21021.htm"],
    payload: {
      slug: "psalm-21",
      title: "Psalm 21 (22): O God my God, look upon me",
      body: "Unto the end, for the morning protection, a psalm for David.\nO God my God, look upon me: why hast thou forsaken me? Far from my salvation are the words of my sins.\nO my God, I shall cry by day, and thou wilt not hear: and by night, and it shall not be reputed as folly in me.\nBut thou dwellest in the holy place, the praise of Israel.\nIn thee have our fathers hoped: they have hoped, and thou hast delivered them.\nThey cried to thee, and they were saved: they trusted in thee, and were not confounded.\nBut I am a worm, and no man: the reproach of men, and the outcast of the people.\nAll they that saw me have laughed me to scorn: they have spoken with the lips, and wagged the head.\nHe hoped in the Lord, let him deliver him: let him save him, seeing he delighteth in him.\nFor thou art he that hast drawn me out of the womb: my hope from the breasts of my mother.\nI was cast upon thee from the womb. From my mother's womb thou art my God,\nDepart not from me. For tribulation is very near: for there is none to help me.\nMany calves have surrounded me: fat bulls have besieged me.\nThey have opened their mouths against me, as a lion ravening and roaring.\nI am poured out like water; and all my bones are scattered. My heart is become like wax melting in the midst of my bowels.\nMy strength is dried up like a potsherd, and my tongue hath cleaved to my jaws: and thou hast brought me down into the dust of death.\nFor many dogs have encompassed me: the council of the malignant hath besieged me. They have dug my hands and feet.\nThey have numbered all my bones. And they have looked and stared upon me.\nThey parted my garments amongst them; and upon my vesture they cast lots.\nBut thou, O Lord, remove not thy help to a distance from me; look towards my defence.\nDeliver, O God, my soul from the sword: my only one from the hand of the dog.\nSave me from the lion's mouth; and my lowness from the horns of the unicorns.\nI will declare thy name to my brethren: in the midst of the church will I praise thee.\nYe that fear the Lord, praise him: all ye the seed of Jacob, glorify him.\nLet all the seed of Israel fear him: because he hath not slighted nor despised the supplication of the poor man. Neither hath he turned away his face from me: and when I cried to him he heard me.\nWith thee is my praise in a great church: I will pay my vows in the sight of them that fear him.\nThe poor shall eat and shall be filled: and they shall praise the Lord that seek him: their hearts shall live for ever and ever.\nAll the ends of the earth shall remember, and shall be converted to the Lord: And all the kindreds of the Gentiles shall adore in his sight.\nFor the kingdom is the Lord's; and he shall have dominion over the nations.\nAll the fat ones of the earth have eaten and have adored: all they that go down to the earth shall fall before him.\nAnd to him my soul shall live: and my seed shall serve him.\nThere shall be declared to the Lord a generation to come: and the heavens shall shew forth his justice to a people that shall be born, which the Lord hath made.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The psalm whose opening words our Lord prayed from the Cross (Matthew 27:46); its account of the pierced hands and feet and the divided garments is read by the Church as prophecy of the Passion. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["good-friday", "passion", "lent"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21021.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-22",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21022.htm"],
    payload: {
      slug: "psalm-22",
      title: "Psalm 22 (23): The Lord ruleth me",
      body: "A psalm for David. The Lord ruleth me: and I shall want nothing.\nHe hath set me in a place of pasture. He hath brought me up, on the water of refreshment:\nHe hath converted my soul. He hath led me on the paths of justice, for his own name's sake.\nFor though I should walk in the midst of the shadow of death, I will fear no evils, for thou art with me. Thy rod and thy staff, they have comforted me.\nThou hast prepared a table before me against them that afflict me. Thou hast anointed my head with oil; and my chalice which inebriateth me, how goodly is it!\nAnd thy mercy will follow me all the days of my life. And that I may dwell in the house of the Lord unto length of days.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The psalm of the Good Shepherd who leads his own to the water of refreshment and prepares a table for them; long prayed at funerals and after Communion. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["funerals", "trust", "after-communion"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21022.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-23",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21023.htm"],
    payload: {
      slug: "psalm-23",
      title: "Psalm 23 (24): The earth is the Lord's",
      body: "On the first day of the week, a psalm for David. The earth is the Lord's and the fulness thereof: the world, and all they that dwell therein.\nFor he hath founded it upon the seas; and hath prepared it upon the rivers.\nWho shall ascend into the mountain of the Lord: or who shall stand in his holy place?\nThe innocent in hands, and clean of heart, who hath not taken his soul in vain, nor sworn deceitfully to his neighbour.\nHe shall receive a blessing from the Lord, and mercy from God his Saviour.\nThis is the generation of them that seek him, of them that seek the face of the God of Jacob.\nLift up your gates, O ye princes, and be ye lifted up, O eternal gates: and the King of Glory shall enter in.\nWho is this King of Glory? the Lord who is strong and mighty: the Lord mighty in battle.\nLift up your gates, O ye princes, and be ye lifted up, O eternal gates: and the King of Glory shall enter in.\nWho is this King of Glory? the Lord of hosts, he is the King of Glory.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "A processional psalm asking who may ascend the mountain of the Lord, ending with the gates lifted up for the King of Glory; sung in the Church at Advent, the Ascension and the dedication of a church. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["advent", "ascension", "dedication"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21023.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-26",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21026.htm"],
    payload: {
      slug: "psalm-26",
      title: "Psalm 26 (27): The Lord is my light and my salvation",
      body: "The psalm of David before he was anointed. The Lord is my light and my salvation, whom shall I fear? The Lord is the protector of my life: of whom shall I be afraid?\nWhilst the wicked draw near against me, to eat my flesh. My enemies that trouble me, have themselves been weakened, and have fallen.\nIf armies in camp should stand together against me, my heart shall not fear. If a battle should rise up against me, in this will I be confident.\nOne thing I have asked of the Lord, this will I seek after; that I may dwell in the house of the Lord all the days of my life. That I may see the delight of the Lord, and may visit his temple.\nFor he hath hidden me in his tabernacle; in the day of evils, he hath protected me in the secret place of his tabernacle.\nHe hath exalted me upon a rock: and now he hath lifted up my head above my enemies. I have gone round, and have offered up in his tabernacle a sacrifice of jubilation: I will sing, and recite a psalm to the Lord.\nHear, O Lord, my voice, with which I have cried to thee: have mercy on me and hear me.\nMy heart hath said to thee: My face hath sought thee: thy face, O Lord, will I still seek.\nTurn not away thy face from me; decline not in thy wrath from thy servant. Be thou my helper, forsake me not; do not thou despise me, O God my Saviour.\nFor my father and my mother have left me: but the Lord hath taken me up.\nSet me, O Lord, a law in thy way, and guide me in the right path, because of my enemies.\nDeliver me not over to the will of them that trouble me; for unjust witnesses have risen up against me; and iniquity hath lied to itself.\nI believe to see the good things of the Lord in the land of the living.\nExpect the Lord, do manfully, and let thy heart take courage, and wait thou for the Lord.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "A psalm of confidence in the face of enemies, whose one desire is to dwell in the house of the Lord all the days of one's life. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["trust", "lent"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21026.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-33",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21033.htm"],
    payload: {
      slug: "psalm-33",
      title: "Psalm 33 (34): I will bless the Lord at all times",
      body: "For David, when he changed his countenance before Achimelech, who dismissed him, and he went his way.\nI will bless the Lord at all times, his praise shall be always in my mouth.\nIn the Lord shall my soul be praised: let the meek hear and rejoice.\nO magnify the Lord with me; and let us extol his name together.\nI sought the Lord, and he heard me; and he delivered me from all my troubles.\nCome ye to him and be enlightened: and your faces shall not be confounded.\nThis poor man cried, and the Lord heard him: and saved him out of all his troubles.\nThe angel of the Lord shall encamp round about them that fear him: and shall deliver them.\nO taste, and see that the Lord is sweet: blessed is the man that hopeth in him.\nFear the Lord, all ye his saints: for there is no want to them that fear him.\nThe rich have wanted, and have suffered hunger: but they that seek the Lord shall not be deprived of any good.\nCome, children, hearken to me: I will teach you the fear of the Lord.\nWho is the man that desireth life: who loveth to see good days?\nKeep thy tongue from evil, and thy lips from speaking guile.\nTurn away from evil and do good: seek after peace and pursue it.\nThe eyes of the Lord are upon the just: and his ears unto their prayers.\nBut the countenance of the Lord is against them that do evil things: to cut off the remembrance of them from the earth.\nThe just cried, and the Lord heard them: and delivered them out of all their troubles.\nThe Lord is nigh unto them that are of a contrite heart: and he will save the humble of spirit.\nMany are the afflictions of the just; but out of them all will the Lord deliver them.\nThe Lord keepeth all their bones, not one of them shall be broken.\nThe death of the wicked is very evil: and they that hate the just shall be guilty.\nThe Lord will redeem the souls of his servants: and none of them that trust in him shall offend.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "An alphabetical psalm of thanksgiving; its verse 'O taste, and see that the Lord is sweet' has long been sung as a Communion antiphon. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["thanksgiving", "after-communion"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21033.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-41",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21041.htm"],
    payload: {
      slug: "psalm-41",
      title: "Psalm 41 (42): As the hart panteth after the fountains of water",
      body: "Unto the end, understanding for the sons of Core.\nAs the hart panteth after the fountains of water; so my soul panteth after thee, O God.\nMy soul hath thirsted after the strong living God; when shall I come and appear before the face of God?\nMy tears have been my bread day and night, whilst it is said to me daily: Where is thy God?\nThese things I remembered, and poured out my soul in me: for I shall go over into the place of the wonderful tabernacle, even to the house of God: With the voice of joy and praise; the noise of one feasting.\nWhy art thou sad, O my soul? and why dost thou trouble me? Hope in God, for I will still give praise to him: the salvation of my countenance,\nAnd my God. My soul is troubled within myself: therefore will I remember thee from the land of Jordan and Hermoniim, from the little hill.\nDeep calleth on deep, at the noise of thy flood-gates. All thy heights and thy billows have passed over me.\nIn the daytime the Lord hath commanded his mercy; and a canticle to him in the night. With me is prayer to the God of my life.\nI will say to God: Thou art my support. Why hast thou forgotten me? and why go I mourning, whilst my enemy afflicteth me?\nWhilst my bones are broken, my enemies who trouble me have reproached me; Whilst they say to me day by day: Where is thy God?\nWhy art thou cast down, O my soul? and why dost thou disquiet me? Hope thou in God, for I will still give praise to him: the salvation of my countenance, and my God.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The exile's longing for the courts of God, sung at the Easter Vigil and associated from the earliest centuries with those preparing for Baptism. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["easter-vigil", "baptism", "longing"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21041.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-45",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21045.htm"],
    payload: {
      slug: "psalm-45",
      title: "Psalm 45 (46): Our God is our refuge and strength",
      body: "Unto the end, for the sons of Core, for the hidden.\nOur God is our refuge and strength: a helper in troubles, which have found us exceedingly.\nTherefore we will not fear, when the earth shall be troubled; and the mountains shall be removed into the heart of the sea.\nTheir waters roared and were troubled: the mountains were troubled with his strength.\nThe stream of the river maketh the city of God joyful: the most High hath sanctified his own tabernacle.\nGod is in the midst thereof, it shall not be moved: God will help it in the morning early.\nNations were troubled, and kingdoms were bowed down: he uttered his voice, the earth trembled.\nThe Lord of armies is with us: the God of Jacob is our protector.\nCome and behold ye the works of the Lord: what wonders he hath done upon earth,\nMaking wars to cease even to the end of the earth. He shall destroy the bow, and break the weapons: and the shield he shall burn in the fire.\nBe still and see that I am God; I will be exalted among the nations, and I will be exalted in the earth.\nThe Lord of armies is with us: the God of Jacob is our protector.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "A song of Sion untroubled amid the raging of the nations, with the refrain 'The Lord of armies is with us: the God of Jacob is our protector.' The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["trust", "times-of-trouble"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21045.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-50",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21050.htm"],
    payload: {
      slug: "psalm-50",
      title: "Psalm 50 (51): Miserere: Have mercy on me, O God",
      body: "Unto the end, a psalm of David,\nWhen Nathan the prophet came to him after he had sinned with Bethsabee.\nHave mercy on me, O God, according to thy great mercy. And according to the multitude of thy tender mercies blot out my iniquity.\nWash me yet more from my iniquity, and cleanse me from my sin.\nFor I know my iniquity, and my sin is always before me.\nTo thee only have I sinned, and have done evil before thee: that thou mayst be justified in thy words and mayst overcome when thou art judged.\nFor behold I was conceived in iniquities; and in sins did my mother conceive me.\nFor behold thou hast loved truth: the uncertain and hidden things of thy wisdom thou hast made manifest to me.\nThou shalt sprinkle me with hyssop, and I shall be cleansed: thou shalt wash me, and I shall be made whiter than snow.\nTo my hearing thou shalt give joy and gladness: and the bones that have been humbled shall rejoice.\nTurn away thy face from my sins, and blot out all my iniquities.\nCreate a clean heart in me, O God: and renew a right spirit within my bowels.\nCast me not away from thy face; and take not thy holy spirit from me.\nRestore unto me the joy of thy salvation, and strengthen me with a perfect spirit.\nI will teach the unjust thy ways: and the wicked shall be converted to thee.\nDeliver me from blood, O God, thou God of my salvation: and my tongue shall extol thy justice.\nO Lord, thou wilt open my lips: and my mouth shall declare thy praise.\nFor if thou hadst desired sacrifice, I would indeed have given it: with burnt offerings thou wilt not be delighted.\nA sacrifice to God is an afflicted spirit: a contrite and humbled heart, O God, thou wilt not despise.\nDeal favourably, O Lord, in thy good will with Sion; that the walls of Jerusalem may be built up.\nThen shalt thou accept the sacrifice of justice, oblations and whole burnt offerings: then shall they lay calves upon thy altar.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The Miserere, the chief of the seven Penitential Psalms, prayed by David after the rebuke of the prophet Nathan and used every Friday at Morning Prayer in the Roman Office. Verses 1-2 are the psalm's title as printed in the Douay-Rheims. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["lent", "penance"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21050.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-61",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21061.htm"],
    payload: {
      slug: "psalm-61",
      title: "Psalm 61 (62): Shall not my soul be subject to God?",
      body: "Unto the end, for Idithun, a psalm of David.\nShall not my soul be subject to God? for from him is my salvation.\nFor he is my God and my saviour: he is my protector, I shall be moved no more.\nHow long do you rush in upon a man? you all kill, as if you were thrusting down a leaning wall, and a tottering fence.\nBut they have thought to cast away my price; I ran in thirst: they blessed with their mouth, but cursed with their heart.\nBut be thou, O my soul, subject to God: for from him is my patience.\nFor he is my God and my saviour: he is my helper, I shall not be moved.\nIn God is my salvation and my glory: he is the God of my help, and my hope is in God.\nTrust in him, all ye congregation of people: pour out your hearts before him. God is our helper for ever.\nBut vain are the sons of men, the sons of men are liars in the balances: that by vanity they may together deceive.\nTrust not in iniquity, and cover not robberies: if riches abound, set not your heart upon them.\nGod hath spoken once, these two things have I heard, that power belongeth to God,\nAnd mercy to thee, O Lord; for thou wilt render to every man according to his works.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "A psalm of quiet confidence: God alone is rock and salvation, and riches and men are but vanity. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["trust", "evening"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21061.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-62",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21062.htm"],
    payload: {
      slug: "psalm-62",
      title: "Psalm 62 (63): O God, my God, to thee do I watch at break of day",
      body: "A psalm of David when he was in the desert of Edom.\nO God, my God, to thee do I watch at break of day. For thee my soul hath thirsted; for thee my flesh, O how many ways!\nIn a desert land, and where there is no way, and no water: so in the sanctuary have I come before thee, to see thy power and thy glory.\nFor thy mercy is better than lives: thee my lips shall praise.\nThus will I bless thee all my life long: and in thy name I will lift up my hands.\nLet my soul be filled as with marrow and fatness: and my mouth shall praise thee with joyful lips.\nIf I have remembered thee upon my bed, I will meditate on thee in the morning:\nBecause thou hast been my helper. And I will rejoice under the covert of thy wings:\nMy soul hath stuck close to thee: thy right hand hath received me.\nBut they have sought my soul in vain, they shall go into the lower parts of the earth:\nThey shall be delivered into the hands of the sword, they shall be the portions of foxes.\nBut the king shall rejoice in God, all they shall be praised that swear by him: because the mouth is stopped of them that speak wicked things.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The morning psalm of thirst for God, prayed at Lauds from the earliest ages of the Church. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["lauds", "morning", "adoration"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21062.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-66",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21066.htm"],
    payload: {
      slug: "psalm-66",
      title: "Psalm 66 (67): May God have mercy on us, and bless us",
      body: "Unto the end, in, hymns, a psalm of a canticle for David.\nMay God have mercy on us, and bless us: may he cause the light of his countenance to shine upon us, and may he have mercy on us.\nThat we may know thy way upon earth: thy salvation in all nations.\nLet people confess to thee, O God: let all people give praise to thee.\nLet the nations be glad and rejoice: for thou judgest the people with justice, and directest the nations upon earth.\nLet the people, O God, confess to thee: let all the people give praise to thee:\nThe earth hath yielded her fruit. May God, our God bless us,\nMay God bless us: and all the ends of the earth fear him.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "A harvest blessing turned into a prayer that all nations may know God's way upon earth; often prayed for the missions and as a grace of blessing. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["lauds", "missions", "blessing"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21066.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-83",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21083.htm"],
    payload: {
      slug: "psalm-83",
      title: "Psalm 83 (84): How lovely are thy tabernacles",
      body: "Unto the end, for the winepresses, a psalm for the sons of Core.\nHow lovely are thy tabernacles, O Lord of hosts!\nMy soul longeth and fainteth for the courts of the Lord. My heart and my flesh have rejoiced in the living God.\nFor the sparrow hath found herself a house, and the turtle a nest for herself where she may lay her young ones: Thy altars, O Lord of hosts, my king and my God.\nBlessed are they that dwell in thy house, O Lord: they shall praise thee for ever and ever.\nBlessed is the man whose help is from thee: in his heart he hath disposed to ascend by steps,\nIn the vale of tears, in the place which he hath set.\nFor the lawgiver shall give a blessing, they shall go from virtue to virtue: the God of gods shall be seen in Sion.\nO Lord God of hosts, hear my prayer: give ear, O God of Jacob.\nBehold, O God our protector: and look on the face of thy Christ.\nFor better is one day in thy courts above thousands. I have chosen to be an abject in the house of my God, rather than to dwell in the tabernacles of sinners.\nFor God loveth mercy and truth: the Lord will give grace and glory.\nHe will not deprive of good things them that walk in innocence: O Lord of hosts, blessed is the man that trusteth in thee.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The pilgrim's love for the house of the Lord, better one day in his courts than thousands elsewhere; sung at the dedication of a church. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["dedication", "pilgrimage", "adoration"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21083.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-89",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21089.htm"],
    payload: {
      slug: "psalm-89",
      title: "Psalm 89 (90): Lord, thou hast been our refuge",
      body: "A prayer of Moses the man of God. Lord, thou hast been our refuge from generation to generation.\nBefore the mountains were made, or the earth and the world was formed; from eternity and to eternity thou art God.\nTurn not man away to be brought low: and thou hast said: Be converted, O ye sons of men.\nFor a thousand years in thy sight are as yesterday, which is past. And as a watch in the night,\nThings that are counted nothing, shall their years be.\nIn the morning man shall grow up like grass; in the morning he shall flourish and pass away: in the evening he shall fall, grow dry, and wither.\nFor in thy wrath we have fainted away: and are troubled in thy indignation.\nThou hast set our iniquities before thy eyes: our life in the light of thy countenance.\nFor all our days are spent; and in thy wrath we have fainted away. Our years shall be considered as a spider:\nThe days of our years in them are threescore and ten years. But if in the strong they be fourscore years: and what is more of them is labour and sorrow. For mildness is come upon us: and we shall be corrected.\nWho knoweth the power of thy anger, and for thy fear\nCan number thy wrath? So make thy right hand known: and men learned in heart, in wisdom.\nReturn, O Lord, how long? and be entreated in favour of thy servants.\nWe are filled in the morning with thy mercy: and we have rejoiced, and are delighted all our days.\nWe have rejoiced for the days in which thou hast humbled us: for the years in which we have seen evils.\nLook upon thy servants and upon their works: and direct their children.\nAnd let the brightness of the Lord our God be upon us: and direct thou the works of our hands over us; yea, the work of our hands do thou direct.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "A prayer of Moses on the brevity of human life before the eternity of God, asking that we may number our days and be filled with his mercy. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["funerals", "lent"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21089.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-90",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21090.htm"],
    payload: {
      slug: "psalm-90",
      title: "Psalm 90 (91): He that dwelleth in the aid of the most High",
      body: "The praise of a canticle for David. He that dwelleth in the aid of the most High, shall abide under the protection of the God of Jacob.\nHe shall say to the Lord: Thou art my protector, and my refuge: my God, in him will I trust.\nFor he hath delivered me from the snare of the hunters: and from the sharp word.\nHe will overshadow thee with his shoulders: and under his wings thou shalt trust.\nHis truth shall compass thee with a shield: thou shalt not be afraid of the terror of the night.\nOf the arrow that flieth in the day, of the business that walketh about in the dark: of invasion, or of the noonday devil.\nA thousand shall fall at thy side, and ten thousand at thy right hand: but it shall not come nigh thee.\nBut thou shalt consider with thy eyes: and shalt see the reward of the wicked.\nBecause thou, O Lord, art my hope: thou hast made the most High thy refuge.\nThere shall no evil come to thee: nor shall the scourge come near thy dwelling.\nFor he hath given his angels charge over thee; to keep thee in all thy ways.\nIn their hands they shall bear thee up: lest thou dash thy foot against a stone.\nThou shalt walk upon the asp and the basilisk: and thou shalt trample under foot the lion and the dragon.\nBecause he hoped in me I will deliver him: I will protect him because he hath known my name.\nHe shall cry to me, and I will hear him: I am with him in tribulation, I will deliver him, and I will glorify him.\nI will fill him with length of days; and I will shew him my salvation.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The psalm of the Lord's protection under whose wings the faithful take refuge; read on the First Sunday of Lent (the devil quotes it in the temptation, Matthew 4:6) and prayed at Compline. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["compline", "lent", "protection"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21090.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-94",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21094.htm"],
    payload: {
      slug: "psalm-94",
      title: "Psalm 94 (95): Venite: Come let us praise the Lord with joy",
      body: "Come let us praise the Lord with joy: let us joyfully sing to God our saviour.\nLet us come before his presence with thanksgiving; and make a joyful noise to him with psalms.\nFor the Lord is a great God, and a great King above all gods.\nFor in his hand are all the ends of the earth: and the heights of the mountains are his.\nFor the sea is his, and he made it: and his hands formed the dry land.\nCome let us adore and fall down: and weep before the Lord that made us.\nFor he is the Lord our God: and we are the people of his pasture and the sheep of his hand.\nToday if you shall hear his voice, harden not your hearts:\nAs in the provocation, according to the day of temptation in the wilderness: where your fathers tempted me, they proved me, and saw my works.\nForty years long was I offended with that generation, and I said: These always err in heart.\nAnd these men have not known my ways: so I swore in my wrath that they shall not enter into my rest.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The Venite, the Invitatory psalm with which the Church opens the daily Office, calling the faithful to worship and warning them not to harden their hearts. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["invitatory", "office", "morning"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21094.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-99",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21099.htm"],
    payload: {
      slug: "psalm-99",
      title: "Psalm 99 (100): Jubilate: Sing joyfully to God, all the earth",
      body: "A psalm of praise.\nSing joyfully to God, all the earth: serve ye the Lord with gladness. Come in before his presence with exceeding great joy.\nKnow ye that the Lord he is God: he made us, and not we ourselves. We are his people and the sheep of his pasture.\nGo ye into his gates with praise, into his courts with hymns: and give glory to him. Praise ye his name:\nFor the Lord is sweet, his mercy endureth for ever, and his truth to generation and generation.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "A short psalm of praise summoning all the earth into God's courts, one of the psalms of Lauds in the Roman Office. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["lauds", "thanksgiving"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21099.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-102",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21102.htm"],
    payload: {
      slug: "psalm-102",
      title: "Psalm 102 (103): Bless the Lord, O my soul",
      body: "For David himself. Bless the Lord, O my soul: and let all that is within me bless his holy name.\nBless the Lord, O my soul, and never forget all he hath done for thee.\nWho forgiveth all thy iniquities: who healeth all thy diseases.\nWho redeemeth thy life from destruction: who crowneth thee with mercy and compassion.\nWho satisfieth thy desire with good things: thy youth shall be renewed like the eagle's.\nThe Lord doth mercies, and judgment for all that suffer wrong.\nHe hath made his ways known to Moses: his wills to the children of Israel.\nThe Lord is compassionate and merciful: longsuffering and plenteous in mercy.\nHe will not always be angry: nor will he threaten for ever.\nHe hath not dealt with us according to our sins: nor rewarded us according to our iniquities.\nFor according to the height of the heaven above the earth: he hath strengthened his mercy towards them that fear him.\nAs far as the east is from the west, so far hath he removed our iniquities from us.\nAs a father hath compassion on his children, so hath the Lord compassion on them that fear him:\nFor he knoweth our frame. He remembereth that we are dust:\nMan's days are as grass, as the flower of the field so shall he flourish.\nFor the spirit shall pass in him, and he shall not be: and he shall know his place no more.\nBut the mercy of the Lord is from eternity and unto eternity upon them that fear him: And his justice unto children's children,\nTo such as keep his covenant, And are mindful of his commandments to do them.\nThe Lord hath prepared his throne in heaven: and his kingdom shall rule over all.\nBless the Lord, all ye his angels: you that are mighty in strength, and execute his word, hearkening to the voice of his orders.\nBless the Lord, all ye his hosts: you ministers of his that do his will.\nBless the Lord, all his works: in every place of his dominion, O my soul, bless thou the Lord.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The great psalm of God's mercy, who forgives all our iniquities and remembers that we are dust, as far as the east is from the west removing our sins from us. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["mercy", "thanksgiving"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21102.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-103",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21103.htm"],
    payload: {
      slug: "psalm-103",
      title:
        "Psalm 103 (104): Bless the Lord, O my soul: O Lord my God, thou art exceedingly great",
      body: "For David himself. Bless the Lord, O my soul: O Lord my God, thou art exceedingly great. Thou hast put on praise and beauty:\nAnd art clothed with light as with a garment. Who stretchest out the heaven like a pavilion:\nWho coverest the higher rooms thereof with water. Who makest the clouds thy chariot: who walkest upon the wings of the winds.\nWho makest thy angels spirits: and thy ministers a burning fire.\nWho hast founded the earth upon its own bases: it shall not be moved for ever and ever.\nThe deep like a garment is its clothing: above the mountains shall the waters stand.\nAt thy rebuke they shall flee: at the voice of thy thunder they shall fear.\nThe mountains ascend, and the plains descend into the place which thou hast founded for them.\nThou hast set a bound which they shall not pass over; neither shall they return to cover the earth.\nThou sendest forth springs in the vales: between the midst of the hills the waters shall pass.\nAll the beasts of the field shall drink: the wild asses shall expect in their thirst.\nOver them the birds of the air shall dwell: from the midst of the rocks they shall give forth their voices.\nThou waterest the hills from thy upper rooms: the earth shall be filled with the fruit of thy works:\nBringing forth grass for cattle, and herb for the service of men. That thou mayst bring bread out of the earth:\nAnd that wine may cheer the heart of man. That he may make the face cheerful with oil: and that bread may strengthen man's heart.\nThe trees of the field shall be filled, and the cedars of Libanus which he hath planted:\nThere the sparrows shall make their nests. The highest of them is the house of the heron.\nThe high hills are a refuge for the harts, the rock for the irchins.\nHe hath made the moon for seasons: the sun knoweth his going down.\nThou hast appointed darkness, and it is night: in it shall all the beasts of the woods go about:\nThe young lions roaring after their prey, and seeking their meat from God.\nThe sun ariseth, and they are gathered together: and they shall lie down in their dens.\nMan shall go forth to his work, and to his labour until the evening.\nHow great are thy works, O Lord? thou hast made all things in wisdom: the earth is filled with thy riches.\nSo is this great sea, which stretcheth wide its arms: there are creeping things without number: Creatures little and great.\nThere the ships shall go. This sea dragon which thou hast formed to play therein.\nAll expect of thee that thou give them food in season.\nWhat thou givest to them they shall gather up: when thou openest thy hand, they shall all be filled with good.\nBut if thou turnest away thy face, they shall be troubled: thou shalt take away their breath, and they shall fail, and shall return to their dust.\nThou shalt send forth thy spirit, and they shall be created: and thou shalt renew the face of the earth.\nMay the glory of the Lord endure for ever: the Lord shall rejoice in his works.\nHe looketh upon the earth, and maketh it tremble: he toucheth the mountains, and they smoke.\nI will sing to the Lord as long as I live: I will sing praise to my God while I have my being.\nLet my speech be acceptable to him: but I will take delight in the Lord.\nLet sinners be consumed out of the earth, and the unjust, so that they be no more: O my soul, bless thou the Lord.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "A hymn to the Creator who clothes himself with light and renews the face of the earth; its verse 'Send forth thy spirit' is sung by the Church at Pentecost. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["pentecost", "creation"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21103.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-109",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21109.htm"],
    payload: {
      slug: "psalm-109",
      title: "Psalm 109 (110): Dixit Dominus: The Lord said to my Lord",
      body: "The Lord said to my Lord: Sit thou at my right hand: Until I make thy enemies thy footstool.\nThe Lord will send forth the sceptre of thy power out of Sion: rule thou in the midst of thy enemies.\nWith thee is the principality in the day of thy strength: in the brightness of the saints: from the womb before the day star I begot thee.\nThe Lord hath sworn, and he will not repent: Thou art a priest for ever according to the order of Melchisedech.\nThe Lord at thy right hand hath broken kings in the day of his wrath.\nHe shall judge among nations, he shall fill ruins: he shall crush the heads in the land of the many.\nHe shall drink of the torrent in the way: therefore shall he lift up the head.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The messianic psalm of the priest-king after the order of Melchisedech, cited by our Lord himself (Matthew 22:44); the first psalm of Sunday Vespers in the Roman Office. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["vespers"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21109.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-112",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21112.htm"],
    payload: {
      slug: "psalm-112",
      title: "Psalm 112 (113): Laudate pueri: Praise the Lord, ye children",
      body: "Praise the Lord, ye children: praise ye the name of the Lord.\nBlessed be the name of the Lord, from henceforth now and for ever.\nFrom the rising of the sun unto the going down of the same, the name of the Lord is worthy of praise.\nThe Lord is high above all nations; and his glory above the heavens.\nWho is as the Lord our God, who dwelleth on high:\nAnd looketh down on the low things in heaven and in earth?\nRaising up the needy from the earth, and lifting up the poor out of the dunghill:\nThat he may place him with princes, with the princes of his people.\nWho maketh a barren woman to dwell in a house, the joyful mother of children.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "One of the Hallel psalms sung at the Pasch and a psalm of Sunday Vespers, praising the God who lifts up the needy from the dunghill. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["vespers"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21112.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-115",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21115.htm"],
    payload: {
      slug: "psalm-115",
      title: "Psalm 115 (116:10-19): I have believed, therefore have I spoken",
      body: "I have believed, therefore have I spoken; but I have been humbled exceedingly.\nI said in my excess: Every man is a liar.\nWhat shall I render to the Lord, for all the things he hath rendered unto me?\nI will take the chalice of salvation; and I will call upon the name of the Lord.\nI will pay my vows to the Lord before all his people:\nPrecious in the sight of the Lord is the death of his saints.\nO Lord, for I am thy servant: I am thy servant, and the son of thy handmaid. Thou hast broken my bonds:\nI will sacrifice to thee the sacrifice of praise, and I will call upon the name of the Lord.\nI will pay my vows to the Lord in the sight of all his people:\nIn the courts of the house of the Lord, in the midst of thee, O Jerusalem.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "A psalm of thanksgiving for deliverance, containing the verse 'I will take the chalice of salvation'; in the Vulgate numbering it is Psalm 115, which the modern numbering counts as Psalm 116:10-19. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["thanksgiving", "after-communion"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21115.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-117",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21117.htm"],
    payload: {
      slug: "psalm-117",
      title: "Psalm 117 (118): Give praise to the Lord, for he is good",
      body: "Give praise to the Lord, for he is good: for his mercy endureth for ever.\nLet Israel now say that he is good: that his mercy endureth for ever.\nLet the house of Aaron now say, that his mercy endureth for ever.\nLet them that fear the Lord now say, that his mercy endureth for ever.\nIn my trouble I called upon the Lord: and the Lord heard me, and enlarged me.\nThe Lord is my helper, I will not fear what man can do unto me.\nThe Lord is my helper: and I will look over my enemies.\nIt is good to confide in the Lord, rather than to have confidence in man.\nIt is good to trust in the Lord, rather than to trust in princes.\nAll nations compassed me about; and in the name of the Lord I have been revenged on them.\nSurrounding me they compassed me about: and in the name of the Lord I have been revenged on them.\nThey surrounded me like bees, and they burned like fire among thorns: and in the name of the Lord I was revenged on them.\nBeing pushed I was overturned that I might fall: but the Lord supported me.\nThe Lord is my strength and my praise: and he is become my salvation.\nThe voice of rejoicing and of salvation is in the tabernacles of the just.\nThe right hand of the Lord hath wrought strength: the right hand of the Lord hath exulted me: the right hand of the Lord hath wrought strength.\nI shall not die, but live: and shall declare the works of the Lord.\nThe Lord chastising hath chastised me: but he hath not delivered me over to death.\nOpen ye to me the gates of justice: I will go into them, and give praise to the Lord.\nThis is the gate of the Lord, the just shall enter into it.\nI will give glory to thee because thou hast heard me: and art become my salvation.\nThe stone which the builders rejected; the same is become the head of the corner.\nThis is the Lord's doing: and it is wonderful in our eyes.\nThis is the day which the Lord hath made: let us be glad and rejoice therein.\nO Lord, save me: O Lord, give good success.\nBlessed be he that cometh in the name Lord. We have blessed you out of the house of the Lord.\nThe Lord is God, and he hath shone upon us. Appoint a solemn day, with shady boughs, even to the horn of the altar.\nThou art my God, and I will praise thee: thou art my God, and I will exalt thee. I will praise thee, because thou hast heard me, and art become my salvation.\nO praise ye the Lord, for he is good: for his mercy endureth for ever.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The paschal psalm of the stone rejected by the builders and of 'This is the day which the Lord hath made'; its 'Blessed is he that cometh in the name of the Lord' was sung to Christ on Palm Sunday. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["easter", "palm-sunday", "thanksgiving"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21117.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-120",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21120.htm"],
    payload: {
      slug: "psalm-120",
      title: "Psalm 120 (121): I have lifted up my eyes to the mountains",
      body: "I have lifted up my eyes to the mountains, from whence help shall come to me.\nMy help is from the Lord, who made heaven and earth.\nMay he not suffer thy foot to be moved: neither let him slumber that keepeth thee.\nBehold he shall neither slumber nor sleep, that keepeth Israel.\nThe Lord is thy keeper, the Lord is thy protection upon thy right hand.\nThe sun shall not burn thee by day: nor the moon by night.\nThe Lord keepeth thee from all evil: may the Lord keep thy soul.\nMay the Lord keep thy coming in and thy going out; from henceforth now and for ever.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "A gradual psalm of the pilgrim going up to Jerusalem, confident that the keeper of Israel neither slumbers nor sleeps; long prayed by travellers. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["travel", "trust"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21120.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-121",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21121.htm"],
    payload: {
      slug: "psalm-121",
      title: "Psalm 121 (122): I rejoiced at the things that were said to me",
      body: "I rejoiced at the things that were said to me: We shall go into the house of the Lord.\nOur feet were standing in thy courts, O Jerusalem.\nJerusalem, which is built as a city, which is compact together.\nFor thither did the tribes go up, the tribes of the Lord: the testimony of Israel, to praise the name of the Lord.\nBecause their seats have sat in judgment, seats upon the house of David.\nPray ye for the things that are for the peace of Jerusalem: and abundance for them that love thee.\nLet peace be in thy strength: and abundance in thy towers.\nFor the sake of my brethren, and of my neighbours, I spoke peace of thee.\nBecause of the house of the Lord our God, I have sought good things for thee.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The pilgrim's joy at entering the house of the Lord, with its prayer for the peace of Jerusalem. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["pilgrimage", "dedication"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21121.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-130",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21130.htm"],
    payload: {
      slug: "psalm-130",
      title: "Psalm 130 (131): Lord, my heart is not exalted",
      body: "Lord, my heart is not exalted: nor are my eyes lofty. Neither have I walked in great matters, nor in wonderful things above me.\nIf I was not humbly minded, but exalted my soul: As a child that is weaned is towards his mother, so reward in my soul.\nLet Israel hope in the Lord, from henceforth now and for ever.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "A very short gradual psalm of humility and childlike trust, the soul quieted as a weaned child upon its mother. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["humility", "trust"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21130.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-138",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21138.htm"],
    payload: {
      slug: "psalm-138",
      title: "Psalm 138 (139): Lord, thou hast proved me, and known me",
      body: "Lord, thou hast proved me, and known me:\nThou hast known my sitting down, and my rising up.\nThou hast understood my thoughts afar off: my path and my line thou hast searched out.\nAnd thou hast foreseen all my ways: for there is no speech in my tongue.\nBehold, O Lord, thou hast known all things, the last and those of old: thou hast formed me, and hast laid thy hand upon me.\nThy knowledge is become wonderful to me: it is high, and I cannot reach to it.\nWhither shall I go from thy spirit? or whither shall I flee from thy face?\nIf I ascend into heaven, thou art there: if I descend into hell, thou art present.\nIf I take my wings early in the morning, and dwell in the uttermost parts of the sea:\nEven there also shall thy hand lead me: and thy right hand shall hold me.\nAnd I said: Perhaps darkness shall cover me: and night shall be my light in my pleasures.\nBut darkness shall not be dark to thee, and night shall be light as day: the darkness thereof, and the light thereof are alike to thee.\nFor thou hast possessed my reins: thou hast protected me from my mother's womb.\nI will praise thee, for thou art fearfully magnified: wonderful are thy works, and my soul knoweth right well.\nMy bone is not hidden from thee, which thou hast made in secret: and my substance in the lower parts of the earth.\nThy eyes did see my imperfect being, and in thy book all shall be written: days shall be formed, and no one in them.\nBut to me thy friends, O God, are made exceedingly honourable: their principality is exceedingly strengthened.\nI will number them, and they shall be multiplied above the sand: I rose up and am still with thee.\nIf thou wilt kill the wicked, O God: ye men of blood, depart from me:\nBecause you say in thought: They shall receive thy cities in vain.\nHave I not hated them, O Lord, that hated thee: and pine away because of thy enemies?\nI have hated them with a perfect hatred: and they are become enemies to me.\nProve me, O God, and know my heart: examine me, and know my paths.\nAnd see if there be in me the way of iniquity: and lead me in the eternal way.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The psalm of God's all-seeing knowledge and inescapable presence, ending with the prayer that he would search the heart and lead it in the eternal way. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["adoration", "examination-of-conscience"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21138.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-142",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21142.htm"],
    payload: {
      slug: "psalm-142",
      title: "Psalm 142 (143): Hear, O Lord, my prayer",
      body: "Hear, O Lord, my prayer: give ear to my supplication in thy truth: hear me in thy justice.\nAnd enter not into judgment with thy servant: for in thy sight no man living shall be justified.\nFor the enemy hath persecuted my soul: he hath brought down my life to the earth. He hath made me to dwell in darkness as those that have been dead of old:\nAnd my spirit is in anguish within me: my heart within me is troubled.\nI remembered the days of old, I meditated on all thy works: I meditated upon the works of thy hands.\nI stretched forth my hands to thee: my soul is as earth without water unto thee.\nHear me speedily, O Lord: my spirit hath fainted away. Turn not away thy face from me, lest I be like unto them that go down into the pit.\nCause me to hear thy mercy in the morning; for in thee have I hoped. Make the way known to me, wherein I should walk: for I have lifted up my soul to thee.\nDeliver me from my enemies, O Lord, to thee have I fled:\nTeach me to do thy will, for thou art my God. Thy good spirit shall lead me into the right land:\nFor thy name's sake, O Lord, thou wilt quicken me in thy justice. Thou wilt bring my soul out of trouble:\nAnd in thy mercy thou wilt destroy my enemies. And thou wilt cut off all them that afflict my soul: for I am thy servant.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The last of the seven Penitential Psalms, pleading that God enter not into judgment with his servant, and asking to be taught to do his will. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["lent", "penance"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21142.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-149",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21149.htm"],
    payload: {
      slug: "psalm-149",
      title: "Psalm 149: Sing ye to the Lord a new canticle",
      body: "Sing ye to the Lord a new canticle: let his praise be in the church of the saints.\nLet Israel rejoice in him that made him: and let the children of Sion be joyful in their king.\nLet them praise his name in choir: let them sing to him with the timbrel and the psaltery.\nFor the Lord is well pleased with his people: and he will exalt the meek unto salvation.\nThe saints shall rejoice in glory: they shall be joyful in their beds.\nThe high praise of God shall be in their mouth: and two-edged swords in their hands:\nTo execute vengeance upon the nations, chastisements among the people:\nTo bind their kings with fetters, and their nobles with manacles of iron.\nTo execute upon them the judgment that is written: this glory is to all his saints. Alleluia.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "A psalm of the praise of God in the assembly of the saints, sung at Lauds in the Roman Office. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["lauds", "all-saints", "praise"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21149.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "psalm-150",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/21150.htm"],
    payload: {
      slug: "psalm-150",
      title: "Psalm 150: Praise ye the Lord in his holy places",
      body: "Praise ye the Lord in his holy places: praise ye him in the firmament of his power.\nPraise ye him for his mighty acts: praise ye him according to the multitude of his greatness.\nPraise him with sound of trumpet: praise him with psaltery and harp.\nPraise him with timbrel and choir: praise him with strings and organs.\nPraise him on high sounding cymbals: praise him on cymbals of joy: let every spirit praise the Lord. Alleluia.",
      prayerType: "psalm",
      category: "liturgical",
      language: "en",
      summary:
        "The final psalm of the Psalter, calling every instrument and every living thing to the praise of God. The text is the Douay-Rheims (Challoner) version, which follows the Vulgate psalm numbering.",
      occasions: ["lauds", "praise", "thanksgiving"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/21150.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "canticle-of-moses",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/02015.htm"],
    payload: {
      slug: "canticle-of-moses",
      title: "Canticle of Moses (Exodus 15:1-18)",
      body: "Then Moses and the children of Israel sung this canticle to the Lord: and said: Let us sing to the Lord: for he is gloriously magnified, the horse and the rider he hath thrown into the sea.\nThe Lord is my strength and my praise, and he is become salvation to me: he is my God and I will glorify him: the God of my father, and I will exalt him.\nThe Lord is as a man of war, Almighty is his name.\nPharao's chariots and his army he hath cast into the sea: his chosen captains are drowned in the Red Sea.\nThe depths have covered them, they are sunk to the bottom like a stone.\nThy right hand, O Lord, is magnified in strength: thy right hand, O Lord, hath slain the enemy.\nAnd in the multitude of thy glory thou hast put down thy adversaries: thou hast sent thy wrath, which hath devoured them like stubble.\nAnd with the blast of thy anger the waters were gathered together: the flowing water stood, the depths were gathered together in the midst of the sea.\nThe enemy said: I will pursue and overtake, I will divide the spoils, my soul shall have its fill: I will draw my sword, my hand shall slay them.\nThy wind blew and the sea covered them: they sunk as lead in the mighty waters.\nWho is like to thee, among the strong, O Lord? who is like to thee, glorious in holiness, terrible and praiseworthy, doing wonders?\nThou stretchedst forth thy hand, and the earth swallowed them.\nIn thy mercy thou hast been a leader to the people which thou hast redeemed: and in thy strength thou hast carried them to thy holy habitation.\nNations rose up, and were angry: sorrows took hold on the inhabitants of Philisthiim.\nThen were the princes of Edom troubled, trembling seized on the stout men of Moab: all the inhabitants of Chanaan became stiff.\nLet fear and dread fall upon them, in the greatness of thy arm: let them become unmoveable as a stone, until thy people, O Lord, pass by: until this thy people pass by, which thou hast possessed.\nThou shalt bring them in, and plant them in the mountain of thy inheritance, in thy most firm habitation which thou hast made, O Lord; thy sanctuary, O Lord, which thy hands have established.\nThe Lord shall reign for ever and ever.",
      prayerType: "canticle",
      category: "liturgical",
      language: "en",
      summary:
        "The song Moses and the children of Israel sang after the passage of the Red Sea, sung by the Church at the Easter Vigil and at Morning Prayer as the canticle of the redeemed. Douay-Rheims text, Exodus 15:1-18.",
      occasions: ["easter-vigil", "lauds", "thanksgiving"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/02015.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "canticle-of-hannah",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/09002.htm"],
    payload: {
      slug: "canticle-of-hannah",
      title: "Canticle of Anna (1 Kings [1 Samuel] 2:1-10)",
      body: "My heart hath rejoiced in the Lord, and my horn is exalted in my God: my mouth is enlarged over my enemies: because I have joyed in thy salvation.\nThere is none holy as the Lord is: for there is no other beside thee, and there is none strong like our God.\nDo not multiply to speak lofty things, boasting: let old matters depart from your mouth: for the Lord is a God of all knowledge, and to him are thoughts prepared.\nThe bow of the mighty is overcome, and the weak are girt with strength.\nThey that were full before have hired out themselves for bread: and the hungry are filled, so that the barren hath borne many: and she that had many children is weakened.\nThe Lord killeth and maketh alive, he bringeth down to hell and bringeth back again.\nThe Lord maketh poor and maketh rich, he humbleth and he exalteth.\nHe raiseth up the needy from the dust, and lifteth up the poor from the dunghill: that he may sit with princes, and hold the throne of glory. For the poles of the earth are the Lord's, and upon them he hath set the world.\nHe will keep the feet of his saints, and the wicked shall be silent in darkness, because no man shall prevail by his own strength.\nThe adversaries of the Lord shall fear him: and upon them shall he thunder in the heavens. The Lord shall judge the ends of the earth, and he shall give empire to his king, and shall exalt the horn of his Christ.",
      prayerType: "canticle",
      category: "liturgical",
      language: "en",
      summary:
        "The thanksgiving of Anna, the mother of Samuel, for the child God gave her; the Church prays it as a canticle at Morning Prayer, and it stands behind Our Lady's Magnificat. The Douay-Rheims calls the book 1 Kings, the modern name being 1 Samuel.",
      occasions: ["lauds", "thanksgiving"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/09002.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "canticle-of-isaiah-12",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/27012.htm"],
    payload: {
      slug: "canticle-of-isaiah-12",
      title: "Canticle of Isaias (Isaias 12)",
      body: "And thou shalt say in that day: I will give thanks to thee, O Lord, for thou wast angry with me: thy wrath is turned away, and thou hast comforted me.\nBehold, God is my saviour, I will deal confidently, and will not fear: O because the Lord is my strength, and my praise, and he is become my salvation.\nYou shall draw waters with joy out of the saviour's fountains:\nAnd you shall say in that day: Praise ye the Lord, and call upon his name: make his works known among the people: remember that his name is high.\nSing ye to the Lord, for he hath done great things: shew this forth in all the earth.\nRejoice, and praise, O thou habitation of Sion: for great is he that is in the midst of thee, the Holy One of Israel.",
      prayerType: "canticle",
      category: "liturgical",
      language: "en",
      summary:
        "Isaias' short song of the day of salvation, 'You shall draw waters with joy out of the saviour's fountains'; used as a canticle at Morning Prayer and read at the Easter Vigil. Douay-Rheims text of the whole chapter.",
      occasions: ["lauds", "advent", "thanksgiving"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/27012.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "canticle-of-daniel-benedicite",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/32003.htm"],
    payload: {
      slug: "canticle-of-daniel-benedicite",
      title: "Benedicite: Canticle of the Three Young Men (Daniel 3:57-88)",
      body: "All ye works of the Lord, bless the Lord: praise and exalt him above all for ever.\nO ye angels of the Lord, bless the Lord: praise and exalt him above all for ever.\nO ye heavens, bless the Lord: praise and exalt him above all for ever.\nO all ye waters that are above the heavens, bless the Lord; praise and exalt him above all for ever.\nO all ye powers of the Lord, bless the Lord: praise and exalt him above all for ever.\nO ye sun and moon, bless the Lord: praise and exalt him above all for ever.\nO ye stars of heaven, bless the Lord: praise and exalt him above all for ever.\nO every shower and dew, bless ye the Lord: praise and exalt him above all for ever.\nO all ye spirits of God, bless the Lord: praise and exalt him above all for ever.\nO ye fire and heat, bless the Lord: praise and exalt him above all for ever.\nO ye cold and heat, bless the Lord: praise and exalt him above all for ever.\nO ye dews and hoar frosts, bless the Lord: praise and exalt him above all for ever.\nO ye frost and cold, bless the Lord: praise and exalt him above all for ever.\nO ye ice and snow, bless the Lord: praise and exalt him above all for ever.\nO ye nights and days, bless the Lord: praise and exalt him above all for ever.\nO ye light and darkness, bless the Lord: praise and exalt him above all for ever.\nO ye lightnings and clouds, bless the Lord: praise and exalt him above all for ever.\nO let the earth bless the Lord: let it praise and exalt him above all for ever.\nO ye mountains and hills, bless the Lord: praise and exalt him above all for ever.\nO all ye things that spring up in the earth, bless the Lord: praise and exalt him above all for ever.\nO ye fountains, bless the Lord: praise and exalt him above all for ever.\nO ye seas and rivers, bless the Lord: praise and exalt him above all for ever.\nO ye whales, and all that move in the waters, bless the Lord: praise and exalt him above all for ever.\nO all ye fowls of the air, bless the Lord: praise and exalt him above all for ever.\nO all ye beasts and cattle, bless the Lord: praise and exalt him above all for ever.\nO ye sons of men, bless the Lord, praise and exalt him above all for ever.\nO let Israel bless the Lord: let them praise and exalt him above all for ever.\nO ye priests of the Lord, bless the Lord: praise and exalt him above all for ever.\nO ye servants of the Lord, bless the Lord: praise and exalt him above all for ever.\nO ye spirits and souls of the just, bless the Lord: praise and exalt him above all for ever.\nO ye holy and humble of heart, bless the Lord: praise and exalt him above all for ever.\nO Ananias, Azarias, and Misael, bless ye the Lord: praise and exalt him above all for ever. For he hath delivered us from hell, and saved us out of the hand of death, and delivered us out of the midst of the burning flame, and saved us out of the midst of the fire.",
      prayerType: "canticle",
      category: "liturgical",
      language: "en",
      summary:
        "The song of Ananias, Azarias and Misael in the fiery furnace, calling every creature to bless the Lord; the Benedicite has been sung at Sunday Lauds since antiquity. Douay-Rheims text, Daniel 3:57-88.",
      occasions: ["lauds", "sundays", "thanksgiving"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/32003.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "canticle-of-habakkuk-3",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/40003.htm"],
    payload: {
      slug: "canticle-of-habakkuk-3",
      title: "Canticle of Habacuc (Habacuc 3)",
      body: "A PRAYER OF HABACUC THE PROPHET FOR IGNORANCES.\nO Lord, I have heard thy hearing, and was afraid. O Lord, thy work, in the midst of the years bring it to life: In the midst of the years thou shalt make it known: when thou art angry, thou wilt remember mercy.\nGod will come from the south, and the holy one from mount Pharan: His glory covered the heavens, and the earth is full of his praise.\nHis brightness shall be as the light; horns are in his hands: There is his strength hid:\nDeath shall go before his face. And the devil shall go forth before his feet.\nHe stood and measured the earth. He beheld, and melted the nations: and the ancient mountains were crushed to pieces. The hills of the world were bowed down by the journeys of his eternity.\nI saw the tents of Ethiopia for their iniquity, the curtains of the land of Madian shall be troubled.\nWast thou angry, O Lord, with the rivers? or was thy wrath upon the rivers? or thy indignation in the sea? Who will ride upon thy horses: and thy chariots are salvation.\nThou wilt surely take up thy bow: according to the oaths which thou hast spoken to the tribes. Thou wilt divide the rivers of the earth.\nThe mountains saw thee, and were grieved: the great body of waters passed away. The deep put forth its voice: the deep lifted up its hands.\nThe sun and the moon stood still in their habitation, in the light of thy arrows, they shall go in the brightness of thy glittering spear.\nIn thy anger thou wilt tread the earth under foot: in thy wrath thou wilt astonish the nations.\nThou wentest forth for the salvation of thy people: for salvation with thy Christ. Thou struckest the head of the house of the wicked: thou hast laid bare his foundation even to the neck.\nThou hast cursed his sceptres, the head of his warriors, them that came out as a whirlwind to scatter me. Their joy was like that of him that devoureth the poor man in secret.\nThou madest a way in the sea for thy horses, in the mud of many waters.\nI have heard and my bowels were troubled: my lips trembled at the voice. Let rottenness enter into my bones, and swarm under me. That I may rest in the day of tribulation: that I may go up to our people that are girded.\nFor the fig tree shall not blossom: and there shall be no spring in the vines. The labour of the olive tree shall fail: and the fields shall yield no food: the flock shall be cut off from the fold, and there shall be no herd in the stalls.\nBut I will rejoice in the Lord: and I will joy in God my Jesus.\nThe Lord God is my strength: and he will make my feet like the feet of harts: and he the conqueror will lead me upon my high places singing psalms.",
      prayerType: "canticle",
      category: "liturgical",
      language: "en",
      summary:
        "The prophet's prayer at the coming of God in judgment and salvation, ending in joy in the God of his salvation even when the fields yield no food; used as a canticle at Morning Prayer. Douay-Rheims text of the whole chapter, whose first verse is the title as printed.",
      occasions: ["lauds", "trust"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/40003.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "canticle-of-tobit-13",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/17013.htm"],
    payload: {
      slug: "canticle-of-tobit-13",
      title: "Canticle of Tobias (Tobias 13:1-10)",
      body: "And Tobias the elder opening his mouth, blessed the Lord, and said: Thou art great, O Lord, for ever, and thy kingdom is unto all ages:\nFor thou scourgest, and thou savest: thou leadest down to hell, and bringest up again: and there is none that can escape thy hand.\nGive glory to the Lord, ye children of Israel, and praise him in the sight of the Gentiles:\nBecause he hath therefore scattered you among the Gentiles, who know not him, that you may declare his wonderful works, and make them know that there is no other almighty God besides him.\nHe hath chastised us for our iniquities: and he will save us for his own mercy.\nSee then what he hath done with us, and with fear and trembling give ye glory to him: and extol the eternal King of worlds in your works.\nAs for me, I will praise him in the land of my captivity: because he hath shewn his majesty toward a sinful nation.\nBe converted therefore, ye sinners, and do justice before God, believing that he will shew his mercy to you.\nAnd I and my soul will rejoice in him.\nBless ye the Lord, all his elect, keep days of joy, and give glory to him.",
      prayerType: "canticle",
      category: "liturgical",
      language: "en",
      summary:
        "The blessing of the elder Tobias, who praises the God that scourges and saves and calls the scattered people to give glory to him among the Gentiles. Douay-Rheims text, Tobias 13:1-10; the Vulgate numbering of Tobias differs from the modern one.",
      occasions: ["thanksgiving", "lauds"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/17013.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "beatitudes",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/47005.htm"],
    payload: {
      slug: "beatitudes",
      title: "The Beatitudes (Matthew 5:3-12)",
      body: "Blessed are the poor in spirit: for theirs is the kingdom of heaven.\nBlessed are the meek: for they shall possess the land.\nBlessed are they that mourn: for they shall be comforted.\nBlessed are they that hunger and thirst after justice: for they shall have their fill.\nBlessed are the merciful: for they shall obtain mercy.\nBlessed are the clean of heart: for they shall see God.\nBlessed are the peacemakers: for they shall be called children of God.\nBlessed are they that suffer persecution for justice' sake: for theirs is the kingdom of heaven.\nBlessed are ye when they shall revile you, and persecute you, and speak all that is evil against you, untruly, for my sake:\nBe glad and rejoice, for your reward is very great in heaven. For so they persecuted the prophets that were before you.",
      prayerType: "general",
      category: "liturgical",
      language: "en",
      summary:
        "The opening words of the Sermon on the Mount, which the Catechism calls the heart of Christ's preaching. Douay-Rheims text, Matthew 5:3-12; in this version the meek are named in the second beatitude.",
      occasions: ["all-saints", "meditation"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/47005.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "philippians-2-hymn",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/57002.htm"],
    payload: {
      slug: "philippians-2-hymn",
      title: "Canticle of Philippians (Philippians 2:6-11)",
      body: "Who being in the form of God, thought it not robbery to be equal with God:\nBut emptied himself, taking the form of a servant, being made in the likeness of men, and in habit found as a man.\nHe humbled himself, becoming obedient unto death, even to the death of the cross.\nFor which cause God also hath exalted him, and hath given him a name which is above all names:\nThat in the name of Jesus every knee should bow, of those that are in heaven, on earth, and under the earth:\nAnd that every tongue should confess that the Lord Jesus Christ is in the glory of God the Father.",
      prayerType: "canticle",
      category: "liturgical",
      language: "en",
      summary:
        "Saint Paul's hymn of the self-emptying and exaltation of Christ, sung as the New Testament canticle at Sunday Evening Prayer. Douay-Rheims text, Philippians 2:6-11.",
      occasions: ["vespers", "holy-week", "palm-sunday"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/57002.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "colossians-1-hymn",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/58001.htm"],
    payload: {
      slug: "colossians-1-hymn",
      title: "Canticle of Colossians (Colossians 1:12-20)",
      body: "Giving thanks to God the Father, who hath made us worthy to be partakers of the lot of the saints in light:\nWho hath delivered us from the power of darkness, and hath translated us into the kingdom of the Son of his love,\nIn whom we have redemption through his blood, the remission of sins;\nWho is the image of the invisible God, the firstborn of every creature:\nFor in him were all things created in heaven and on earth, visible and invisible, whether thrones, or dominations, or principalities, or powers: all things were created by him and in him.\nAnd he is before all, and by him all things consist.\nAnd he is the head of the body, the church, who is the beginning, the firstborn from the dead; that in all things he may hold the primacy:\nBecause in him, it hath well pleased the Father, that all fulness should dwell;\nAnd through him to reconcile all things unto himself, making peace through the blood of his cross, both as to the things that are on earth, and the things that are in heaven.",
      prayerType: "canticle",
      category: "liturgical",
      language: "en",
      summary:
        "Saint Paul's thanksgiving to the Father and hymn to Christ, the image of the invisible God and the head of the body, the Church; one of the New Testament canticles of Evening Prayer. Douay-Rheims text, Colossians 1:12-20.",
      occasions: ["vespers", "christ-the-king"],
      relatedSaints: [],
      citations: ["https://www.drbo.org/chapter/58001.htm"],
    },
  },
  {
    contentType: "PRAYER",
    slug: "revelation-canticle",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: ["https://www.drbo.org/chapter/73004.htm", "https://www.drbo.org/chapter/73005.htm"],
    payload: {
      slug: "revelation-canticle",
      title: "Canticle of the Lamb (Apocalypse 4:11; 5:9-10, 12)",
      body: "Thou art worthy, O Lord our God, to receive glory, and honour, and power: because thou hast created all things; and for thy will they were, and have been created.\nAnd they sung a new canticle, saying: Thou art worthy, O Lord, to take the book, and to open the seals thereof; because thou wast slain, and hast redeemed us to God, in thy blood, out of every tribe, and tongue, and people, and nation.\nAnd hast made us to our God a kingdom and priests, and we shall reign on the earth.\nSaying with a loud voice: The Lamb that was slain is worthy to receive power, and divinity, and wisdom, and strength, and honour, and glory, and benediction.",
      prayerType: "canticle",
      category: "liturgical",
      language: "en",
      summary:
        "The worship of the Creator and of the Lamb that was slain, taken from the vision of the heavenly liturgy and sung as a New Testament canticle at Evening Prayer. Douay-Rheims text; each verse is given whole, so the narrative words that introduce the songs of Apocalypse 5 stand as printed.",
      occasions: ["vespers", "christ-the-king", "adoration"],
      relatedSaints: [],
      citations: [
        "https://www.drbo.org/chapter/73004.htm",
        "https://www.drbo.org/chapter/73005.htm",
      ],
    },
  },
];
