import type { CuratedEntry } from "../index";

const EWTN = "https://www.ewtn.com/catholicism/devotions/";
const EWTN_LIBRARY = "https://www.ewtn.com/catholicism/library/";
const CATHOLIC_ONLINE = "https://www.catholic.org/prayers/prayer.php?p=";
const PRECES = "https://www.preces-latinae.org/thesaurus/";

/**
 * Batch 5 of the curated prayer catalogue: the holy angels, Saint Joseph,
 * prayers to the saints, and the prayers of the Church for the dying and the
 * faithful departed.
 *
 * Every body is the received public-domain English text copied character for
 * character from the cited page, with the line breaks the page prints. Nothing
 * here is modernised, shortened or merged from two versions. Latin is given
 * only where a received liturgical source (Rituale Romanum, the Raccolta)
 * carries it.
 */
export const prayerBatch5: CuratedEntry[] = [
  {
    contentType: "PRAYER",
    slug: "chaplet-of-saint-michael-prayers",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}chaplet-of-st-michael-the-archangel-386`],
    payload: {
      slug: "chaplet-of-saint-michael-prayers",
      title: "The Chaplet of St. Michael the Archangel",
      body: "O God, come to my assistance. O Lord, make haste to help me. Glory be to the Father, etc.\n\n[Say one Our Father and three Hail Marys after each of the following nine salutations in honor of the nine Choirs of Angels]\n\n1. By the intercession of St. Michael and the celestial Choir of Seraphim may the Lord make us worthy to burn with the fire of perfect charity.\nAmen.\n\n2. By the intercession of St. Michael and the celestial Choir of Cherubim may the Lord grant us the grace to leave the ways of sin and run in the paths of Christian perfection.\nAmen.\n\n3. By the intercession of St. Michael and the celestial Choir of Thrones may the Lord infuse into our hearts a true and sincere spirit of humility.\nAmen.\n\n4. By the intercession of St. Michael and the celestial Choir of Dominations may the Lord give us grace to govern our senses and overcome any unruly passions.\nAmen.\n\n5. By the intercession of St. Michael and the celestial Choir of Virtues may the Lord preserve us from evil and falling into temptation.\nAmen.\n\n6. By the intercession of St. Michael and the celestial Choir of Powers may the Lord protect our souls against the snares and temptations of the devil.\nAmen.\n\n7. By the intercession of St. Michael and the celestial Choir of Principalities may God fill our souls with a true spirit of obedience.\nAmen.\n\n8. By the intercession of St. Michael and the celestial Choir of Archangels may the Lord give us perseverance in faith and in all good works in order that we may attain the glory of Heaven.\nAmen.\n\n9. By the intercession of St. Michael and the celestial Choir of Angels may the Lord grant us to be protected by them in this mortal life and conducted in the life to come to Heaven.\nAmen.\n\nSay one Our Father in honor of each of the following leading Angels: St. Michael, St. Gabriel, St. Raphael and our Guardian Angel.\n\nConcluding prayers:\n\nO glorious prince St. Michael, chief and commander of the heavenly hosts, guardian of souls, vanquisher of rebel spirits, servant in the house of the Divine King and our admirable conductor, you who shine with excellence and superhuman virtue deliver us from all evil, who turn to you with confidence and enable us by your gracious protection to serve God more and more faithfully every day.\n\nPray for us, O glorious St. Michael, Prince of the Church of Jesus Christ, that we may be made worthy of His promises.\n\nAlmighty and Everlasting God, Who, by a prodigy of goodness and a merciful desire for the salvation of all men, has appointed the most glorious Archangel St. Michael Prince of Your Church, make us worthy, we ask You, to be delivered from all our enemies, that none of them may harass us at the hour of death, but that we may be conducted by him into Your Presence. This we ask through the merits of Jesus Christ Our Lord.\nAmen.",
      prayerType: "rosary",
      category: "chaplet",
      language: "en",
      summary:
        "A chaplet of nine salutations honouring St. Michael together with the nine choirs of angels, each followed by an Our Father and three Hail Marys, and closed with prayers to the Archangel. The devotion is associated with Antonia d'Astonac and is prayed especially on the feast of the Holy Archangels.",
      occasions: ["september-29", "spiritual-warfare", "daily"],
      relatedSaints: [],
      citations: [`${EWTN}chaplet-of-st-michael-the-archangel-386`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayers-to-saint-raphael",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}prayers-to-st-raphael-the-archangel-28507`],
    payload: {
      slug: "prayers-to-saint-raphael",
      title: "Prayers to St. Raphael the Archangel",
      body: "Prayer to St. Raphael for Healing\n\nO glorious Archangel, St Raphael,\ngreat Prince of the heavenly court,\nillustrious for your gifts of wisdom and grace,\nguide of those who journey by land or sea,\nconsoler of the afflicted, and refuge of sinners:\nI beg you to assist me in all my needs\nand in all the sufferings of this life,\nas once you did help the young Tobias on his travels.\nAnd because you are the 'Medicine of God,\nI humbly ask you to heal the many infirmities of my soul,\nand the ills which afflict my body, if it be for my greater good.\nI especially ask of you an angelic purity,\nwhich may fit me to be the temple of the Holy Spirit.\nBe pleased, O Lord God,\nto send to our aid St Raphael the Archangel:\nand may he, who, we believe,\nstands forever before the throne of Your Majesty,\noffer unto You our humble petitions\nto be blessed by You.\nThrough Christ our Lord. Amen.\n\nPrayer to St. Raphael for Protection\n\nO God, who did give blessed Raphael the Archangel to Thy servant Tobias,\nas a companion on his journey: grant to us, Thy servants,\nthat we may always be guarded by his care and strengthened by his help.\nThrough our Lord Jesus Christ Thy Son,\nwho lives and reigns with Thee in the unity of the Holy Spirit,\nworld without end. Amen.",
      prayerType: "intercession",
      category: "angelic",
      language: "en",
      summary:
        "Two prayers to the Archangel Raphael, the angelic companion of Tobias, asked here for healing and for safe journeying. EWTN notes that the second is the Collect, and the closing petition of the first the Communion prayer, of the former Roman Missal Mass for the feast of St. Raphael, before the Archangels were joined in one feast on 29 September.",
      occasions: ["september-29", "travel", "sickness", "healing"],
      relatedSaints: [],
      citations: [`${EWTN}prayers-to-st-raphael-the-archangel-28507`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-gabriel",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}10`],
    payload: {
      slug: "prayer-to-saint-gabriel",
      title: "Prayer to St. Gabriel, for Intercession",
      body: "O Blessed Archangel Gabriel, we beseech thee, do thou intercede for us at the throne of divine Mercy in our present necessities, that as thou didst announce to Mary the mystery of the Incarnation, so through thy prayers and patronage in heaven we may obtain the benefits of the same, and sing the praise of God forever in the land of the living. Amen.",
      prayerType: "intercession",
      category: "angelic",
      language: "en",
      summary:
        "A traditional invocation of the Archangel Gabriel, messenger of the Incarnation, asking that those who announce Christ's coming to Mary may also obtain for us the fruits of that mystery. It is prayed especially on the Annunciation and the feast of the Holy Archangels.",
      occasions: ["annunciation", "september-29"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}10`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-joseph",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}prayer-to-st-joseph-334`],
    payload: {
      slug: "prayer-to-saint-joseph",
      title: "A Prayer to St. Joseph",
      body: "O blessed Joseph, faithful guardian of my Redeemer, Jesus Christ, protector of thy chaste spouse, the virgin Mother of God, I choose thee this day to be my special patron and advocate and I firmly resolve to honor thee all the days of my life. Therefore I humbly beseech thee to receive me as thy client, to instruct me in every doubt, to comfort me in every affliction, to obtain for me and for all the knowledge and love of the Heart of Jesus, and finally to defend and protect me at the hour of my death. Amen",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "A traditional act by which a Christian chooses St. Joseph, guardian of the Redeemer and spouse of the Virgin Mary, as patron and advocate, asking his guidance in doubt, his comfort in affliction and his protection at the hour of death. It is prayed especially on 19 March and on Wednesdays.",
      occasions: ["march-19", "wednesdays", "daily"],
      relatedSaints: ["saint-joseph"],
      citations: [`${EWTN}prayer-to-st-joseph-334`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-joseph-leo-xiii",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}devotion-to-st-joseph-346`, `${PRECES}Ioseph/AdTe.html`],
    payload: {
      slug: "prayer-to-saint-joseph-leo-xiii",
      title: "To You, O Blessed Joseph (Prayer of Leo XIII)",
      body: "To you, O blessed Joseph,\ndo we come in our tribulation,\nand having implored the help of your most holy spouse,\nwe confidently invoke your patronage also.\nThrough that charity which bound you to the Immaculate Virgin Mother of God and through the paternal love with which you embraced the Child Jesus,\nwe humbly beg you graciously to regard the inheritance which Jesus Christ has purchased by his Blood,\nand with your power and strength to aid us in our necessities.\nO most watchful Guardian of the Holy Family, defend the chosen children of Jesus Christ;\nO most loving father,\nward off from us every contagion of error and corrupting influence;\nO our most mighty protector,\nbe propitious to us and from heaven assist us in our struggle with the power of darkness;\nand, as once you rescued the Child Jesus from deadly peril, so now protect God's Holy Church from the snares of the enemy and from all adversity;\nshield, too, each one of us by your constant protection,\nso that, supported by your example and your aid, we may be able to live piously, to die holily, and to obtain eternal happiness in heaven. Amen.",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      latin:
        "Ad te beate Ioseph, in tribulatione nostra confugimus, atque, implorato Sponsae tuae sanctissimae auxilio, patrocinium quoque tuum fidenter exposcimus. Per eam, quaesumus quae te cum immaculata Virgine Dei Genetrice coniunxit, caritatem, perque paternum, quo Puerum Iesum amplexus es, amorem, supplices deprecamur, ut ad hereditatem, quam Iesus Christus acquisivit Sanguine suo, benignus respicias, ac necessitatibus nostris tua virtute et ope succurras.\n\nTuere, o Custos providentissime divinae Familiae, Iesu Christi subolem electam; prohibe a nobis, amantissime Pater, omnem errorum ac corruptelarum luem; propitius nobis, sospitator noster fortissime, in hoc cum potestate tenebrarum certamine e caelo adesto; et sicut olim Puerum Iesum e summo eripuisti vitae discrimine, ita nunc Ecclesiam sanctam Dei ab hostilibus insidiis atque ab omni adversitate defende: nosque singulos perpetuo tege patrocinio, ut ad tui exemplar et ope tua suffulti, sancte vivere, pie emori, sempiternamque in caelis beatitudinem assequi possimus. Amen.",
      summary:
        "The prayer Pope Leo XIII attached to his 1889 encyclical Quamquam pluries, ordering that it be added to the Rosary during October. The body is EWTN's modern-language form of the prayer; the Latin is the received text of the Raccolta (no. 476), to which the Enchiridion Indulgentiarum attaches a partial indulgence.",
      occasions: ["october", "march-19", "for-the-church"],
      relatedSaints: ["saint-joseph"],
      citations: [`${EWTN}devotion-to-st-joseph-346`, `${PRECES}Ioseph/AdTe.html`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "memorare-to-saint-joseph",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}memorare-to-st-joseph-350`],
    payload: {
      slug: "memorare-to-saint-joseph",
      title: "Memorare to St. Joseph",
      body: "Remember, O most chaste spouse of the Virgin Mary, that never was it known that anyone who implored your help and sought your intercession were left unassisted.\nFull of confidence in your power I fly unto you and beg your protection.\nDespise not O Guardian of the Redeemer my humble supplication, but in your bounty, hear and answer me. Amen.",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "A prayer to St. Joseph modelled on the Memorare to Our Lady, appealing with confidence to the intercession of the Guardian of the Redeemer. It is commonly prayed on Wednesdays and throughout the month of March.",
      occasions: ["march-19", "wednesdays", "daily"],
      relatedSaints: ["saint-joseph"],
      citations: [`${EWTN}memorare-to-st-joseph-350`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "consecration-to-saint-joseph",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}memorare-to-st-joseph-350`, `${CATHOLIC_ONLINE}440`],
    payload: {
      slug: "consecration-to-saint-joseph",
      title: "Act of Consecration to St. Joseph",
      body: "O dearest St. Joseph, I consecrate myself to your honor and give myself to you, that you may always be my father, my protector and my guide in the way of salvation.\nObtain for me a greater purity of heart and fervent love of the interior life.\nAfter your example may I do all my actions for the greater glory of God, in union with the Divine Heart of Jesus and the Immaculate Heart of Mary.\nO Blessed St. Joseph, pray for me, that I may share in the peace and joy of your holy death. Amen.",
      prayerType: "consecration",
      category: "consecration",
      language: "en",
      summary:
        "A short act by which a Christian entrusts himself to St. Joseph as father, protector and guide, asking purity of heart, an interior life and a death like his own. Catholic Online prints the same text with 'Saint Joseph' spelled out.",
      occasions: ["march-19", "wednesdays"],
      relatedSaints: ["saint-joseph"],
      citations: [`${EWTN}memorare-to-st-joseph-350`, `${CATHOLIC_ONLINE}440`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-joseph-for-a-happy-death",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}479`],
    payload: {
      slug: "prayer-to-saint-joseph-for-a-happy-death",
      title: "Prayer to Saint Joseph for a Happy Death",
      body: "O Blessed Joseph, you gave your last breath in the loving embrace of Jesus and Mary. When the seal of death shall close my life, come with Jesus and Mary to aid me. Obtain for me this solace for that hour - to die with their holy arms around me. Jesus, Mary and Joseph, I commend my soul, living and dying, into your sacred arms. Amen.",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "A prayer asking St. Joseph, who died in the presence of Jesus and Mary, to be present at the hour of one's own death. St. Joseph has long been honoured by the Church as patron of a happy death.",
      occasions: ["deathbed", "illness", "march-19"],
      relatedSaints: ["saint-joseph"],
      citations: [`${CATHOLIC_ONLINE}479`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "thirty-days-prayer-to-saint-joseph",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}thirty-days-prayer-to-saint-joseph-399`],
    payload: {
      slug: "thirty-days-prayer-to-saint-joseph",
      title: "Thirty Days' Prayer to Saint Joseph",
      body: "Ever blessed and glorious Joseph, kind and loving father, and helpful friend of all in sorrow! You are the good father and protector of orphans, the defender of the defenseless, the patron of those in need and sorrow. Look kindly on my request. My sins have drawn down on me the just displeasure of my God, and so I am surrounded with unhappiness. To you, loving guardian of the Family of Nazareth, do I go for help and protection.\n\nListen, then, I beg you, with fatherly concern, to my earnest prayers, and obtain for me the favors I ask.\n\nI ask it by the infinite mercy of the eternal Son of God, which moved Him to take our nature and to be born into this world of sorrow.\n\nI ask it by the weariness and suffering you endured when you found no shelter at the inn of Bethlehem for the holy Virgin, nor a house where the Son of God could be born. Then, being everywhere refused, you had to allow the Queen of Heaven to give birth to the world's Redeemer in a cave.\n\nI ask it by the loveliness and power of that sacred Name, Jesus, which you conferred on the adorable infant.\n\nI ask it by that painful torture you felt at the prophecy of holy Simeon, which declared the Child Jesus and His holy Mother future victims of our sins and of their great love for us.\n\nI ask it through your sorrow and pain of soul when the angel declared to you that the life of the Child Jesus was sought by His enemies. From their evil plan you had to flee with Him and His Blessed Mother to Egypt. I ask it by all the suffering, weariness, and labors of that long and dangerous journey.\n\nI ask it by all your care to protect the Sacred Child and His Immaculate Mother during your second journey, when you were ordered to return to your own country. I ask it by your peaceful life in Nazareth where you met with so many joys and sorrows.\n\nI ask it by your great distress when the adorable Child was lost to you and His Mother for three days. I ask it by your joy at finding Him in the Temple, and by the comfort you found at Nazareth, while living in the company of the Child Jesus. I ask it by the wonderful submission He showed in His obedience to you.\n\nI ask it by the perfect love and conformity you showed in accepting the Divine order to depart from this life, and from the company of Jesus and Mary. I ask it by the joy which filled your soul, when the Redeemer of the world, triumphant over death and hell, entered into the possession of His kingdom and led you into it with special honors.\n\nI ask it through Mary's glorious Assumption, and through that endless happiness you have with her in the presence of God.\n\nO good father! I beg you, by all your sufferings, sorrows, and joys, to hear me and obtain for me what I ask.\n\n(make your request)\n\nObtain for all those who have asked my prayers everything that is useful to them in the plan of God. Finally, my dear patron and father, be with me and all who are dear to me in our last moments, that we may eternally sing the praises of Jesus, Mary and Joseph.",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "A long traditional petition to St. Joseph recalling the sorrows and joys of his life, prayed for thirty consecutive days for a particular intention. EWTN notes that it may be begun on any day of the year.",
      occasions: ["march-19", "lent", "special-intentions"],
      relatedSaints: ["saint-joseph"],
      citations: [`${EWTN}thirty-days-prayer-to-saint-joseph-399`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-for-saint-josephs-protection",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}prayer-for-st-josephs-protection-329`],
    payload: {
      slug: "prayer-for-saint-josephs-protection",
      title: "Prayer for St. Joseph's Protection",
      body: "Oh, St. Joseph, whose protection is so great, so prompt, so strong,\nbefore the throne of God, I place in you all my interests and desires.\nOh, St. Joseph, do assist me by your powerful intercession,\nand obtain for me from your Divine Son\nall spiritual blessings, through Jesus Christ, our Lord.\nSo that, having engaged here below your heavenly power,\nI may offer my thanksgiving and homage to the most loving of fathers.\nOh, St. Joseph, I never weary contemplating you and Jesus asleep in your arms;\nI dare not approach while he reposes near your heart.\nPress him in my name and kiss his fine head for me and\nask him to return the kiss when I draw my dying breath.\nSt. Joseph, patron of departing souls - pray for me.\nAmen.",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "One of the best known prayers to St. Joseph, placing all one's interests before God through his intercession and ending with the tender request that he kiss the Child Jesus in the petitioner's name. It is often prayed by families and by those preparing for death.",
      occasions: ["march-19", "families", "deathbed", "daily"],
      relatedSaints: ["saint-joseph"],
      citations: [`${EWTN}prayer-for-st-josephs-protection-329`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "unfailing-prayer-to-saint-anthony",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}163`],
    payload: {
      slug: "unfailing-prayer-to-saint-anthony",
      title: "Unfailing Prayer to St. Anthony",
      body: '"Blessed be God in His Angels and in His Saints"\n\nO Holy St. Anthony, gentlest of Saints, your love for God and Charity for His creatures, made you worthy, when on earth, to possess miraculous powers. Encouraged by this thought, I implore you to obtain for me (request). O gentle and loving St. Anthony, whose heart was ever full of human sympathy, whisper my petition into the ears of the sweet Infant Jesus, who loved to be folded in your arms; and the gratitude of my heart will ever be yours. Amen.',
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "A widely used petition to St. Anthony of Padua, opening with the traditional acclamation 'Blessed be God in His Angels and in His Saints'. St. Anthony is invoked as patron of those who have lost something and of those in urgent need.",
      occasions: ["june-13", "tuesdays", "lost-things"],
      relatedSaints: ["saint-anthony-of-padua"],
      citations: [`${CATHOLIC_ONLINE}163`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "si-quaeris-miracula",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${PRECES}Sancti/SAntoniusDePadova/SiQuaeris.html`],
    payload: {
      slug: "si-quaeris-miracula",
      title: "Si Quaeris Miracula (Responsory of St. Anthony)",
      body: "If, then, thou seekest miracles,\nDeath, error, all calamities,\nThe leprosy and demons flee,\nThe sick, by him made whole, arise.\n\nAnt: The sea withdraws and fetters break,\nAnd withered limbs he doth restore,\nWhile treasures lost are found again,\nWhen young or old his help implore.\n\nAll dangers vanish from our path,\nOur direst needs do quickly flee:\nLet those who know repeat the theme:\nLet Paduans praise St. Anthony.\n\nAnt: The sea withdraws...\n\nTo the Father, Son let glory be,\nAnd Holy Ghost eternally.\n\nAnt: The sea withdraws...\n\nV. Pray for us, O blessed Anthony,\nR. That we may be made worthy of the promises of Christ.\n\nLet us pray:\nLet Thy Church, O God, be gladdened by the solemn commemoration of blessed Anthony Thy Confessor: that she may be evermore defended by Thy spiritual assistance and merit to possess everlasting joy. Through Christ our Lord. Amen.",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      latin:
        "Si quaeris miracula,\nMors, error calamitas,\nDaemon, lepra fugiunt,\nAegri surgunt sani.\n\nAnt: Cedunt mare, vincula:\nMembra resque, perditas\nPetunt et accipiunt\nIuvenes et cani.\n\nPereunt pericula,\nCessat et necessitas:\nNarrent hi, qui sentiunt,\nDicant Paduani.\n\nAnt: Cedunt mare, vincula...\n\nGloria Patri et Filio\net Spiritui Sancto.\n\nAnt: Cedunt mare, vincula...\n\nV. Ora pro nobis, beate Antoni,\nR. Ut digni efficiamur promissionibus Christi.\n\nOremus:\nEcclesiam tuam, Deus, beati Antonii Confessoris tui commemoratio votiva laetificet, ut spiritualibus semper muniatur auxiliis et gaudiis perfrui mereatur aeternis. Per Christum Dominum nostrum. Amen.",
      summary:
        "The responsory in honour of St. Anthony of Padua, believed to have been composed by Friar Julian of Speyer between about 1232 and 1240 and long attributed by some to St. Bonaventure. The English is the Raccolta translation (Raccolta no. 531).",
      occasions: ["june-13", "tuesdays", "lost-things"],
      relatedSaints: ["saint-anthony-of-padua"],
      citations: [`${PRECES}Sancti/SAntoniusDePadova/SiQuaeris.html`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-jude",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}187`],
    payload: {
      slug: "prayer-to-saint-jude",
      title: "Prayer to Saint Jude",
      body: "Most holy Apostle St. Jude, faithful servant and friend of Jesus, the name of the traitor who delivered the beloved Master into the hands of His enemies has caused you to be forgotten by many, but the Church honors and invokes you universally as the patron of hopeless cases, of things despaired of. Pray for me who am so miserable; make use, I implore you, of this particular privilege accorded to you, to bring visible and speedy help, where help is almost despaired of. Come to my assistance in this great need, that I may receive the consolations and succor of Heaven in all my necessities, tribulations and sufferings, particularly (here make your request), and that I may bless God with you and all the elect forever.\n\nI promise you, O blessed St. Jude, to be ever mindful of this great favor, and I will never cease to honor you as my special and powerful patron and to do all in my power to encourage devotion to you. Amen.",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "The customary prayer to the Apostle St. Jude Thaddeus, honoured in the Church as patron of desperate and seemingly hopeless causes. Catholic Online prints a shorter alternative form of the same petition alongside this one.",
      occasions: ["october-28", "hopeless-causes"],
      relatedSaints: ["saint-jude-thaddeus"],
      citations: [`${CATHOLIC_ONLINE}187`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-therese",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}prayer-to-st-therese-of-lisieux-372`],
    payload: {
      slug: "prayer-to-saint-therese",
      title: "A Prayer to St. Therese of Lisieux",
      body: "O little St. Theresa of the Child Jesus, who during your short life on earth became a mirror of angelic purity, of love strong as death, and of wholehearted abandonment to God, now that you rejoice in the reward of your virtues, cast a glance of pity on me as I leave all things in your hands. Make my troubles your own - speak a word for me to our Lady Immaculate, whose flower of special love you were - to that Queen of heaven 'who smiled on you at the dawn of life. ' Beg her as the Queen of the heart of Jesus to obtain for me by her powerful intercession, the grace I yearn for so ardently at this moment, and that she join with it a blessing that may strengthen me during life. Defend me at the hour of death, and lead me straight on to a happy eternity.\nAmen",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "A petition to St. Thérèse of the Child Jesus, the Little Flower, asking her to carry the petitioner's needs to Our Lady and to defend him at the hour of death. It is prayed especially on her feast, 1 October.",
      occasions: ["october-1", "special-intentions"],
      relatedSaints: ["saint-therese-of-lisieux"],
      citations: [`${EWTN}prayer-to-st-therese-of-lisieux-372`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-cecilia",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}prayer-to-saint-cecilia-369`],
    payload: {
      slug: "prayer-to-saint-cecilia",
      title: "Prayer to Saint Cecilia",
      body: "Dear Saint Cecilia, one thing we know for certain about you is that you became a heroic martyr in fidelity to your divine Bridegroom.\nWe do not know that you were a musician but we are told that you heard Angels sing.\nInspire musicians to gladden the hearts of people by filling the air with God's gift of music and reminding them of the divine Musician who created all beauty.\nAmen.",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "A prayer to the Roman martyr St. Cecilia, patroness of musicians and of sacred music, asking her intercession for those who make music for the Church. Her feast is kept on 22 November.",
      occasions: ["november-22", "musicians"],
      relatedSaints: ["saint-cecilia"],
      citations: [`${EWTN}prayer-to-saint-cecilia-369`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-mary-magdalene",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}prayer-to-st-mary-magdalen-370`],
    payload: {
      slug: "prayer-to-saint-mary-magdalene",
      title: "Prayer to St. Mary Magdalen",
      body: "Saint Mary Magdalene,\nwoman of many sins, who by conversion\nbecame the beloved of Jesus,\nthank you for your witness\nthat Jesus forgives\nthrough the miracle of love.\nYou, who already possess eternal happiness\nin His glorious presence,\nplease intercede for me, so that some day\nI may share in the same everlasting joy.\nAmen.",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "A prayer to St. Mary Magdalene, who stood by the Cross and was the first to whom the risen Lord appeared, giving thanks for her witness to the forgiveness of Christ. Her feast is kept on 22 July.",
      occasions: ["july-22", "conversion", "penitence"],
      relatedSaints: ["saint-mary-magdalene"],
      citations: [`${EWTN}prayer-to-st-mary-magdalen-370`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-of-saint-benedict-of-nursia",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}prayer-of-saint-benedict-of-nursia-362`],
    payload: {
      slug: "prayer-of-saint-benedict-of-nursia",
      title: "Prayer of Saint Benedict of Nursia",
      body: "O Lord, I place myself in your hands and dedicate myself to you. I pledge myself to do your will in all things: To love the Lord God with all my heart, all my soul, all my strength. Not to kill. Not to steal. Not to covet. Not to bear false witness. To honor all persons. Not to do to another what I would not wish done to myself. To chastise the body. Not to seek after pleasures. To love fasting. To relieve the poor. To clothe the naked. To visit the sick. To bury the dead. To help in trouble. To console the sorrowing. To hold myself aloof from worldly ways. To prefer nothing to the love of Christ. Not to give way to anger. Not to foster a desire for revenge. Not to entertain deceit in the heart. Not to make a false peace. Not to forsake charity. Not to swear, lest I swear falsely. To speak the truth with heart and tongue. Not to return evil for evil. To do no injury: yea, even to bear patiently any injury done to me. To love my enemies. Not to curse those who curse me, but rather to bless them. To bear persecution for justice' sake. Not to be proud. Not to be given to intoxicating drink. Not to be an over-eater. Not to be lazy. Not to be slothful. Not to be a murmured. Not to be a detractor. To put my trust in God. To refer the good I see in myself to God. To refer any evil in myself to myself. To fear the Day of Judgment. To be in dread of hell. To desire eternal life with spiritual longing. To keep death before my eyes daily. To keep constant watch over my actions. To remember that God sees me everywhere. To call upon Christ for defense against evil thoughts that arises in my heart. To guard my tongue against wicked speech. To avoid much speaking. To avoid idle talk. To read only what is good to read. To look at only what is good to see. To pray often. To ask forgiveness daily for my sins, and to seek ways to amend my life. To obey my superiors in all things rightful. Not to desire to be thought holy, but to seek holiness. To fulfill the commandments of God by good works. To love chastity. To hate no one. Not to be jealous or envious of anyone. Not to love strife. Not to love pride. To honor the aged. To pray for my enemies. To make peace after a quarrel, before the setting of the sun. Never to despair of your mercy, O God of Mercy. Amen.",
      prayerType: "general",
      category: "saintly",
      language: "en",
      summary:
        "A prayer drawn from the 'tools of good works' in chapter four of the Rule of St. Benedict, made into a personal dedication of one's whole life to God. It is prayed especially on his feast, 11 July.",
      occasions: ["july-11", "daily", "retreat"],
      relatedSaints: ["saint-benedict-of-nursia"],
      citations: [`${EWTN}prayer-of-saint-benedict-of-nursia-362`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-peregrine",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}76`],
    payload: {
      slug: "prayer-to-saint-peregrine",
      title: "To Saint Peregrine",
      body: 'O great St. Peregrine, you have been called "The Mighty," "The Wonder-Worker," because of the numerous miracles which you have obtained from God for those who have had recourse to you. For so many years you bore in your own flesh this cancerous disease that destroys the very fiber of our being, and who had recourse to the source of all grace when the power of man could do no more. You were favored with the vision of Jesus coming down from His Cross to heal your affliction. Ask of God and Our Lady, the cure of the sick whom we entrust to you.\n\n(Pause here and silently recall the names of the sick for whom you are praying)\n\nAided in this way by your powerful intercession, we shall sing to God, now and for all eternity, a song of gratitude for His great goodness and mercy. Amen.',
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "A prayer to St. Peregrine Laziosi, the Servite friar healed of a cancer of the leg, who is invoked by those suffering from cancer and by those who care for them. His feast is kept on 1 May.",
      occasions: ["may-1", "sickness", "cancer"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}76`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-dymphna",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}177`],
    payload: {
      slug: "prayer-to-saint-dymphna",
      title: "Prayer to Saint Dymphna",
      body: "Lord, our God, you graciously chose St. Dymphna as patroness of those afflicted with mental and nervous disorders. She is thus an inspiration and a symbol of charity to the thousands who ask her intercession.\n\nPlease grant, Lord, through the prayers of this pure youthful martyr, relief and consolation to all suffering such trials, and especially those for whom we pray. (Here mention those for whom you wish to pray).\n\nWe beg you, Lord, to hear the prayers of St. Dymphna on our behalf. Grant all those for whom we pray patience in their sufferings and resignation to your divine will. Please fill them with hope, and grant them the relief and cure they so much desire.\n\nWe ask this through Christ our Lord who suffered agony in the garden. Amen.",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "A prayer through the intercession of St. Dymphna, the young Irish martyr honoured as patroness of those who suffer mental and nervous illness and of those who care for them. Her feast is kept on 15 May.",
      occasions: ["may-15", "mental-illness", "anxiety"],
      relatedSaints: ["saint-dymphna"],
      citations: [`${CATHOLIC_ONLINE}177`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-for-travelers",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}prayer-for-travelers-330`],
    payload: {
      slug: "prayer-for-travelers",
      title: "A Prayer for Travelers",
      body: "O Almighty and merciful God, who hast commissioned Thy angels to guide and protect us, command them to be our assiduous companions from our setting out until our return; to clothe us with their invisible protection; to keep from us all danger of collision, of fire, of explosion, of fall and bruises, and finally, having preserved us from all evil, and especially\nfrom sin, to guide us to our heavenly home.\nThrough Jesus Christ, our Lord.\nAmen.",
      prayerType: "intercession",
      category: "angelic",
      language: "en",
      summary:
        "A traditional prayer before a journey, asking God to send his angels as companions and to bring the traveller safely home. EWTN prints it with the Lord's words on entering a house, 'Peace to this house' (Lk 10:5-6).",
      occasions: ["travel", "pilgrimage"],
      relatedSaints: [],
      citations: [`${EWTN}prayer-for-travelers-330`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-anne",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}1292`],
    payload: {
      slug: "prayer-to-saint-anne",
      title: "A Prayer in Honour of the Blessed Virgin and Her Mother, St. Anne",
      body: "Hail full of grace,\nthe Lord is with thee.\nMay I partake of that grace.\nBlessed art thou amongst women,\nand blessed be St. Anne,\nthy mother,\nof whom thou wert born without spot or stain,\nO Virgin Mary;\nand of thee was born Jesus Christ,\nSon of the living God.\n\nAmen.",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "A short traditional salutation that honours the Blessed Virgin together with her mother St. Anne, from whom Mary was born immaculate. St. Anne's feast, with St. Joachim, is kept on 26 July.",
      occasions: ["july-26", "mothers", "families"],
      relatedSaints: ["saint-anne"],
      citations: [`${CATHOLIC_ONLINE}1292`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-patrick",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}3291`],
    payload: {
      slug: "prayer-to-saint-patrick",
      title: "Prayer to St. Patrick, Patron of Ireland",
      body: "Dear St. Patrick,\n\nin your humility you called yourself a sinner,\n\nbut you became a most successful missionary\n\nand prompted countless pagans\n\nto follow the Saviour.\n\nMany of their descendents in turn\n\nspread the Good News in numerous foreign lands.\n\nThrough your powerful intercession with God,\n\nobtain the missionaries we need\n\nto continue the work you began.\n\nAmen.",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      summary:
        "A prayer to St. Patrick, the bishop who evangelised Ireland, asking his intercession for missionary vocations. His feast is kept on 17 March.",
      occasions: ["march-17", "missions", "vocations"],
      relatedSaints: ["saint-patrick"],
      citations: [`${CATHOLIC_ONLINE}3291`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-saint-francis-xavier",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${PRECES}Varia/XaveriiProConv.html`],
    payload: {
      slug: "prayer-to-saint-francis-xavier",
      title: "Prayer of St. Francis Xavier for the Conversion of Unbelievers",
      body: "O GOD, everlasting creator of all things, remember that the souls of unbelievers were made by Thee and formed in Thine own image and likeness. Remember that Jesus, Thy Son, endured a most bitter death for their salvation. Permit not, I beseech Thee, O Lord, that Thy Son should be despised any longer by unbelievers, but do Thou graciously accept the prayers of holy men and of the Church, the Spouse of Thy most holy Son, and be mindful of Thy mercy. Forget their idolatry and unbelief and grant that they too may some day know Him Thou hast sent, the Lord Jesus Christ, who is our Life and Resurrection, by whom we have been saved and delivered, to whom be glory for endless ages. Amen.",
      prayerType: "intercession",
      category: "saintly",
      language: "en",
      latin:
        "Aeterne rerum omnium effector Deus, memento abs te animas infidelium procreatas, easque ad imaginem et similitudinem tuam conditas. Memento Iesum, Filium tuum, pro illorum salute atrocissimam subiisse necem. Noli, quaeso, Domine, ultra permittere, ut Filius tuus ab infidelibus contemnatur, sed precibus sanctorum virorum et Ecclesiae, sanctissimi Filii tui Sponsae, placatus, recordare misericordiae tuae et, oblitus idololatriae et infidelitatis eorum, effice ut ipsi quoque agnoscant aliquando quem misisti Dominum Iesum Christum, qui est salus, vita et resurrectio nostra, per quem salvati et liberati sumus, cui sit gloria per infinita saecula saeculorum. Amen.",
      summary:
        "A missionary prayer written by St. Francis Xavier (1506-1552), the Jesuit apostle of the Indies and Japan, begging God for the conversion of those who do not yet know Christ. The English is the Raccolta translation (Raccolta no. 612).",
      occasions: ["december-3", "missions"],
      relatedSaints: ["saint-francis-xavier"],
      citations: [`${PRECES}Varia/XaveriiProConv.html`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-jesus-christ-for-the-holy-souls",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}prayer-to-jesus-christ-for-the-holy-souls-286`],
    payload: {
      slug: "prayer-to-jesus-christ-for-the-holy-souls",
      title: "Prayer to Jesus Christ for the Holy Souls",
      body: "O most sweet Jesus, through the bloody sweat which Thou didst suffer in the Garden of Gethsemane, have mercy on these Blessed Souls. Have mercy on them.\nR. Have mercy on them, O Lord.\n\nO most sweet Jesus, through the pains which Thou didst suffer during Thy most cruel scourging, have mercy on them.\nR. Have mercy on them, O Lord.\n\nO most sweet Jesus, through the pains which Thou didst suffer in Thy most painful crowning with thorns, have mercy on them.\nR. Have mercy on them, O Lord.\n\nO most sweet Jesus, through the pains which Thou didst suffer in carrying Thy cross to Calvary, have mercy on them.\nR. Have mercy on them, O Lord.\n\nO most sweet Jesus, through the pains which Thou didst suffer during Thy most cruel Crucifixion, have mercy on them.\nR. Have mercy on them, O Lord.\n\nO most sweet Jesus, through the pains which Thou didst suffer in Thy most bitter agony on the Cross, have mercy on them.\nR. Have mercy on them, O Lord.\n\nO most sweet Jesus, through the immense pain which Thou didst suffer in breathing forth Thy Blessed Soul, have mercy on them.\nR. Have mercy on them, O Lord.\n\n(Recommend yourself to the Souls in Purgatory and mention your intentions)\n\nBlessed Souls, we have prayed for thee; we entreat thee, who are so dear to God, and who are secure of never losing Him, to pray for us miserable sinners, who are in danger of being damned, and of losing God forever.\n\nLet us pray:\nO God, the author of mercy, the lover of the salvation of mankind; we address thy clemency, in behalf of our brethren, relations, and benefactors, who are departed this life, that by the intercession of blessed Mary, ever virgin, and of all the saints, thou wouldst receive them into the enjoyment of eternal happiness; through Christ our Lord. Amen.",
      prayerType: "intercession",
      category: "general",
      language: "en",
      summary:
        "Seven invocations of the sufferings of Christ offered for the souls in purgatory, followed by a petition for their prayers and a collect for the faithful departed. EWTN notes that it may be prayed in common or alone, at any time or as a novena, and especially on All Souls Day.",
      occasions: ["november", "all-souls", "funerals"],
      relatedSaints: [],
      citations: [`${EWTN}prayer-to-jesus-christ-for-the-holy-souls-286`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-for-the-faithful-departed",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}2181`],
    payload: {
      slug: "prayer-for-the-faithful-departed",
      title: "A Prayer for the Faithful Departed",
      body: "O God, the Creator and Redeemer of all the faithful,\ngrant to the souls of Thy servants\ndeparted the remission of their sins, that,\nthrough pious supplications,\nthey may obtain the pardon\nwhich they have always desired.\nWho livest and reignest with God the Father,\nin the unity of the Holy Ghost,\nworld without end.\n\nAmen.",
      prayerType: "intercession",
      category: "liturgical",
      language: "en",
      summary:
        "The Church's ancient collect for all the faithful departed, 'Fidelium, Deus, omnium conditor', prayed on All Souls Day and whenever the dead are remembered.",
      occasions: ["all-souls", "november", "funerals"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}2181`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-for-a-happy-death",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}478`],
    payload: {
      slug: "prayer-for-a-happy-death",
      title: "Prayer for a Happy Death",
      body: 'O God, great and omnipotent judge of the living and the dead, we are to appear before You after this short life to render an account of our works. Give us the grace to prepare for our last hour by a devout and holy life, and protect us against a sudden and unprovided death. Let us remember our frailty and mortality, that we may always live in the ways of Your commandments. Teach us to "watch and pray" (Luke 21, 36), that when Your summons comes for our departure from this world, we may go forth to meet You, experience a merciful judgment, and rejoice in everlasting happiness. We ask this through Christ our Lord. Amen.',
      prayerType: "intercession",
      category: "general",
      language: "en",
      summary:
        "A prayer asking the grace of a well-prepared death: a devout life, protection from a sudden and unprovided end, and a merciful judgment. It is traditionally prayed daily and in times of serious illness.",
      occasions: ["daily", "illness", "deathbed", "november"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}478`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "plenary-indulgence-at-the-hour-of-death",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}488`],
    payload: {
      slug: "plenary-indulgence-at-the-hour-of-death",
      title: "Act of Acceptance of Death",
      body: "My Lord God, even now resignedly and willingly, I accept at Thy hand, with all its anxieties, pains, and sufferings, whatever kind of death it shall please Thee to be mine.",
      prayerType: "act",
      category: "general",
      language: "en",
      summary:
        "A short act by which a Christian accepts beforehand, from the hand of God, whatever death he may be given. Catholic Online records that by a decree of the Congregation of Indulgences of 9 March 1904 Pope St. Pius X attached a plenary indulgence at the moment of death to this act, made on any chosen day after Confession and Holy Communion; the Enchiridion Indulgentiarum should be consulted for its present form.",
      occasions: ["daily", "illness", "deathbed"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}488`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "commendation-of-the-dying",
    authorityLevel: "LITURGICAL_BOOK",
    citations: [
      `${PRECES}Varia/CommendatioAnimae.html`,
      `${EWTN_LIBRARY}roman-ritual-part-i-11882`,
    ],
    payload: {
      slug: "commendation-of-the-dying",
      title: "Commendation of a Departing Soul (Proficiscere, anima christiana)",
      body: "Depart, O Christian soul, out of this miserable world, in the name of God the Father Almighty, who created thee; in the name of Jesus Christ, the Son of the living God, who suffered for thee; in the name of the Holy Ghost, who sanctified thee; in the name of the glorious and holy Mother of God, the Blessed Virgin Mary; in the name of Blessed Joseph, the illustrious spouse of the Blessed Virgin; in the name of the Angels, Archangels, Thrones, Dominations, Cherubim and Seraphim: in the name of the patriarchs and prophets, of the holy apostles and evangelists, of the holy martyrs and confessors, of the holy monks and hermits, of the holy virgins and of all the Saints of God; let thy place be this day in peace, and thy abode in holy Sion: Through the same Christ our Lord.\nR. Amen.",
      prayerType: "intercession",
      category: "liturgical",
      language: "en",
      latin:
        "Proficiscere, anima christiana, de hoc mundo, in nomine Dei Patris omnipotentis, qui te creavit: in nomine Iesu Christi, Filii Dei vivi, qui pro te passus est: in nomine Spiritus Sancti, qui in te effusus est: in nomine gloriosae et sanctae Dei Genetricis Virginis Mariae: in nomine beati Ioseph, inclyti eiusdem Virginis Sponsi: in nomine Angelorum et Archangelorum: in nomine Thronorum et Dominationum: in nomine Principatuum et Potestatum: in nomine Virtutum, Cherubim et Seraphim: in nomine Patriarcharum et Prophetarum: in nomine sanctorum Apostolorum et Evangelistarum: in nomine sanctorum Martyrum et Confessorum: in nomine sanctorum Monachorum et Eremitarum: in nomine sanctarum Virginum, et omnium Sanctorum et Sanctarum Dei. Hodie sit in pace locus tuus, et habitatio tua in sancta Sion. Per eundem Christum Dominum nostrum. R. Amen.",
      summary:
        "The central prayer of the Church's rite for the commendation of a departing soul, said as a Christian enters the last agony. Both the Latin of the Rituale Romanum and the older English version are those printed by Preces Latinae; that printing carries two evident typographical corruptions ('Blessed Joseph.' and 'the sanio Christ'), given here as 'Blessed Joseph,' and 'the same Christ' in accordance with the Latin 'Per eundem Christum Dominum nostrum'. The received English abbreviates the list of the angelic choirs that the Latin gives in full. In the full rite the prayer is preceded by a short litany of the saints and followed by further prayers of commendation.",
      occasions: ["deathbed", "last-rites", "illness"],
      relatedSaints: ["saint-joseph"],
      citations: [
        `${PRECES}Varia/CommendatioAnimae.html`,
        `${EWTN_LIBRARY}roman-ritual-part-i-11882`,
      ],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-for-vocations",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}prayer-for-vocations-360`],
    payload: {
      slug: "prayer-for-vocations",
      title: "Prayer for Vocations",
      body: "O Holy Spirit, Spirit of wisdom and divine love, impart Your knowledge, understanding, and counsel to youth that they may know the vocation wherein they can best serve God. Give them courage and strength to follow God's holy will. Guide their uncertain steps, strengthen their resolutions, shield their chastity, fashion their minds, conquer their hearts, and lead them to the vineyards where they will labor in God's holy service.\nAmen.",
      prayerType: "intercession",
      category: "general",
      language: "en",
      summary:
        "A prayer to the Holy Spirit for young people discerning their vocation, asking light to know God's call and courage to follow it. EWTN prints a second vocations prayer alongside this one.",
      occasions: ["vocations", "good-shepherd-sunday", "daily"],
      relatedSaints: [],
      citations: [`${EWTN}prayer-for-vocations-360`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-for-priests",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}1749`],
    payload: {
      slug: "prayer-for-priests",
      title: "Prayer for Priests",
      body: "O Jesus,\nI pray for Your faithful and fervent priests;\nfor Your unfaithful and tepid priests;\nfor Your priests labouring at home\nor abroad in distant mission fields;\nfor Your tempted priests;\nfor Your lonely and desolate priest;\nfor Your young priests;\nfor Your dying priests;\nfor the souls of Your priests in purgatory.\nBut above all I recommend to You the priests dearest to me;\nthe priest who baptized me;\nthe priests who absolved me from my sins;\nthe priests at whose Masses I assisted\nand who gave me Your Body and Blood in Holy communion;\nthe priests who taught and instructed me;\nall the priests to whom I am indebted in any other way.\nO Jesus, keep them all close to Your heart,\nand bless them abundantly in time and in eternity.\n\nAmen.",
      prayerType: "intercession",
      category: "general",
      language: "en",
      summary:
        "A prayer commending every kind of priest to the Heart of Jesus, and in particular the priests through whom one has received the sacraments. It is prayed especially on Holy Thursday and on the feast of the Sacred Heart.",
      occasions: ["holy-thursday", "vocations", "first-friday"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}1749`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-for-the-pope",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}1337`],
    payload: {
      slug: "prayer-for-the-pope",
      title: "Prayer for the Pope",
      body: "Heavenly Father,\nbe pleased to bless and protect our Holy Father,\nPope ____________________,\nwhom you have chosen as the successor of St. Peter\nas the chief minister of unity\nand charity in the Church.\nKeep him safe in holiness of life\nand in wise fulfillment of his awesome responsibilities.\nWe ask this through Christ, our Lord.\n\nAmen.",
      prayerType: "intercession",
      category: "general",
      language: "en",
      summary:
        "A prayer for the Successor of St. Peter, asking that God keep him holy and wise in his office as the visible principle of unity and charity in the Church. The blank is filled with the name of the reigning Pope.",
      occasions: ["daily", "june-29", "for-the-church"],
      relatedSaints: ["saint-peter"],
      citations: [`${CATHOLIC_ONLINE}1337`],
    },
  },
];
