import type { CuratedEntry } from "../index";

const EWTN = "https://www.ewtn.com/catholicism/devotions/";
const CATHOLIC_ONLINE = "https://www.catholic.org/prayers/prayer.php?p=";
const COMPENDIUM =
  "https://www.vatican.va/archive/compendium_ccc/documents/archive_2005_compendium-ccc_en.html";

/**
 * Batch 4 of the curated prayer catalogue: prayers to Christ, Eucharistic
 * prayers and hymns, the Sacred Heart and Holy Face, and prayers to the Holy
 * Spirit and the Blessed Trinity. Every body is the received public-domain
 * text copied character for character from the cited page; line breaks follow
 * the page. Where a page prints only part of a longer hymn, the summary says
 * so rather than filling the gap from another version.
 */
export const prayerBatch4: CuratedEntry[] = [
  {
    contentType: "PRAYER",
    slug: "pange-lingua",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}1673`],
    payload: {
      slug: "pange-lingua",
      title: "Pange Lingua Gloriosi (Sing, My Tongue, the Saviour's Glory)",
      body: "Sing, my tongue, the Saviour's glory,\nOf His flesh the mystery sing;\nOf the blood all price exceeding,\nShed by our immortal King.\nDestined for the world's redemption.\nFrom a noble womb to spring.\nOf a pure and spotless virgin,\nBorn for us on earth below,\nHe, as man with man conversing,\nStay'd, the seeds of truth to sow;\nThen He closed in solemn order\nWondrously His life of woe.\nOn the night of that last supper,\nSeated with His chosen band,\nHe the paschal victim eating,\nFirst fulfils the law's command;\nThen, as food of all His brethren,\nGives Himself with His own hand.\nWord made flesh, the bread of nature\nBy His word to flesh he turns;\nWine into His blood he changes:\nWhat though sense no change discerns?\nOnly be the heart in earnest,\nFaith her lesson quickly learns",
      prayerType: "general",
      category: "eucharistic",
      language: "en",
      summary:
        "The hymn Saint Thomas Aquinas composed for the feast of Corpus Christi, sung at the procession of the Blessed Sacrament on Holy Thursday and Corpus Christi. The cited page prints the first four stanzas; the two closing stanzas of the hymn are the Tantum Ergo, curated separately.",
      occasions: ["corpus-christi", "holy-thursday", "adoration", "benediction"],
      relatedSaints: ["saint-thomas-aquinas"],
      citations: [`${CATHOLIC_ONLINE}1673`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "ave-verum-corpus",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}1308`],
    payload: {
      slug: "ave-verum-corpus",
      title: "Ave Verum Corpus (Hail to Thee! True Body Sprung)",
      body: "Hail to Thee! True body sprung\nFrom the Virgin Mary’s womb!\nThe same that on the cross was hung\nAnd bore for man the bitter doom.\nThou Whose side was pierced and flowed\nBoth with water and with blood;\nSuffer us to taste of Thee\nIn our life’s last agony.\nO kind, O loving One!\nO Jesus, Mary’s Son!\n\nAmen.",
      prayerType: "general",
      category: "eucharistic",
      language: "en",
      summary:
        "A short medieval Eucharistic hymn, greeting the true Body born of the Virgin and sacrificed on the Cross, long sung at the elevation and at Benediction. Its authorship is unknown; the cited page attributes it to Saint Thomas Aquinas, but the hymn is generally dated to the fourteenth century.",
      occasions: ["adoration", "benediction", "corpus-christi", "after-communion"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}1308`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-before-mass",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}126`],
    payload: {
      slug: "prayer-before-mass",
      title: "Prayer before Mass",
      body: "Receive, O Holy Trinity, One God, this Holy Sacrifice of the Body and Blood of our Lord Jesus Christ, which I, Your unworthy servant, desire now to offer to Your Divine Majesty by the hands of this Your minister, with all the Sacrifices which have ever been or will be offered to You, in union with that most Holy Sacrifice offered by the same Christ our Lord at the Last Supper, and on the Altar of the Cross.\n\nI offer it to You with the utmost affection of devotion, out of pure love for Your infinite goodness, and according to the most holy intention of the same Christ our Lord, and of our Holy Mother the Church.\n\nO God, almighty and merciful, grant us through this Holy Sacrifice, joy and peace, a holier life, time to do penance, grace and consolation of the Holy Spirit, and perseverance in good works. Amen.",
      prayerType: "general",
      category: "eucharistic",
      language: "en",
      summary:
        "A traditional prayer of intention said before Mass, uniting the offering the priest is about to make with the sacrifice of Christ at the Last Supper and on the Cross.",
      occasions: ["mass", "before-mass"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}126`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-of-saint-thomas-before-communion",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}2030`],
    payload: {
      slug: "prayer-of-saint-thomas-before-communion",
      title: "Prayer of Saint Thomas Aquinas before Communion (Omnipotens sempiterne Deus)",
      body: "Almighty and everlasting God,\nbehold I come to the Sacrament of Thine only-begotten Son,\nour Lord Jesus Christ:\nI come as one infirm to the physician of life,\nas one unclean to the fountain of mercy,\nas one blind to the light of everlasting brightness,\nas one poor and needy to the Lord of heaven and earth.\nTherefore I implore the abundance of Thy measureless bounty\nthat Thou wouldst vouchsafe to heal my infirmity,\nwash my uncleanness,\nenlighten my blindness,\nenrich my poverty and clothe my nakedness,\nthat I may receive the Bread of Angels,\nthe King of kings, the Lord of lords,\nwith such reverence and humility,\nwith such sorrow and devotion,\nwith such purity and faith,\nwith such purpose and intention\nas may be profitable to my soul’s salvation.\nGrant unto me, I pray,\nthe grace of receiving not only the Sacrament of our Lord’s Body and Blood,\nbut also the grace and power of the Sacrament.\nO most gracious God,\ngrant me so to receive the Body of Thine only-begotten Son,\nour Lord Jesus Christ,\nwhich He took from the Virgin Mary,\nas to merit to be incorporated into His mystical Body,\nand to be numbered amongst His members.\nO most loving Father,\ngive me grace to behold forever\nThy beloved Son with His face at last unveiled,\nwhom I now purpose to receive under the sacramental veil here below.\n\nAmen.",
      prayerType: "general",
      category: "eucharistic",
      language: "en",
      summary:
        "The preparation for Holy Communion written by Saint Thomas Aquinas, beginning 'Omnipotens sempiterne Deus', printed among the prayers of preparation in the Roman Missal. This is the traditional English translation.",
      occasions: ["before-communion", "mass", "adoration"],
      relatedSaints: ["saint-thomas-aquinas"],
      citations: [`${CATHOLIC_ONLINE}2030`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-of-saint-thomas-after-communion",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}2025`],
    payload: {
      slug: "prayer-of-saint-thomas-after-communion",
      title: "Prayer of Saint Thomas Aquinas after Communion (Gratias tibi ago)",
      body: "I give thanks to Thee, O Lord, most holy,\nFather almighty, eternal God,\nthat Thou hast vouchsafed,\nfor no merit of mine own,\nbut out of Thy pure mercy,\nto appease the hunger of my soul\nwith the precious body and blood of Thy Son,\nOur Lord Jesus Christ.\nHumbly I implore Thee,\nlet not this holy communion\nbe to me an increase of guilt unto my punishment,\nbut an availing plea unto pardon and salvation.\nLet it be to me the armour of faith\nand the shield of good will.\nMay it root out from my heart all vice;\nmay it utterly subdue my evil passions\nand all my unruly desires.\nMay it perfect me in charity and patience;\nin humility and obedience;\nand in all other virtues.\nMay it be my sure defence\nagainst the snares laid for me by my enemies,\nvisible and invisible.\nMay it restrain and quiet all my evil impulses,\nand make me ever cleave to Thee\nWho art the one true God.\nMay I owe to it a happy ending of my life.\nAnd do Thou, O heavenly Father,\nvouchsafe one day to call me, a sinner,\nto that ineffable banquet,\nwhere Thou, together with Thy Son and the Holy Ghost,\nart to Thy saints true and unfailing light,\nfullness of content,\njoy for evermore,\ngladness without alloy,\nconsummate and everlasting happiness.\nThrough the same Christ our Lord.\n\nAmen.",
      prayerType: "general",
      category: "eucharistic",
      language: "en",
      summary:
        "The thanksgiving after Holy Communion written by Saint Thomas Aquinas, beginning 'Gratias tibi ago', printed among the prayers of thanksgiving in the Roman Missal. This is the traditional English translation.",
      occasions: ["after-communion", "thanksgiving", "mass"],
      relatedSaints: ["saint-thomas-aquinas"],
      citations: [`${CATHOLIC_ONLINE}2025`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-while-visiting-the-blessed-sacrament",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}prayer-while-visiting-the-most-blessed-sacrament-374`],
    payload: {
      slug: "prayer-while-visiting-the-blessed-sacrament",
      title: "Prayer while Visiting the Most Blessed Sacrament",
      body: "My Lord Jesus Christ, for the love which You bear to men, You remain night and day in this Sacrament full of compassion and of love, awaiting, calling, and welcoming all who come to visit You. I believe that You are present in the Sacrament of the Altar: I adore You from the abyss of my nothingness, and I thank You for all the graces which You have bestowed upon me and in particular for having given me Yourself in this Sacrament, for having given me your holy Mother Mary for my advocate, and for having called me to visit You in this chapel. I now salute\nYour most loving Heart: and this for three ends:\n1. In thanksgiving for this great gift;\n2. To make amends to You for all the outrages which You receive in this Sacrament from all Your enemies;\n3. I intend by this visit to adore You in all the places on earth in which You are the least revered and the most abandoned.\nMy Jesus, I love You with all my heart. I grieve for having so many times offended Your infinite goodness. I promise with Your grace never more to offend You in the future.\nNow, miserable and unworthy though I be, I consecrate myself to You without reserve;\nI give You my entire will, my affections, my desires, and all that I possess. From now on dispose of me and of all that I have as You please. All that I ask of You and desire is Your holy love, final perseverance, and the perfect accomplishment of Your will. I recommend to You the souls in purgatory; but especially those who had the greatest devotion to the most Blessed Sacrament and to the Blessed Virgin Mary. I also recommend to You all poor sinners.\nMy dear Saviour, I unite all my affections with the affections of Your most loving Heart; and I offer them, thus united, to Your eternal Father, and beseech Him in Your name to vouchsafe, for Your love, to accept them.\nAmen.",
      prayerType: "general",
      category: "eucharistic",
      language: "en",
      summary:
        "The prayer Saint Alphonsus Liguori wrote for visits to the Blessed Sacrament, adoring Christ present in the tabernacle and offering the visit in thanksgiving, in reparation, and for the churches where he is least honoured.",
      occasions: ["adoration", "visit-to-the-blessed-sacrament"],
      relatedSaints: ["saint-alphonsus-liguori"],
      citations: [`${EWTN}prayer-while-visiting-the-most-blessed-sacrament-374`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-the-holy-face",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}holy-face-389`],
    payload: {
      slug: "prayer-to-the-holy-face",
      title: "The Holy Face",
      body: "O Blessed Face of my kind Savior,\nby the tender love\nand piercing sorrow\nof Our Lady as she beheld You in\nYour cruel Passion,\ngrant us to share in this\nintense sorrow and love\nso as to fulfill the holy will\nof God to the utmost\nof our ability.\nAmen.",
      prayerType: "general",
      category: "devotional",
      language: "en",
      summary:
        "A short prayer of the devotion to the Holy Face of Jesus, asking through Our Lady's sorrow at the Passion for a share in her love and grief and for the strength to do God's will.",
      occasions: ["lent", "shrove-tuesday", "reparation"],
      relatedSaints: [],
      citations: [`${EWTN}holy-face-389`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "golden-arrow",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}140`],
    payload: {
      slug: "golden-arrow",
      title: "The Golden Arrow",
      body: "May the most holy, most sacred, most adorable, most mysterious and unutterable Name of God be always praised, blessed, loved, adored and glorified in heaven on earth and under the earth, by all the creatures of God, and by the Sacred Heart of our Lord Jesus Christ in the most Holy Sacrament of the altar.\n\nAmen",
      prayerType: "general",
      category: "devotional",
      language: "en",
      summary:
        "An act of reparation for blasphemy against the holy Name of God, made known through Sister Mary of Saint Peter, a Discalced Carmelite of Tours, in 1843, and prayed within the devotion to the Holy Face.",
      occasions: ["reparation", "daily"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}140`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "short-consecration-to-the-sacred-heart",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [
      `${CATHOLIC_ONLINE}3069`,
      `${EWTN}short-act-of-consecration-to-the-sacred-heart-272`,
    ],
    payload: {
      slug: "short-consecration-to-the-sacred-heart",
      title: "A Short Consecration to the Sacred Heart of Jesus",
      body: "Sacred Heart of Jesus,\nfilled with infinite love,\nbroken by my ingratitude,\npierced by my sins,\nyet loving me still,\naccept the consecration that I make to You,\nof all that I am and all that I have.\nTake every faculty of my soul and body,\nand draw me, day by day,\nnearer and nearer to Your Sacred Side,\nand there, as I can bear the lesson,\nteach me Your blessed ways.\n\nAmen.",
      prayerType: "consecration",
      category: "consecration",
      language: "en",
      summary:
        "A brief daily act of consecration to the Sacred Heart of Jesus, giving over every faculty of soul and body and asking to be drawn nearer to the pierced Side of Christ. The same text is printed by EWTN as a single paragraph.",
      occasions: ["daily", "first-friday", "june"],
      relatedSaints: [],
      citations: [
        `${CATHOLIC_ONLINE}3069`,
        `${EWTN}short-act-of-consecration-to-the-sacred-heart-272`,
      ],
    },
  },
  {
    contentType: "PRAYER",
    slug: "consecration-of-the-family-to-the-sacred-heart",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}consecration-of-the-family-to-the-sacred-heart-of-jesus-271`],
    payload: {
      slug: "consecration-of-the-family-to-the-sacred-heart",
      title: "Consecration of the Family to the Sacred Heart of Jesus",
      body: "Sacred Heart of Jesus, You made clear to Saint Margaret Mary Your desire of being King in Christian families. We today wish to proclaim Your most complete kingly dominion over our own family. We want to live in the future with Your life. We want to cause to flourish in our midst those virtues to which You have promised peace here below. We want to banish far from us the spirit of the world which You have cursed. You shall be King over our minds in the simplicity of our faith, and over our hearts by the wholehearted love with which they shall burn for You, the flame of which we will keep alive by the frequent reception of Your divine Eucharist. Be so kind, O divine Heart, as to preside over our assemblings, to bless our enterprises, both spiritual and temporal, to dispel our cares, to sanctify our joys, and to alleviate our sufferings. If ever one or other of us should have the misfortune to afflict You, remind him, O Heart of Jesus, that You are good and merciful to the penitent sinner. And when the hour of separation strikes, when death shall come to cast mourning into our midst, we will all, both those who go and those who stay, be submissive to Your eternal decrees. We shall console ourselves with the thought that a day will come when the entire family, reunited in heaven, can sing forever Your glories and Your mercies. May the Immaculate Heart of Mary and the glorious patriarch Saint Joseph present this consecration to You, and keep it in our minds all the days of our life. All glory to the Heart of Jesus, our King and our Father!",
      prayerType: "consecration",
      category: "consecration",
      language: "en",
      summary:
        "The act by which a household consecrates itself to the Sacred Heart, used at the enthronement of an image of the Sacred Heart in the home. It recalls the desire Christ made known to Saint Margaret Mary that he reign in Christian families.",
      occasions: ["enthronement", "family", "june"],
      relatedSaints: ["saint-margaret-mary-alacoque"],
      citations: [`${EWTN}consecration-of-the-family-to-the-sacred-heart-of-jesus-271`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "act-of-oblation-to-the-sacred-heart",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}442`],
    payload: {
      slug: "act-of-oblation-to-the-sacred-heart",
      title: "Act of Oblation to the Sacred Heart",
      body: "My loving Jesus, out of the grateful love I bear you, and to make reparation for my unfaithfulness to grace, I give you my heart, and I consecrate myself wholly to you; and with your help I purpose never to sin again. Amen.",
      prayerType: "act",
      category: "devotional",
      language: "en",
      summary:
        "A short act of oblation to the Sacred Heart of Jesus, offering the heart in gratitude and in reparation for unfaithfulness to grace, with the resolution not to sin again.",
      occasions: ["first-friday", "daily", "june"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}442`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-to-the-wounded-heart",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}prayer-to-the-wounded-heart-of-jesus-12726`],
    payload: {
      slug: "prayer-to-the-wounded-heart",
      title: "Prayer to the Wounded Heart of Jesus",
      body: "O my Most Loving and Gentle Jesus, I desire with all the affections of my heart, that all beings should praise Thee, honor Thee and glorify Thee eternally for that sacred wound wherewith Thy divine side was rent. I deposit, enclose, conceal in that wound and in that opening in Thy Heart, my heart and all my feelings, thoughts, desires, intentions and all the faculties of my soul. I entreat Thee, by the precious Blood and Water that flowed from Thy Most Loving Heart, to take entire possession of me, that Thou may guide me in all things. Consume me in the burning fire of thy holy Love, so that I may be so absorbed and transformed into Thee that I may no longer be but one with Thee.\nAmen.",
      prayerType: "general",
      category: "devotional",
      language: "en",
      summary:
        "A prayer of Blessed John Justus Lanspergius, the Carthusian, asking to be hidden in the wound of Christ's pierced side and wholly transformed into him by love.",
      occasions: ["sacred-heart", "lent", "first-friday"],
      relatedSaints: [],
      citations: [`${EWTN}prayer-to-the-wounded-heart-of-jesus-12726`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "salutation-to-the-hearts-of-jesus-and-mary",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}1293`],
    payload: {
      slug: "salutation-to-the-hearts-of-jesus-and-mary",
      title: "Salutations to the Hearts of Jesus and Mary",
      body: "Hail, Heart most holy.\nHail, Heart most gentle.\nHail, Heart most humble.\nHail, Heart most pure.\nHail, Heart most wise.\nHail, Heart most patient.\nHail, Heart most merciful.\nHail, most loving Heart of Jesus and Mary.\nWe revere Thee.\nWe glorify Thee.\nWe give Thee thanks.\nWe love Thee.\nWe offer Thee our heart.\nReceive it and possess it wholly.\nPurify it.\nEnlighten it.\nSanctify it.\nThat Thou may live and reign in it now,\nalways and forever and ever.\nAmen.",
      prayerType: "general",
      category: "devotional",
      language: "en",
      summary:
        "A salutation of the united Hearts of Jesus and Mary, from the devotion spread by Saint John Eudes, offering the one who prays it to those Hearts. EWTN prints a longer form of the same salutation with additional invocations.",
      occasions: ["daily", "sacred-heart", "immaculate-heart"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}1293`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "offering-of-the-hearts-of-jesus-and-mary",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}offering-of-the-hearts-of-jesus-and-mary-312`],
    payload: {
      slug: "offering-of-the-hearts-of-jesus-and-mary",
      title: "An Offering of the Hearts of Jesus and Mary",
      body: "O Jesus, only Son of God, only Son of Mary,\nI offer Thee the most loving Heart of Thy divine Mother\nwhich is more precious and pleasing to Thee than all hearts.\nO Mary, Mother of Jesus,\nI offer Thee the most adorable Heart of Thy well-beloved Son,\nwho is the life and love and joy of Thy Heart.\nBlessed be the Most Loving Heart\nand Sweet Name of Our Lord Jesus Christ\nand the most glorious\nVirgin Mary, His Mother,\nin eternity and forever.\nAmen.",
      prayerType: "general",
      category: "devotional",
      language: "en",
      summary:
        "A prayer of Saint John Eudes, apostle of the Hearts of Jesus and Mary, offering each Heart to the other and blessing the Holy Name of Jesus and his Mother.",
      occasions: ["daily", "sacred-heart", "immaculate-heart"],
      relatedSaints: [],
      citations: [`${EWTN}offering-of-the-hearts-of-jesus-and-mary-312`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "jesus-prayer",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}3088`],
    payload: {
      slug: "jesus-prayer",
      title: "The Jesus Prayer",
      body: "Lord Jesus Christ, Son of God, Have mercy on me, a sinner.",
      prayerType: "general",
      category: "general",
      language: "en",
      summary:
        "The short invocation of the Holy Name repeated continually in the Eastern tradition of the prayer of the heart, drawn from the cry of the publican and of the blind man in the Gospels. The Catechism treats it among the forms of vocal prayer that lead to prayer without ceasing.",
      occasions: ["daily", "silent-prayer"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}3088`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "holy-name-aspiration",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}471`],
    payload: {
      slug: "holy-name-aspiration",
      title: "Pious Invocations",
      body: "My God I love Thee. Amen.\nJesus, Mary, I love you. Save souls. Amen.\nMost Sacred Heart of Jesus may the whole world burn with love for You! Amen.\nLord Jesus Christ, have mercy on me. Amen.\nSacred Heart of Jesus I trust in you. Amen.\nEucharistic Heart of Jesus, have mercy on us. Amen.\nSacred Heart of Jesus, your kingdom come. Amen.\nDivine heart of Jesus, convert sinners, save the dying, deliver the holy souls in purgatory. Amen.\nJesus, meek and humble of heart, make our hearts like unto yours. Amen.\nSacred Heart of Jesus, I believe in your love for me. Amen.\nGlory, love, and thanksgiving be to the Sacred Heart of Jesus. Amen.\nOh Mary, queen of the clergy, pray for us; obtain for us a number of holy priests. Amen.\nMay the peace of God which surpasses all understanding, guard your hearts and minds in Christ Jesus. Amen.\nMay the souls of the faithful departed through the mercy of God, rest in peace. Amen.",
      prayerType: "general",
      category: "general",
      language: "en",
      summary:
        "A set of short aspirations, or ejaculatory prayers, meant to be repeated through the day so that work and prayer are woven together. Most are addressed to the Sacred Heart of Jesus; the page also prints an invocation of Our Lady for holy priests, the blessing of the peace of God from Philippians, and the prayer for the faithful departed.",
      occasions: ["daily", "work"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}471`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "veni-sancte-spiritus",
    authorityLevel: "VATICAN",
    citations: [COMPENDIUM],
    payload: {
      slug: "veni-sancte-spiritus",
      title: "Veni Sancte Spiritus (Come, Holy Spirit)",
      body: "Come, Holy Spirit, come!\nAnd from your celestial home\nShed a ray of light divine!\nCome, Father of the poor!\nCome, source of all our store!\nCome, within our bosoms shine.\nYou, of comforters the best;\nYou, the soul’s most welcome guest;\nSweet refreshment here below;\nIn our labor, rest most sweet;\nGrateful coolness in the heat;\nSolace in the midst of woe.\nO most blessed Light divine,\nShine within these hearts of yours,\nAnd our inmost being fill!\nWhere you are not, we have naught,\nNothing good in deed or thought,\nNothing free from taint of ill.\nHeal our wounds, our strength renew;\nOn our dryness pour your dew;\nWash the stains of guilt away:\nBend the stubborn heart and will;\nMelt the frozen, warm the chill;\nGuide the steps that go astray.\nOn the faithful, who adore\nAnd confess you, evermore\nIn your sevenfold gift descend:\nGive them virtue’s sure reward;\nGive them your salvation, Lord;\nGive them joys that never end.",
      prayerType: "general",
      category: "trinitarian",
      language: "en",
      latin:
        "Veni, Sancte Spíritus,\net emítte cælitus\nlucis tuæ rádium.\nVeni, pater páuperum,\nveni, dator múnerum,\nveni, lumen córdium.\nConsolátor óptime,\ndulcis hospes ánimæ,\ndulce refrigérium.\nIn labóre réquies,\nin æstu tempéries,\nin fletu solácium.\nO lux beatíssima,\nreple cordis íntima\ntuórum fidélium.\nSine tuo númine,\nnihil est in hómine\nnihil est innóxium.\nLava quod est sórdidum,\nriga quod est áridum,\nsana quod est sáucium.\nFlecte quod est rígidum,\nfove quod est frígidum,\nrege quod est dévium.\nDa tuis fidélibus,\nin te confidéntibus,\nsacrum septenárium.\nDa virtútis méritum,\nda salútis éxitum,\nda perénne gáudium. Amen.",
      summary:
        "The sequence of Pentecost, known as the Golden Sequence, sung at Mass on Pentecost Sunday. The Latin text and this English translation are those printed in the Appendix of Common Prayers of the Compendium of the Catechism of the Catholic Church.",
      occasions: ["pentecost", "confirmation", "before-work"],
      relatedSaints: [],
      citations: [COMPENDIUM],
    },
  },
  {
    contentType: "PRAYER",
    slug: "consecration-to-the-holy-spirit",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}330`],
    payload: {
      slug: "consecration-to-the-holy-spirit",
      title: "Act of Consecration to the Holy Ghost",
      body: "On my knees before the great multitude of heavenly witnesses, I offer myself soul and body to Thee, Eternal Spirit of God. I adore the brightness of Thy purity, the unerring keenness of Thy justice, and the might of Thy love. Thou art the Strength and Light of my soul. In Thee I live and move and am. I desire never to grieve Thee by unfaithfulness to grace, and I pray with all my heart to be kept from the smallest sin against Thee. Mercifully guard my every thought and grant that I may always watch for Thy light and listen to Thy voice and follow Thy gracious inspirations. I cling to Thee and give myself to Thee and ask Thee by Thy compassion to watch over me in my weakness. Holding the pierced Feet of Jesus and looking at His Five Wounds and trusting in His Precious Blood and adoring His opened Side and stricken Heart, I implore Thee Adorable Spirit, helper of my infirmity, so to keep me in Thy grace that I may never sin against Thee. Give me grace O Holy Ghost, Spirit of the Father and the Son, to say to Thee always and everywhere, Speak Lord, for Thy servant heareth. Amen.",
      prayerType: "consecration",
      category: "consecration",
      language: "en",
      summary:
        "A traditional act of self-offering to the Holy Spirit, adoring his purity, justice and love and asking never to grieve him by unfaithfulness to grace. It is often prayed at Confirmation and during the days before Pentecost.",
      occasions: ["pentecost", "confirmation"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}330`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-for-the-seven-gifts",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}335`],
    payload: {
      slug: "prayer-for-the-seven-gifts",
      title: "Prayer for the Seven Gifts of the Holy Ghost",
      body: "O Lord Jesus Christ, Who, before ascending into heaven, didst promise to send the Holy Ghost to finish Thy work in the souls of Thy Apostles and Disciples, deign to grant the same Holy Spirit to me, that He may perfect in my soul the work of Thy grace and Thy love. Grant me the Spirit of Wisdom that I may despise the perishable things of this world and aspire only after the things that are eternal, the Spirit of Understanding to enlighten my mind with the light of Thy divine truth, the Spirit of Counsel that I may ever choose the surest way of pleasing God and gaining Heaven, the Spirit of Fortitude that I may bear my cross with Thee, and that I may overcome with courage all the obstacles that oppose my salvation, the Spirit of Knowledge that I may know God and know myself and grow perfect in the science of the Saints, the Spirit of Piety that I may find the service of God sweet and amiable, the Spirit of Fear that I may be filled with a loving reverence towards God, and may dread in any way to displease Him. Mark me, dear Lord, with the sign of Thy true disciples and animate me in all things with Thy Spirit. Amen.",
      prayerType: "general",
      category: "trinitarian",
      language: "en",
      summary:
        "A prayer asking Christ for the sevenfold gift of the Holy Spirit named by the prophet Isaiah — wisdom, understanding, counsel, fortitude, knowledge, piety and fear of the Lord. It is commonly prayed in preparation for Confirmation.",
      occasions: ["confirmation", "pentecost"],
      relatedSaints: [],
      citations: [`${CATHOLIC_ONLINE}335`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-for-the-help-of-the-holy-spirit",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}333`],
    payload: {
      slug: "prayer-for-the-help-of-the-holy-spirit",
      title: "Prayer for the Help of the Holy Spirit",
      body: "O God, send forth your Holy Spirit into my heart that I may perceive, into my mind that I may remember, and into my soul that I may meditate. Inspire me to speak with piety, holiness, tenderness and mercy. Teach, guide and direct my thoughts and senses from beginning to end. May your grace ever help and correct me, and may I be strengthened now with wisdom from on high, for the sake of your infinite mercy. Amen.",
      prayerType: "general",
      category: "trinitarian",
      language: "en",
      summary:
        "A prayer attributed to Saint Anthony of Padua asking the Holy Spirit for light in the heart, memory and understanding, and for grace in speaking and acting. It is often used before study, preaching or teaching.",
      occasions: ["daily", "before-study", "before-work"],
      relatedSaints: ["saint-anthony-of-padua"],
      citations: [`${CATHOLIC_ONLINE}333`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "trisagion",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}angelic-trisagion-382`],
    payload: {
      slug: "trisagion",
      title: "The Angelic Trisagion",
      body: "In the name of the Father, and of the Son, and of the Holy Spirit. Amen.\n\nV. Lord, open my lips.\nR. And my mouth shall declare Thy praise.\nV. O God, come to my assistance.\nR. O Lord, make haste to help me.\nV. Glory be to the Father, and to the Son, and to the Holy Spirit,\nR. As it was in the beginning, is now and will be forever. Amen.\n\nThe decade below is recited three times, once for each member of the Trinity.\n\nAll: Holy God! Holy Strong One! Holy Immortal One, have mercy upon us.\n\nV. Our Father, Who art in heaven, hallowed be Thy name. Thy kingdom come. Thy will be done, on earth as it is in heaven. Give us this day our daily bread and forgive us our trespasses as we forgive those who trespass against us. And lead us not into temptation, but deliver us from evil. Amen.\n\nThe following part of the decade is repeated nine times\n\nV. To Thee, O Blessed Trinity, be praise, and honor, and thanksgiving, for ever and ever!\nR. Holy, holy, holy Lord, God of hosts. Heaven and earth are filled with Thy glory.\nV. Glory be to the Father, and to the Son, and to the Holy Spirit,\nR. As it was in the beginning, is now and will be forever. Amen.\n\nEnd of Decade\n\nAntiphon\n\nGod the Father unbegotten, only-begotten Son, and Holy Spirit, the Comforter; holy and undivided Trinity, with all our hearts we acknowledge Thee: Glory to Thee forever.\nV. Let us bless the Father, and the Son with the Holy Spirit.\nR. Be praised and exalted above all things forever.\n\nLet us pray,\nAlmighty, ever-living God, who has permitted us Thy servants, in our profession of the true faith, to acknowledge the glory of the eternal Trinity, and in the power of that majesty to adore the Unity, grant, that by steadfastness in this same faith, we may be ever guarded against all adversity: through Christ our Lord.\n\nAll: Amen\nAll: Set us free, save us, vivify us, O Blessed Trinity!",
      prayerType: "general",
      category: "trinitarian",
      language: "en",
      latin:
        "In nomine Patris et Filii et Spiritus Sancti. Amen.\nV. Domine, labia mea aperies.\nR. Et os meum annuntiabit laudem tuam.\nV. Deus in adiutorium meum intende.\nR. Domine, ad adiuvandum me festina.\nV. Gloria Patri et Filio et Spiritui Sancto,\nR. Sicut erat in principio, et nunc, et semper, et in saecula saeculorum. Amen.\n\nThe decade below is recited three times, once for each member of the Trinity.\n\nAll: Sanctus Deus, Sanctus fortis, Sanctus immortalis, miserere nobis.\n\nV. Pater noster, qui es in caelis, sanctificetur nomen tuum. Adveniat regnum tuum. Fiat voluntas tua, sicut in caelo et in terra. Panem nostrum quotidianum da nobis hodie, et dimitte nobis debita nostra sicut et nos dimittimus debitoribus nostris. Et ne nos inducas in tentationem, sed libera nos a malo. Amen.\n\nThe following part of the decade is repeated nine times.\n\nV. Tibi laus, Tibi gloria, Tibi gratiarum actio in saecula sempiterna, O Beata Trinitas.\nR. Sanctus, Sanctus, Sanctus Dominus Deus exercituum. Pleni sunt coeli et terra gloria tua.\nV. Gloria Patri et Filio et Spiritui Sancto,\nR. Sicut erat in principio, et nunc, et semper, et in saecula saeculorum. Amen.\n\nEnd of Decade\n\nAntiphon\n\nTe Deum Patrem ingenitum, te Filium unigenitum, te Spiritum Sanctum Paraclitum, sanctam et individuam Trinitatem, toto corde et ore confitemur, laudamus, atque benedicimus: Tibi gloria in saecula.\nV. Benedicimus Patrem, et Filium cum Sancto Spiritu.\nR. Laudemus et superexaltemus eum in saecula.\nOremus.\nOmnipotens sempiterne Deus, qui dedisti famulis tuis in confessione verae fidei, aeternae Trinitatis gloriam agnoscere, et in potentia maiestatis adorare Unitatem: quaesumus, ut eiusdem fidei firmitate, ab omnibus semper muniamur adversis. Per Christum Dominum nostrum.\nAll: Amen.\nAll: Libera nos, salva nos, vivifica nos, O Beata Trinitas!",
      summary:
        "The Trisagion of the Order of the Most Holy Trinity, praising the Father, the Son and the Holy Spirit in three decades that echo the angels' cry of 'Holy, holy, holy'. It has been the proper prayer of the Trinitarians for centuries.",
      occasions: ["trinity-sunday", "daily"],
      relatedSaints: [],
      citations: [`${EWTN}angelic-trisagion-382`],
    },
  },
  {
    contentType: "PRAYER",
    slug: "prayer-of-thanksgiving-to-the-trinity",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}prayer-of-thanksgiving-to-the-trinity-366`],
    payload: {
      slug: "prayer-of-thanksgiving-to-the-trinity",
      title: "Prayer of Thanksgiving to the Trinity",
      body: "O Eternal God! O Eternal Trinity! Through the union of Thy divine nature Thou has made so precious the Blood of Thine Only-begotten Son! O eternal Trinity, Thou art as deep a mystery as the sea, in whom the more I seek, the more I find; and the more I find, the more I seek. For even immersed in the depths of Thee, my soul is never satisfied, always famished and hungering for Thee eternal Trinity, wishing and desiring to see Thee, the True Light.\n\nO Eternal Trinity, with the light of understanding I have tasted and seen the depths of Thy mystery and the beauty of Thy creation. In seeing myself in Thee, I have seen that I will become like Thee. O eternal Father, from Thy power and Thy wisdom, clearly, Thou has given to me a share of that wisdom which belongs to Thine Only-begotten Son. And truly has the Holy Spirit, who proceeds from Thee, Father and Son, given to me the desire to love Thee.\n\nO Eternal Trinity, Thou art my maker and I am Thy creation. Illuminated by Thee, I have learned that Thou has made me a new creation through the Blood of Thine Only-begotten Son because Thou are captivated by love at the beauty of Thy creation.\n\nO Eternal Trinity, O Divinity, O Unfathomable Abyss, O Deepest Sea, what greater gift could Thou give me than Thy very Self? Thou art a fire that burns eternally yet is never consumed, a fire that consumes with Thy heat my self-love. Again, and again Thou art the fire who taketh away all cold heartedness and illuminates the mind by Thy light, the light with which Thou has made me to know Thy truth.\n\nBy this mirrored light I know Thou are the highest good, a good above all good, a fortunate good, an incomprehensible good, an unmeasurable good, a beauty above all beauty, a wisdom above all wisdom, for Thou art wisdom itself, the food of angels, the fire of love that Thou gives to man.\n\nThou art the garment covering our nakedness. Thou feed our family with Thy sweetness, a sweetness Thou art from which there is no trace of bitterness. O Eternal Trinity! Amen.",
      prayerType: "general",
      category: "trinitarian",
      language: "en",
      summary:
        "The closing prayer of the Dialogue on Divine Providence of Saint Catherine of Siena, Doctor of the Church, giving thanks to the Trinity as an unfathomable sea and a fire of love that is never consumed.",
      occasions: ["trinity-sunday", "thanksgiving"],
      relatedSaints: ["saint-catherine-of-siena"],
      citations: [`${EWTN}prayer-of-thanksgiving-to-the-trinity-366`],
    },
  },
];
