import type { CuratedEntry } from "../index";

const EWTN = "https://www.ewtn.com/catholicism/devotions/";
const CATHOLIC_ONLINE = "https://www.catholic.org/prayers/prayer.php?p=";
const LORETO = "https://www.vatican.va/special/rosary/documents/litanie-lauretane_en.html";
const JOSEPH_LITANY_2021 =
  "https://press.vatican.va/content/salastampa/en/bollettino/pubblico/2021/05/01/210501c.html";
const JOSEPH_LETTER_2021 =
  "https://press.vatican.va/content/salastampa/en/bollettino/pubblico/2021/05/01/210501b.html";

interface LitanyInput {
  slug: string;
  title: string;
  authorityLevel: CuratedEntry["authorityLevel"];
  citations: string[];
  lines: string[];
  occasions: string[];
  relatedSaints?: string[];
  summary: string;
  latin?: string[];
}

/**
 * Batch 1 of the curated prayer catalogue: the litanies.
 *
 * Each body is the received public-domain English text of the cited page,
 * reproduced word for word. Because the sources set litanies as two-column
 * tables (invocation | response), each row is rendered here as a single line,
 * "Invocation, response." — the form in which litanies are printed and the
 * form the prayer page renders as plain text. Nothing else is changed:
 * no invocation is added, dropped, reordered or reworded.
 *
 * The Litany of Loreto carries the invocations published by the Holy See
 * (Mother of mercy, Mother of hope, Solace of Migrants, Queen of families)
 * and the Litany of Saint Joseph the seven invocations added on 1 May 2021,
 * with the official Latin from the Holy See Press Office.
 */
function litany(input: LitanyInput): CuratedEntry {
  const payload: Record<string, unknown> = {
    slug: input.slug,
    title: input.title,
    body: input.lines.join("\n"),
    prayerType: "litany",
    category: "litany",
    language: "en",
    summary: input.summary,
    occasions: input.occasions,
    relatedSaints: input.relatedSaints ?? [],
    citations: input.citations,
  };
  if (input.latin) payload.latin = input.latin.join("\n");
  return {
    contentType: "PRAYER",
    slug: input.slug,
    authorityLevel: input.authorityLevel,
    citations: input.citations,
    payload,
  };
}

export const prayerBatch1: CuratedEntry[] = [
  litany({
    slug: "litany-of-the-saints",
    title: "Litany of the Saints",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-of-the-saints-250`],
    occasions: ["easter-vigil", "ordination", "all-saints", "baptism", "processions"],
    summary:
      "One of the six litanies of the Church that may be used in the liturgy, sung at the Easter Vigil, at ordinations and religious profession, and in processions. This is the traditional form; in private devotion the names of patron and other favourite saints may be added in the appropriate place.",
    lines: [
      "Lord, have mercy on us. Lord, have mercy on us.",
      "Christ, have mercy on us. Christ, have mercy on us.",
      "Lord, have mercy on us. Lord, have mercy on us.",
      "Christ, hear us. Christ, graciously hear us.",
      "",
      "God, the Father of Heaven, have mercy on us.",
      "God the Son, Redeemer of the world, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "",
      "Holy Mary, pray for us.",
      "Holy Mother of God, pray for us.",
      "Holy Virgin of Virgins, pray for us.",
      "St. Michael, pray for us.",
      "St. Gabriel, pray for us.",
      "St. Raphael, pray for us.",
      "All you Holy Angels and Archangels, pray for us.",
      "St. John the Baptist, pray for us.",
      "St. Joseph, pray for us.",
      "All you Holy Patriarchs and Prophets, pray for us.",
      "",
      "St. Peter, pray for us.",
      "St. Paul, pray for us.",
      "St. Andrew, pray for us.",
      "St. James, pray for us.",
      "St. John, pray for us.",
      "St. Thomas, pray for us.",
      "St. James, pray for us.",
      "St. Philip, pray for us.",
      "St. Bartholomew, pray for us.",
      "St. Matthew, pray for us.",
      "St. Simon, pray for us.",
      "St. Jude, pray for us.",
      "St. Matthias, pray for us.",
      "St. Barnabas, pray for us.",
      "St. Luke, pray for us.",
      "St. Mark, pray for us.",
      "All you Holy Apostles and Evangelists, pray for us.",
      "All you Holy Disciples of the Lord, pray for us.",
      "All you Holy Innocents, pray for us.",
      "",
      "St. Stephen, pray for us.",
      "St. Lawrence, pray for us.",
      "St. Vincent, pray for us.",
      "St. Fabian and Sebastian, pray for us.",
      "St. John and Paul, pray for us.",
      "St. Cosmas and Damian, pray for us.",
      "All you Holy Martyrs, pray for us.",
      "",
      "St. Sylvester, pray for us.",
      "St. Gregory, pray for us.",
      "St. Ambrose, pray for us.",
      "St. Augustine, pray for us.",
      "St. Jerome, pray for us.",
      "St. Martin, pray for us.",
      "St. Nicholas, pray for us.",
      "All you Holy Bishops and Confessors, pray for us.",
      "All you Holy Doctors, pray for us.",
      "",
      "St. Anthony, pray for us.",
      "St. Benedict, pray for us.",
      "St. Bernard, pray for us.",
      "St. Dominic, pray for us.",
      "St. Francis, pray for us.",
      "All you Holy Priests and Levites, pray for us.",
      "All you Holy Monks and Hermits, pray for us.",
      "",
      "St. Mary Magdalene, pray for us.",
      "St. Agatha, pray for us.",
      "St. Lucy, pray for us.",
      "St. Agnes, pray for us.",
      "St. Cecilia, pray for us.",
      "St. Anastasia, pray for us.",
      "St. Catherine, pray for us.",
      "St. Clare, pray for us.",
      "All you Holy Virgins and Widows, pray for us.",
      "All you Holy Saints of God, pray for us.",
      "",
      "Lord, be merciful, Lord, save your people.",
      "From all evil, Lord, save your people.",
      "From all sin, Lord, save your people.",
      "From your wrath, Lord, save your people.",
      "From a sudden and unprovided death, Lord, save your people.",
      "From the snares of the devil, Lord, save your people.",
      "From anger, hatred and all ill-will, Lord, save your people.",
      "From the spirit of uncleanness, Lord, save your people.",
      "From lightning and tempest, Lord, save your people.",
      "From the scourge of earthquake, Lord, save your people.",
      "From plague, famine and war, Lord, save your people.",
      "From everlasting death, Lord, save your people.",
      "By the mystery of your Holy Incarnation, Lord, save your people.",
      "By Your Coming, Lord, save your people.",
      "By Your Birth, Lord, save your people.",
      "By Your Baptism and Holy Fasting, Lord, save your people.",
      "By Your Cross and Passion, Lord, save your people.",
      "By Your Death and Burial, Lord, save your people.",
      "By Your Holy Resurrection, Lord, save your people.",
      "By Your wonderful Ascension, Lord, save your people.",
      "By the coming of the Holy Spirit, Lord, save your people.",
      "On the Day of Judgment, Lord, save your people.",
      "",
      "Be merciful to us sinners, Lord, hear our prayer.",
      "That you will spare us, Lord, hear our prayer.",
      "That you will pardon us, Lord, hear our prayer.",
      "That it may please you to bring us to true penance, Lord, hear our prayer.",
      "Guide and protect your holy Church, Lord, hear our prayer.",
      "Preserve in holy religion the Pope, and all those in holy Orders, Lord, hear our prayer.",
      "Humble the enemies of holy Church, Lord, hear our prayer.",
      "Give peace and unity to the whole Christian people, Lord, hear our prayer.",
      "Bring back to the unity of the Church all those who are straying, and bring all unbelievers to the light of the Gospel, Lord, hear our prayer.",
      "Strengthen and preserve us in your holy service, Lord, hear our prayer.",
      "Raise our minds to desire the things of heaven, Lord, hear our prayer.",
      "Reward all our benefactors with eternal blessings, Lord, hear our prayer.",
      "Deliver our souls from eternal damnation, and the souls of our brethren, relatives, and benefactors, Lord, hear our prayer.",
      "Give and preserve the fruits of the earth, Lord, hear our prayer.",
      "Grant eternal rest to all the faithful departed, Lord, hear our prayer.",
      "That it may please You to hear and heed us, Jesus, Son of the Living God, Lord, hear our prayer.",
      "",
      "Lamb of God, who takes away the sins of the world, spare us, O Lord!",
      "Lamb of God, who takes away the sins of the world, graciously hear us, O Lord!",
      "Lamb of God, who takes away the sins of the world, have mercy on us.",
      "",
      "Christ, hear us. Christ, graciously hear us.",
      "Lord Jesus, hear our prayer. Lord Jesus, hear our prayer.",
      "Lord, have mercy on us. Lord, have mercy on us.",
      "Christ, have mercy on us. Christ, have mercy on us.",
      "Lord, have mercy on us. Lord, have mercy on us.",
    ],
  }),
  litany({
    slug: "litany-of-the-holy-name-of-jesus",
    title: "Litany of the Most Holy Name of Jesus",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [
      `${EWTN}holy-name-litany-27905`,
      `${EWTN}litany-of-the-most-holy-name-of-jesus-268`,
    ],
    occasions: ["january", "holy-name-of-jesus", "new-year"],
    summary:
      "An old and popular form of prayer in honour of the Name of Jesus, of unknown authorship. Pope Pius IX approved one of the formularies in use in 1862, and Pope Leo XIII extended the privilege to the whole world on 16 January 1886. It is one of the six litanies approved for public recitation as well as private devotion.",
    lines: [
      "Lord, have mercy on us. Christ, have mercy on us.",
      "Lord, have mercy on us. Christ, hear us. Christ, graciously hear us.",
      "",
      "God the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the World, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "",
      "Jesus, Son of the living God, have mercy on us.",
      "Jesus, Splendor of the Father, have mercy on us.",
      "Jesus, Brightness of eternal Light, have mercy on us.",
      "Jesus, King of Glory, have mercy on us.",
      "Jesus, Sun of Justice, have mercy on us.",
      "Jesus, Son of the Virgin Mary, have mercy on us.",
      "Jesus, most amiable, have mercy on us.",
      "Jesus, most admirable, have mercy on us.",
      "Jesus, the mighty God, have mercy on us.",
      "Jesus, Father of the world to come, have mercy on us.",
      "Jesus, angel of great counsel, have mercy on us.",
      "Jesus, most powerful, have mercy on us.",
      "Jesus, most patient, have mercy on us.",
      "Jesus, most obedient, have mercy on us.",
      "Jesus, meek and humble of heart, have mercy on us.",
      "Jesus, Lover of Chastity, have mercy on us.",
      "Jesus, our Lover, have mercy on us.",
      "Jesus, God of Peace, have mercy on us.",
      "Jesus, Author of Life, have mercy on us.",
      "Jesus, Model of Virtues, have mercy on us.",
      "Jesus, zealous for souls, have mercy on us.",
      "Jesus, our God, have mercy on us.",
      "Jesus, our Refuge, have mercy on us.",
      "Jesus, Father of the Poor, have mercy on us.",
      "Jesus, Treasure of the Faithful, have mercy on us.",
      "Jesus, good Shepherd, have mercy on us.",
      "Jesus, true Light, have mercy on us.",
      "Jesus, eternal Wisdom, have mercy on us.",
      "Jesus, infinite Goodness, have mercy on us.",
      "Jesus, our Way and our Life, have mercy on us.",
      "Jesus, joy of the Angels, have mercy on us.",
      "Jesus, King of the Patriarchs, have mercy on us.",
      "Jesus, Master of the Apostles, have mercy on us.",
      "Jesus, Teacher of the Evangelists, have mercy on us.",
      "Jesus, Strength of Martyrs, have mercy on us.",
      "Jesus, Light of Confessors, have mercy on us.",
      "Jesus, Purity of Virgins, have mercy on us.",
      "Jesus, Crown of all Saints, have mercy on us.",
      "",
      "Be merciful, spare us, O Jesus.",
      "Be merciful, graciously spare us, O Jesus.",
      "",
      "From all evil, deliver us, O Jesus.",
      "From all sin, deliver us, O Jesus.",
      "From Your wrath, deliver us, O Jesus.",
      "From the snares of the devil, deliver us, O Jesus.",
      "From the spirit of fornication, deliver us, O Jesus.",
      "From everlasting death, deliver us, O Jesus.",
      "From the neglect of Your inspirations, deliver us, O Jesus.",
      "Through the mystery of Your Holy Incarnation, deliver us, O Jesus.",
      "Through Your Nativity, deliver us, O Jesus.",
      "Through Your Infancy, deliver us, O Jesus.",
      "Through Your most divine Life, deliver us, O Jesus.",
      "Through Your Labors, deliver us, O Jesus.",
      "Through Your Agony and Passion, deliver us, O Jesus.",
      "Through Your cross and Dereliction, deliver us, O Jesus.",
      "Through your Sufferings, deliver us, O Jesus.",
      "Through Your Death and Burial, deliver us, O Jesus.",
      "Through Your Resurrection, deliver us, O Jesus.",
      "Through Your Ascension, deliver us, O Jesus.",
      "Through Your Institution of the Most Holy Eucharist, deliver us, O Jesus.",
      "Through Your Joys, deliver us, O Jesus.",
      "Through Your Glory, deliver us, O Jesus.",
      "",
      "Lamb of God, who takes away the sins of the world, spare us, O Jesus.",
      "Lamb of God, who takes away the sins of the world, graciously hear us, O Jesus.",
      "Lamb of God, who takes away the sins of the world, have mercy on us, O Jesus.",
      "",
      "Jesus, hear us. Jesus, graciously hear us.",
      "",
      "Let us pray:",
      "Lord Jesus Christ, You have said, 'Ask and you shall receive; seek and you shall find; knock and it shall be opened to you'; mercifully attend to our supplications, and grant us the grace of Your most divine love, that we have loved You with all our hearts, and in all our words and actions, and never cease to praise You.",
      "Make us, O Lord, to have a perpetual fear and love of Your Holy Name, for You never fail to govern those whom You establish in Your love. You, Who live and reign forever and ever. Amen",
    ],
  }),
  litany({
    slug: "litany-of-the-precious-blood",
    title: "Litany of the Most Precious Blood of Jesus",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-of-the-most-precious-blood-of-jesus-248`, `${CATHOLIC_ONLINE}465`],
    occasions: ["july", "precious-blood", "lent"],
    summary:
      "One of the six litanies approved by the Holy See for public recitation as well as private devotion. Its invocations follow the Blood of Christ from the Agony in the Garden to the Cross and the Eucharist, and it is prayed especially in July, the month traditionally dedicated to the Precious Blood.",
    lines: [
      "Lord, have mercy. Lord, have mercy.",
      "Christ, have mercy. Christ, have mercy on us.",
      "Lord, have mercy. Lord, have mercy.",
      "",
      "Jesus, hear us. Jesus, graciously hear us.",
      "",
      "God, the Father of Heaven, have mercy on us.",
      "God, the Son, Redeemer of the world, have mercy on us.",
      "God, the Holy Spirit, have mercy on us.",
      "Holy Trinity, One God, have mercy on us.",
      "",
      "Blood of Christ, only-begotten Son of the Eternal Father, save us.",
      "Blood of Christ, Incarnate Word of God, save us.",
      "Blood of Christ, of the New and Eternal Testament, save us.",
      "Blood of Christ, falling upon the earth in the Agony, save us.",
      "Blood of Christ, shed profusely in the Scourging, save us.",
      "Blood of Christ, flowing forth in the Crowning with Thorns, save us.",
      "Blood of Christ, poured out on the Cross, save us.",
      "Blood of Christ, price of our salvation, save us.",
      "Blood of Christ, without which there is no forgiveness, save us.",
      "Blood of Christ, Eucharistic drink and refreshment of souls, save us.",
      "Blood of Christ, stream of mercy, save us.",
      "Blood of Christ, victor over demons, save us.",
      "Blood of Christ, courage of Martyrs, save us.",
      "Blood of Christ, strength of Confessors, save us.",
      "Blood of Christ, bringing forth Virgins, save us.",
      "Blood of Christ, help of those in peril, save us.",
      "Blood of Christ, relief of the burdened, save us.",
      "Blood of Christ, solace in sorrow, save us.",
      "Blood of Christ, hope of the penitent, save us.",
      "Blood of Christ, consolation of the dying, save us.",
      "Blood of Christ, peace and tenderness of hearts, save us.",
      "Blood of Christ, pledge of eternal life, save us.",
      "Blood of Christ, freeing souls from purgatory, save us.",
      "Blood of Christ, most worthy of all glory and honor, save us.",
      "",
      "Lamb of God, who takes away the sins of the world, spare us, O Lord.",
      "Lamb of God, who takes away the sins of the world, graciously hear us, O Lord.",
      "Lamb of God, who takes away the sins of the world, have mercy on us, O Lord.",
      "",
      "You have redeemed us, O Lord, in your Blood.",
      "And made us, for our God, a kingdom.",
      "",
      "Let us pray, - Almighty and eternal God, you have appointed your only-begotten Son the Redeemer of the world, and willed to be appeased by his Blood. Grant we beg of you, that we may worthily adore this price of our salvation, and through its power be safeguarded from the evils of the present life, so that we may rejoice in its fruits forever in heaven. Through the same Christ our Lord. Amen.",
    ],
  }),
  litany({
    slug: "litany-of-the-blessed-virgin-mary",
    title: "Litany of the Blessed Virgin Mary (Litany of Loreto)",
    authorityLevel: "VATICAN",
    citations: [LORETO],
    occasions: ["may", "october", "rosary", "marian-feasts"],
    summary:
      "The Litany of Loreto, named for the Marian shrine where it has been sung since the sixteenth century, is one of the six litanies approved for public recitation. This is the text published by the Holy See, which includes the invocations Mother of Mercy, Mother of Hope, Solace of Migrants and Queen of families.",
    lines: [
      "Lord have mercy.",
      "Christ have mercy.",
      "Lord have mercy.",
      "Christ hear us.",
      "Christ graciously hear us.",
      "",
      "God, the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the world, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "",
      "Holy Mary, pray for us.",
      "Holy Mother of God, pray for us.",
      "Holy Virgin of virgins, pray for us.",
      "Mother of Christ, pray for us.",
      "Mother of the Church, pray for us.",
      "Mother of Mercy, pray for us.",
      "Mother of divine grace, pray for us.",
      "Mother of Hope, pray for us.",
      "Mother most pure, pray for us.",
      "Mother most chaste, pray for us.",
      "Mother inviolate, pray for us.",
      "Mother undefiled, pray for us.",
      "Mother most amiable, pray for us.",
      "Mother most admirable, pray for us.",
      "Mother of good counsel, pray for us.",
      "Mother of our Creator, pray for us.",
      "Mother of our Saviour, pray for us.",
      "Virgin most prudent, pray for us.",
      "Virgin most venerable, pray for us.",
      "Virgin most renowned, pray for us.",
      "Virgin most powerful, pray for us.",
      "Virgin most merciful, pray for us.",
      "Virgin most faithful, pray for us.",
      "Mirror of justice, pray for us.",
      "Seat of wisdom, pray for us.",
      "Cause of our joy, pray for us.",
      "Spiritual vessel, pray for us.",
      "Vessel of honour, pray for us.",
      "Singular vessel of devotion, pray for us.",
      "Mystical rose, pray for us.",
      "Tower of David, pray for us.",
      "Tower of ivory, pray for us.",
      "House of gold, pray for us.",
      "Ark of the covenant, pray for us.",
      "Gate of heaven, pray for us.",
      "Morning star, pray for us.",
      "Health of the sick, pray for us.",
      "Refuge of sinners, pray for us.",
      "Solace of Migrants, pray for us.",
      "Comfort of the afflicted, pray for us.",
      "Help of Christians, pray for us.",
      "Queen of Angels, pray for us.",
      "Queen of Patriarchs, pray for us.",
      "Queen of Prophets, pray for us.",
      "Queen of Apostles, pray for us.",
      "Queen of Martyrs, pray for us.",
      "Queen of Confessors, pray for us.",
      "Queen of Virgins, pray for us.",
      "Queen of all Saints, pray for us.",
      "Queen conceived without original sin, pray for us.",
      "Queen assumed into heaven, pray for us.",
      "Queen of the most holy Rosary, pray for us.",
      "Queen of families, pray for us.",
      "Queen of peace, pray for us.",
      "",
      "Lamb of God, who takes away the sins of the world, spare us, O Lord.",
      "Lamb of God, who takes away the sins of the world, graciously hear us, O Lord.",
      "Lamb of God, who takes away the sins of the world, have mercy on us.",
      "",
      "Pray for us, O holy Mother of God.",
      "That we may be made worthy of the promises of Christ.",
      "",
      "Let us pray.",
      "Grant, we beseech thee, O Lord God, that we, your servants, may enjoy perpetual health of mind and body; and by the glorious intercession of the Blessed Mary, ever Virgin, may be delivered from present sorrow, and obtain eternal joy. Through Christ our Lord. Amen.",
    ],
  }),
  litany({
    slug: "litany-of-saint-joseph",
    title: "Litany of Saint Joseph",
    authorityLevel: "VATICAN",
    citations: [JOSEPH_LITANY_2021, JOSEPH_LETTER_2021, `${EWTN}litany-of-st-joseph-247`],
    occasions: ["march-19", "may-1", "wednesdays", "year-of-saint-joseph"],
    relatedSaints: ["saint-joseph"],
    summary:
      "The litany in honour of Saint Joseph, approved by the Apostolic See in 1909 and updated on 1 May 2021, when the Congregation for Divine Worship published seven new invocations approved by Pope Francis: Guardian of the Redeemer, Servant of Christ, Minister of salvation, Support in difficulties, and Patron of exiles, of the afflicted and of the poor. The Latin below is the text issued by the Holy See Press Office.",
    lines: [
      "Lord, have mercy on us. Lord, have mercy on us.",
      "Christ, have mercy on us. Christ, have mercy on us.",
      "Lord, have mercy on us. Lord, have mercy on us.",
      "Christ, hear us. Christ, graciously hear us.",
      "",
      "God the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the World, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "",
      "Holy Mary, pray for us.",
      "St. Joseph, pray for us.",
      "Renowned offspring of David, pray for us.",
      "Light of Patriarchs, pray for us.",
      "Spouse of the Mother of God, pray for us.",
      "Guardian of the Redeemer, pray for us.",
      "Chaste guardian of the Virgin, pray for us.",
      "Foster father of the Son of God, pray for us.",
      "Diligent protector of Christ, pray for us.",
      "Servant of Christ, pray for us.",
      "Minister of salvation, pray for us.",
      "Head of the Holy Family, pray for us.",
      "Joseph most just, pray for us.",
      "Joseph most chaste, pray for us.",
      "Joseph most prudent, pray for us.",
      "Joseph most strong, pray for us.",
      "Joseph most obedient, pray for us.",
      "Joseph most faithful, pray for us.",
      "Mirror of patience, pray for us.",
      "Lover of poverty, pray for us.",
      "Model of workers, pray for us.",
      "Glory of family life, pray for us.",
      "Guardian of virgins, pray for us.",
      "Pillar of families, pray for us.",
      "Support in difficulties, pray for us.",
      "Solace of the wretched, pray for us.",
      "Hope of the sick, pray for us.",
      "Patron of exiles, pray for us.",
      "Patron of the afflicted, pray for us.",
      "Patron of the poor, pray for us.",
      "Patron of the dying, pray for us.",
      "Terror of demons, pray for us.",
      "Protector of Holy Church, pray for us.",
      "",
      "Lamb of God, who takes away the sins of the world, spare us, O Jesus.",
      "Lamb of God, who takes away the sins of the world, graciously hear us, O Jesus.",
      "Lamb of God, who takes away the sins of the world, have mercy on us, O Jesus.",
      "",
      "He made him the lord of his household.",
      "And prince over all his possessions.",
      "",
      "Let us pray:",
      "O God, in your ineffable providence you were pleased to choose Blessed Joseph to be the spouse of your most holy Mother; grant, we beg you, that we may be worthy to have him for our intercessor in heaven whom on earth we venerate as our Protector: You who live and reign forever and ever.",
      "",
      "Saint Joseph, pray for us.",
    ],
    latin: [
      "Kyrie, eleison.",
      "Christe, eleison.",
      "Kyrie, eleison.",
      "Christe, audi nos.",
      "Christe, exaudi nos.",
      "",
      "Pater de caelis, Deus, miserere nobis.",
      "Fili, Redemptor mundi, Deus, miserere nobis.",
      "Spiritus sancte, Deus, miserere nobis.",
      "Sancta Trinitas, unus Deus, miserere nobis.",
      "",
      "Sancta Maria, ora pro nobis.",
      "Sancte Ioseph, ora pro nobis.",
      "Proles David inclyta, ora pro nobis.",
      "Lumen Patriarcharum, ora pro nobis.",
      "Dei Genitricis sponse, ora pro nobis.",
      "Custos Redemptoris, ora pro nobis.",
      "Custos pudice Virginis, ora pro nobis.",
      "Filii Dei nutritie, ora pro nobis.",
      "Christi defensor sedule, ora pro nobis.",
      "Serve Christi, ora pro nobis.",
      "Minister salutis, ora pro nobis.",
      "Almae Familiae praeses, ora pro nobis.",
      "Ioseph iustissime, ora pro nobis.",
      "Ioseph castissime, ora pro nobis.",
      "Ioseph prudentissime, ora pro nobis.",
      "Ioseph fortissime, ora pro nobis.",
      "Ioseph obedientissime, ora pro nobis.",
      "Ioseph fidelissime, ora pro nobis.",
      "Speculum patientiae, ora pro nobis.",
      "Amator paupertatis, ora pro nobis.",
      "Exemplar opificum, ora pro nobis.",
      "Domesticae vitae decus, ora pro nobis.",
      "Custos virginum, ora pro nobis.",
      "Familiarum columen, ora pro nobis.",
      "Fulcimen in difficultatibus, ora pro nobis.",
      "Solatium miserorum, ora pro nobis.",
      "Spes aegrotantium, ora pro nobis.",
      "Patrone exsulum, ora pro nobis.",
      "Patrone afflictorum, ora pro nobis.",
      "Patrone pauperum, ora pro nobis.",
      "Patrone morientium, ora pro nobis.",
      "Terror daemonum, ora pro nobis.",
      "Protector sanctae Ecclesiae, ora pro nobis.",
      "",
      "Agnus Dei, qui tollis peccata mundi, parce nobis, Domine.",
      "Agnus Dei, qui tollis peccata mundi, exaudi nos, Domine.",
      "Agnus Dei, qui tollis peccata mundi, miserere nobis.",
      "",
      "V. Constituit eum dominum domus suae.",
      "R. Et principem omnis possessionis suae.",
      "",
      "Oremus.",
      "Deus, qui ineffabili providentia beatum Ioseph, sanctissimae Genitricis tuae sponsum eligere dignatus es, praesta, quaesumus, ut, quem protectorem veneramur in terris, intercessorem habere mereamur in caelis. Qui vivis et regnas in saecula saeculorum. R. Amen.",
    ],
  }),
  litany({
    slug: "litany-of-humility",
    title: "Litany of Humility",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-of-humility-245`],
    occasions: ["daily", "lent", "examination-of-conscience"],
    summary:
      "A private litany traditionally attributed to Cardinal Rafael Merry del Val, Secretary of State to Pope Saint Pius X. It asks to be freed from the desires and fears that feed pride, and then for the grace to desire the good of others above one's own standing.",
    lines: [
      "O Jesus, meek and humble of heart, hear me.",
      "",
      "From the desire of being esteemed, deliver me, O Jesus.",
      "From the desire of being loved, deliver me, O Jesus.",
      "From the desire of being extolled, deliver me, O Jesus.",
      "From the desire of being honored, deliver me, O Jesus.",
      "From the desire of being praised, deliver me, O Jesus.",
      "From the desire of being preferred to others, deliver me, O Jesus.",
      "From the desire of being consulted, deliver me, O Jesus.",
      "From the desire of being approved, deliver me, O Jesus.",
      "From the fear of being humiliated, deliver me, O Jesus.",
      "From the fear of being despised, deliver me, O Jesus.",
      "From the fear of suffering rebukes, deliver me, O Jesus.",
      "From the fear of being calumniated, deliver me, O Jesus.",
      "From the fear of being forgotten, deliver me, O Jesus.",
      "From the fear of being ridiculed, deliver me, O Jesus.",
      "From the fear of being wronged, deliver me, O Jesus.",
      "From the fear of being suspected, deliver me, O Jesus.",
      "",
      "That others may be loved more than I, Jesus, grant me the grace to desire it.",
      "That others may be esteemed more than I, Jesus, grant me the grace to desire it.",
      "That, in the opinion of the world, others may increase and I may decrease, Jesus, grant me the grace to desire it.",
      "That others may be chosen and I set aside, Jesus, grant me the grace to desire it.",
      "That others may be praised and I go unnoticed, Jesus, grant me the grace to desire it.",
      "That others may be preferred to me in everything, Jesus, grant me the grace to desire it.",
      "That others may become holier than I, provided that I may become as holy as I should, Jesus, grant me the grace to desire it.",
    ],
  }),
  litany({
    slug: "litany-of-the-holy-spirit",
    title: "Litany of the Holy Ghost",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}463`, `${EWTN}litany-to-the-holy-spirit--ii-265`],
    occasions: ["pentecost", "confirmation", "before-work", "discernment"],
    summary:
      "A private litany invoking the Holy Spirit under the titles the tradition has given him — Promise of the Father, consuming fire, spirit of counsel and fortitude — and asking for his gifts. It is prayed especially in preparation for Pentecost and for Confirmation.",
    lines: [
      "Lord, have mercy on us.",
      "Christ, have mercy on us.",
      "Lord, have mercy on us.",
      "",
      "Father all powerful, have mercy on us",
      "Jesus, Eternal Son of the Father, Redeemer of the world, save us.",
      "Spirit of the Father and the Son, boundless life of both, sanctify us.",
      "Holy Trinity, hear us",
      "",
      "Holy Ghost, Who proceedest from the Father and the Son, enter our hearts.",
      "Holy Ghost, Who art equal to the Father and the Son, enter our hearts.",
      "Promise of God the Father, have mercy on us.",
      "Ray of heavenly light, have mercy on us",
      "Author of all good, have mercy on us",
      "Source of heavenly water, have mercy on us",
      "Consuming fire, have mercy on us",
      "Ardent charity, have mercy on us",
      "Spiritual unction, have mercy on us",
      "Spirit of love and truth, have mercy on us",
      "Spirit of wisdom and understanding, have mercy on us",
      "Spirit of counsel and fortitude, have mercy on us",
      "Spirit of knowledge and piety, have mercy on us",
      "Spirit of the fear of the Lord, have mercy on us",
      "Spirit of grace and prayer, have mercy on us",
      "Spirit of peace and meekness, have mercy on us",
      "Spirit of modesty and innocence, have mercy on us",
      "Holy Ghost, the Comforter, have mercy on us",
      "Holy Ghost, the Sanctifier, have mercy on us",
      "Holy Ghost, Who governest the Church, have mercy on us",
      "Gift of God, the Most High, have mercy on us",
      "Spirit Who fillest the universe, have mercy on us",
      "Spirit of the adoption of the children of God, have mercy on us",
      "",
      "Holy Ghost, inspire us with horror of sin.",
      "Holy Ghost, come and renew the face of the earth.",
      "Holy Ghost, shed Thy light in our souls.",
      "Holy Ghost, engrave Thy law in our hearts",
      "Holy Ghost, inflame us with the flame of Thy love.",
      "Holy Ghost, open to us the treasures of Thy graces",
      "Holy Ghost, teach us to pray well.",
      "Holy Ghost, enlighten us with Thy heavenly inspirations.",
      "Holy Ghost, lead us in the way of salvation",
      "Holy Ghost, grant us the only necessary knowledge.",
      "Holy Ghost, inspire in us the practice of good.",
      "Holy Ghost, grant us the merits of all virtues.",
      "Holy Ghost, make us persevere in justice.",
      "Holy Ghost, be Thou our everlasting reward.",
      "",
      "Lamb of God, Who takest away the sins of the world, Send us Thy Holy Ghost.",
      "Lamb of God, Who takest away the sins of the world, pour down into our souls the gifts of the Holy Ghost.",
      "Lamb of God, Who takest away the sins of the world, grant us the Spirit of wisdom and piety.",
      "",
      "V. Come, Holy Ghost! Fill the hearts of Thy faithful,",
      "R. And enkindle in them the fire of Thy love.",
      "",
      "Let Us Pray",
      "Grant, O merciful Father, that Thy Divine Spirit may enlighten, inflame and purify us, that He may penetrate us with His heavenly dew and make us fruitful in good works, through Our Lord Jesus Christ, Thy Son, Who with Thee, in the unity of the same Spirit, liveth and reigneth forever and ever. R. Amen",
    ],
  }),
  litany({
    slug: "litany-of-the-holy-angels",
    title: "Litany of the Holy Angels",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-to-the-holy-angels-264`],
    occasions: ["september-29", "october-2", "guardian-angels"],
    summary:
      "A private litany honouring the archangels Michael, Gabriel and Raphael and all the angelic hosts, recalling the works Scripture attributes to them and asking their protection. It is prayed especially on the feast of the Archangels and the memorial of the Guardian Angels.",
    lines: [
      "Lord, have mercy on us.",
      "Christ, have mercy on us.",
      "Lord, have mercy on us.",
      "Christ, hear us.",
      "Christ, graciously hear us.",
      "",
      "God the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the World, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "",
      "Holy Mary, Queen of Angels, pray for us.",
      "Holy Mother of God, pray for us.",
      "Holy Virgin of Virgins, pray for us.",
      "Saint Michael, who was ever the defender of the people of God, pray for us.",
      "St. Michael, who did drive from Heaven Lucifer and his rebel crew, pray for us.",
      "St. Michael, who did cast down to Hell the accuser of our brethren, pray for us.",
      "Saint Gabriel, who did expound to Daniel the heavenly vision, pray for us.",
      "St. Gabriel, who did foretell to Zachary the birth and ministry of John the Baptist, pray for us.",
      "St. Gabriel, who did announce to Blessed Mary the Incarnation of the Divine Word, pray for us.",
      "Saint Raphael, who did lead Tobias safely through his journey to his home again, pray for us.",
      "St. Raphael, who did deliver Sara from the devil, pray for us.",
      "St. Raphael, who did restore his sight to Tobias the elder, pray for us.",
      "All ye holy Angels, who stand around the high and lofty throne of God, pray for us.",
      "Who cry to Him continually: Holy, Holy, Holy, pray for us.",
      "Who dispel the darkness of our minds and give us light, pray for us.",
      "Who are the messengers of heavenly things to men, pray for us.",
      "Who have been appointed by God to be our guardians, pray for us.",
      "Who always behold the Face of our Father Who is in Heaven, pray for us.",
      "Who rejoice over one sinner doing penance, pray for us.",
      "Who struck the Sodomites with blindness, pray for us.",
      "Who led Lot out of the midst of the ungodly, pray for us.",
      "Who ascended and descended on the ladder of Jacob, pray for us.",
      "Who delivered the Divine Law to Moses on Mount Sinai, pray for us.",
      "Who brought good tidings when Christ was born, pray for us.",
      "Who comforted Him in His agony, pray for us.",
      "Who sat in white garments at His sepulcher, pray for us.",
      "Who appeared to the disciples as He went up into Heaven, pray for us.",
      "Who shall go before Him bearing the standard of the Cross when He comes to judgment, pray for us.",
      "Who shall gather together the elect at the End of the World, pray for us.",
      "Who shall separate the wicked from among the just, pray for us.",
      "Who offer to God the prayers of those who pray, pray for us.",
      "Who assist us at the hour of death, pray for us.",
      "Who carried Lazarus into Abraham's bosom, pray for us.",
      "Who conduct to Heaven the souls of the just, pray for us.",
      "Who perform signs and wonders by the power of God, pray for us.",
      "Who are sent to minister for those who shall receive the inheritance of salvation, pray for us.",
      "Who are set over kingdoms and provinces, pray for us.",
      "Who have often put to flight armies of enemies, pray for us.",
      "Who have often delivered God's servants from prison and other perils of this life, pray for us.",
      "Who have often consoled the holy martyrs in their torments, pray for us.",
      "Who are wont to cherish with peculiar care the prelates and princes of the Church, pray for us.",
      "All ye holy orders of blessed spirits, pray for us.",
      "",
      "From all dangers, deliver us, O Lord.",
      "From the snares of the devil, deliver us, O Lord.",
      "From all heresy and schism, deliver us, O Lord.",
      "From plague, famine and war, deliver us, O Lord.",
      "From sudden and unlooked-for death, deliver us, O Lord.",
      "From everlasting death, deliver us, O Lord.",
      "",
      "Through Thy holy Angels, we beseech Thee, hear us.",
      "That Thou would spare us, we beseech Thee, hear us.",
      "That Thou would pardon us, we beseech Thee, hear us.",
      "That Thou would govern and preserve Thy Holy Church, we beseech Thee, hear us.",
      "That Thou would protect our Apostolic Prelate and all ecclesiastical orders, we beseech Thee, hear us.",
      "That Thou would grant peace and security to kings and all Christian princes, we beseech Thee, hear us.",
      "That Thou would give and preserve the fruits of the earth, we beseech Thee, hear us.",
      "That Thou would grant eternal rest to all the faithful departed, we beseech Thee, hear us.",
      "",
      "Lamb of God, who takes away the sins of the world, spare us, O Lord.",
      "Lamb of God, who takes away the sins of the world, graciously hear us, O Lord.",
      "Lamb of God, who takes away the sins of the world, have mercy on us.",
      "",
      "Lord, have mercy on us.",
      "Christ, have mercy on us.",
      "Lord, have mercy on us.",
      "",
      "Our Father, Hail Mary, Glory Be",
      "",
      "Bless the Lord, all ye Angels: Ye who are mighty in strength, who fulfill His commandments, hearkening unto the voice of His words.",
      "He hath given His Angels charge concerning thee, To keep thee in all thy ways.",
      "",
      "Let us pray:",
      "O God, Who dost arrange the services of Angels and men in a wonderful order, mercifully grant that our life may be protected on earth by those who always do Thee service in Heaven, through Jesus Christ Thy Son, Who with Thee and the Holy Ghost are one God now and forever. Amen.",
      "O God, Who in Thine unspeakable Providence dost send Thine Angels to keep guard over us, grant unto Thy suppliants that we may be continually defended by their protection and may rejoice eternally in their society, through Jesus Christ Our Lord, Who lives and reigns with Thee, in the unity of the Holy Ghost, forever and ever. Amen.",
    ],
  }),
  litany({
    slug: "litany-of-the-passion",
    title: "Litany of the Passion",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-of-the-passion-249`, `${CATHOLIC_ONLINE}466`],
    occasions: ["lent", "fridays", "holy-week"],
    summary:
      "A private litany that follows the whole course of the Lord's Passion, from the betrayal in the garden to the burial, and then on to the Resurrection and Ascension. It is prayed especially on Fridays and throughout Lent.",
    lines: [
      "Lord, have mercy.",
      "Christ, have mercy.",
      "Lord, have mercy.",
      "Christ, hear us.",
      "Christ, graciously hear us.",
      "",
      "God, the Father of Heaven, have mercy on us.",
      "God, the Son, Redeemer of the world, have mercy on us.",
      "God, the Holy Spirit, have mercy on us.",
      "Holy Trinity, One God, have mercy on us.",
      "",
      "Jesus, the eternal Wisdom, have mercy on us.",
      "Jesus, conversing with men, have mercy on us.",
      "Jesus, hated by the world, have mercy on us.",
      "Jesus, sold for thirty pieces of silver, have mercy on us.",
      "Jesus, prostrate in prayer, have mercy on us.",
      "Jesus, strengthened by an angel, have mercy on us.",
      "Jesus, agonizing in a bloody sweat, have mercy on us.",
      "Jesus, betrayed by Judas with a kiss, have mercy on us.",
      "Jesus, bound by the soldiers, have mercy on us.",
      "Jesus, forsaken by your disciples, have mercy on us.",
      "Jesus, before Annas and Caiaphas, have mercy on us.",
      "Jesus, struck by a servant on the face, have mercy on us.",
      "Jesus, accused by false witnesses, have mercy on us.",
      "Jesus, declared worthy of death, have mercy on us.",
      "Jesus, spit upon in the face, have mercy on us.",
      "Jesus, blindfolded, have mercy on us.",
      "Jesus, smitten on the cheek, have mercy on us.",
      "Jesus, thrice denied by Peter, have mercy on us.",
      "Jesus, delivered up to Pilate, have mercy on us.",
      "Jesus, despised and mocked by Herod, have mercy on us.",
      "Jesus, clothed in a white garment, have mercy on us.",
      "Jesus, rejected for Barabbas, have mercy on us.",
      "Jesus, torn by scourges, have mercy on us.",
      "Jesus, bruised for our sins, have mercy on us.",
      "Jesus, regarded as a leper, have mercy on us.",
      "Jesus, covered with a purple robe, have mercy on us.",
      "Jesus, crowned with thorns, have mercy on us.",
      "Jesus, struck with a reed, have mercy on us.",
      "Jesus, demanded for crucifixion, have mercy on us.",
      "Jesus, condemned to death, have mercy on us.",
      "Jesus, given up to your enemies, have mercy on us.",
      "Jesus, laden with the Cross, have mercy on us.",
      "Jesus, led as a lamb to the slaughter, have mercy on us.",
      "Jesus, stripped of your garments, have mercy on us.",
      "Jesus, fastened with nails to the Cross, have mercy on us.",
      "Jesus, wounded for our iniquities, have mercy on us.",
      "Jesus, praying for your murderers, have mercy on us.",
      "Jesus, reputed with the wicked, have mercy on us.",
      "Jesus, blasphemed on the Cross, have mercy on us.",
      "Jesus, reviled by the malefactor, have mercy on us.",
      "Jesus, giving Paradise to the thief, have mercy on us.",
      "Jesus, commending Saint John to your Mother as her son, have mercy on us.",
      "Jesus, forsaken by your Father, have mercy on us.",
      "Jesus, given gall and vinegar to drink, have mercy on us.",
      "Jesus, testifying that all things written concerning you were accomplished, have mercy on us.",
      "Jesus, commending your spirit into the hands of your Father, have mercy on us.",
      "Jesus, obedient even unto death, have mercy on us.",
      "Jesus, pierced with a lance, have mercy on us.",
      "Jesus, made a propitiation for us, have mercy on us.",
      "Jesus, taken down from the Cross, have mercy on us.",
      "Jesus, laid in a sepulcher, have mercy on us.",
      "Jesus, rising gloriously from the dead, have mercy on us.",
      "Jesus, ascending into heaven, have mercy on us.",
      "Jesus, our Advocate with the Father, have mercy on us.",
      "Jesus, sending down the Holy Spirit, have mercy on us.",
      "Jesus, exalting your Mother, have mercy on us.",
      "Jesus, who shall come to judge the living and the dead, have mercy on us.",
      "",
      "Be merciful, spare us, O Jesus.",
      "Be merciful, graciously hear us, O Jesus.",
      "",
      "From all evil, deliver us, O Jesus.",
      "From all sin, deliver us, O Jesus.",
      "From anger, hatred, and every evil will, deliver us, O Jesus.",
      "From war, famine, and pestilence, deliver us, O Jesus.",
      "From all dangers of mind and body, deliver us, O Jesus.",
      "From everlasting death, deliver us, O Jesus.",
      "Through your most pure conception, deliver us, O Jesus.",
      "Through your miraculous nativity, deliver us, O Jesus.",
      "Through your humble circumcision, deliver us, O Jesus.",
      "Through your baptism and fasting, deliver us, O Jesus.",
      "Through your labors and watchings, deliver us, O Jesus.",
      "Through your cruel scourging and crowning, deliver us, O Jesus.",
      "Through your thirst, and tears, and nakedness, deliver us, O Jesus.",
      "Through your precious death and Cross, deliver us, O Jesus.",
      "Through your glorious resurrection and ascension, deliver us, O Jesus.",
      "Through your sending forth the Holy Spirit, the Paraclete, deliver us, O Jesus.",
      "",
      "On the day of judgment, we sinners, we beseech you, hear us.",
      "That you would spare us, we beseech you, hear us.",
      "That you would pardon us, we beseech you, hear us.",
      "That you would bring us to true penance, we beseech you, hear us.",
      "That you would pour into our hearts the grace of the Holy Spirit, we beseech you, hear us.",
      "That you would defend and propagate your Church, we beseech you, hear us.",
      "That you would preserve and increase all societies assembled in your holy Name, we beseech you, hear us.",
      "That you would bestow upon us true peace, humility, and charity, we beseech you, hear us.",
      "That you would give us perseverance in grace and in your holy service, we beseech you, hear us.",
      "That you would deliver us from unclean thoughts, the temptations of the devil, and everlasting damnation, we beseech you, hear us.",
      "That you would unite us to the company of your Saints, we beseech you, hear us.",
      "That you would graciously hear us, we beseech you, hear us.",
      "",
      "Lamb of God, who take away the sins of the world, spare us, O Lord.",
      "Lamb of God, who take away the sins of the world, graciously hear us, O Lord.",
      "Lamb of God, who take away the sins of the world, have mercy on us, O Lord.",
      "",
      "Christ, hear us.",
      "Christ, graciously hear us.",
      "Lord, have mercy.",
      "Christ, have mercy.",
      "Lord, have mercy.",
      "",
      "We adore you, O Christ, and we bless you, because by your holy Cross you have redeemed the world.",
    ],
  }),
  litany({
    slug: "litany-of-our-lady-of-sorrows",
    title: "Litany of Our Lady of Sorrows",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}328`, `${CATHOLIC_ONLINE}459`],
    occasions: ["september-15", "lent", "fridays"],
    summary:
      "A private litany honouring the Blessed Virgin Mary in her Seven Sorrows, prayed especially on 15 September, the memorial of Our Lady of Sorrows, and during Lent. Its closing prayer recalls the sword foretold by Simeon that pierced her soul at the Passion of her Son.",
    lines: [
      "Lord, have mercy on us.",
      "Christ, have mercy on us.",
      "Lord, have mercy on us.",
      "Christ, hear us.",
      "Christ, graciously hear us.",
      "",
      "God, the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the world, have mercy on us.",
      "God the Holy Ghost, have mercy on us.",
      "",
      "Holy Mary, Mother of God, pray for us.",
      "Holy Virgin of virgins, pray for us.",
      "Mother of the Crucified, pray for us.",
      "Sorrowful Mother, pray for us.",
      "Mournful Mother, pray for us.",
      "Sighing Mother, pray for us.",
      "Afflicted Mother, pray for us.",
      "Forsaken Mother, pray for us.",
      "Desolate Mother, pray for us.",
      "Mother most sad, pray for us.",
      "Mother set around with anguish, pray for us.",
      "Mother overwhelmed by grief, pray for us.",
      "Mother transfixed by a sword, pray for us.",
      "Mother crucified in thy heart, pray for us.",
      "Mother bereaved of thy Son, pray for us.",
      "Sighing Dove, pray for us.",
      "Mother of Dolors, pray for us.",
      "Fount of tears, pray for us.",
      "Sea of bitterness, pray for us.",
      "Field of tribulation, pray for us.",
      "Mass of suffering, pray for us.",
      "Mirror of patience, pray for us.",
      "Rock of constancy, pray for us.",
      "Remedy in perplexity, pray for us.",
      "Joy of the afflicted, pray for us.",
      "Ark of the desolate, pray for us.",
      "Refuge of the abandoned, pray for us.",
      "Shield of the oppressed, pray for us.",
      "Conqueror of the incredulous, pray for us.",
      "Solace of the wretched, pray for us.",
      "Medicine of the sick, pray for us.",
      "Help of the faint, pray for us.",
      "Strength of the weak, pray for us.",
      "Protectress of those who fight, pray for us.",
      "Haven of the shipwrecked, pray for us.",
      "Calmer of tempests, pray for us.",
      "Companion of the sorrowful, pray for us.",
      "Retreat of those who groan, pray for us.",
      "Terror of the treacherous, pray for us.",
      "Standard-bearer of the Martyrs, pray for us.",
      "Treasure of the Faithful, pray for us.",
      "Light of Confessors, pray for us.",
      "Pearl of Virgins, pray for us.",
      "Comfort of Widows, pray for us.",
      "Joy of all Saints, pray for us.",
      "Queen of thy Servants, pray for us.",
      "Holy Mary, who alone art unexampled, pray for us.",
      "",
      "Pray for us, most Sorrowful Virgin,",
      "That we may be made worthy of the promises of Christ.",
      "",
      "O God, in whose Passion, according to the prophecy of Simeon, a sword of grief pierced through the most sweet soul of Thy glorious Blessed Virgin Mother Mary: grant that we, who celebrate the memory of her Seven Sorrows, may obtain the happy effect of Thy Passion, Who lives and reigns world without end. Amen.",
    ],
  }),
  litany({
    slug: "litany-of-our-lady-of-lourdes",
    title: "Litany of Our Lady of Lourdes",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}327`, `${CATHOLIC_ONLINE}458`],
    occasions: ["february-11", "sickness", "pilgrimage"],
    relatedSaints: ["saint-bernadette-soubirous"],
    summary:
      "A private litany invoking the Blessed Virgin under the title she is given at Lourdes, where she appeared to Saint Bernadette Soubirous in 1858. Its invocations gather the poor, the sick, the lonely and the dying, and it is prayed especially on 11 February, the World Day of the Sick.",
    lines: [
      "Lord have mercy; Lord have mercy.",
      "Christ have mercy; Christ have mercy.",
      "Lord have mercy; Lord have mercy.",
      "Christ hear us; Christ graciously hear us.",
      "",
      "God the Father of Heaven; Have mercy on us.",
      "God the Son, Redeemer of the world; Have mercy on us.",
      "God the Holy Spirit; Have mercy on us.",
      "Holy Trinity, one God; Have mercy on us.",
      "",
      "Holy Mary; Pray for us.",
      "Holy Mother of God; Pray for us.",
      "Mother of Christ; Pray for us.",
      "Mother of our Savior; Pray for us.",
      "Our Lady of Lourdes, help of Christians; Pray for us.",
      "Our Lady of Lourdes, source of love; Pray for us.",
      "Our Lady of Lourdes, mother of the poor; Pray for us.",
      "Our Lady of Lourdes, mother of the handicapped; Pray for us.",
      "Our Lady of Lourdes, mother of orphans; Pray for us.",
      "Our Lady of Lourdes, mother of all children; Pray for us.",
      "Our Lady of Lourdes, mother of all nations; Pray for us.",
      "Our Lady of Lourdes, mother of the Church; Pray for us.",
      "Our Lady of Lourdes, friend of the lonely; Pray for us.",
      "Our Lady of Lourdes, comforter of those who mourn; Pray for us.",
      "Our Lady of Lourdes, shelter of the homeless; Pray for us.",
      "Our Lady of Lourdes, guide of travelers; Pray for us.",
      "Our Lady of Lourdes, strength of the weak; Pray for us.",
      "Our Lady of Lourdes, refuge of sinners; Pray for us.",
      "Our Lady of Lourdes, comforter of the suffering; Pray for us.",
      "Our Lady of Lourdes, help of the dying; Pray for us.",
      "Queen of heaven; Pray for us.",
      "Queen of peace; Pray for us.",
      "",
      "Lamb of God, you take away the sins of the world; Spare us O Lord.",
      "Lamb of God, you take away the sins of the world; Graciously hear us, O Lord.",
      "Lamb of God, you take away the sins of the world; Have mercy on us.",
      "",
      "Christ hear us; Christ graciously hear us.",
      "",
      "Let us pray:",
      "Grant us, your servants, we pray you, Lord God, to enjoy perpetual health of mind and body. By the glorious intercession of Blessed Mary ever Virgin, may we be delivered from present sorrows, and enjoy everlasting happiness. Through Christ our Lord. Amen.",
    ],
  }),
  litany({
    slug: "litany-of-saint-jude",
    title: "Litany of Saint Jude",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-to-st-jude-259`],
    occasions: ["october-28", "difficult-cases", "novena"],
    relatedSaints: ["saint-jude-thaddeus"],
    summary:
      "A private litany in honour of the apostle Jude Thaddeus, whose feast is kept on 28 October with Saint Simon. Its invocations recall his kinship with the Lord, his apostolic mission and the epistle that bears his name.",
    lines: [
      "Lord, have mercy on us. Christ, have mercy on us.",
      "Lord, have mercy on us.",
      "Christ, hear us. Christ, graciously hear us.",
      "",
      "God the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the World, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "",
      "Holy Mary, Mother of God, pray for us.",
      "Holy Mary, Mother of the Church, pray for us.",
      "Holy Mary, Queen of the Apostles, pray for us.",
      "",
      "Saint Jude, Apostle of Christ, pray for us.",
      "Saint Jude, surnamed Thaddeus, pray for us.",
      "Saint Jude, among 'the brethren of the Lord', pray for us.",
      "Saint Jude, cousin of the Lord, pray for us.",
      "Saint Jude, relative of Mary, pray for us.",
      "Saint Jude, brother of Saint James the Less, pray for us.",
      "Saint Jude, Zealot party member turned Disciple, pray for us.",
      "Saint Jude, spiritual heir of the Maccabees, pray for us.",
      "Saint Jude, one of the Twelve, pray for us.",
      "Saint Jude, honored by thy humble Master washing thy feet, pray for us.",
      "Saint Jude, who received thy Eucharistic Lord from His own hands at the Last Supper, pray for us.",
      "Saint Jude, Saint of the Impossible, pray for us.",
      "Saint Jude, Helper in Difficult Cases, pray for us.",
      "Saint Jude, in whom so many have confidence, pray for us.",
      "Saint Jude, redeemer of the name of Judas, pray for us.",
      "Saint Jude, one in whom we can trust, pray for us.",
      "Saint Jude, sent by Christ on missions of healing, pray for us.",
      "Saint Jude, sent without silver, staff or sandals, pray for us.",
      "Saint Jude, sent as a sheep among wolves, pray for us.",
      "Saint Jude, sent to announce the reign of God, pray for us.",
      "Saint Jude, promised the Holy Spirit under trial, pray for us.",
      "Saint Jude, filled with the Holy Spirit on Pentecost, pray for us.",
      "Saint Jude, witness to the Resurrection of Christ and His Ascension, pray for us.",
      "Saint Jude, miracle worker, pray for us.",
      "Saint Jude, to whom the epistle by that name is attributed, pray for us.",
      "Saint Jude, believed to have preached in Mesopotamia, pray for us.",
      "Saint Jude, thought to have been martyred with Saint Simon in Persia, pray for us.",
      "Saint Jude, saint for our needs, pray for us.",
      "Saint Jude, saint for our times, pray for us.",
      "Saint Jude, pictured with a burning flame, pray for us.",
      "Saint Jude, patron of many shrines in thy honor, pray for us.",
      "Saint Jude, beloved intercessor at novenas, pray for us.",
      "Saint Jude, inspirer of confidence, pray for us.",
      "Saint Jude, helper of the persistent, pray for us.",
      "",
      "Lamb of God, who takes away the sins of the world, spare us, O Lord.",
      "Lamb of God, who takes away the sins of the world, graciously hear us, O Lord.",
      "Lamb of God, who takes away the sins of the world, have mercy on us.",
      "",
      "Christ, hear us. Christ, graciously hear us.",
      "",
      "Pray for us, St. Jude, Apostle of Christ.",
      "That we may be made worthy of the promises of Christ.",
      "",
      "Let us pray:",
      "O glorious Saint Jude Thaddeus, by whose sublime prerogatives wherewith thou wast ennobled in thy lifetime, namely, thy kinship with Our Lord Jesus Christ according to the flesh, and thy vocation to be an Apostle; by that glory which is now thine in Heaven as the reward of thine apostolic labors and thy martyrdom: Obtain for us from the Giver of every good and perfect gift all the graces we stand in need of in order to treasure up in our hearts the divinely inspired doctrines which thou hast transmitted to us in thine Epistle; that is to say, to build our edifice of perfection upon our most holy Faith, praying by the grace of the Holy Spirit; to keep ourselves in the love of God, looking for the mercy of Jesus Christ unto eternal life; to strive by all means to help those who go astray, exalting thus the glory and majesty, the dominion and power of Him Who is able to keep us without sin and to present us spotless with exceeding joy at the coming of our Divine Savior, the Lord Jesus Christ. Amen.",
    ],
  }),
  litany({
    slug: "litany-of-saint-therese",
    title: "Litany of Saint Therese of the Child Jesus",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-to-st-therese-of-the-child-jesus-261`],
    occasions: ["october-1", "novena"],
    relatedSaints: ["saint-therese-of-lisieux"],
    summary:
      "A private litany in honour of Saint Therese of Lisieux, the Carmelite of the Little Way, whose feast is kept on 1 October. Its invocations follow the virtues of her hidden life: obedience, trust, simplicity and zeal for souls.",
    lines: [
      "Lord, have mercy on us. Christ, have mercy on us.",
      "Lord, have mercy on us.",
      "Christ, hear us. Christ, graciously hear us.",
      "",
      "God the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the World, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "",
      "Holy Mary, pray for us.",
      "Our Lady of Victory, pray for us.",
      "Saint Therese, servant of God, pray for us.",
      "Saint Therese, victim of the merciful love of God, pray for us.",
      "Saint Therese, spouse of Jesus, pray for us.",
      "Saint Therese, gift of Heaven, pray for us.",
      "Saint Therese, remarkable in childhood, pray for us.",
      "Saint Therese, an example of obedience, pray for us.",
      "Saint Therese, lover of the will of God, pray for us.",
      "Saint Therese, lover of peace, pray for us.",
      "Saint Therese, lover of patience, pray for us.",
      "Saint Therese, lover of gentleness, pray for us.",
      "Saint Therese, heroic in sacrifice, pray for us.",
      "Saint Therese, generous in forgiving, pray for us.",
      "Saint Therese, benefactress of the needy, pray for us.",
      "Saint Therese, lover of Jesus, pray for us.",
      "Saint Therese, devoted to the Holy Face, pray for us.",
      "Saint Therese, consumed with divine love of God, pray for us.",
      "Saint Therese, advocate of extreme cases, pray for us.",
      "Saint Therese, persevering in prayer, pray for us.",
      "Saint Therese, a powerful advocate with God, pray for us.",
      "Saint Therese, showering roses, pray for us.",
      "Saint Therese, doing good upon earth, pray for us.",
      "Saint Therese, answering all prayers, pray for us.",
      "Saint Therese, lover of holy chastity, pray for us.",
      "Saint Therese, lover of voluntary poverty, pray for us.",
      "Saint Therese, lover of obedience, pray for us.",
      "Saint Therese, burning with zeal for God's glory, pray for us.",
      "Saint Therese, inflamed with the Spirit of Love, pray for us.",
      "Saint Therese, child of benediction, pray for us.",
      "Saint Therese, perfect in simplicity, pray for us.",
      "Saint Therese, so remarkable for trust in God, pray for us.",
      "Saint Therese, gifted with unusual intelligence, pray for us.",
      "Saint Therese, never invoked without some answer, pray for us.",
      "Saint Therese, teaching us the sure way, pray for us.",
      "Saint Therese, victim of Divine Love, pray for us.",
      "",
      "Lamb of God, who takes away the sins of the world, spare us, O Lord.",
      "Lamb of God, who takes away the sins of the world, graciously hear us, O Lord.",
      "Lamb of God, who takes away the sins of the world, have mercy on us.",
      "",
      "V. St Therese, the Little Flower of Jesus,",
      "R. Pray for us.",
      "",
      "Let us pray:",
      "O God, Who inflamed with Thy Spirit of Love the soul of Thy servant Therese of the Child Jesus, grant that we may also love Thee and may make Thee much loved. Amen.",
    ],
  }),
  litany({
    slug: "litany-of-saint-francis",
    title: "Litany of Saint Francis of Assisi",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-to-st-francis-of-assisi-257`],
    occasions: ["october-4", "september-17", "novena"],
    relatedSaints: ["saint-francis-of-assisi"],
    summary:
      "A private litany in honour of Saint Francis of Assisi, founder of the Friars Minor, whose feast is kept on 4 October. Its closing prayer recalls the stigmata he received on Mount La Verna.",
    lines: [
      "Lord, have mercy on us. Christ, have mercy on us.",
      "Lord, have mercy on us.",
      "Christ, hear us. Christ, graciously hear us.",
      "",
      "God, the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the world, have mercy on us.",
      "God the Holy Ghost, have mercy on us.",
      "Holy Trinity, One God, have mercy on us.",
      "",
      "Holy Mary, conceived without sin, pray for us.",
      "Holy Mary, special patroness of the three Orders of Saint Francis, pray for us.",
      "Saint Francis, seraphic patriarch, pray for us.",
      "Saint Francis, most prudent father, pray for us.",
      "Saint Francis, despiser of the world, pray for us.",
      "Saint Francis, model of penance, pray for us.",
      "Saint Francis, conqueror of vices, pray for us.",
      "Saint Francis, imitator of the Saviour, pray for us.",
      "Saint Francis, bearer of the marks of Christ, pray for us.",
      "Saint Francis, sealed with the character of Jesus, pray for us.",
      "Saint Francis, example of purity, pray for us.",
      "Saint Francis, image of humility, pray for us.",
      "Saint Francis, abounding in grace, pray for us.",
      "Saint Francis, reformer of the erring, pray for us.",
      "Saint Francis, healer of the sick, pray for us.",
      "Saint Francis, pillar of the Church, pray for us.",
      "Saint Francis, defender of the Faith, pray for us.",
      "Saint Francis, champion of Christ, pray for us.",
      "Saint Francis, defender of thy children, pray for us.",
      "Saint Francis, invulnerable shield, pray for us.",
      "Saint Francis, confounder of the heretics, pray for us.",
      "Saint Francis, converter of the pagans, pray for us.",
      "Saint Francis, supporter of the lame, pray for us.",
      "Saint Francis, raiser of the dead, pray for us.",
      "Saint Francis, healer of the lepers, pray for us.",
      "Saint Francis, our advocate, pray for us.",
      "",
      "Lamb of God, Who takest away the sins of the world, spare us, O Lord.",
      "Lamb of God, Who takest away the sins of the world, graciously hear us, O Lord.",
      "Lamb of God, Who takest away the sins of the world, have mercy on us.",
      "",
      "Christ, hear us. Christ, graciously hear us.",
      "",
      "V. Pray for us, O blessed father Francis.",
      "R. That we may be made worthy of the promises of Christ.",
      "",
      "Let us pray",
      "O Lord Jesus Christ, Who, when the world was growing cold, in order to renew in our hearts the flame of love, imprinted the sacred marks of Thy Passion on the body of our blessed father Francis, mercifully grant that by his merits and prayers we may persevere in bearing the cross and may bring forth fruits worthy of penance, Thou Who livest and reignest, world without end. Amen.",
    ],
  }),
  litany({
    slug: "litany-of-saint-teresa-of-avila",
    title: "Litany of Saint Teresa of Avila",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-to-st-teresa-of-avila-260`],
    occasions: ["october-15", "novena"],
    relatedSaints: ["saint-teresa-of-avila"],
    summary:
      "A private litany in honour of Saint Teresa of Avila, reformer of Carmel and Doctor of the Church, whose feast is kept on 15 October. Its invocations quote her own sayings on suffering, death and the sweetness of God's ways.",
    lines: [
      "Lord, have mercy on us. Christ, have mercy on us.",
      "Lord, have mercy on us.",
      "Christ, hear us. Christ, graciously hear us.",
      "",
      "God the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the World, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "",
      "Holy Mary, Mother of God, pray for us.",
      "Holy Mary, Our Lady of Mt. Carmel, pray for us.",
      "",
      "St. Teresa, whose heart was transverberated by the love of God, pray for us.",
      "St. Teresa, most humble servant of God, pray for us.",
      "St. Teresa, most zealous for the glory of God, pray for us.",
      "St. Teresa, truly detached from all created objects, pray for us.",
      "St. Teresa, great light of the Catholic Church, pray for us.",
      "St. Teresa, reformer and glory of the Carmelite Order, pray for us.",
      "St. Teresa, queen of mystical theology, pray for us.",
      "St. Teresa, lustrous name of Avila and Spain, pray for us.",
      "St. Teresa, who didst forever glorify the name of Teresa, pray for us.",
      "St. Teresa, wishing to suffer or to die, pray for us.",
      "St. Teresa, exclaiming, 'O Lord, how sweet and pleasing are Thy ways!', pray for us.",
      "St. Teresa, desiring so much the salvation of souls, pray for us.",
      "St. Teresa, tasting and seeing how sweet is the Lord, even in this vale of miseries, pray for us.",
      "St. Teresa, exclaiming, 'O death, who can fear thee who art the way to true life!', pray for us.",
      "St. Teresa, true lover of the Cross of Christ, pray for us.",
      "St. Teresa, who didst live to love, who died to love, and who wilt love eternally, pray for us.",
      "",
      "Lamb of God, who takes away the sins of the world, spare us, O Lord.",
      "Lamb of God, who takes away the sins of the world, graciously hear us, O Lord.",
      "Lamb of God, who takes away the sins of the world, have mercy on us.",
      "",
      "Christ, hear us. Christ, graciously hear us.",
      "",
      "V. Pray for us, O Holy St. Teresa",
      "R. That we may be made worthy of the promises of Christ.",
      "",
      "Let us pray:",
      "O God, Who didst replenish the heart of Thy blessed servant St. Teresa with the treasures of Thy divine love, grant that, like her, we may love Thee and suffer all things for Thee and in union with Thee, that we may gain souls for Thee, and that we may secure the salvation of our own soul. This we beg though the merits of our Savior and the intercession of Thy glorious virgin Teresa. Amen.",
    ],
  }),
  litany({
    slug: "litany-of-saint-john-the-baptist",
    title: "Litany of Saint John the Baptist",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-to-st-john-the-baptist-258`],
    occasions: ["june-24", "august-29", "advent"],
    relatedSaints: ["saint-john-the-baptist"],
    summary:
      "A private litany in honour of the Precursor of the Lord, whose Nativity is kept on 24 June and whose Passion on 29 August. Its invocations follow him from the sanctification in his mother's womb to his martyrdom for the law of God.",
    lines: [
      "Lord, have mercy on us. Christ, have mercy on us.",
      "Lord, have mercy on us.",
      "Christ, hear us. Christ, graciously hear us.",
      "",
      "God the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the World, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "",
      "Holy Mary, pray for us.",
      "Queen of Prophets, pray for us.",
      "Queen of Martyrs, pray for us.",
      "Saint John the Baptist, pray for us.",
      "St. John the Baptist, precursor of Christ, pray for us.",
      "St. John the Baptist, glorious forerunner of the Sun of Justice, pray for us.",
      "St. John the Baptist, minister of baptism to Jesus, pray for us.",
      "St. John the Baptist, burning and shining lamp of the world, pray for us.",
      "St. John the Baptist, angel of purity before thy birth, pray for us.",
      "St. John the Baptist, special friend and favorite of Christ, pray for us.",
      "St. John the Baptist, heavenly contemplative, whose element was prayer, pray for us.",
      "St. John the Baptist, intrepid preacher of truth, pray for us.",
      "St. John the Baptist, voice crying in the wilderness, pray for us.",
      "St. John the Baptist, miracle of mortification and penance, pray for us.",
      "St. John the Baptist, example of profound humility, pray for us.",
      "St. John the Baptist, glorious martyr of zeal for God's holy law, pray for us.",
      "St. John the Baptist, gloriously fulfilling thy mission, pray for us.",
      "",
      "Lamb of God, who takes away the sins of the world, spare us, O Lord.",
      "Lamb of God, who takes away the sins of the world, hear us, O Lord.",
      "Lamb of God, who takes away the sins of the world, have mercy on us.",
      "",
      "Christ, hear us. Christ, graciously hear us.",
      "",
      "V. Pray for us, O glorious St. John the Baptist,",
      "R. That we may be made worthy of the promises of Christ.",
      "",
      "Let us pray:",
      "O God, Who hast honored this world by the birth of Saint John the Baptist, grant that Thy faithful people may rejoice in the way of eternal salvation, through Jesus Christ Our Lord. Amen.",
    ],
  }),
  litany({
    slug: "litany-of-saint-kateri-tekakwitha",
    title: "Litany of Saint Kateri Tekakwitha",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-to-kateri-tekakwitha-253`],
    occasions: ["july-14", "novena"],
    relatedSaints: ["saint-kateri-tekakwitha"],
    summary:
      "A private litany in honour of Kateri Tekakwitha, the Mohawk convert known as the Lily of the Mohawks, canonised in 2012 and commemorated on 14 July in the United States. The text was composed before her canonisation and addresses her simply by name.",
    lines: [
      "Lord, have mercy on us. Christ, have mercy on us.",
      "Lord, have mercy on us.",
      "Christ, hear us. Christ, graciously hear us.",
      "",
      "God the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the World, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "",
      "Kateri, lily of purity, pray for us.",
      "Kateri, consoler of the heart of Jesus, pray for us.",
      "Kateri, bright light for all Indians, pray for us.",
      "Kateri, courage of the afflicted, pray for us.",
      "Kateri, lover of the cross of Jesus, pray for us.",
      "Kateri, flower of fortitude for the persecuted, pray for us.",
      "Kateri, unshakeable in temptations, pray for us.",
      "Kateri, full of patience in suffering, pray for us.",
      "Kateri, keeper of your virginity in persecutions, pray for us.",
      "Kateri, leader of many Indians to the true faith through your love for Mary, pray for us.",
      "Kateri, who loved Jesus in the Blessed Sacrament, pray for us.",
      "Kateri, lover of penance, pray for us.",
      "Kateri, who traveled many miles to learn the faith, pray for us.",
      "Kateri, steadfast in all prayer, pray for us.",
      "Kateri, who loved to pray the rosary for all people, pray for us.",
      "Kateri, example to your people in all virtues, pray for us.",
      "Kateri, humble servant to the sick, pray for us.",
      "Kateri, who by your love of humility, gave joy to the angels, pray for us.",
      "Kateri, your holy death gave strength to all Indians to love Jesus and Mary, pray for us.",
      "Kateri, whose scarred face in life became beautiful after death, pray for us.",
      "",
      "Lamb of God, who takes away the sins of the world, spare us, O Lord.",
      "Lamb of God, who takes away the sins of the world, graciously hear us, O Lord.",
      "Lamb of God, who takes away the sins of the world, have mercy on us.",
      "",
      "Let us pray:",
      "O Jesus, who gave Kateri to the Indians as an example of purity, teach all men to love purity, and to console your immaculate Mother Mary through the lily, Kateri Tekakwitha, and your Holy Cross, Amen.",
      "",
      "Kateri Tekakwitha, pray for us.",
    ],
  }),
  litany({
    slug: "litany-of-our-lady-of-fatima",
    title: "Litany of Our Lady of Fatima",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-to-our-lady-of-fatima-254`],
    occasions: ["may-13", "october-13", "first-saturday"],
    summary:
      "A short private litany of petitions to the Blessed Virgin under the title given her at Fatima, where she appeared to three shepherd children in 1917. It closes with the Miraculous Medal invocation and a prayer to Our Lady of the Rosary.",
    lines: [
      "Our Lady of Fatima, pray for our dear country.",
      "Our Lady of Fatima, sanctify our clergy.",
      "Our Lady of Fatima, make our Catholics more fervent.",
      "Our Lady of Fatima, guide and inspire those who govern us.",
      "Our Lady of Fatima, cure the sick who confide in thee.",
      "Our Lady of Fatima, console the sorrowful who trust in thee.",
      "Our Lady of Fatima, help those who invoke your aid.",
      "Our Lady of Fatima, deliver us from all dangers.",
      "Our Lady of Fatima, help us to resist temptation.",
      "Our Lady of Fatima, obtain for us all that we lovingly ask of thee.",
      "Our Lady of Fatima, help those who are dear to us.",
      "Our Lady of Fatima, bring back to the right road our erring brothers.",
      "Our Lady of Fatima, give us back our ancient fervor.",
      "Our Lady of Fatima, obtain for us pardon of our manifold sins and offenses.",
      "Our Lady of Fatima, bring all men to the feet of thy Divine Child.",
      "Our Lady of Fatima, obtain peace for the world.",
      "",
      "O Mary conceived without sin, pray for us who have recourse to thee.",
      "Immaculate Heart of Mary, pray for us now and at the hour of our death. Amen.",
      "",
      "Let Us Pray",
      "O God of infinite goodness and mercy, fill our hearts with a great confidence in Thy dear Mother, whom we invoke under the title of Our Lady of the Rosary and our Lady of Fatima, and grant us by her powerful intercession all the graces, spiritual and temporal, which we need. Through Christ our Lord. Amen.",
    ],
  }),
  litany({
    slug: "litany-of-our-lady-of-good-counsel",
    title: "Litany of Our Lady of Good Counsel",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-to-our-lady-of-good-counsel-255`],
    occasions: ["april-26", "discernment", "decisions"],
    summary:
      "A private litany invoking the Blessed Virgin under the title of Good Counsel, honoured at the shrine of Genazzano and kept on 26 April. It is prayed in doubts, difficulties and decisions.",
    lines: [
      "Lord, have mercy on us. Christ, have mercy on us.",
      "Lord, have mercy on us.",
      "Christ, hear us. Christ, graciously hear us.",
      "",
      "God the Father of Heaven, have mercy on us.",
      "God the Son, Redeemer of the world, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, One God, have mercy on us.",
      "",
      "Beloved Daughter of the Eternal Father, pray for us.",
      "August Mother of God the Son, pray for us.",
      "Blessed Spouse of God the Holy Ghost, pray for us.",
      "Living temple of the Holy Trinity, pray for us.",
      "Queen of Heaven and earth, pray for us.",
      "Seat of Divine wisdom, pray for us.",
      "Depositary of the secrets of the Most High, pray for us.",
      "Virgin most prudent, pray for us.",
      "In our doubts and difficulties, pray for us.",
      "In our tribulations and anguish, pray for us.",
      "In our discouragements, pray for us.",
      "In perils and temptations, pray for us.",
      "In all our undertakings, pray for us.",
      "In all our needs, pray for us.",
      "At the hour of death, pray for us.",
      "By thine Immaculate Conception, pray for us.",
      "By thy happy nativity, pray for us.",
      "By thine admirable presentation, pray for us.",
      "By thy glorious Annunciation, pray for us.",
      "By thy charitable Visitation, pray for us.",
      "By thy Divine Maternity, pray for us.",
      "By thy holy Purification, pray for us.",
      "By the sorrows and anguish of thy maternal heart, pray for us.",
      "By thy precious death, pray for us.",
      "By thy triumphant Assumption, pray for us.",
      "",
      "Lamb of God, Who takes away the sins of the world, spare us, O Lord.",
      "Lamb of God, Who takes away the sins of the world, graciously hear us, O Lord.",
      "Lamb of God, Who takes away the sins of the world, have mercy on us.",
      "",
      "Pray for us, O holy Mother of God,",
      "And obtain for us the gift of good counsel.",
      "",
      "Let Us Pray",
      "Lord Jesus, Author and Dispenser of all good, Who in becoming incarnate in the womb of the Blessed Virgin has communicated to her lights above those of all the heavenly intelligences, grant that in honoring her under the title of Our Lady of Good Counsel, we may merit always to receive from her goodness, counsels of wisdom and salvation, which will conduct us to the port of a blessed eternity. Amen.",
    ],
  }),
  litany({
    slug: "litany-of-the-infant-jesus",
    title: "Litany of the Infant Jesus",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [
      `${EWTN}litany-to-the-infant-jesus-267`,
      "https://www.catholicdoors.com/prayers/litanies/p03488.htm",
    ],
    occasions: ["christmas", "epiphany", "holy-childhood"],
    summary:
      "A private litany honouring the Word made flesh in his infancy, from his conception to his hidden life at Nazareth. It is prayed especially during Christmastide and in the devotion to the Holy Child.",
    lines: [
      "Lord, have mercy on us. Christ, have mercy on us.",
      "Lord, have mercy on us. Jesus, hear us. Jesus, graciously hear us.",
      "",
      "God the Father of Heaven, have mercy on us.",
      "God the Son, Redeemer of the world, have mercy on us.",
      "God the Holy Spirit, have mercy on us.",
      "Holy Trinity, One God, have mercy on us.",
      "",
      "Infant, Jesus Christ, have mercy on us.",
      "Infant, true God, have mercy on us.",
      "Infant, Son of the living God, have mercy on us.",
      "Infant, Son of the Virgin Mary, have mercy on us.",
      "Infant, strong in weakness, have mercy on us.",
      "Infant, powerful in tenderness, have mercy on us.",
      "Infant, Treasure of grace, have mercy on us.",
      "Infant, Fountain of love, have mercy on us.",
      "Infant, Renewer of the heavens, have mercy on us.",
      "Infant, Repairer of the evils of the earth, have mercy on us.",
      "Infant, Head of the angels, have mercy on us.",
      "Infant, Root of the patriarchs, have mercy on us.",
      "Infant, Speech of the prophets, have mercy on us.",
      "Infant, Desire of the Gentiles, have mercy on us.",
      "Infant, Joy of shepherds, have mercy on us.",
      "Infant, Light of the Magi, have mercy on us.",
      "Infant, Salvation of infants, have mercy on us.",
      "Infant, Expectation of the just, have mercy on us.",
      "Infant, Instructor of the wise, have mercy on us.",
      "Infant, First-fruit of all saints, have mercy on us.",
      "",
      "Be merciful, spare us, O Infant Jesus.",
      "Be merciful, graciously hear us, O Infant Jesus.",
      "",
      "From the slavery of the children of Adam, Infant Jesus, deliver us.",
      "From the slavery of the devil, Infant Jesus, deliver us.",
      "From the evil desires of the flesh, Infant Jesus, deliver us.",
      "From the malice of the world, Infant Jesus, deliver us.",
      "From the pride of life, Infant Jesus, deliver us.",
      "From the inordinate desire of knowing, Infant Jesus, deliver us.",
      "From blindness of spirit, Infant Jesus, deliver us.",
      "From an evil will, Infant Jesus, deliver us.",
      "From our sins, Infant Jesus, deliver us.",
      "Through Thy most pure Conception, Infant Jesus, deliver us.",
      "Through Thy most humble Nativity, Infant Jesus, deliver us.",
      "Through Thy tears, Infant Jesus, deliver us.",
      "Through Thy most painful Circumcision, Infant Jesus, deliver us.",
      "Through Thy most glorious Epiphany, Infant Jesus, deliver us.",
      "Through Thy most pious Presentation, Infant Jesus, deliver us.",
      "Through Thy most divine life, Infant Jesus, deliver us.",
      "Through Thy poverty, Infant Jesus, deliver us.",
      "Through Thy many sufferings, Infant Jesus, deliver us.",
      "Through Thy labors and travels, Infant Jesus, deliver us.",
      "",
      "Lamb of God, Who takes away the sins of the world, spare us, O Infant Jesus.",
      "Lamb of God, Who takes away the sins of the world, graciously hear us, O Infant Jesus.",
      "Lamb of God, Who takes away the sins of the world, have mercy on us, O Infant Jesus.",
      "",
      "Jesus, Infant, hear us. Jesus, Infant, graciously hear us.",
    ],
  }),
  litany({
    slug: "litany-of-the-love-of-god",
    title: "Litany of the Love of God",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${CATHOLIC_ONLINE}464`],
    occasions: ["daily", "act-of-love", "adoration"],
    summary:
      "A private litany that is one long act of charity: each petition names a circumstance — wealth or poverty, health or sickness, life or death — and answers it with the same profession of love for God. It closes with a prayer for the purifying of every other love.",
    lines: [
      "Lord, have mercy on us.",
      "Christ, have mercy on us.",
      "Lord, have mercy on us.",
      "Christ, hear us. Christ graciously hear us.",
      "",
      "God, the Father of heaven, have mercy on us.",
      "God the Son, Redeemer of the world, have mercy on us.",
      "God, the Holy Ghost, have mercy on us.",
      "Holy Trinity, one God, have mercy on us.",
      "Thou Who art Infinite Love, have mercy on us.",
      "Thou Who didst first love me, have mercy on us.",
      "Thou Who commandest me to love Thee, have mercy on us.",
      "",
      "With all my heart, I love Thee, O my God.",
      "With all my soul, I love Thee, O my God.",
      "With all my mind, I love Thee, O my God.",
      "With all my strength, I love Thee, O my God.",
      "Above all possessions and honors, I love Thee, O my God.",
      "Above all pleasures and enjoyments, I love Thee, O my God.",
      "More than myself, and everything belonging to me, I love Thee, O my God.",
      "More than all my relatives and friends, I love Thee, O my God.",
      "More than all men and angels, I love Thee, O my God.",
      "Above all created things in heaven or on earth, I love Thee, O my God.",
      "Only for Thyself, I love Thee, O my God.",
      "Because Thou art the sovereign Good, I love Thee, O my God.",
      "Because Thou art infinitely worthy of being loved, I love Thee, O my God.",
      "Because Thou art infinitely perfect, I love Thee, O my God.",
      "Even hadst Thou not promised me heaven, I love Thee, O my God.",
      "Even hadst Thou not menaced me with hell, I love Thee, O my God.",
      "Even shouldst Thou try me by want and misfortune, I love Thee, O my God.",
      "In wealth and in poverty, I love Thee, O my God.",
      "In prosperity and in adversity, I love Thee, O my God.",
      "In health and in sickness, I love Thee, O my God.",
      "In life and in death, I love Thee, O my God.",
      "In time and in eternity, I love Thee, O my God.",
      "In union with that love wherewith all the saints and all the angels love Thee in heaven, I love Thee, O my God.",
      "In union with that love wherewith the Blessed Virgin Mary loveth Thee, I love Thee, O my God.",
      "In union with that infinite love wherewith Thou lovest Thyself eternally, I love Thee, O my God.",
      "",
      "My God, Who dost possess in incomprehensible abundance all that is perfect and worthy of love, annihilate in me all guilty, sensual, and undue love for creatures. Kindle in my heart the pure fire of Thy love, so that I may love nothing but Thee or in Thee, until being so entirely consumed by holy love of Thee, I may go to love Thee eternally with the elect in heaven, the country of pure love. Amen.",
    ],
  }),
  litany({
    slug: "litany-for-priests",
    title: "Litany for Priests",
    authorityLevel: "TRUSTED_PUBLISHER",
    citations: [`${EWTN}litany-for-priests-244`],
    occasions: ["holy-thursday", "vocations", "first-friday"],
    summary:
      "A short private litany asking that priests be given the virtues of the Heart of Christ — humility, zeal, compassion, sacrifice and charity — and closing with a petition to Mary, Queen of the Clergy, for holy priests and religious.",
    lines: [
      "Jesus, meek and humble of heart, give all priests Thy spirit of humility;",
      "Jesus, poor and worn out for souls, give all priests Thy spirit of zeal;",
      "Jesus, full of patience and mercy for sinners, give all priests Thy spirit of compassion;",
      "Jesus, victim for the sins of the world, give all priests Thy spirit of sacrifice;",
      "Jesus, lover of the little and the poor, give all priests Thy spirit of charity.",
      "",
      "Mary, Queen of the Clergy, pray for us;",
      "and obtain for us numerous and holy priests and religious.",
      "Amen.",
    ],
  }),
];
