import type { CuratedEntry } from "./index";

const CCC = "https://www.vatican.va/archive/ENG0015/_INDEX.HTM";
const USCCB_SACRAMENTS = "https://www.usccb.org/prayer-and-worship/sacraments-and-sacramentals";

function sacrament(
  slug: string,
  key: string,
  title: string,
  overview: string,
  matter: string,
  form: string,
  minister: string,
  recipient: string,
  effects: string[],
  institution: string,
  catechismRefs: string[],
): CuratedEntry {
  return {
    contentType: "SACRAMENT",
    slug,
    authorityLevel: "CATECHISM",
    citations: [CCC, USCCB_SACRAMENTS],
    payload: {
      slug,
      sacramentKey: key,
      title,
      summary: overview,
      theologicalOverview: overview,
      institution,
      matterAndForm: { matter, form },
      minister,
      recipient,
      effects,
      preparation: "See the parish RCIA / OCIA office or your pastor for catechetical preparation.",
      relatedRites: [],
      catechismReferences: catechismRefs,
      citations: [CCC, USCCB_SACRAMENTS],
    },
  };
}

export const sacramentKnowledge: CuratedEntry[] = [
  sacrament(
    "baptism",
    "baptism",
    "Baptism",
    "Baptism is the basis of the whole Christian life, the gateway to life in the Spirit, and the door which gives access to the other sacraments. Through Baptism we are freed from sin and reborn as sons of God; we become members of Christ, are incorporated into the Church, and made sharers in her mission. The Catechism teaches that Baptism is necessary for salvation for those to whom the Gospel has been proclaimed and who have had the possibility of asking for this sacrament.",
    "Natural water poured upon the head (or by immersion).",
    "I baptize you in the name of the Father, and of the Son, and of the Holy Spirit.",
    "Ordinary minister: bishop, priest, or deacon. In case of necessity, any person, even a non-baptized one, with the required intention.",
    "Every person not yet baptized, and only such a person, is able to be baptized.",
    [
      "Forgiveness of original sin and all personal sins",
      "Birth into the new life by which we become adoptive sons of the Father, members of Christ, and temples of the Holy Spirit",
      "Incorporation into the Church and configuration to her mission",
      "An indelible spiritual mark (character) on the soul",
    ],
    "Christ instituted Baptism by his own baptism in the Jordan and by his command to the apostles: 'Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit' (Matthew 28:19).",
    ["CCC 1213-1284"],
  ),
  sacrament(
    "confirmation",
    "confirmation",
    "Confirmation",
    "Confirmation perfects baptismal grace; it is the sacrament which gives the Holy Spirit in order to root us more deeply in the divine filiation, incorporate us more firmly into Christ, strengthen our bond with the Church, associate us more closely with her mission, and help us bear witness to the Christian faith in words accompanied by deeds.",
    "The anointing with sacred chrism on the forehead, done by the laying on of hands.",
    "Be sealed with the Gift of the Holy Spirit.",
    "Ordinary minister: bishop. Priests may confirm with delegated faculty, especially in the case of adults baptized in the Easter Vigil and those in danger of death.",
    "Every baptized person not yet confirmed.",
    [
      "Increase and deepening of baptismal grace",
      "Roots us more deeply in divine filiation",
      "Unites us more firmly to Christ",
      "Increases in us the gifts of the Holy Spirit",
      "Renders our bond with the Church more perfect",
      "Gives a special strength of the Holy Spirit to spread and defend the faith",
      "An indelible character on the soul",
    ],
    "The promised Spirit was poured out on the apostles at Pentecost (Acts 2). The apostles continued the gift by the laying on of hands (Acts 8:14-17, 19:5-6).",
    ["CCC 1285-1321"],
  ),
  sacrament(
    "eucharist",
    "eucharist",
    "The Holy Eucharist",
    "The Eucharist is 'the source and summit of the Christian life.' The other sacraments, and indeed all ecclesiastical ministries and works of the apostolate, are bound up with the Eucharist and are oriented toward it. For in the blessed Eucharist is contained the whole spiritual good of the Church, namely Christ himself, our Pasch. In the Eucharist Christ is truly, really, and substantially present under the appearances of bread and wine.",
    "Wheat bread and natural grape wine.",
    "The words of institution: 'This is my Body... This is the chalice of my Blood...'",
    "Only validly ordained priests can preside at the Eucharist and consecrate the bread and wine to become the Body and Blood of the Lord.",
    "Every baptized Catholic in the state of grace.",
    [
      "Real, true, and substantial presence of Christ",
      "Increase in sanctifying grace",
      "Union with Christ and his Body the Church",
      "Forgiveness of venial sins; preservation from future mortal sins",
      "Pledge of future glory",
    ],
    "Christ instituted the Eucharist on the night before he died, at the Last Supper, when he gave his apostles the command: 'Do this in remembrance of me' (Luke 22:19, 1 Corinthians 11:24-25).",
    ["CCC 1322-1419"],
  ),
  sacrament(
    "reconciliation",
    "reconciliation",
    "The Sacrament of Reconciliation",
    "Those who approach the sacrament of Penance obtain pardon from God's mercy for the offense committed against him, and are, at the same time, reconciled with the Church which they have wounded by their sins and which by charity, by example, and by prayer labors for their conversion. It is called the sacrament of conversion, of Penance, of confession, of forgiveness, and of Reconciliation.",
    "The acts of the penitent: contrition, confession of sins, and intention to do penance.",
    "I absolve you from your sins in the name of the Father, and of the Son, and of the Holy Spirit.",
    "Only priests who have received the faculty of absolving from the authority of the Church.",
    "Every baptized Catholic conscious of grave sin must approach this sacrament before receiving Holy Communion.",
    [
      "Reconciliation with God by which the penitent recovers grace",
      "Reconciliation with the Church",
      "Remission of the eternal punishment incurred by mortal sins",
      "Remission, at least in part, of temporal punishments resulting from sin",
      "Peace and serenity of conscience, and spiritual consolation",
      "An increase of spiritual strength for the Christian battle",
    ],
    "Christ instituted the sacrament on the evening of his resurrection: 'Receive the Holy Spirit. If you forgive the sins of any, they are forgiven' (John 20:22-23).",
    ["CCC 1422-1498"],
  ),
  sacrament(
    "anointing-of-the-sick",
    "anointing_of_the_sick",
    "The Anointing of the Sick",
    "By the sacred anointing of the sick and the prayer of the priests the whole Church commends those who are ill to the suffering and glorified Lord, that he may raise them up and save them. The Anointing of the Sick is not a sacrament for those only who are at the point of death; the proper time to receive it has certainly already arrived when the believer begins to be in danger of death because of sickness or old age.",
    "Oil blessed by the bishop (or, in case of necessity, by the priest who celebrates the sacrament).",
    "Through this holy anointing may the Lord in his love and mercy help you with the grace of the Holy Spirit. May the Lord who frees you from sin save you and raise you up.",
    "Priests (bishops and presbyters) alone.",
    "The faithful whose health is seriously impaired by sickness or old age.",
    [
      "A particular gift of the Holy Spirit",
      "The strengthening, peace, and courage to endure suffering",
      "The forgiveness of sins, if the sick person was unable to obtain it through Reconciliation",
      "The restoration of health, if it is conducive to the salvation of the soul",
      "Preparation for passing over to eternal life",
    ],
    "Christ's compassion toward the sick and his many healings constitute the foundation of this sacrament. The Letter of James commends the sick to call for the priests of the Church to pray over them and anoint them (James 5:14-15).",
    ["CCC 1499-1532"],
  ),
  sacrament(
    "holy-orders",
    "holy_orders",
    "Holy Orders",
    "Holy Orders is the sacrament through which the mission entrusted by Christ to his apostles continues to be exercised in the Church until the end of time: thus it is the sacrament of apostolic ministry. It includes three degrees: episcopate, presbyterate, and diaconate.",
    "The laying on of hands by the bishop.",
    "The consecratory prayer proper to each degree of orders.",
    "Only a validly consecrated bishop can validly confer the three degrees of the sacrament of Holy Orders.",
    "Only a baptized man validly receives sacred ordination.",
    [
      "An indelible spiritual character",
      "Configuration to Christ as Priest, Prophet, and King",
      "The grace of the Holy Spirit proper to the order received",
      "The sacred power of teaching, sanctifying, and governing in the name of Christ",
    ],
    "Christ instituted Holy Orders when he chose the Twelve, gave them authority, and at the Last Supper said: 'Do this in remembrance of me.' The Holy Spirit was given them at Easter and Pentecost to fulfill their mission.",
    ["CCC 1536-1600"],
  ),
  sacrament(
    "matrimony",
    "matrimony",
    "Matrimony",
    "The matrimonial covenant, by which a man and a woman establish between themselves a partnership of the whole of life, is by its nature ordered toward the good of the spouses and the procreation and education of offspring; this covenant between baptized persons has been raised by Christ the Lord to the dignity of a sacrament.",
    "The mutual consent of the spouses expressed in words and signified by the spousal embrace.",
    "I, N., take you, N., to be my wife/husband. I promise to be faithful to you, in good times and in bad, in sickness and in health, to love you and to honor you all the days of my life.",
    "The spouses themselves are the ministers of Matrimony in the Latin Church; the priest or deacon assists and receives their consent in the name of the Church.",
    "A baptized man and a baptized woman, free to marry, who freely express their consent.",
    [
      "A bond of marriage which is perpetual and exclusive",
      "An increase of sanctifying grace",
      "A particular grace for the sanctification of the spouses and the Christian education of their children",
    ],
    "Marriage was instituted by God at the dawn of creation (Genesis 2:24). Christ raised it to the dignity of a sacrament in his own person and made it a sign of his union with the Church (Ephesians 5:25-32).",
    ["CCC 1601-1666"],
  ),
];
