import type { ChecklistSeed } from "./index";

export const churchDocumentsChecklist: ChecklistSeed[] = [
  {
    canonicalName: "Catechism of the Catholic Church",
    canonicalSlug: "catechism-of-the-catholic-church",
    priority: 5,
    authorityLevelHint: "CATECHISM",
  },
  {
    canonicalName: "Lumen Gentium",
    canonicalSlug: "lumen-gentium",
    priority: 10,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "council_document" },
  },
  {
    canonicalName: "Dei Verbum",
    canonicalSlug: "dei-verbum",
    priority: 10,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "council_document" },
  },
  {
    canonicalName: "Sacrosanctum Concilium",
    canonicalSlug: "sacrosanctum-concilium",
    priority: 10,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "council_document" },
  },
  {
    canonicalName: "Gaudium et Spes",
    canonicalSlug: "gaudium-et-spes",
    priority: 10,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "council_document" },
  },
  {
    canonicalName: "Rerum Novarum",
    canonicalSlug: "rerum-novarum",
    priority: 15,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "encyclical" },
  },
  {
    canonicalName: "Humanae Vitae",
    canonicalSlug: "humanae-vitae",
    priority: 15,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "encyclical" },
  },
  {
    canonicalName: "Veritatis Splendor",
    canonicalSlug: "veritatis-splendor",
    priority: 15,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "encyclical" },
  },
  {
    canonicalName: "Evangelium Vitae",
    canonicalSlug: "evangelium-vitae",
    priority: 15,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "encyclical" },
  },
  {
    canonicalName: "Fides et Ratio",
    canonicalSlug: "fides-et-ratio",
    priority: 15,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "encyclical" },
  },
  {
    canonicalName: "Deus Caritas Est",
    canonicalSlug: "deus-caritas-est",
    priority: 20,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "encyclical" },
  },
  {
    canonicalName: "Spe Salvi",
    canonicalSlug: "spe-salvi",
    priority: 20,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "encyclical" },
  },
  {
    canonicalName: "Lumen Fidei",
    canonicalSlug: "lumen-fidei",
    priority: 20,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "encyclical" },
  },
  {
    canonicalName: "Laudato Si'",
    canonicalSlug: "laudato-si",
    priority: 20,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "encyclical" },
  },
  {
    canonicalName: "Evangelii Gaudium",
    canonicalSlug: "evangelii-gaudium",
    priority: 20,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "apostolic_exhortation" },
  },
  {
    canonicalName: "Amoris Laetitia",
    canonicalSlug: "amoris-laetitia",
    priority: 25,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "apostolic_exhortation" },
  },
  {
    canonicalName: "Pastores Dabo Vobis",
    canonicalSlug: "pastores-dabo-vobis",
    priority: 30,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "apostolic_exhortation" },
  },
  {
    canonicalName: "Ineffabilis Deus",
    canonicalSlug: "ineffabilis-deus",
    priority: 25,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "apostolic_constitution" },
  },
  {
    canonicalName: "Munificentissimus Deus",
    canonicalSlug: "munificentissimus-deus",
    priority: 25,
    authorityLevelHint: "VATICAN",
    metadata: { documentType: "apostolic_constitution" },
  },
];
