import type { ChecklistSeed } from "./index";

export const saintsChecklist: ChecklistSeed[] = [
  {
    canonicalName: "Saint Joseph",
    canonicalSlug: "saint-joseph",
    priority: 10,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "03-19" },
  },
  {
    canonicalName: "Saint Peter the Apostle",
    canonicalSlug: "saint-peter",
    priority: 10,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "06-29" },
  },
  {
    canonicalName: "Saint Paul the Apostle",
    canonicalSlug: "saint-paul",
    priority: 10,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "06-29" },
  },
  {
    canonicalName: "Saint John the Baptist",
    canonicalSlug: "saint-john-the-baptist",
    priority: 15,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "06-24" },
  },
  {
    canonicalName: "Saint Mary Magdalene",
    canonicalSlug: "saint-mary-magdalene",
    priority: 20,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "07-22" },
  },
  {
    canonicalName: "Saint Augustine of Hippo",
    canonicalSlug: "saint-augustine-of-hippo",
    priority: 20,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "08-28" },
  },
  {
    canonicalName: "Saint Thomas Aquinas",
    canonicalSlug: "saint-thomas-aquinas",
    priority: 20,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "01-28" },
  },
  {
    canonicalName: "Saint Francis of Assisi",
    canonicalSlug: "saint-francis-of-assisi",
    priority: 15,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "10-04" },
  },
  {
    canonicalName: "Saint Dominic",
    canonicalSlug: "saint-dominic",
    priority: 25,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "08-08" },
  },
  {
    canonicalName: "Saint Ignatius of Loyola",
    canonicalSlug: "saint-ignatius-of-loyola",
    priority: 25,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "07-31" },
  },
  {
    canonicalName: "Saint Teresa of Avila",
    canonicalSlug: "saint-teresa-of-avila",
    priority: 25,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "10-15" },
  },
  {
    canonicalName: "Saint John of the Cross",
    canonicalSlug: "saint-john-of-the-cross",
    priority: 25,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "12-14" },
  },
  {
    canonicalName: "Saint Therese of Lisieux",
    canonicalSlug: "saint-therese-of-lisieux",
    aliases: ["Little Flower"],
    priority: 20,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "10-01" },
  },
  {
    canonicalName: "Saint Padre Pio of Pietrelcina",
    canonicalSlug: "saint-padre-pio",
    priority: 20,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "09-23" },
  },
  {
    canonicalName: "Saint Pope John Paul II",
    canonicalSlug: "saint-john-paul-ii",
    priority: 15,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "10-22" },
  },
  {
    canonicalName: "Saint Faustina Kowalska",
    canonicalSlug: "saint-faustina-kowalska",
    priority: 20,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "10-05" },
  },
  {
    canonicalName: "Saint Maximilian Kolbe",
    canonicalSlug: "saint-maximilian-kolbe",
    priority: 25,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "08-14" },
  },
  {
    canonicalName: "Saint Mother Teresa of Calcutta",
    canonicalSlug: "saint-mother-teresa-of-calcutta",
    priority: 20,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "09-05" },
  },
  {
    canonicalName: "Saint Anthony of Padua",
    canonicalSlug: "saint-anthony-of-padua",
    priority: 25,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "06-13" },
  },
  {
    canonicalName: "Saint Patrick",
    canonicalSlug: "saint-patrick",
    priority: 25,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "03-17" },
  },
  {
    canonicalName: "Saint Benedict of Nursia",
    canonicalSlug: "saint-benedict-of-nursia",
    priority: 25,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "07-11" },
  },
  {
    canonicalName: "Saint Catherine of Siena",
    canonicalSlug: "saint-catherine-of-siena",
    priority: 25,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "04-29" },
  },
  {
    canonicalName: "Saint Joan of Arc",
    canonicalSlug: "saint-joan-of-arc",
    priority: 30,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "05-30" },
  },
  {
    canonicalName: "Saint Monica",
    canonicalSlug: "saint-monica",
    priority: 30,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "08-27" },
  },
  {
    canonicalName: "Saint Jerome",
    canonicalSlug: "saint-jerome",
    priority: 25,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "09-30" },
  },
  {
    canonicalName: "Saint Athanasius",
    canonicalSlug: "saint-athanasius",
    priority: 30,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "05-02" },
  },
  {
    canonicalName: "Saint Ambrose",
    canonicalSlug: "saint-ambrose",
    priority: 30,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "12-07" },
  },
  {
    canonicalName: "Saint Cecilia",
    canonicalSlug: "saint-cecilia",
    priority: 30,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "11-22" },
  },
  {
    canonicalName: "Saint Lucy",
    canonicalSlug: "saint-lucy",
    priority: 30,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "12-13" },
  },
  {
    canonicalName: "Saint Nicholas of Myra",
    canonicalSlug: "saint-nicholas-of-myra",
    priority: 30,
    authorityLevelHint: "VATICAN",
    metadata: { feastDay: "12-06" },
  },
];
