/**
 * The lectionary table package: the calendar engine's `lectionaryKey` → the
 * Lectionary for Mass number → the citations of that formulary.
 *
 * Everything here is pure data lookup — no database, no network, no Scripture
 * text. The text layer (src/lib/content-shared/lectionary.ts) resolves the
 * citations returned here against the Douay-Rheims store.
 *
 * The tables are generated by scripts/lectionary/build-tables.ts; edit the
 * script or its sources, never the JSON.
 */

import byNumberJson from "./tables/by-number.json";
import keyMapJson from "./tables/key-map.json";
import sanctoralJson from "./tables/sanctoral.json";
import sundaysJson from "./tables/sundays.json";
import weekdaysJson from "./tables/weekdays.json";

import { compareLectionaryNumbers, readingOrderIndex } from "./keys";
import type {
  KeyMapEntry,
  KeyMapMass,
  LectionaryByNumber,
  LectionaryEntry,
  LectionaryEntryKind,
  LectionaryIndex,
  LectionaryIndexEntry,
  LectionaryKeyMap,
  LectionarySection,
  SundayCycle,
  WeekdayCycle,
} from "./types";

export * from "./types";
export { READING_ORDER, compareLectionaryNumbers, labelSlug, readingOrderIndex } from "./keys";

const BY_NUMBER = byNumberJson as unknown as LectionaryByNumber;
const KEY_MAP = keyMapJson as unknown as LectionaryKeyMap;
const SANCTORAL_INDEX = sanctoralJson as unknown as LectionaryIndex;
const SUNDAY_INDEX = sundaysJson as unknown as LectionaryIndex;
const WEEKDAY_INDEX = weekdaysJson as unknown as LectionaryIndex;

/**
 * Credits the tables must be published with. The citations come from the USCCB
 * Lectionary for Mass; the index that supplied the days those years never showed
 * is Fr Felix Just's, whose licence asks for the credit line below.
 */
export const LECTIONARY_ATTRIBUTION = [
  {
    source: "usccb",
    label: "United States Conference of Catholic Bishops",
    url: "https://bible.usccb.org/daily-bible-reading",
    note: "Lectionary for Mass for Use in the Dioceses of the United States of America.",
  },
  {
    source: "catholic-resources",
    label: "Rev. Felix Just, S.J.",
    url: "http://catholic-resources.org",
    note: "Material provided by Rev. Felix Just, S.J., at http://catholic-resources.org",
  },
] as const;

export interface LectionaryCycles {
  sundayCycle?: SundayCycle;
  weekdayCycle?: WeekdayCycle;
}

export interface LectionaryLookupOptions extends LectionaryCycles {
  /**
   * Mass formulary to resolve. Omit (or pass undefined) for the principal Mass
   * of the day; pass "vigil", "night", "year-a" … for an alternative one.
   */
  variant?: string | null;
}

export interface LectionaryLookup {
  key: string;
  number: string;
  /** Day label as printed in the Lectionary index, e.g. "Week 3 - Mon". */
  label: string;
  cycle: SundayCycle | null;
  variant: string | null;
  /** Sections in proclamation order, reduced to the requested cycles. */
  sections: LectionarySection[];
  /** Every formulary this key has, principal first — the "or" Masses of the day. */
  masses: readonly KeyMapMass[];
  /** How the key was mapped: "dates" = joined with a dated source; "labels" = from the index. */
  mappedFrom: KeyMapEntry["source"];
}

/** Every lectionary number in the table, in Lectionary order. */
export function lectionaryNumbers(): string[] {
  return Object.keys(BY_NUMBER).sort(compareLectionaryNumbers);
}

/** Every engine key the table can answer for. */
export function lectionaryKeys(): string[] {
  return Object.keys(KEY_MAP).sort();
}

export function lectionaryEntry(number: string): LectionaryEntry | null {
  return BY_NUMBER[number] ?? null;
}

/** The per-kind index: Sundays and weekdays by label slug, the sanctoral by "MM-DD". */
export function lectionaryIndex(
  kind: Extract<LectionaryEntryKind, "sunday" | "weekday" | "sanctoral">,
): LectionaryIndex {
  if (kind === "sunday") return SUNDAY_INDEX;
  if (kind === "weekday") return WEEKDAY_INDEX;
  return SANCTORAL_INDEX;
}

/** Proper-of-Saints formularies printed for a calendar date. */
export function sanctoralEntriesForDate(month: number, day: number): LectionaryIndexEntry[] {
  const key = `${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
  return SANCTORAL_INDEX[key] ?? [];
}

/**
 * The key-map row that applies to a Sunday cycle. Keys whose numbers do not vary
 * by year hold a single row with `cycle: null`.
 */
export function keyMapEntry(key: string, sundayCycle?: SundayCycle): KeyMapEntry | null {
  const rows = KEY_MAP[key];
  if (!rows || rows.length === 0) return null;
  if (sundayCycle) {
    const forCycle = rows.find((row) => row.cycle === sundayCycle);
    if (forCycle) return forCycle;
  }
  return rows.find((row) => row.cycle === null) ?? rows[0];
}

/** Every Mass formulary a key offers, principal first. */
export function lectionaryMasses(key: string, sundayCycle?: SundayCycle): readonly KeyMapMass[] {
  return keyMapEntry(key, sundayCycle)?.masses ?? [];
}

/**
 * The sections of an entry that apply to the given cycles: a cycle-specific
 * section always overrides the shared one of the same kind, and the result is in
 * proclamation order.
 */
export function sectionsForCycles(
  entry: LectionaryEntry,
  cycles: LectionaryCycles = {},
): LectionarySection[] {
  const chosen = new Map<string, LectionarySection>();
  for (const section of entry.sections) {
    const applies =
      section.cycle === null ||
      section.cycle === cycles.sundayCycle ||
      section.cycle === cycles.weekdayCycle;
    if (!applies) continue;
    const current = chosen.get(section.kind);
    // A cycle-tagged section beats the shared one; two shared ones keep the first.
    if (!current || (current.cycle === null && section.cycle !== null)) {
      chosen.set(section.kind, section);
    }
  }
  return [...chosen.values()].sort((a, b) => readingOrderIndex(a.kind) - readingOrderIndex(b.kind));
}

/**
 * Resolve an engine `lectionaryKey` to the Lectionary formulary for the given
 * year, with its citations. Returns null when the key is unknown or its
 * formulary is not in the table — callers must stay fail-open and fall back to
 * the celebration heading alone rather than inventing readings.
 */
export function lookupLectionary(
  key: string,
  options: LectionaryLookupOptions = {},
): LectionaryLookup | null {
  const row = keyMapEntry(key, options.sundayCycle);
  if (!row || row.masses.length === 0) return null;
  const mass =
    options.variant === undefined || options.variant === null
      ? row.masses[0]
      : row.masses.find((m) => m.variant === options.variant);
  if (!mass) return null;
  const entry = BY_NUMBER[mass.number];
  if (!entry) return null;
  return {
    key,
    number: entry.number,
    label: entry.label,
    cycle: entry.cycle,
    variant: mass.variant,
    sections: sectionsForCycles(entry, options),
    masses: row.masses,
    mappedFrom: row.source,
  };
}

/** Table sizes, for the coverage script and the Command Center. */
export function lectionaryTableStats(): {
  numbers: number;
  keys: number;
  sections: number;
  byKind: Record<LectionaryEntryKind, number>;
} {
  const byKind: Record<LectionaryEntryKind, number> = {
    sunday: 0,
    weekday: 0,
    sanctoral: 0,
    common: 0,
  };
  let sections = 0;
  for (const entry of Object.values(BY_NUMBER)) {
    byKind[entry.kind] += 1;
    sections += entry.sections.length;
  }
  return {
    numbers: Object.keys(BY_NUMBER).length,
    keys: Object.keys(KEY_MAP).length,
    sections,
    byKind,
  };
}
