/**
 * Shapes of the committed lectionary tables (src/lib/content-shared/lectionary/tables/*.json),
 * generated by scripts/lectionary/build-tables.ts from the USCCB daily-readings
 * dataset (westhong/catholic-daily-readings, MIT), the USCCB annual liturgical
 * calendars and the catholic-resources.org lectionary index (Felix Just, S.J.).
 *
 * The tables hold CITATIONS and labels only — never Scripture text. Text is
 * resolved at call time from the Douay-Rheims store (../bible/dra.ts).
 */

import type { ReadingKind } from "../daily-readings";

/** Sunday cycle (A/B/C) or Ordinary-Time weekday cycle (I/II). */
export type LectionaryCycle = "A" | "B" | "C" | "I" | "II";

export type SundayCycle = "A" | "B" | "C";
export type WeekdayCycle = "I" | "II";

/**
 * Where a citation was taken from, in order of authority:
 *  - "usccb": the USCCB daily-readings pages (via the westhong dataset);
 *  - "usccb-calendar": the USCCB annual liturgical calendar (First/Second/Gospel only);
 *  - "catholic-resources": the catholic-resources.org lectionary index.
 */
export type LectionarySource = "usccb" | "usccb-calendar" | "catholic-resources";

export interface LectionarySection {
  kind: ReadingKind;
  /**
   * Cycle this section applies to, or null for every year. A section with a
   * cycle OVERRIDES the cycle-null sections of the same kind for that cycle
   * (e.g. an Ordinary-Time weekday's First Reading is given once per weekday
   * cycle; the Holy Family's optional Year B/C readings replace the ABC set).
   */
  cycle: LectionaryCycle | null;
  /** Normalised USCCB-style citation (parses with bible/citation.ts); " or " joins alternatives. */
  citation: string;
  /** Heading override for multi-reading Masses (Easter Vigil "Reading III", "Epistle"). */
  label?: string;
  source: LectionarySource;
}

export type LectionaryEntryKind = "sunday" | "weekday" | "sanctoral" | "common";

export interface LectionaryEntry {
  /** Lectionary number as printed by the USCCB (a string: "1", "510A", "690A"). */
  number: string;
  /** Day label from the source index, e.g. "2nd Sunday of Advent", "Week 3 - Mon". */
  label: string;
  /** Sunday cycle the whole entry belongs to (Sunday numbers are per-cycle), else null. */
  cycle: SundayCycle | null;
  kind: LectionaryEntryKind;
  /** Mass variant when a celebration has several formularies ("vigil", "night", "dawn", "day", "chrism", "procession", "extended-vigil", "year-a"). */
  variant: string | null;
  /** Engine `lectionaryKey` derived from the source's day label / date, when known. */
  key: string | null;
  /** Sections in proclamation order (cycle-specific sections follow the shared ones). */
  sections: LectionarySection[];
}

/** A Mass formulary a key maps to: the lectionary number and its variant. */
export interface KeyMapMass {
  number: string;
  /** null = the principal Mass of the day (the first entry is always the principal one). */
  variant: string | null;
}

export interface KeyMapEntry {
  /** Sunday cycle the numbers belong to, or null when the same for every year. */
  cycle: SundayCycle | null;
  /** Principal Mass first, then the variants (vigil, night, dawn, year-a …). */
  masses: KeyMapMass[];
  /**
   * "dates": derived by joining the engine with dated USCCB sources;
   * "labels": filled from the catholic-resources day labels (keys the dated
   * sources never showed, e.g. weeks omitted in 2023–2028).
   */
  source: "dates" | "labels";
}

/** Engine `lectionaryKey` → one entry per applicable Sunday cycle (or a single cycle-null entry). */
export type LectionaryKeyMap = Record<string, KeyMapEntry[]>;

/** by-number.json: lectionary number → entry. */
export type LectionaryByNumber = Record<string, LectionaryEntry>;
