/**
 * brain-candidates - candidate-action enumeration for the Admin Worker
 * brain. Extracted from brain.ts (spec: refactor oversized worker files
 * into smaller modules). Pure function over WorldState; scoring lives in
 * brain-scoring.ts and orchestration stays in brain.ts.
 */

import type { BrainAction, WorldState } from "./brain";

/**
 * Build the candidate action list. One BrainAction per primitive
 * pipeline stage / mode the brain can choose. Scoring (next step)
 * picks the best one.
 */
export function enumerateCandidateActions(world: WorldState): BrainAction[] {
  const ct = world.contentGoalContentType;
  return [
    // Paused — only fires when the operator pulled the pause toggle.
    {
      actionType: "PAUSED",
      missionStage: "PAUSED",
      mode: "PAUSED",
      priority: "SECURITY_THREAT",
      passType: "SECURITY",
      contentType: null,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Security defender stays online; nothing else runs.",
      confidenceScore: 1,
      riskScore: 0,
      qualityExpectation: 1,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: null,
      stopCondition: "operator resumes the worker",
      reasonSummary: `Worker paused${world.pausedReason ? ` (${world.pausedReason})` : ""}.`,
      rulesEvaluated: { isPaused: world.isPaused, pausedReason: world.pausedReason },
      safe: true,
      rejectionReason: null,
    },
    // Security defense — confirmed breach in the last 24h.
    {
      actionType: "SECURITY_DEFENSE",
      missionStage: "SECURITY_DEFENSE",
      mode: "SECURITY_DEFENSE",
      priority: "SECURITY_THREAT",
      passType: "SECURITY",
      contentType: null,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Defender records actions for confirmed breaches; bans confirmed attackers.",
      confidenceScore: 0.95,
      riskScore: 0.2,
      qualityExpectation: 0.9,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "log + escalate",
      stopCondition: "no security breaches in last 24h",
      reasonSummary: `${world.recentSecurityBreaches24h} confirmed security breach(es) in 24h.`,
      rulesEvaluated: { recentSecurityBreaches24h: world.recentSecurityBreaches24h },
      safe: true,
      rejectionReason: null,
    },
    // Worker health repair — stale heartbeat or active blocker.
    {
      actionType: "REPAIR",
      missionStage: "REPAIR",
      mode: "REPAIR",
      priority: "WORKER_HEALTH",
      passType: "SOURCE_REPAIR",
      contentType: null,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Clear worker blocker / refresh heartbeat / unstick queue.",
      confidenceScore: 0.85,
      riskScore: 0.25,
      qualityExpectation: 0.7,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "diagnostics",
      stopCondition: "heartbeat fresh and no active blocker",
      reasonSummary: world.currentBlocker
        ? `Active blocker: ${world.currentBlocker}.`
        : `Heartbeat stale (${Math.round(world.heartbeatAgeMs / 1000)}s).`,
      rulesEvaluated: {
        heartbeatAgeMs: world.heartbeatAgeMs,
        currentBlocker: world.currentBlocker,
      },
      safe: true,
      rejectionReason: null,
    },
    // Discovery — content goal has gap and no candidate URLs ready.
    {
      actionType: "DISCOVER_SOURCE",
      missionStage: "DISCOVERY",
      mode: "CONSTANT_FILL",
      priority: "CONTENT_GOAL",
      passType: "CONTENT_GOAL",
      contentType: ct,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: `Surface candidate URLs for ${ct ?? "the highest-gap content type"}.`,
      confidenceScore: 0.75,
      riskScore: 0.15,
      qualityExpectation: 0.5,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "maintenance",
      stopCondition: "candidateUrlsAvailable above min threshold",
      reasonSummary: `Discovery for ${ct ?? "any type"}: gap=${world.contentGoalGap}, candidates=${world.candidateUrlsAvailable}.`,
      rulesEvaluated: {
        contentGoalGap: world.contentGoalGap,
        candidateUrlsAvailable: world.candidateUrlsAvailable,
      },
      safe: true,
      rejectionReason: null,
    },
    // Candidate prioritization — discovered URLs exist that have never been
    // scored. Without this the fetcher has nothing to fetch (every candidate
    // sits DISCOVERED with fetchPriority 0) and the whole pipeline stalls at
    // "candidates exist but none prioritized".
    {
      actionType: "DISCOVER_SOURCE",
      missionStage: "CANDIDATE_PRIORITIZATION",
      mode: "CONSTANT_FILL",
      priority: "CONTENT_GOAL",
      passType: "CONTENT_GOAL",
      contentType: ct,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Score discovered candidates so the fetcher can sort by fetchPriority.",
      confidenceScore: 0.8,
      riskScore: 0.1,
      qualityExpectation: 0.6,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "discovery",
      stopCondition: "all discovered candidates scored",
      reasonSummary: `${world.candidatesNeedingPrioritization} candidate(s) need scoring/prioritization.`,
      rulesEvaluated: {
        candidatesNeedingPrioritization: world.candidatesNeedingPrioritization,
      },
      safe: true,
      rejectionReason: null,
    },
    // Source read — candidates available, no source-read row yet for them.
    {
      actionType: "READ_SOURCE",
      missionStage: "SOURCE_FETCH",
      mode: "CONSTANT_FILL",
      priority: "CONTENT_GOAL",
      passType: "CONTENT_GOAL",
      contentType: ct,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Fetch + parse the highest-priority candidate; write source-read row.",
      confidenceScore: 0.8,
      riskScore: 0.15,
      qualityExpectation: 0.6,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "discovery",
      stopCondition: "candidate becomes FETCHED",
      reasonSummary: `${world.candidateUrlsAvailable} candidates ready to fetch.`,
      rulesEvaluated: { candidateUrlsAvailable: world.candidateUrlsAvailable },
      safe: true,
      rejectionReason: null,
    },
    // Classification — source-read rows exist with no detected type.
    {
      actionType: "CLASSIFY_CONTENT",
      missionStage: "CLASSIFICATION",
      mode: "CONSTANT_FILL",
      priority: "CONTENT_GOAL",
      passType: "CONTENT_GOAL",
      contentType: ct,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Classify unclassified source-reads.",
      confidenceScore: 0.8,
      riskScore: 0.1,
      qualityExpectation: 0.65,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "discovery",
      stopCondition: "no unclassified source-reads",
      reasonSummary: `${world.unclassifiedReads} unclassified source-reads.`,
      rulesEvaluated: { unclassifiedReads: world.unclassifiedReads },
      safe: true,
      rejectionReason: null,
    },
    // Extraction — classified reads exist that have no package artifact.
    {
      actionType: "BUILD_CONTENT",
      missionStage: "EXTRACTION",
      mode: "CONSTANT_FILL",
      priority: "CONTENT_BUILD",
      passType: "CONTENT_GOAL",
      contentType: ct,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Extract a package artifact from a classified source-read.",
      confidenceScore: 0.82,
      riskScore: 0.12,
      qualityExpectation: 0.75,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "classification",
      stopCondition: "no classified reads awaiting extraction",
      reasonSummary: `${world.readsAwaitingExtraction} classified read(s) awaiting extraction.`,
      rulesEvaluated: { readsAwaitingExtraction: world.readsAwaitingExtraction },
      safe: true,
      rejectionReason: null,
    },
    // Checklist + citations — CHECKLIST_READY artifacts need checklist
    // items + citations created before they can be built/published.
    {
      actionType: "BUILD_CONTENT",
      missionStage: "CHECKLIST_CREATION",
      mode: "CONSTANT_FILL",
      priority: "CONTENT_BUILD",
      passType: "CONTENT_GOAL",
      contentType: ct,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Create checklist items + citations for CHECKLIST_READY artifacts.",
      confidenceScore: 0.85,
      riskScore: 0.1,
      qualityExpectation: 0.8,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "extraction",
      stopCondition: "no CHECKLIST_READY artifacts",
      reasonSummary: `${world.artifactsAwaitingChecklist} artifact(s) awaiting checklist + citations.`,
      rulesEvaluated: { artifactsAwaitingChecklist: world.artifactsAwaitingChecklist },
      safe: true,
      rejectionReason: null,
    },
    // Build — pending build jobs or content-type gap with candidates available.
    {
      actionType: "BUILD_CONTENT",
      missionStage: "PACKAGE_BUILD",
      mode: "CONSTANT_FILL",
      priority: world.pendingBuildJobs > 0 ? "CONTENT_BUILD" : "CONTENT_GOAL",
      passType: "CONTENT_GOAL",
      contentType: ct,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Run a build cycle: pick the next job, build a package.",
      confidenceScore: 0.9,
      riskScore: 0.15,
      qualityExpectation: 0.75,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "maintenance",
      stopCondition: "no pending build jobs",
      reasonSummary: `Build queue: ${world.pendingBuildJobs} pending, ${world.runningBuildJobs} running.`,
      rulesEvaluated: {
        pendingBuildJobs: world.pendingBuildJobs,
        contentGoalGap: world.contentGoalGap,
      },
      safe: true,
      rejectionReason: null,
    },
    // Validate / cross-source verify — QA reports waiting on review.
    {
      actionType: "CROSS_SOURCE_VERIFY",
      missionStage: "CROSS_SOURCE_VERIFICATION",
      mode: "CONSTANT_FILL",
      priority: "CONTENT_VALIDATION",
      passType: "CONTENT_GOAL",
      contentType: ct,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Run cross-source verifier on sensitive fields; record evidence.",
      confidenceScore: 0.75,
      riskScore: 0.1,
      qualityExpectation: 0.7,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "human review",
      stopCondition: "no artifacts awaiting validation evidence and no pending QA reviews",
      reasonSummary: `${world.artifactsAwaitingVerification} artifact(s) awaiting cross-source evidence; ${world.pendingQAReviews} QA review(s) pending.`,
      rulesEvaluated: {
        artifactsAwaitingVerification: world.artifactsAwaitingVerification,
        pendingQAReviews: world.pendingQAReviews,
      },
      safe: true,
      rejectionReason: null,
    },
    // Strict QA — BUILD_READY / VERIFICATION_READY artifacts need their
    // durable strict-QA result before they can publish (mandatory gate).
    {
      actionType: "VALIDATE_CONTENT",
      missionStage: "STRICT_QA",
      mode: "CONSTANT_FILL",
      priority: "CONTENT_VALIDATION",
      passType: "CONTENT_GOAL",
      contentType: ct,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Score strict QA on built artifacts; pass/repair/reject.",
      confidenceScore: 0.85,
      riskScore: 0.1,
      qualityExpectation: 0.85,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "repair",
      stopCondition: "no artifacts awaiting strict QA",
      reasonSummary: `${world.artifactsAwaitingQA} artifact(s) awaiting strict QA.`,
      rulesEvaluated: { artifactsAwaitingQA: world.artifactsAwaitingQA },
      safe: true,
      rejectionReason: null,
    },
    // Publish — QA-passed artifacts go public through the orchestrator.
    // Highest content-side urgency: this is the stage that actually
    // closes the content-goal gap, so the brain drains it first.
    {
      actionType: "PUBLISH_CONTENT",
      missionStage: "PUBLIC_PUBLISH",
      mode: "CONSTANT_FILL",
      priority: "CONTENT_BUILD",
      passType: "CONTENT_GOAL",
      contentType: ct,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Publish QA-passed artifacts via the publish orchestrator.",
      confidenceScore: 0.9,
      riskScore: 0.15,
      qualityExpectation: 0.9,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "strict QA",
      stopCondition: "no QA-passed artifacts awaiting publish",
      reasonSummary: `${world.artifactsAwaitingPublish} QA-passed artifact(s) awaiting publish.`,
      rulesEvaluated: { artifactsAwaitingPublish: world.artifactsAwaitingPublish },
      safe: true,
      rejectionReason: null,
    },
    // Post-publish verification — published items missing verification.
    {
      actionType: "POST_PUBLISH_VERIFY",
      missionStage: "POST_PUBLISH_VERIFY",
      mode: "CONSTANT_FILL",
      priority: "CONTENT_VALIDATION",
      passType: "CONTENT_GOAL",
      contentType: null,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Probe public URL + check tab placement, search, sitemap, cache.",
      confidenceScore: 0.8,
      riskScore: 0.1,
      qualityExpectation: 0.8,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "maintenance",
      stopCondition: "all published content verified",
      reasonSummary: `${world.publishedButUnverified} published items missing verification.`,
      rulesEvaluated: { publishedButUnverified: world.publishedButUnverified },
      safe: true,
      rejectionReason: null,
    },
    // Source repair — failed jobs / pending repair plans.
    {
      actionType: "REPAIR",
      missionStage: "REPAIR",
      mode: "REPAIR",
      priority: "SOURCE_REPAIR",
      passType: "SOURCE_REPAIR",
      contentType: null,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Drain failed build jobs + execute pending repair plans.",
      confidenceScore: 0.75,
      riskScore: 0.25,
      qualityExpectation: 0.6,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "diagnostics",
      stopCondition: "no failed jobs and no pending repair plans",
      reasonSummary: `${world.failedBuildJobs} failed jobs, ${world.pendingRepairPlans} repair plans.`,
      rulesEvaluated: {
        failedBuildJobs: world.failedBuildJobs,
        pendingRepairPlans: world.pendingRepairPlans,
        pipelineStagesBlocked: world.pipelineStagesBlocked,
      },
      safe: true,
      rejectionReason: null,
    },
    // Homepage redesign — score below threshold.
    {
      actionType: "UPDATE_HOMEPAGE",
      missionStage: "HOMEPAGE_WORK",
      mode: "HOMEPAGE",
      priority: "HOMEPAGE",
      passType: "HOMEPAGE",
      contentType: null,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "File a homepage draft to lift the score.",
      confidenceScore: 0.7,
      riskScore: 0.3,
      qualityExpectation: 0.65,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "maintenance",
      stopCondition: "homepage score >= 0.65",
      reasonSummary: `Homepage score ${world.homepageScore.toFixed(2)}.`,
      rulesEvaluated: { homepageScore: world.homepageScore },
      safe: true,
      rejectionReason: null,
    },
    // Diagnostics — no recent success.
    {
      actionType: "DIAGNOSTICS",
      missionStage: "REPORTING",
      mode: "DIAGNOSTICS",
      priority: "DIAGNOSTICS",
      passType: "DIAGNOSTICS",
      contentType: null,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Run a full diagnostic sweep.",
      confidenceScore: 0.6,
      riskScore: 0.1,
      qualityExpectation: 0.5,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: "maintenance",
      stopCondition: "fresh successful pass recorded",
      reasonSummary:
        world.lastSuccessAgeMs == null
          ? "No successful pass on record."
          : `Last success ${Math.round(world.lastSuccessAgeMs / 60_000)}m ago.`,
      rulesEvaluated: { lastSuccessAgeMs: world.lastSuccessAgeMs },
      safe: true,
      rejectionReason: null,
    },
    // Maintenance — the floor action; safe to run any time.
    {
      actionType: "CLEANUP",
      missionStage: "MAINTENANCE",
      mode: "MAINTENANCE",
      priority: "MAINTENANCE",
      passType: "AUTONOMOUS",
      contentType: null,
      sourceTarget: null,
      candidateUrl: null,
      expectedOutput: "Run cleanup pass; trim stale candidates and closed reviews.",
      confidenceScore: 0.5,
      riskScore: 0.05,
      qualityExpectation: 0.4,
      urgencyScore: 0,
      sourceScore: 0,
      repairScore: 0,
      finalScore: 0,
      fallbackAction: null,
      stopCondition: "next pass",
      reasonSummary: "Floor maintenance pass.",
      rulesEvaluated: {},
      safe: true,
      rejectionReason: null,
    },
  ];
}
