-- Content subtitle support: a one-line descriptive subtitle on every published
-- item (generated by the worker, rendered under the title). Additive, nullable.

-- AlterTable
ALTER TABLE "PublishedContent" ADD COLUMN "subtitle" TEXT;
